"""The staff: exactly 50 reporters, each with a family (register), signature opener(s), closer(s) and tics.

Names and outlets are invented. Openers/closers/tics never state a fact about the league: they are flavor only.
A tic is used at most once per article, an opener once at the top, a closer once at the bottom.
Beat codes: R recap/roundup, P preview, T trade, W waiver, S shotgun (Beer Report), N standings,
F feud, V rivalry, O offseason.
"""
from __future__ import annotations

from dataclasses import dataclass

BEAT_CODES = {"R": "recap", "P": "preview", "T": "trade", "W": "waiver", "S": "shotgun",
              "N": "standings", "F": "feud", "V": "rivalry", "O": "offseason"}


@dataclass(frozen=True)
class Voice:
    id: str
    name: str
    outlet: str
    bio: str
    family: str
    beats: frozenset
    openers: tuple
    closers: tuple
    tics: tuple

    def card(self) -> dict:
        return {"id": self.id, "name": self.name, "outlet": self.outlet, "bio": self.bio, "family": self.family}


def _v(id, name, outlet, bio, family, beats, openers, closers, tics) -> Voice:
    return Voice(id, name, outlet, bio, family, frozenset(BEAT_CODES[c] for c in beats),
                 tuple(openers), tuple(closers), tuple(tics))


VOICES: list[Voice] = [
    # ---------------- wire-service straight news ----------------
    _v("hollis-tanager", "Hollis Tanager", "Tri-County Wire Service",
       "Thirty-one years on the wire desk and has never used an adjective he couldn't source.", "wire", "RPTWNO",
       ["THE GROUP CHAT —", "LEAGUE OFFICE (Sleeper) —"],
       ["(Reporting by Hollis Tanager. Editing by whoever was still awake.)", "This story will be updated if the stat corrections say so."],
       ["Figures are final unless the stat corrections say otherwise.", "Details were limited to the box score.", "All times are group-chat time."]),
    _v("marguerite-valdane", "Marguerite Valdane", "Lakeshore Associated Dispatch",
       "Writes the first paragraph last and the headline never.", "wire", "RTWSNF",
       ["Per the official box score:", "The scoreboard reported the following."],
       ["End of dispatch.", "Further updates will follow the next round of games."],
       ["Numbers were checked twice.", "No adjectives were used where a number would do.", "Source: the scoreboard."]),
    _v("roy-pell", "Roy Pell", "Midland Press Bureau",
       "Believes a story is just the box score with the dull parts left in.", "wire", "RPWFVO",
       ["Here are the facts.", "From the league ledger:"],
       ["Those are the facts. There are no others.", "That is the record as it stands."],
       ["Facts only.", "The record speaks for itself, and slowly.", "Attribution: the box score."]),
    _v("ines-varga-holt", "Ines Varga-Holt", "Continental News Digest",
       "Files copy in four languages and still has nothing to add to the standings.", "wire", "RPTSNV",
       ["In brief:", "A summary of the results follows."],
       ["Developing.", "Full results are on the scoreboard."],
       ["Readers are advised to consult the standings.", "Scores are reproduced as reported.", "The figures stand."]),
    # ---------------- hype beat reporters ----------------
    _v("cody-brandish", "Cody Brandish", "Sunday Surge Network",
       "Has never met a Tuesday he couldn't describe as a must-see event.", "hype", "RPTWSF",
       ["BREAKING!", "Folks, buckle up!"],
       ["Buckle up, because next week is already loading.", "Stay locked in. I'll be right here."],
       ["I cannot stress this enough!", "Mark the date!", "Are you not entertained?!"]),
    _v("delia-fontaine", "Delia Fontaine", "Primetime Pulse",
       "Her voicemail greeting is a cold open with a cliffhanger.", "hype", "RPNFVS",
       ["Stop what you're doing.", "Drop everything."],
       ["See you at kickoff.", "Set the alarm. The next slate is coming."],
       ["Read that again.", "Yes, really.", "I'm not exaggerating. I never exaggerate."]),
    _v("marcus-oyelaran", "Marcus Oyelaran", "The Hot Stove Report",
       "Declared every week the biggest of the season, and has been technically correct twice.", "hype", "RTWFVO",
       ["Pound the table, because this one earns it.", "Okay. Okay. OKAY."],
       ["That's the report. Hot enough for you?", "Get your lineups set. Seriously, set them."],
       ["Unbelievable stuff.", "You can't make this up.", "Remember where you heard it."]),
    _v("tamsin-rourke", "Tamsin Rourke", "Gridiron Live Desk",
       "Reports from the group chat as though it were a war zone with better snacks.", "hype", "RPSNFV",
       ["Live from the group chat!", "We interrupt your regularly scheduled week!"],
       ["Back to you, league!", "Next week: same energy, higher stakes."],
       ["Chills. Genuine chills.", "That's the story. That is THE story.", "Big, big, big."]),
    # ---------------- analytics nerds ----------------
    _v("priya-anand-whitlock", "Priya Anand-Whitlock", "The Regression Review",
       "Once cited a p-value in a eulogy.", "nerd", "RPNWFO",
       ["Let's look at the data.", "First, a note on sample size: it is small."],
       ["Sample size: small. Confidence: unearned. Proceed.", "Further analysis pending more weeks."],
       ["Correlation is not a lineup decision.", "I have run the numbers and they are indifferent.", "The model has opinions and has been asked to keep them down."]),
    _v("felix-okonkwo-brandt", "Felix Okonkwo-Brandt", "Expected Wins Quarterly",
       "Keeps a spreadsheet of his own spreadsheets.", "nerd", "RPNSWT",
       ["Method note: all figures come from the box score.", "Before the narrative, the numbers."],
       ["The model will be revised as the season is.", "Results may vary. Results already did."],
       ["Regression to the mean is undefeated.", "Variance remains the league's most consistent player.", "Plot it and see."]),
    _v("linnea-marchetti", "Dr. Linnea Marchetti", "Variance & Co.",
       "Holds a doctorate in a field she refuses to disclose, and a grudge against small samples.", "nerd", "RPNTO",
       ["Dr. Marchetti's note on this week's data follows.", "Hypothesis first, scores second."],
       ["Reject the null at your own risk.", "Peer review is welcome and unlikely."],
       ["The error bars are doing a lot of work here.", "I would like a larger sample, as always.", "Footnote: it is a game of luck and also of skill, mostly luck."]),
    _v("gideon-sato-pryce", "Gideon Sato-Pryce", "The Standard Deviation",
       "Speaks only in percentiles, even to his dog.", "nerd", "RPNSFV",
       ["Averages lie. Distributions don't.", "A word about the spread."],
       ["Stay within one sigma.", "That is the distribution. Draw your own conclusions."],
       ["Plot twist: it was variance.", "Noted for the spreadsheet.", "This is not a prediction, only a probability wearing a hat."]),
    # ---------------- old-school columnists ----------------
    _v("everett-lindqvist", "Everett J. Lindqvist", "The Evening Ledger",
       "Has filed a column every week since before the group chat and resents it.", "columnist", "RTWFVO",
       ["Pull up a chair.", "I have been thinking about this all weekend."],
       ["That is one man's view, and it happens to be correct.", "Draw the shades. The league will still be here in the morning."],
       ["I have seen this before, though not often.", "A fellow learns things in this line of work.", "There is a lesson in that, if you are in the market for lessons."]),
    _v("winifred-castellano", "Winifred Castellano", "The Morning Clarion",
       "Writes with a fountain pen and lets everyone know it.", "columnist", "RPTFVO",
       ["A word, if I may.", "One does notice these things."],
       ["Do give it some thought.", "And with that, the tea has gone cold."],
       ["One notices.", "I shall say no more, and then say a little more.", "It is not my place, but I do have a column."]),
    _v("harlan-beaumont-roe", "Harlan Beaumont Roe", "The Sunday Standard",
       "Insists the game was better when the scores were smaller.", "columnist", "RWSNFV",
       ["Sit down, I'm going to tell you something.", "Let me tell you how it looked from where I sat."],
       ["That is how it looked from here.", "Write that on the wall of the league and move on."],
       ["Mark my words.", "I've been wrong before. Not about this.", "That's football, or something like it."]),
    _v("beatrix-aldous-lowe", "Beatrix Aldous-Lowe", "The Weekend Review",
       "Reads three newspapers a day and quotes none of them.", "columnist", "RPTWNO",
       ["It is a quiet morning, so allow me to be loud.", "Consider, if you will, the week that was."],
       ["Consider it considered.", "More next week, weather and waiver wire permitting."],
       ["Consider the following.", "The more things change, the more the fantasy league stays the same.", "A little perspective never hurt a standings page."]),
    # ---------------- tabloid / gossip ----------------
    _v("trixie-delacroix", "Trixie Delacroix", "The Daily Scoop",
       "Treats every box score as a leaked document.", "tabloid", "RTFSVW",
       ["EXCLUSIVE!", "You'll never guess what the box score says."],
       ["You read it here first, darlings.", "Muah. Burn after reading."],
       ["Spill!", "Oh, the drama!", "We simply cannot make this up."]),
    _v("rex-moxley", "Rex Moxley", "The Weekly Whisper",
       "Has a source in every group chat and a lawyer for the rest.", "tabloid", "RTWFSV",
       ["PSSST.", "Hush-hush, but the numbers are out."],
       ["Our lips are sealed. The scoreboard's aren't.", "That's all the gossip fit to print."],
       ["Allegedly.", "We hear things.", "Take it with a grain of salt and a side of box score."]),
    _v("pamela-sixsmith", "Pamela Sixsmith", "The Tattler's Corner",
       "Collects rumors the way other people collect stamps, and licks them first.", "tabloid", "RPTFSN",
       ["Well, well, well.", "Darlings, gather round the water cooler."],
       ["Tell no one. Tell everyone.", "Until next time, keep your lineups close and your rivals closer."],
       ["Do keep up.", "The tea is hot and the figures are public record.", "One simply cannot look away."]),
    _v("jules-vandermeer", "Jules Vandermeer", "Gridiron Gossip Daily",
       "Types with one finger and judges with all ten.", "tabloid", "RPWFSV",
       ["Flash!", "Scoop alert."],
       ["Stay nosy.", "We'll be watching. The box score always is."],
       ["Chaos, honestly.", "Not a drill.", "Make of that what you will."]),
    # ---------------- deadpan minimalists ----------------
    _v("walter-nibbs", "Walter Nibbs", "The Bulletin of Minor Events",
       "Has never raised his voice, his eyebrows, or a point of order.", "deadpan", "RPTWSNO",
       ["Week's results.", "It happened."],
       ["That is all.", "Moving on."],
       ["Noted.", "As expected, or not.", "Fine."]),
    _v("ottoline-frame", "Ottoline Frame", "The Quiet Column",
       "Her longest sentence is nine words and she is proud of it.", "deadpan", "RTWSFO",
       ["Briefly.", "Some things occurred."],
       ["Thank you for reading, I suppose.", "There is nothing further."],
       ["Make of it what you will.", "Not remarkable. Mentioned anyway.", "So it goes."]),
    _v("stan-pomeroy", "Stan Pomeroy", "Brief Notes",
       "Charges by the word and has been losing money happily for years.", "deadpan", "RPSNFV",
       ["Notes follow.", "Here's what happened."],
       ["End of notes.", "Back to work."],
       ["Sure.", "That's the job.", "Nothing to add."]),
    _v("mabel-kowalczyk", "Mabel Kowalczyk", "Thursday Notes",
       "Reports the news the way a lighthouse reports the sea: steadily and without opinion.", "deadpan", "RPTWNF",
       ["The results are in.", "Plainly:"],
       ["Anyway.", "That's the week. I'm going to lie down."],
       ["It is what it is, and it is exactly that.", "No further comment, and none needed.", "Yes, that happened."]),
    # ---------------- noir ----------------
    _v("sal-montrose-greaves", "Sal Montrose Greaves", "The Back Alley Gazette",
       "Files copy from a booth at the back of a bar that may not exist.", "noir", "RTSFVO",
       ["It was a Sunday, and the rain had a lineup to set.", "The week came in through the window, smelling of cheap beer and bad lineup decisions."],
       ["The city never sleeps. Neither does the waiver wire.", "I lit a cigarette. The scoreboard didn't blink."],
       ["Nobody asked. I told it anyway.", "The facts were cold. The coffee was colder.", "Trouble always wears a team name."]),
    _v("lorraine-vesper", "Lorraine Vesper", "Rain & Ink",
       "Writes every lead twice and burns the better one.", "noir", "RPSFNV",
       ["The league keeps its secrets in the box score.", "Rain streaked the window. The scores streaked the page."],
       ["Case closed, until Thursday.", "I poured another one. The standings poured nothing back."],
       ["Everybody lies. The points don't.", "Some stories end in the red zone. This one just ended.", "The night had teeth."]),
    _v("mick-dollard", "Mick Dollard", "The Midnight Edition",
       "Works the overnight desk and the overnight bar, in that order.", "noir", "RTWSFO",
       ["Midnight. The kind of hour when scores confess.", "I got the tip at midnight: check the box score."],
       ["The sun came up like an apology.", "That's the story. Pour yourself something."],
       ["I'd seen worse. Not by much.", "The evidence was a number.", "A bartender once told me never to trust a projection."]),
    _v("cassandra-blythe", "Cassandra Blythe", "The Streetlamp Sentinel",
       "Takes the standings personally and the waiver wire as an alibi.", "noir", "RPTSNF",
       ["Under the streetlamp, the numbers waited.", "The call came in at 3 a.m. It was about the standings."],
       ["The lamp flickered. The league kept going.", "I closed the file. Not the case."],
       ["It was that kind of week.", "Every score has a story. Most of them are sad.", "I wasn't surprised. I'm never surprised. It's a gift."]),
    # ---------------- nature documentary ----------------
    _v("aubrey-thistlewood", "Sir Aubrey Thistlewood", "Planet Gridiron",
       "Narrates from a blind in the corner of the group chat, whispering.", "nature", "RPWSFO",
       ["Here, on the vast plains of the waiver wire, we find a remarkable scene.", "And so, as the light fades over the league, we observe."],
       ["And so the cycle continues.", "Life, as ever, finds a way, and then drops it for a streaming option."],
       ["Remarkable.", "Nature is cruel, but fair, but mostly cruel.", "One must not interfere."]),
    _v("marisol-quenby", "Dr. Marisol Quenby", "Wild Fantasy",
       "Has spent four seasons observing the commissioner in his natural habitat.", "nature", "RTWSFV",
       ["Deep in the roster, a drama unfolds.", "In the great migration of the NFL season, we begin with the herd."],
       ["The herd moves on.", "Each week, the same hunt, a different outcome."],
       ["Extraordinary.", "Few creatures survive this stretch of the schedule.", "Observe the plumage."]),
    _v("basil-cartwright-moon", "Basil Cartwright-Moon", "The Savanna Channel",
       "Whispers into a microphone shaped like a pith helmet.", "nature", "RPSNFV",
       ["Dawn breaks over the standings.", "The watering hole is quiet. Not for long."],
       ["Night falls on the savanna.", "The sun sets on another week of the hunt."],
       ["Nothing is wasted in nature, least of all points.", "A rare sight.", "Viewers are advised to keep a safe distance."]),
    _v("elspeth-tarn", "Elspeth Tarn", "Habitat Weekly",
       "Mostly covers moss and has found the transition to fantasy football surprisingly smooth.", "nature", "RPTWNO",
       ["In the habitat of the standings, activity is brisk.", "The ecosystem of the league is delicate, and the week disturbed it."],
       ["Conservation efforts continue.", "The habitat endures."],
       ["An elegant adaptation, in its way.", "Evolution, in real time.", "Quietly, the food chain turns."]),
    # ---------------- wrestling play-by-play ----------------
    _v("boomer-dunlevy", "Boomer Dunlevy", "Steel Cage Sports Network",
       "Lost his voice in 1998 and has been shouting without it ever since.", "wrestling", "RPSFVT",
       ["OH MY GOODNESS, ladies and gentlemen!", "Ring the bell!"],
       ["I'm Boomer Dunlevy, and nobody gets out of this league alive!", "Let's go home, folks, and get ready for next week's main event!"],
       ["What a maneuver!", "Unbelievable! Unbelievable!", "Somebody check the referee!"]),
    _v("candi-moreau", "Candi Moreau", "Turnbuckle Tonight",
       "Calls the fantasy week like a title match and has the folding chair to prove it.", "wrestling", "RWSFVT",
       ["Welcome, welcome, welcome to the squared circle!", "The crowd is on its feet!"],
       ["Until the next bell, stay dangerous.", "That's the show. Tip your referee."],
       ["Hold onto your folding chairs!", "Off the top rope!", "Pin it and call it!"]),
    _v("duke-hargrove", "Duke Hargrove III", "Main Event Monday",
       "Third of his name, first to describe a waiver claim as a heel turn.", "wrestling", "RPTSFN",
       ["Gentlemen, the card is set.", "Tonight's main event is brought to you by points."],
       ["Good night, and may all your finishers land.", "That's the card. See you at the next show."],
       ["Down goes the lineup!", "The ref counted to three and kept going.", "That's a clean pin!"]),
    # ---------------- corporate memo ----------------
    _v("gregory-pemberton-ash", "Gregory Pemberton-Ash", "Internal Communications, Fantasy Division",
       "Replies all by reflex and has never once been asked to stop.", "memo", "RPTWNO",
       ["To all stakeholders:", "Re: weekly deliverables."],
       ["Please advise.", "Let me know if you have questions. You will."],
       ["Going forward, let's circle back on this.", "Action item: none.", "This has been flagged for visibility."]),
    _v("sharon-whitcombe-diaz", "Sharon Whitcombe-Diaz", "HR Synergy Bulletin",
       "Starts every sentence with a compliment and ends it with a policy.", "memo", "RWSNFO",
       ["Team: a quick note on this week's performance indicators.", "Hi all, a friendly update from People Operations."],
       ["Thanks in advance for your engagement.", "Let's keep the momentum going."],
       ["No further action is required at this time.", "We value your continued participation.", "Please refer to the standings."]),
    _v("trevor-ashbury-lowe", "Trevor Ashbury-Lowe", "Quarterly Alignment Digest",
       "Has a slide for everything and a meeting about the slide.", "memo", "RPTNFV",
       ["Executive summary:", "Key takeaways for leadership:"],
       ["End of digest. Synergies to follow.", "Next steps: next week."],
       ["Bandwidth is limited.", "Let's take this offline.", "This is a leadership opportunity."]),
    # ---------------- British football commentators ----------------
    _v("alistair-pennywhistle", "Alistair Pennywhistle", "Radio Gridiron Five",
       "Describes a punt as though a minor royal had been shot out of a cannon.", "british", "RPSFVN",
       ["And we are live!", "Good evening, and welcome to a remarkable week."],
       ["And that, ladies and gentlemen, is the full-time whistle.", "Back to the studio."],
       ["Absolutely extraordinary scenes.", "You couldn't write it.", "The pundits will be having a field day."]),
    _v("clive-dobson-fry", "Clive Dobson-Fry", "Saturday Terraces",
       "Commentated on the wrong sport for nineteen years and nobody has corrected him.", "british", "RTWSFV",
       ["Right, here we go.", "Let me set the scene."],
       ["That's the lot. Cheers.", "Same time next week, if the lads are up to it."],
       ["Proper stuff.", "I'll tell you what.", "That's football for you."]),
    _v("rosamund-haverford-gray", "Rosamund Haverford-Gray", "The Sunday Touchline",
       "Covers fantasy football with the composure of a cricket correspondent at tea.", "british", "RPTWNO",
       ["Do forgive me, but I must describe this.", "It is a fine day for it, and the week was finer still."],
       ["Jolly good. Until next time.", "That concludes our coverage, with thanks."],
       ["Quite.", "Rather splendid, if you ask me.", "One could not have scripted it better."]),
    # ---------------- courtroom ----------------
    _v("cornelius-ashworth-bell", "Hon. Cornelius Ashworth-Bell (ret.)", "The Docket",
       "Retired from the bench and unretired for the standings.", "courtroom", "RPTSNF",
       ["The court will come to order.", "Let the record show the following."],
       ["So ordered.", "The court stands adjourned until next week."],
       ["Objection noted and overruled.", "The record reflects as much.", "The court takes judicial notice of the scoreboard."]),
    _v("delphine-roux-abernathy", "Delphine Roux-Abernathy", "The People's Brief",
       "Has never lost a case against a lineup.", "courtroom", "RWSFVN",
       ["The People will show the following.", "Ladies and gentlemen of the league, the evidence."],
       ["The People rest.", "The prosecution has nothing further."],
       ["Exhibit A is the box score.", "I put it to you that the numbers are the numbers.", "No further questions, for now."]),
    _v("barnaby-quillfeather", "Barnaby Quillfeather, Esq.", "Appellate Weekly",
       "Files an appeal for every loss, including other people's.", "courtroom", "RPTWFO",
       ["Respectfully submitted for the record:", "On the matter at hand, the briefs are in."],
       ["Respectfully submitted.", "The appeal is denied. All of them."],
       ["Precedent suggests otherwise, but the standings control.", "The undersigned notes the following for the record.", "I reserve the right to be dramatic."]),
    # ---------------- weather forecasters ----------------
    _v("winston-achterberg", "Winston Achterberg", "StormTrack Nine",
       "Once forecast a lineup change at 90 percent and has been insufferable since.", "weather", "RPSNFV",
       ["Good evening, and here's your seven-day league forecast.", "Grab an umbrella; it's been a busy week."],
       ["That's the forecast. I'll see you at the next front.", "Stay dry, stay safe, and set your lineups."],
       ["Things are looking unsettled.", "Pressure is building.", "Keep an eye on the radar."]),
    _v("ingrid-sorensen-vale", "Ingrid Sorensen-Vale", "The Pressure System",
       "Describes every setback as a front moving through and every comeback as a clearing.", "weather", "RTWNFO",
       ["Forecast models show a lively system this week.", "A quick look at the isobars before we begin."],
       ["Clearing skies ahead, or at least a change in the pattern.", "That's the outlook. Do dress in layers."],
       ["The barometer is falling.", "Expect a scattering of drama.", "Winds are shifting."]),
    _v("reggie-hale-thornbury", "Reggie Hale-Thornbury", "KLAB Weather Desk",
       "Points at a green screen with great authority and no map behind him.", "weather", "RPTWSF",
       ["Time for a look at the radar.", "Let's check in on the satellite."],
       ["Back to you in the studio.", "That's your weather. Don't let it rain on your lineup."],
       ["Unseasonable, that.", "A wintry mix of results.", "Batten down the hatches."]),
    # ---------------- finance analysts ----------------
    _v("preston-aldridge-wynn", "Preston Aldridge-Wynn", "The Roster Exchange Daily",
       "Rings a bell when the waiver wire opens and has been asked to stop.", "finance", "RPTWNO",
       ["Markets opened with a flurry of activity.", "The close, from the trading floor of the league:"],
       ["Past performance is not a guarantee of future lineup decisions.", "This is not investment advice. It is barely sports advice."],
       ["Volatility remains elevated.", "Analysts are cautiously optimistic, which is to say bored.", "Bullish, bearish, or merely bleary."]),
    _v("natalia-brightmore", "Natalia Brightmore", "Bull & Bye Report",
       "Rates every roster move buy, hold, or sell, including her own lunch.", "finance", "RWSFVN",
       ["Tickers up, tickers down, lineups sideways.", "An early look at the week's moves."],
       ["Diversify your bench.", "That's the bell. Markets resume next week."],
       ["Short-term noise, long-term story.", "Risk-adjusted, it was quite a week.", "Do your own due diligence."]),
    _v("cormac-delacourt-fisk", "Cormac Delacourt-Fisk", "Alpha Dispatch",
       "Publishes a flash note before the games have finished and a correction after.", "finance", "RPTFSO",
       ["A flash note from the desk.", "Our view, in brief:"],
       ["We maintain our rating.", "Alpha is where you find it, and it was found."],
       ["Upside is limited. Downside is a lineup.", "We are overweight on drama.", "Guidance may be revised."]),
]

BY_ID: dict[str, Voice] = {v.id: v for v in VOICES}
FAMILY_OF = {v.id: v.family for v in VOICES}
