"""British football commentator: 'absolutely extraordinary scenes', the lads, the pundits, a stoic stream of understatement."""
FAMILY = {
    "id": "british",
    "label": "British football commentator",
    "desc": "Live radio voice: 'and it's...!', 'extraordinary scenes', 'the lads', 'proper', 'full-time whistle'. Warm, excitable, self-deprecating. Football metaphors applied to fantasy football, spelled the British way.",
    "rhythm": "breathless run-ons broken by 'and' and a short exclamation",
    "formality": "informal, chatty",
    "metaphors": "the match, the table, relegation, the dugout, the pundits, top bins",
    "numbers": "exact, read out like a scoreline",
    "lex": {
        "verb": {
            "blowout": ["thrashed", "hammered", "demolished"],
            "comfortable": ["saw off", "swept aside", "handled"],
            "normal": ["beat", "overcame", "got past"],
            "close": ["edged", "squeezed past", "nicked it against"],
        },
        "noun": {
            "blowout": ["an absolute hammering", "a proper thrashing", "a drubbing"],
            "comfortable": ["a comfortable afternoon's work", "a controlled win", "a professional performance"],
            "normal": ["a decent three points", "a straightforward win", "a perfectly good win"],
            "close": ["a nail-biter", "a late scare", "a proper squeaker"],
        },
        "tier": {
            "hi": ["a cracking bit of business", "a proper bargain", "a masterstroke"],
            "mid": ["a decent bit of business", "fair business", "useful business"],
            "lo": ["a bit of a flop so far", "not much to show yet", "a quiet start"],
        },
    },
    "T": {
        "h.r.blow": [
            "{w} {verb} {l}, {wp}-{lp}: {noun}!",
            "Absolute scenes! {w} wins by {m} against {l}",
            "{w_team} put {m} on {l_team} in {wl}",
        ],
        "h.r.upset": [
            "Giant-killing! {w} ({w_rank0}) beat {l} ({l_rank0})",
            "{w} {verb} {l}, and the table has been turned on its head",
            "Shock result: {w_rank0} takes down {l_rank0} in {wl}",
        ],
        "h.r.close": [
            "{w} {verb} {l} by {m}, and what {noun} that was",
            "{m} points: {w} survive {l} in {wl}",
            "{wp}-{lp}: {w} and {l} serve up {noun}",
        ],
        "h.r.top": [
            "{w} hits {wp}: the best of the week",
            "{wp} for {w}, the top score in {wl}",
            "Top of the charts: {w}, {wp}, and {l} left chasing",
        ],
        "h.r.tie": [
            "Honours even: {a} and {b} draws at {pts}",
            "A draw! {a} and {b}, {pts} apiece",
            "{pts}-{pts}: the points are shared between {a} and {b}",
        ],
        "r.lede.blow": [
            "Oh, my word. {w} {verb} {l}, {wp} to {lp}, in {wl}, and a margin of {m} points is the biggest of the week. That was {noun}.",
            "And it's an absolute hammering! {w_team} ({w}) win by {m} over {l}, {wp}-{lp}, the widest margin of the round in {wl}.",
            "You couldn't script it. {w} {verb} {l}, {wp}-{lp}, a {m}-point margin and the biggest of {wl}.",
        ],
        "r.lede.upset": [
            "Extraordinary scenes! Going into {wl}, {l} was {l_rank0} in the table and {w} was {w_rank0}, and {w} {verb} {l}, {wp} to {lp}. The biggest upset of the round.",
            "Giant-killing in {wl}! {w}, {w_rank0} in the table, beat {l}, {l_rank0}, {wp}-{lp}. Nobody would have put their pension on it.",
            "{l} was {l_rank0}. {w} was {w_rank0}. {w} won, {wp} to {lp}. That's the beauty of the thing.",
        ],
        "r.lede.close": [
            "What a finish! {w} {verb} {l}, {wp} to {lp}, in {wl}, a margin of just {m} points and the closest match of the round. That's {noun}.",
            "Hearts in mouths! {w_team} ({w}) win by {m} over {l}, {wp}-{lp}, the tightest result of {wl}.",
            "And it's {noun}! {w} over {l}, {wp} to {lp}, by {m}: the closest game of the round.",
        ],
        "r.lede.top": [
            "Top of the charts! {w} hits {wp} in {wl}, the highest score of the round against a league average of {wavg}, and {verb} {l} ({lp}) on the way.",
            "What a performance! {w_team} ({w}) put up {wp} in {wl}, best in the league, with {l} managing {lp}. The league average was {wavg}.",
            "{wp}! That's the top score of {wl}, and it belongs to {w}. {l} had {lp}. League average: {wavg}.",
        ],
        "r.lede.tie": [
            "Honours even! {a_team} ({a}) and {b_team} ({b}) drew at {pts} each in {wl}.",
            "A score draw: {a} and {b}, {pts} apiece, in {wl}. Nobody going home happy.",
            "{pts} each for {a} and {b} in {wl}. A point apiece, as it were.",
        ],
        "g.result": [
            "{w_team} ({w}) {verb} {l_team} ({l}), and it finished {wp}-{lp}.",
            "{w} {verb} {l}, {wp} to {lp}.",
            "In {wl}, {w_nick} {verb} {l}: {wp}-{lp}. {noun}.",
            "{l_nick} went down to {w}, {lp}-{wp}, by {m}. That was {noun}.",
            "Full-time: {w} {wp}, {l} {lp}. {noun}.",
            "{w} and {l}, {wl}: {wp}-{lp} at full-time.",
            "{l} couldn't cope with {w}, going down {lp}-{wp}.",
            "A {m}-point win for {w} over {l}, {wp} to {lp}.",
            "{w} {verb} {l}. {noun}, no more, no less.",
            "{wp}-{lp} to {w}: {l} can have a think about that.",
        ],
        "g.tie": [
            "{a} and {b} drew at {pts} each.",
            "{a_team} ({a}) and {b_team} ({b}): {pts}-{pts}, honours even.",
            "A score draw for {a} and {b}, {pts} apiece.",
        ],
        "g.star": [
            "{star} ({spos}) was the man of the match for {w}, with {spts}, {sshare} of the {wp}.",
            "Top of the bill for {w}: {star} ({spos}), {spts}.",
            "{star} ({spos}) bagged {spts} for {w}, and what a contribution.",
        ],
        "g.goat": [
            "{l} got {gpts} from {gname} ({gpos}) in the starting eleven. Not ideal.",
            "{gname} ({gpos}) had a quiet one for {l}: {gpts}.",
            "And {gname} ({gpos}), in the starting lineup for {l}, managed {gpts}. Dear me.",
        ],
        "g.bench": [
            "{l} left {bench_left} on the bench, and {bench_name} ({bench_pos}) scored {bench_pts} from the subs' bench. Questions for the gaffer.",
            "{bench_name} ({bench_pos}) scored {bench_pts} while sitting on {l}'s bench, and a better lineup was worth {bench_left}.",
            "A selection headache for {l}: {bench_left} on the bench, {bench_pts} of them from {bench_name} ({bench_pos}).",
        ],
        "g.streak_w": [
            "{w} has now won {k} on the bounce and sit {w_rank} at {w_rec}.",
            "That's {k} wins in a row for {w}: {w_rec}, {w_rank} in the table.",
            "{w} is {w_rec} and {w_rank}, on a run of {k} straight wins.",
        ],
        "g.streak_l": [
            "{l} has now lost {k} on the bounce and sit {l_rank} at {l_rec}.",
            "That's {k} defeats in a row for {l}: {l_rec}, {l_rank} in the table.",
            "{l} is {l_rec} and {l_rank}, on a run of {k} straight losses. Not great, not great at all.",
        ],
        "g.record": [
            "{w} moves to {w_rec} ({w_rank}); {l} drops to {l_rec} ({l_rank}).",
            "The table now reads {w}, {w_rec}, {w_rank}, and {l}, {l_rec}, {l_rank}.",
            "After {wl}, {w} is {w_rec} and {l} is {l_rec}.",
        ],
        "g.top": [
            "{w}'s {wp} was the highest score of {wl}. The league average was {wavg}.",
            "Nobody scored more than {w} in {wl}: {wp}. The average was {wavg}.",
            "{wp} for {w}, the top mark of the week by a distance. Average: {wavg}.",
        ],
        "g.low": [
            "{l}'s {lp} was the lowest score of {wl}. The league average was {wavg}.",
            "Nobody scored less than {l} in {wl}: {lp}. The average was {wavg}.",
            "{lp} for {l}, the lowest mark of the week. Average: {wavg}.",
        ],
        "g.luck_up": [
            "{n} ({n_rec}) is {luck} wins ahead of the all-play numbers. A bit fortunate, that.",
            "By all-play, {n} has {luck} more wins than they've earned at {n_rec}. The football gods are smiling.",
            "{n}: {n_rec}, and {luck} wins above expectation. Lucky, lucky, lucky.",
        ],
        "g.luck_down": [
            "{n} ({n_rec}) is {luck} wins behind the all-play numbers. Hard done by, that.",
            "By all-play, {n} should have more than {n_rec}: {luck}. The football gods are not smiling.",
            "{n}: {n_rec}, and {luck} wins below expectation. Unlucky, unlucky, unlucky.",
        ],
        "g.upset": [
            "Going in, {w} was {w_rank0} and {l} was {l_rank0}. The table doesn't know what it's doing.",
            "The pre-match table had {l} at {l_rank0} and {w} at {w_rank0}.",
            "{l_rank0} against {w_rank0}, and {w} won. Absolutely lovely.",
        ],
        "g.shotgun": [
            "And {n} owes {sgn}, for {why}. Dear, dear me.",
            "Down the pub with {n}, who owes {sgn} for {why}.",
            "{n} must pay {sgn} for {why}. That's the rules, lads.",
        ],
        "g.aside": [
            "Spare a thought for {n}, who {trait}, and who took {event}.",
            "{n}, who {trait}, left {wl} with {event}.",
            "{n}, who {trait}, now has {event} to chew over.",
        ],
        "r.close_shift": [
            "And in the table, {in_names} are up into the top six, and {out_names} are out of it. {leader} still lead at {leader_rec}.",
            "Movement in the table after {wl}: {in_names} in, {out_names} out of the top six. {leader} is first at {leader_rec}.",
            "After {wl}, {in_names} climb into the playoff places and {out_names} slip out. {leader} sits top, {leader_rec}.",
        ],
        "r.close_table": [
            "After {wl}, {leader} is top at {leader_rec}, and {cut} hold the last playoff place at {cut_rec}.",
            "The table after {wl}: {leader} tops ({leader_rec}), {cut} just in at sixth ({cut_rec}).",
            "{leader} leads the table at {leader_rec}. {cut} cling to sixth at {cut_rec}.",
        ],
        "r.close_po": [
            "That's {wl} done: {ngames}. The biggest margin was {big_m}, {big_w} over {big_l}, and the top score was {top_w}'s {top_pts}.",
            "And that's {wl} in the books. {ngames}: {big_w} wins by {big_m} over {big_l}, and {top_w} hits {top_pts}.",
            "{ngames} in {wl}. {big_w}'s {big_m}-point win over {big_l} was the widest, and {top_w}'s {top_pts} the best score.",
        ],
        "h.p.fav": [
            "{fav} favourites against {dog} in {wl}",
            "{wl}: {fav} ({fav_odds}) the bookies' pick over {dog} ({dog_odds})",
            "Can {dog} spring a surprise on {fav} in {wl}?",
        ],
        "h.p.even": [
            "{a} against {b} in {wl}: too close to call",
            "{wl}: {a} and {b} neck and neck at {a_odds} and {b_odds}",
            "{a} and {b} meets in {wl}, with no clear favourite",
        ],
        "h.p.lev": [
            "The tie of the round in {wl}: {a} against {b}",
            "{swing} points of playoff swing: {a} meets {b} in {wl}",
            "{wl}'s six-pointer: {a} against {b}",
        ],
        "p.lede": [
            "The tie of the round in {wl} is {a_team} ({a}) against {b_team} ({b}).",
            "Your match of the round: {a} against {b}, {wl}.",
            "It's {a} versus {b} in {wl}, and it's the one to watch.",
            "{swing} points of playoff swing on {a} against {b} in {wl}. That's a proper six-pointer.",
        ],
        "p.matchup": [
            "{a_team} ({a}, {a_rec}, {a_avg} a game) meet {b_team} ({b}, {b_rec}, {b_avg}) in {wl}.",
            "{a} is {a_rec} and scoring {a_avg}. {b} is {b_rec} and scoring {b_avg}. Somebody's got to win.",
            "On the one side, {a} ({a_rec}, {a_avg}); on the other, {b} ({b_rec}, {b_avg}).",
            "{b_team} ({b}, {b_rec}, {b_avg} a game) against {a_team} ({a}, {a_rec}, {a_avg}) in {wl}.",
        ],
        "p.h2h_split": [
            "They've met already this season and shared the spoils, {h2h_rec}.",
            "{a} and {b} is {h2h_rec} against each other this term.",
            "The head-to-head between {a} and {b} is level at {h2h_rec}.",
        ],
        "p.h2h_lead": [
            "{lead} has the better of {trail} this season, {h2h_rec}.",
            "{trail} is down {h2h_rec} to {lead} in the head-to-head, and will want revenge.",
            "{lead} leads the head-to-head {h2h_rec}.",
        ],
        "p.h2h_none": [
            "They haven't met this season, so it's all to play for.",
            "{a} and {b} is yet to face each other this term.",
            "This is the first meeting of the season for {a} and {b}.",
        ],
        "p.stakes": [
            "A win takes {a} to {a_win} playoff odds; a defeat, {a_loss}. For {b}, it's {b_win} or {b_loss}. That's a lot riding on it.",
            "{a}: {a_win} with a win, {a_loss} with a defeat. {b}: {b_win} and {b_loss}.",
            "Look at the swing: {a} between {a_loss} and {a_win}, {b} between {b_loss} and {b_win}.",
        ],
        "p.leverage": [
            "{swing} points of combined playoff swing. There's not a bigger game on the card.",
            "No match this week has more riding on it: {swing} points of swing between {a} and {b}.",
            "{a} and {b} is playing for {swing} points of playoff odds. Nothing else comes close.",
        ],
        "p.favorite": [
            "{fav} is the favourites on {fav_why}: {fav_odds} to {dog}'s {dog_odds}.",
            "The numbers favour {fav} ({fav_odds}) over {dog} ({dog_odds}), going by {fav_why}.",
            "{dog} is the underdogs at {dog_odds}, with {fav} at {fav_odds}. Stranger things have happened.",
        ],
        "p.vol": [
            "{vol_n} is the unpredictable ones, swinging {vol_std} points a week, against {other_std} for {other}.",
            "Mind you, {vol_n} can swing by {vol_std} points from week to week, and {other} by {other_std}.",
            "{other} is steady ({other_std} points of swing); {vol_n} is anything but ({vol_std}).",
        ],
        "p.rivnote": [
            "And it's {rv_name}, don't forget. {backstory}",
            "This one's {rv_name}, a proper local derby. {backstory}",
            "It's {rv_name}, and the history is real. {backstory}",
        ],
        "p.close": [
            "Kick-off isn't far away for {a} and {b} in {wl}.",
            "We'll be there for {a} against {b} in {wl}.",
            "{wl} awaits for {a} and {b}.",
        ],
        "h.t": [
            "Transfer news: {a} sends {gave_s} to {b} for {got_s}",
            "{a} and {b} does a deal: {gave_s} for {got_s}",
            "{b} signs {gave_s} from {a}, who take {got_s} in return",
            "Done deal: {gave_s} goes from {a} to {b}, {got_s} comes back",
        ],
        "t.sides": [
            "A transfer deal in {wl}: {a} brings in {a_got}, and {b} brings in {b_got}.",
            "Here's the deal from {wl}. {a} gets {a_got}. {b} gets {b_got}.",
            "{a} lets go {b_got} and take {a_got} in {wl}.",
            "{b} sends {a_got} to {a} in {wl} and take {b_got} the other way.",
        ],
        "t.returns": [
            "And the early returns: over {since_wk}, {a}'s new players have scored {a_pts} and {b}'s have scored {b_pts}. {lead} has the better of it so far.",
            "The scoreboard since the deal: {lead}'s new boys have {lead_pts}, {trail}'s have {trail_pts}, over {since_wk}.",
            "After {since_wk}, {a}'s side of the deal has {a_pts}, and {b}'s has {b_pts}. {lead} is ahead.",
        ],
        "t.pending": [
            "{pk_side} takes {pk_got}, and {pl_side} takes {pl_got}. Picks for players, so it can't be judged yet.",
            "It's picks for players: {pl_side} has {pl_got}, {pk_side} has {pk_got}. Time will tell.",
            "{pl_side} has the players ({pl_got}), {pk_side} the picks ({pk_got}). No verdict yet.",
        ],
        "t.fresh": [
            "It's far too early to say who won that one.",
            "Only time will tell, as the man on the radio says.",
            "No games played since, so nothing to judge.",
        ],
        "t.count": [
            "That's {n}'s {nth} trade of the season. Busy, busy.",
            "{n} has now done the {nth} deal of the season.",
            "The {nth} trade for {n} this term, and counting.",
        ],
        "t.rec": [
            "Before the deal, {a} sat on {a_rec} ({a_rank}), and {b} on {b_rec} ({b_rank}).",
            "At the time, {a} sat {a_rank} at {a_rec}, and {b} sat {b_rank} at {b_rec}.",
            "Going in, {a} stood {a_rec} ({a_rank}); {b} stood {b_rec} ({b_rank}).",
        ],
        "t.close": [
            "And the league log has it: the deal's done.",
            "It's official. Done and dusted.",
            "Signed, sealed, in the log.",
        ],
        "h.w.big": [
            "{n} splashes out {bid} on {player}",
            "{bid} for {player} ({pos}): {n} break the bank",
            "{n} bids {bid} for {player}",
        ],
        "h.w.small": [
            "{n} snaps up {player} for {bid}",
            "{player} ({pos}) joins {n} for {bid}",
            "{n} snaps up {player}, {bid}",
        ],
        "h.w.free": [
            "{n} signs free agent {player}",
            "{player} ({pos}) joins {n} for nothing",
            "{n} picks up {player} off the wire",
        ],
        "w.top_bid": [
            "{n} splashed {bid} on {player} ({pos}) in {wl}, the biggest bid of the week.",
            "The week's biggest bid was {bid}, from {n}, for {player} ({pos}).",
            "{n} went big: {bid} for {player} ({pos}).",
        ],
        "w.top_free": [
            "{n} signed {player} ({pos}) in {wl}, at no cost.",
            "{player} ({pos}) arrives at {n} in {wl}.",
            "The signing of {wl}: {player} ({pos}), by {n}.",
        ],
        "w.since": [
            "Since then, {player} has scored {spts} over {since_wk}: {tier}.",
            "Over {since_wk}, {n} has had {spts} from {player}. That's {tier}.",
            "{player}: {spts} in the {since_wk} since. {tier}.",
        ],
        "w.others": [
            "And in the transfer market: {others_text}.",
            "Also in the market: {others_text}.",
            "Other business: {others_text}.",
        ],
        "w.total": [
            "In all, {total_owners} signed {total_n} in {wl}.",
            "{total_n} were signed by {total_owners} in {wl}.",
            "The wire was busy in {wl}: {total_n} to {total_owners}.",
        ],
        "w.budget": [
            "{n} has blown {spent} of a {budget} FAAB transfer budget.",
            "FAAB books: {n}, {spent} of {budget} gone.",
            "{n} has got through {spent} of {budget} so far.",
        ],
        "w.close": [
            "{player} is now on {n}'s books.",
            "{n} has {player}. Done.",
            "{player} belongs to {n} now.",
        ],
        "h.s": [
            "The Beer Report, Week {wk}: {total_n} owed",
            "{top} is on {topn} in Week {wk}",
            "Week {wk}: {total_n} on the tab, lads",
            "{top} leads the Week {wk} round with {topn}",
        ],
        "s.total": [
            "The Week {wk} shotgun ledger lists {total_n} across {owners_n}. Pints all round.",
            "{owners_n} are in for a round, with {total_n} between them for Week {wk}.",
            "Week {wk} leaves {total_n} on the tab, across {owners_n}.",
        ],
        "s.owner": [
            "{n} is buying {sgn} this week: {list}.",
            "{n} is on {sgn}, thanks to {list}.",
            "{n}: {sgn}. Here's why: {list}.",
            "{n} racked up {sgn} with {list}.",
        ],
        "s.low": [
            "The lowest score on the ledger: {player} ({pos}), {pts}, in {n}'s lineup.",
            "{n}'s {player} ({pos}) managed {pts}, the floor of the week.",
            "At {pts}, {player} ({pos}) set the bar, so to speak, for {n}.",
        ],
        "s.leader": [
            "{leader} is top of the drinking table with {ltotal} through Week {wk}.",
            "Through Week {wk}, nobody owes more than {leader}: {ltotal}.",
            "{leader} tops the season's shotgun table at {ltotal}.",
        ],
        "s.close": [
            "{top} is first on the Week {wk} list. Cheers.",
            "{top} heads the Week {wk} ledger. Get the round in.",
            "{top} leads the list for Week {wk}.",
        ],
        "h.n": [
            "The table through {wl}: {top} tops, {six} clinging to sixth",
            "{alive} teams still in it for {spots} playoff places through {wl}",
            "{top} tops, {bottom} bottom: the table through {wl}",
            "Through {wl}, {six} clings to the last playoff place",
        ],
        "h.nf": [
            "Final table: {top} tops, {seven} just miss out",
            "{six} grabs the last place, {seven} don't: the final table",
            "{top} first, {bottom} last: the regular season is done",
            "The playoff places are decided: {six} in, {seven} out",
        ],
        "n.top": [
            "Through {wl}, {top} sits top of the table at {top_rec}.",
            "{top} leads at {top_rec} through {wl}.",
            "Top of the league through {wl}: {top}, {top_rec}.",
            "{top} leads on {top_rec}, with {top_odds} to reach the playoffs.",
            "Through {wl}, {top} leads at {top_rec}, with {top_odds} playoff odds and {bye} for a bye.",
        ],
        "n.cut": [
            "{six} ({six_rec}) hold the last playoff place, with {seven} ({seven_rec}) just behind.",
            "The cut-off falls between {six} ({six_rec}) and {seven} ({seven_rec}).",
            "{seven} ({seven_rec}) is the first out, with {six} ({six_rec}) hanging on.",
        ],
        "n.luck": [
            "Luck of the draw: {lucky} is {lucky_luck} wins above all-play expectation, and {unlucky} is {unlucky_luck}.",
            "By all-play, {lucky} has {lucky_luck} wins they haven't earned; {unlucky} has {unlucky_luck}.",
            "{lucky} ({lucky_luck}) has had the bounce of the ball; {unlucky} ({unlucky_luck}) haven't.",
        ],
        "n.clinch": [
            "Safe in the playoffs: {names}.",
            "Safe in the playoffs, and no mistake: {names}.",
            "{names} have booked their places.",
        ],
        "n.elim": [
            "Out of it, mathematically: {names}.",
            "Relegated from contention: {names}.",
            "{names} can't get in now.",
        ],
        "n.bottom": [
            "Bottom of the table: {bottom}, {bottom_rec}.",
            "{bottom} is propping up the table at {bottom_rec}.",
            "The wooden spoon is currently with {bottom} ({bottom_rec}).",
        ],
        "n.eff": [
            "On selection: {best_n} gets {best_pct} of the available points; {worst_n} gets {worst_pct}.",
            "{best_n} picks the best lineups at {best_pct}, and {worst_n} the worst at {worst_pct}.",
            "Lineup efficiency: {best_n}, {best_pct}; {worst_n}, {worst_pct}.",
        ],
        "n.records": [
            "For the record books: the top score is {hi_pts}, by {hi_n} in Week {hi_wk}, and the biggest margin is {blow_m}, by {blow_w} over {blow_l} in Week {blow_wk}.",
            "{hi_n}'s {hi_pts} in Week {hi_wk} is still the highest score, and {blow_w}'s {blow_m}-point win over {blow_l} in Week {blow_wk} is the widest margin.",
            "Records: {hi_pts} ({hi_n}, Week {hi_wk}) and {blow_m} points ({blow_w} over {blow_l}, Week {blow_wk}).",
        ],
        "n.ftop": [
            "{top} finishes first at {top_rec}, with {top_pf} scored.",
            "The one seed goes to {top}, on {top_rec} and {top_pf}.",
            "{top} ends the regular season top, {top_rec}, {top_pf}.",
        ],
        "n.fcut": [
            "{six} sneaks the last playoff place at {six_rec}, and {seven} ({seven_rec}) miss out.",
            "The cut falls between {six} ({six_rec}) and {seven} ({seven_rec}).",
            "{six} ({six_rec}) is in. {seven} ({seven_rec}) is out. Cruel.",
        ],
        "n.fpts": [
            "{pf_n} took the golden boot with {pf_pts}; {low_n} scraped {low_pts}.",
            "Goals for: {pf_n} tops with {pf_pts}, {low_n} bottom with {low_pts}.",
            "{pf_pts} for {pf_n} is the golden boot; {low_pts} for {low_n} is the wooden spoon.",
        ],
        "n.fbottom": [
            "{bottom} finishes last at {bottom_rec}.",
            "Bottom of the table: {bottom}, {bottom_rec}.",
            "{bottom} takes the wooden spoon, {bottom_rec}.",
        ],
        "n.close": [
            "That's the table through {wl}, with {top} at the top.",
            "Through {wl}, {top} sits top of the pile.",
            "{top} remains top through {wl}.",
        ],
        "h.f": [
            "{a} and {b}: bad blood",
            "Ill feeling between {a} and {b}",
            "{a} against {b}: the grudge explained",
            "Trouble brewing: {a} and {b}",
        ],
        "f.h2h": [
            "It all goes back to Week {gwk}, when {w} {verb} {l}, {wp} to {lp}, by {m}. Nobody forgets that.",
            "In Week {gwk}, {w} beat {l}, {wp}-{lp}, by {m} points, and {l} haven't forgotten.",
            "{l} went down to {w} in Week {gwk}, {lp} to {wp}. What {noun}.",
        ],
        "f.trade": [
            "In Week {twk}, they did a deal: {a} took {a_got}, and {b} took {b_got}. Awkward for someone.",
            "A trade in Week {twk} ties them together: {a} got {a_got}, and {b} got {b_got}.",
            "In Week {twk}, {b_got} went to {b}, and {a_got} to {a}.",
        ],
        "f.adj": [
            "In the table, {hi} ({hi_rec}, {hi_rank}) sit just above {lo} ({lo_rec}, {lo_rank}), {pf_gap} apart in points scored. Neighbours, and not friendly ones.",
            "{hi} is {hi_rank}, {lo} is {lo_rank}, and only {pf_gap} apart in points scored.",
            "{lo} trails {hi} by {pf_gap} in points scored, {lo_rank} to {hi_rank} in the table.",
        ],
        "f.blow": [
            "There's Week {gwk} to think about: {w} {verb} {l}, {wp} to {lp}, by {m} points.",
            "In Week {gwk}, {w} puts {m} on {l}, {wp}-{lp}. That doesn't wash out.",
            "{w}'s {m}-point win over {l} in Week {gwk} ({wp}-{lp}) is the sort of margin a rival remembers.",
        ],
        "f.sg": [
            "On the pub tab, {a} is down for {a_sg} and {b} for {b_sg}.",
            "The round of drinks: {a}, {a_sg}; {b}, {b_sg}.",
            "{a} is on {a_sg}, {b} on {b_sg}, on the season tab.",
        ],
        "f.story": [
            "The lads call this one {rv_name}. {backstory}",
            "It's known as {rv_name}, a proper derby. {backstory}",
            "Welcome to {rv_name}. {backstory}",
        ],
        "f.trait": [
            "{a} {a_trait}; {b} {b_trait}. You can see how it happened.",
            "Look at the pair of them: {a} {a_trait}, and {b} {b_trait}.",
            "{a} {a_trait}. {b} {b_trait}. Draw your own conclusions.",
        ],
        "f.mid": [
            "After Week {wk}, {a} sits {a_rank} on {a_rec}, and {b} sits {b_rank} on {b_rec}.",
            "The table through Week {wk}: {a}, {a_rank}, {a_rec}; {b}, {b_rank}, {b_rec}.",
            "The league table through Week {wk}: {a} on {a_rec} ({a_rank}), {b} on {b_rec} ({b_rank}).",
        ],
        "f.close": [
            "And there's no sign of it dying down.",
            "That's a feud that'll run and run.",
            "We'll be watching, lads.",
        ],
        "h.v": [
            "{rv_name} returns: {a} against {b} in Week {wk}",
            "The derby's back: {a} and {b}, Week {wk}",
            "Week {wk}: {rv_name}, and it matters",
            "{a} against {b} in {rv_name}, Week {wk}",
        ],
        "v.lede": [
            "It's derby day in {wl}! {rv_name} is back, with {a} against {b}. {backstory}",
            "Here we go: {rv_name} returns in {wl}, {a} against {b}. {backstory}",
            "{wl} brings {rv_name}: {a} versus {b}. {backstory}",
        ],
        "v.form": [
            "{a} comes in {a_rec} ({a_rank}), scoring {a_avg}. {b} comes in {b_rec} ({b_rank}), scoring {b_avg}.",
            "{a}: {a_rec}, {a_rank}, {a_avg} a game. {b}: {b_rec}, {b_rank}, {b_avg} a game.",
            "{b} sits {b_rank} at {b_rec} ({b_avg} a game), and {a} sits {a_rank} at {a_rec} ({a_avg} a game).",
        ],
        "v.close": [
            "Kick-off in Week {wk}, {a} against {b}.",
            "Week {wk} can't come soon enough for {a} and {b}.",
            "See you in Week {wk}, for {a} against {b}.",
        ],
        "h.o": [
            "Close-season round-up: {ntrades} and {npick}",
            "{ntrades} and {npick} before a ball was kicked",
            "The transfer window: {ntrades}, {npick}",
        ],
        "o.lede": [
            "Before a ball was kicked, the league logged {ntrades} and {npick}. Busy window.",
            "The close season saw {ntrades} and {npick}, according to the log.",
            "{ntrades} and {npick}, all before the opening day.",
        ],
        "o.busy": [
            "The busiest in the window: {busy_text}.",
            "Most active in the window: {busy_text}.",
            "The ones who couldn't sit still: {busy_text}.",
        ],
        "o.big": [
            "The biggest deal of the window: {side_a} got {a_got}, and {side_b} got {b_got}.",
            "The largest trade sent {b_got} to {side_b} and {a_got} to {side_a}.",
            "{side_a} took {a_got}; {side_b} took {b_got}. The biggest deal of the close season.",
        ],
        "o.close": [
            "{busiest} made the most trades. Busy, busy.",
            "Nobody traded more than {busiest}.",
            "{busiest} led the window in trades.",
        ],
        "x.sig": [
            "And then, as always: “{catch}” Classic {n}.",
            "{n} couldn't resist: “{catch}”",
            "{n}'s signature line, once more: “{catch}”",
        ],
        "x.attr": [
            "“{qc}” said {n}, afterwards.",
            "{n}, in the mixed zone: “{qp}”",
            "“{qc}” {n} told the cameras.",
            "{n} didn't hold back: “{qp}”",
            "“{qc}” said {n}, as the pundits nodded.",
        ],
    },
}
