"""Old-school newspaper columnist: first person, long reflective sentences, folksy wisdom, mild nostalgia."""
FAMILY = {
    "id": "columnist",
    "label": "Old-school columnist",
    "desc": "First person, unhurried, long sentences with a turn at the end. Draws small morals from the box score, remembers how things used to be, never raises his or her voice.",
    "rhythm": "long, periodic, with a short sentence to land the point",
    "formality": "medium-high, conversational",
    "metaphors": "the barbershop, the ballpark, the weather, the way things used to be",
    "numbers": "rounded in prose when it helps, exact when it hurts",
    "lex": {
        "verb": {
            "blowout": ["flattened", "dismantled", "ran roughshod over"],
            "comfortable": ["handled", "got the better of", "outplayed"],
            "normal": ["beat", "got by", "bested"],
            "close": ["nosed out", "edged", "got past"],
        },
        "noun": {
            "blowout": ["a thrashing", "a rout", "a beating of the old-fashioned kind"],
            "comfortable": ["a workmanlike win", "a win with room to spare", "a clean, honest win"],
            "normal": ["an ordinary win", "a win like any other", "a plain win"],
            "close": ["a squeaker", "a game that went to the wire", "a one-score affair"],
        },
        "tier": {
            "hi": ["money well spent", "a bargain by any measure", "the best dollar spent all year"],
            "mid": ["fair value", "a respectable return", "about what a sensible person would expect"],
            "lo": ["not much to show for it yet", "a thin return so far", "little to show for the money"],
        },
    },
    "T": {
        "h.r.blow": [
            "{w} {verb} {l}, and I do not mean that kindly",
            "A {m}-point lesson: {w} over {l}, {wp} to {lp}",
            "{wl}: {w_team} hands {l_team} {noun}",
        ],
        "h.r.upset": [
            "The table said one thing; {w} said another, {wp} to {lp}",
            "{w}, {w_rank0} in the standings, beats {l}, {l_rank0}, and reminds us why we play",
            "On the order of things: {w} {verb} {l} in {wl}",
        ],
        "h.r.close": [
            "{m} points: {w} and {l} give us {noun}",
            "{w} {verb} {l}, {wp} to {lp}, and some of us are still breathing",
            "The way it used to be: {w} wins by {m} in {wl}",
        ],
        "h.r.top": [
            "{wp} points and not a word of apology: {w} leads the week",
            "On {w}'s {wp} in {wl}, the best of the week",
            "A score worth remembering: {w}, {wp}, against {l}",
        ],
        "h.r.tie": [
            "A tie, and what it says about {a} and {b}",
            "{pts} apiece: {a} and {b} meet in the middle",
            "Nobody wins, nobody loses: {a} and {b} tie in {wl}",
        ],
        "r.lede.blow": [
            "I have watched a good many Sundays in this league, and I can tell you that {m} points is a margin you do not forget. {w} {verb} {l}, {wp} to {lp}, in {wl}, and that was the widest gap of the week.",
            "There are weeks that leave a mark. In {wl}, {w_team} ({w}) {verb} {l_team} ({l}) by {m} points, {wp} to {lp}, the widest margin of the slate, and I expect it will be talked about for a while.",
            "It was {noun}. {w} {verb} {l}, {wp}-{lp}, in {wl}, and the {m}-point margin was the largest of the week.",
        ],
        "r.lede.upset": [
            "The standings are a kind of promise, and now and then a team breaks it. Going into {wl}, {l} was {l_rank0} and {w} was {w_rank0}; {w} {verb} {l}, {wp} to {lp}, which was the biggest broken promise of the week.",
            "By the standings, {l}, {l_rank0} before {wl}, ought to have had little trouble with {w}, who was {w_rank0}. The scoreboard said {wp}-{lp} the other way.",
            "{w} came into {wl} {w_rank0} in the table, and {l} came in {l_rank0}. They went home {wp} to {lp}, and the table is no longer quite what it was.",
        ],
        "r.lede.close": [
            "Some games are won, and some are survived. In {wl}, {w} {verb} {l}, {wp} to {lp}, by {m} points, the narrowest margin of the week, and I would not call it anything but {noun}.",
            "A {m}-point margin is hardly any margin at all. {w_team} ({w}) beat {l_team} ({l}), {wp}-{lp}, in {wl}, the closest game of the slate.",
            "If you want to know how close a thing can be, ask {l}, who lost to {w} by {m} points in {wl}, {lp} to {wp}, the closest result of the week.",
        ],
        "r.lede.top": [
            "I have a soft spot for a big number, and {w} posted the biggest of {wl}: {wp} points, against a league average of {wavg}. {l} scored {lp} and lost anyway, which seems a bit hard.",
            "The high score of {wl} belonged to {w}, who put up {wp} (the league average was {wavg}) and {verb} {l}. {l} had {lp} to show for the week.",
            "There was one score in {wl} that stood a little taller than the rest: {w}'s {wp}. {l} came up with {lp}. The league as a whole averaged {wavg}.",
        ],
        "r.lede.tie": [
            "It is a rare thing, and I do not know that we handle it well. {a_team} ({a}) and {b_team} ({b}) tied at {pts} apiece in {wl}.",
            "{a} and {b} finished {wl} at {pts} points each, which is to say that neither of them lost, and neither of them is happy.",
            "I have seen a tie in this league perhaps once before. In {wl}, {a} and {b} both scored {pts}.",
        ],
        "g.result": [
            "{w_team} ({w}) {verb} {l_team} ({l}), {wp} to {lp}.",
            "{w} {verb} {l}, {wp}-{lp}, and that was that.",
            "In {wl}, {w_nick} {verb} {l}, {wp} to {lp}, by {m}.",
            "{l_nick} lost to {w}, {lp}-{wp}, which was {noun}.",
            "The score was {wp}-{lp} in favor of {w} over {l}, a margin of {m}: {noun}.",
            "{w} and {l} played it out, and {w} came away with it, {wp} to {lp}.",
            "{l} could not match {w}, who finished {wp} to {lp}.",
            "The books will show {w} ahead of {l}, {wp}-{lp}, by {m}.",
            "{w} {verb} {l}, as the score of {wp}-{lp} plainly attests.",
            "It went {w}'s way against {l}: {wp}, {lp}.",
        ],
        "g.tie": [
            "{a} and {b} finished even at {pts}, and nobody knew quite what to do with it.",
            "{a_team} ({a}) and {b_team} ({b}) tied at {pts}, the sort of result that pleases nobody.",
            "{pts} for {a}, {pts} for {b}: a draw.",
        ],
        "g.star": [
            "{star} ({spos}) led the way for {w}, with {spts}, some {sshare} of the {wp}.",
            "I would give the game ball to {star}, the {spos}, who put up {spts} for {w}.",
            "{star} ({spos}) scored {spts}, {sshare} of {w}'s total, and carried {over_half}.",
            "{star} ({spos}) scored {spts}, {sshare} of {w}'s total, and that was {part_note}.",
            "{star} ({spos}) led {w}'s lineup with {spts}, which was {sshare} of the {wp}.",
            "If {w} had a hero, it was {star} ({spos}), with {spts}.",
            "{star} ({spos}) gave {w} {spts}, and the rest followed as it could.",
        ],
        "g.goat": [
            "{l} got {gpts} out of {gname} ({gpos}), and a lineup cannot carry that kind of weight.",
            "At {gpos}, {gname} gave {l} {gpts}, a figure that tells its own sad story.",
            "{gname} ({gpos}), starting for {l}, finished with {gpts}.",
        ],
        "g.bench": [
            "It is a sorry thing to sit a player who scores {bench_pts}, as {l} did with {bench_name} ({bench_pos}), and the best lineup would have added {bench_left}.",
            "{l} left {bench_left} on the bench, {bench_pts} of it from {bench_name} ({bench_pos}), who watched.",
            "A better lineup would have been worth {bench_left} to {l}. {bench_name} ({bench_pos}) scored {bench_pts} on the bench, and nobody asked.",
            "I cannot let {l}'s bench go unremarked: {bench_name} ({bench_pos}) scored {bench_pts} there, and {bench_left} went unused.",
            "{l} will think about {bench_name} ({bench_pos}) all week, and the {bench_pts} the player scored on the bench.",
        ],
        "g.bench_total": [
            "It is a sorry thing to leave {bench_left} on the bench, as {l} did, and call it a lineup.",
            "A better lineup would have been worth {bench_left} to {l}, and nobody asked for it.",
            "{l} left {bench_left} sitting on the bench, which is the kind of mistake a person remembers.",
            "The bench cost {l} {bench_left}, and I suspect {l} knows it.",
            "{l} could have had {bench_left} more, and chose otherwise.",
        ],
        "g.streak_w": [
            "{w} has now won {k} in a row and stands {w_rank} at {w_rec}, and a streak like that begins to feel less like luck and more like habit.",
            "That is {k} straight for {w}, who is {w_rec} and {w_rank} in the table.",
            "{k} wins in a row now for {w}, at {w_rec}, good for {w_rank} place.",
        ],
        "g.streak_l": [
            "{l} has now lost {k} in a row and stands {l_rank} at {l_rec}, and I do not envy anyone in that group chat.",
            "That is {k} straight losses for {l}, who is {l_rec} and {l_rank} in the table.",
            "{k} defeats in a row for {l}, now {l_rec}, in {l_rank} place.",
        ],
        "g.record": [
            "{w} goes to {w_rec} ({w_rank}) and {l} to {l_rec} ({l_rank}), and the table settles a little.",
            "After {wl}, {w} is {w_rec} and {w_rank}; {l} is {l_rec} and {l_rank}.",
            "The result leaves {w} at {w_rec} and {l} at {l_rec}, for what it is worth.",
        ],
        "g.top": [
            "{w}'s {wp} was the best score of {wl}, and the league average was {wavg}.",
            "No one scored more than {w} in {wl}: {wp}, against an average of {wavg}.",
            "{wp} for {w}, the top mark of the week by some distance; the average was {wavg}.",
        ],
        "g.low": [
            "{l}'s {lp} was the lowest of {wl}, and the league average was {wavg}.",
            "No one scored less than {l} in {wl}: {lp}, against an average of {wavg}.",
            "{lp} for {l}, the low mark of the week by some distance; the average was {wavg}.",
        ],
        "g.luck_up": [
            "{n} is {n_rec}, and by the all-play numbers {luck_abs} wins better than the team has earned, which is the kind of luck you should not count on.",
            "I notice {n} is {luck_abs} wins ahead of the all-play expectation at {n_rec}. Fortune has been kind.",
            "{n} ({n_rec}) has {luck_abs} wins more than their weekly scoring deserves, and that sort of thing tends to be repaid.",
        ],
        "g.luck_down": [
            "{n} is {n_rec}, and by the all-play numbers {luck_abs} wins worse than the team has earned, which is the kind of luck you would not wish on a friend.",
            "I notice {n} is {luck_abs} wins behind the all-play expectation at {n_rec}. Fortune has not been kind.",
            "{n} ({n_rec}) has {luck_abs} wins fewer than their weekly scoring deserves, and I would expect that to be repaid in time.",
        ],
        "g.upset": [
            "Before the game, {w} stood {w_rank0} and {l} stood {l_rank0}, and the order of things was clear. It did not last.",
            "{l} ranked {l_rank0} going in and {w} ranked {w_rank0}. So much for rank.",
            "The standings had {l} {l_rank0} and {w} {w_rank0} entering {wl}, which only goes to show.",
        ],
        "g.shotgun": [
            "{n} will be paying {sgn} for {why}, as the rules require.",
            "And there is the matter of {sgn} that {n} now owes, for {why}.",
            "{n} owes {sgn} after {wl}, for {why}, and I suspect it will be paid.",
        ],
        "g.aside": [
            "{n}, who {trait}, took {event}, and carried it as one does.",
            "I think of {n}, who {trait}, and of what {wl} left behind: {event}.",
            "{n}, who {trait}, goes home with {event}.",
        ],
        "r.close_shift": [
            "And the table, as it will, moved: {in_names} climbed into the top six after {wl} and {out_names} slipped out of it. {leader} still leads at {leader_rec}.",
            "In the standings, {in_names} are now among the top six and {out_names} are not. {leader} is first at {leader_rec}.",
            "The top six changed hands a little after {wl}, with {in_names} in and {out_names} out. {leader} remains in front at {leader_rec}.",
        ],
        "r.close_table": [
            "After {wl}, {leader} stands first at {leader_rec}, and {cut} holds the last of the six playoff places at {cut_rec}.",
            "The table after {wl}: {leader} on top at {leader_rec}, and {cut} sixth at {cut_rec}.",
            "{leader} leads at {leader_rec}, and {cut} clings to sixth at {cut_rec}, for the moment.",
        ],
        "r.close_po": [
            "That was {wl}: {ngames}, a widest margin of {big_m} points ({big_w} over {big_l}), and a top score of {top_pts} from {top_w}.",
            "So ended {wl}. {big_w} won by the most, {big_m} points over {big_l}, and {top_w} scored the most, {top_pts}, in {ngames}.",
            "{ngames} are in the books for {wl}: {big_w}'s {big_m}-point win over {big_l}, and {top_w}'s {top_pts}.",
        ],
        "h.p.fav": [
            "{fav} is the favorite over {dog} in {wl}, and I would not argue",
            "{wl}: {fav} ({fav_win}) against {dog} ({dog_win})",
            "Why I like {fav} over {dog} in {wl}",
        ],
        "h.p.even": [
            "{a} and {b} meet in {wl}, and I cannot pick a side",
            "{wl}: {a} against {b}, a game with no obvious favorite",
            "Too close to call: {a} and {b} in {wl}",
        ],
        "h.p.lev": [
            "The game that matters most in {wl}: {a} against {b}",
            "{swing} points of playoff odds at stake: {a} and {b}, {wl}",
            "{wl} comes down to {a} and {b}, if you ask me",
        ],
        "p.lede": [
            "If I could watch only one game in {wl}, it would be {a_team} ({a}) against {b_team} ({b}).",
            "The game I am looking forward to in {wl} is {a} against {b}.",
            "Pull up a chair for {a} and {b}, the featured game of {wl}.",
            "With {swing} points of combined playoff swing, {a} against {b} is the game to see in {wl}.",
        ],
        "p.matchup": [
            "{a_team} ({a}) comes in at {a_rec} and {a_avg} a game; {b_team} ({b}) comes in at {b_rec} and {b_avg}.",
            "{a} is {a_rec} and scoring {a_avg} a game. {b} is {b_rec} and scoring {b_avg}. Those are the facts of the matter.",
            "On one side, {a} at {a_rec}, scoring {a_avg}; on the other, {b} at {b_rec}, scoring {b_avg}.",
            "{b_team} ({b}, {b_rec}, {b_avg} a game) will face {a_team} ({a}, {a_rec}, {a_avg}) in {wl}.",
            "Consider {a}, at {a_rec} and {a_avg} a game, and {b}, at {b_rec} and {b_avg}.",
            "{a} and {b} meet in {wl}, one at {a_rec} and one at {b_rec}, scoring {a_avg} and {b_avg}.",
        ],
        "p.h2h_split": [
            "They have met already this season and split it, {h2h_rec}, which settles nothing.",
            "{a} and {b} are even against each other this year, {h2h_rec}.",
            "The season series stands at {h2h_rec}, level.",
        ],
        "p.h2h_lead": [
            "{lead} has had the better of {trail} this season, {h2h_rec}.",
            "{trail} trails {lead} {h2h_rec} in games between the two this year, and I imagine {trail} remembers.",
            "In meetings this season, {lead} leads {h2h_rec}.",
        ],
        "p.h2h_none": [
            "They have not yet met this season, so there is nothing in the record to go on.",
            "{a} and {b} are strangers this season, as far as the schedule goes.",
            "This will be the first time {a} and {b} have met this year.",
        ],
        "p.stakes": [
            "A win would take {a} to {a_win} in playoff odds, a loss to {a_loss}; for {b}, it is {b_win} or {b_loss}. That is what is at stake.",
            "For {a}, the playoff odds are {a_win} with a win and {a_loss} without one, and for {b}, {b_win} and {b_loss}.",
            "If you want to know why this matters: {a} goes from {a_loss} to {a_win}, and {b} from {b_loss} to {b_win}, depending on the result.",
        ],
        "p.leverage": [
            "No game on the slate moves the playoff picture more: {swing} points of combined swing between the two.",
            "{swing} points of playoff swing hang on this one, more than on any other game this week.",
            "{a} and {b} are playing for {swing} points of playoff odds, and nothing else this week comes close.",
        ],
        "p.favorite": [
            "{fav} is the favorite on {fav_why}, {fav_win} to win against {dog}'s {dog_win}, and I would take that.",
            "By {fav_why}, {fav} ({fav_win} to win) stands ahead of {dog} ({dog_win}).",
            "{dog} is the underdog at {dog_win} to win, with {fav} at {fav_win}, and I have seen stranger things.",
        ],
        "p.vol": [
            "{vol_n} is the less predictable of the two, swinging {vol_std} points a week against {other_std} for {other}.",
            "A word about nerves: {vol_n} swings {vol_std} points from week to week, while {other} swings {other_std}.",
            "{other}'s scores are steadier ({other_std} points of swing) than {vol_n}'s ({vol_std}).",
        ],
        "p.rivnote": [
            "It is also {rv_name}, and I will let the record speak. {backstory}",
            "This one has an old name, {rv_name}. {backstory}",
            "And then there is {rv_name}. {backstory}",
        ],
        "p.close": [
            "Set your lineups, and may the best team win. I will be watching {a} and {b} in {wl}.",
            "That is all for now, and {a} and {b} will do the rest in {wl}.",
            "We will see how it goes for {a} and {b} in {wl}.",
        ],
        "h.t": [
            "{a} sends {gave_s} to {b} for {got_s}, and I have my doubts",
            "A swap between {a} and {b}: {gave_s} for {got_s}",
            "{b} gets {gave_s} from {a}, who takes {got_s} in return",
            "A trade worth a second look: {a} sends {gave_s} to {b} and gets {got_s} back",
        ],
        "t.sides": [
            "In {wl}, {a} and {b} made a trade. {a} took {a_got}, and {b} took {b_got}.",
            "The details, for the record: {a} received {a_got}, and {b} received {b_got}, in {wl}.",
            "{a} gave up {b_got} in {wl} and received {a_got}, which is the whole of it.",
            "{b} sent {a_got} to {a} in {wl}, and {b_got} went the other way.",
        ],
        "t.returns": [
            "The early returns, for what they are worth: over {since_wk}, {a}'s new players have scored {a_pts} and {b}'s have scored {b_pts}, and {lead} has the better of it so far.",
            "Since the deal, {lead}'s additions have produced {lead_pts}, and {trail}'s {trail_pts}, over {since_wk}.",
            "Over {since_wk}, {a}'s side of the trade has scored {a_pts} and {b}'s side {b_pts}. {lead} is ahead, but I would not carve it in stone.",
        ],
        "t.pending": [
            "Picks for players cannot be graded until the picks play a game, and I will wait.",
            "{pl_side} has the players and {pk_side} has the picks. We will know who was wise later.",
            "The verdict will come in time, and {pk_side} and {pl_side} will both hear it.",
        ],
        "t.fresh": [
            "It is too early to say who got the better of it, and I will not pretend otherwise.",
            "Time will tell. It always does.",
            "The grade will have to wait for the games.",
        ],
        "t.count": [
            "It is {n}'s {nth} trade of the season, and I begin to wonder about the phone bills.",
            "This is the {nth} deal {n} has made this year.",
            "That makes {n}'s {nth} trade of the year, a busy hand.",
        ],
        "t.rec": [
            "Going in, {a} stood {a_rank} at {a_rec} and {b} stood {b_rank} at {b_rec}.",
            "Before the deal, {a} was {a_rec} ({a_rank}); {b} was {b_rec} ({b_rank}).",
            "At the time of the trade, the table had {a} {a_rank} ({a_rec}) and {b} {b_rank} ({b_rec}).",
        ],
        "t.close": [
            "The league log lists the trade as complete.",
            "It is done, and the log says so.",
            "That is the trade, and it is on the books.",
        ],
        "h.w.big": [
            "{n} pays {bid} for {player}, and that is a good deal of money",
            "{bid} for {player} ({pos}): {n} makes a statement",
            "{n} spends {bid} on {player}",
        ],
        "h.w.small": [
            "{n} picks up {player} for {bid}",
            "{player} ({pos}) goes to {n} for {bid}",
            "A quiet claim: {n} adds {player} for {bid}",
        ],
        "h.w.free": [
            "{n} picks up {player} for nothing",
            "{player} ({pos}), free of charge, goes to {n}",
            "{n} takes a flyer on {player}",
        ],
        "w.top_bid": [
            "The biggest bid of {wl} was {bid}, from {n}, for {player} ({pos}), and that is serious money.",
            "{n} spent {bid} on {player} ({pos}) in {wl}, the largest bid of the week.",
            "If one claim made noise in {wl}, it was {n}'s {bid} for {player} ({pos}).",
        ],
        "w.top_free": [
            "{n} added {player} ({pos}) in {wl}, and it did not cost a cent.",
            "The pickup I noticed in {wl} was {player} ({pos}), by {n}.",
            "{player} ({pos}) found a home with {n} in {wl}.",
        ],
        "w.since": [
            "Since then, {player} has scored {spts} over {since_wk}, and I would call that {tier}.",
            "Over {since_wk}, {n} has had {spts} from {player}, which is {tier}.",
            "{player} has put up {spts} in the {since_wk} since, {tier}.",
        ],
        "w.others": [
            "Down the wire a way, there was more: {others_text}.",
            "Others who dipped into the pool: {others_text}.",
            "And the rest: {others_text}.",
        ],
        "w.total": [
            "All told, {total_owners} went shopping in {wl} and came home with {total_n}.",
            "{total_n} changed hands in {wl}, among {total_owners}.",
            "The wire saw {total_n} go to {total_owners} in {wl}.",
        ],
        "w.budget": [
            "{n} has now used {spent} of a {budget} FAAB budget, and the season is not over.",
            "Of {n}'s {budget} in FAAB, {spent} is gone.",
            "{n} has spent {spent} of {budget} so far, for what it is worth.",
        ],
        "w.close": [
            "{player} is now on {n}'s roster, and we will see.",
            "The league log has {player} with {n}.",
            "{n} has {player}. That is all there is to say.",
        ],
        "h.s": [
            "Week {wk}'s Beer Report: {total_n}, and a few regrets",
            "{top} owes {topn} for Week {wk}, and I am sorry to report it",
            "Shotgun ledger, Week {wk}: {total_n}",
            "A word on {top}, who leads Week {wk} with {topn}",
        ],
        "s.total": [
            "The shotgun ledger for Week {wk} lists {total_n} across {owners_n}, and I am told the beer is cold.",
            "{owners_n} will be paying {total_n} for Week {wk}.",
            "Week {wk} produced {total_n}, with {owners_n} to answer for the lot.",
        ],
        "s.owner": [
            "{n} will be settling up for {sgn}: {list}.",
            "{sgn} for {n}, thanks to {list}.",
            "On {n}'s tab: {sgn}, from {list}.",
            "{n} will be paying {sgn} for {list}.",
        ],
        "s.low": [
            "The low point of the week was {player} ({pos}), who scored {pts} for {n}.",
            "{n}'s {player} ({pos}) managed {pts}, which is as low as the ledger goes this week.",
            "I give you {player} ({pos}), {pts}, in {n}'s lineup: the floor of the week.",
        ],
        "s.leader": [
            "{leader} leads the season in shotguns with {ltotal} through Week {wk}, a distinction of a kind.",
            "Through Week {wk}, no one owes more than {leader}: {ltotal}.",
            "The season ledger belongs to {leader}, at {ltotal}.",
        ],
        "s.close": [
            "{top} is first on the Week {wk} ledger, and I hope the beer is good.",
            "Week {wk} is settled in the usual way, with {top} at the head of the line.",
            "{top} heads the Week {wk} list. Drink responsibly.",
        ],
        "h.n": [
            "The standings through {wl}: {top} first, {six} hanging on to sixth",
            "{alive} teams still have a real chance at {spots} playoff spots through {wl}",
            "{top} on top and {bottom} at the foot of the table, through {wl}",
            "Through {wl}, {six} holds the last playoff place",
        ],
        "h.nf": [
            "The final table: {top} on top, {six} just in, {seven} just out",
            "{top} finishes first and {bottom} last: the regular season, closed",
            "On the last seed: {six} gets it, and {seven} does not",
            "A season in the standings: {top} at the top, {bottom} at the bottom",
        ],
        "n.top": [
            "Through {wl}, {top} sits at the top of the standings at {top_rec}.",
            "{top} is first at {top_rec} through {wl}, and no one has taken it away yet.",
            "At the head of the table through {wl}, {top}, {top_rec}.",
            "{top} leads at {top_rec} with {top_odds} playoff odds, through {wl}.",
            "Through {wl}, {top} leads at {top_rec}, with {top_odds} playoff odds and {bye} to get a bye.",
        ],
        "n.cut": [
            "{six} ({six_rec}) holds the sixth and last playoff place, with {seven} ({seven_rec}) a step behind.",
            "The line falls between {six} ({six_rec}) and {seven} ({seven_rec}), and it is a thin line.",
            "{seven} ({seven_rec}) is first out, and {six} ({six_rec}) is last in.",
        ],
        "n.luck": [
            "The luck of it: {lucky} is {lucky_luck} wins ahead of the all-play expectation, and {unlucky} is {unlucky_luck}. Fortune plays favorites.",
            "By all-play, {lucky} has {lucky_luck} wins more than it deserves, and {unlucky} has {unlucky_luck}.",
            "If fortune is a stat, {lucky} owns {lucky_luck} of it and {unlucky} owes {unlucky_luck}.",
        ],
        "n.clinch": [
            "Those who have clinched a place: {names}.",
            "In, and safely: {names}.",
            "{names} have punched their tickets.",
        ],
        "n.elim": [
            "Those who can no longer get in: {names}.",
            "Out, mathematically: {names}.",
            "For {names}, there is next year.",
        ],
        "n.bottom": [
            "At the foot of the table sits {bottom}, at {bottom_rec}.",
            "{bottom} is last at {bottom_rec}, and it is a lonely view.",
            "Last place belongs to {bottom} ({bottom_rec}).",
        ],
        "n.eff": [
            "A word on lineups: {best_n} gets {best_pct} of the points available, {worst_n} gets {worst_pct}.",
            "In setting a lineup, {best_n} is best ({best_pct} of the possible points) and {worst_n} is worst ({worst_pct}).",
            "{best_n} makes the most of a roster at {best_pct}; {worst_n} makes the least at {worst_pct}.",
        ],
        "n.records": [
            "For the record books: the high score is {hi_pts}, by {hi_n} in Week {hi_wk}, and the biggest margin is {blow_m}, by {blow_w} over {blow_l} in Week {blow_wk}.",
            "{hi_n}'s {hi_pts} in Week {hi_wk} still stands as the top score, and {blow_w}'s {blow_m}-point win over {blow_l} in Week {blow_wk} is the widest margin.",
            "The marks to beat: {hi_pts} (by {hi_n}, Week {hi_wk}) and {blow_m} points (by {blow_w} over {blow_l}, Week {blow_wk}).",
        ],
        "n.ftop": [
            "{top} finished first at {top_rec}, with {top_pf} to show for it.",
            "The top seed went to {top}, {top_rec} and {top_pf}.",
            "{top} ended the regular season where it began wanting to be: on top, {top_rec}, {top_pf}.",
        ],
        "n.fcut": [
            "{six} took the last playoff seed at {six_rec}, and {seven} finished just short at {seven_rec}.",
            "The line fell between {six} ({six_rec}) and {seven} ({seven_rec}), and it is a cruel line.",
            "{six} ({six_rec}) made it in, and {seven} ({seven_rec}) did not, and that is how the thing goes.",
        ],
        "n.fpts": [
            "{pf_n} scored the most points all season ({pf_pts}), and {low_n} the fewest ({low_pts}).",
            "In points scored, {pf_n} led ({pf_pts}) and {low_n} trailed ({low_pts}).",
            "{pf_pts} made {pf_n} the top scorer; {low_pts} made {low_n} the lowest.",
        ],
        "n.fbottom": [
            "{bottom} came in last, at {bottom_rec}, and I would not call it a surprise.",
            "At the bottom of the table, {bottom}, {bottom_rec}.",
            "Last place went to {bottom}, at {bottom_rec}.",
        ],
        "n.close": [
            "That is how the table stands through {wl}, with {top} in front.",
            "Through {wl}, {top} leads, and that is the lay of the land.",
            "{top} remains first through {wl}.",
        ],
        "h.f": [
            "{a} and {b}: a quarrel worth a column",
            "I have been thinking about {a} and {b}",
            "On {a} and {b}, and the long memory of a league",
            "A word about {a} and {b}",
        ],
        "f.h2h": [
            "The trouble, as I see it, began in Week {gwk}, when {w} {verb} {l}, {wp} to {lp}, by {m} points.",
            "In Week {gwk}, {w} beat {l}, {wp}-{lp}, by {m}, and some wounds do not close.",
            "{l} lost to {w} in Week {gwk}, {lp} to {wp}, and has not forgotten.",
        ],
        "f.trade": [
            "In Week {twk}, the two did business: {a} took {a_got}, and {b} took {b_got}. In my experience, trades like that stay with people.",
            "They traded in Week {twk}, {a} getting {a_got} and {b} getting {b_got}, and I do not think either has stopped counting.",
            "In Week {twk}, {b_got} went to {b} and {a_got} to {a}.",
        ],
        "f.adj": [
            "{hi} ({hi_rec}, {hi_rank}) and {lo} ({lo_rec}, {lo_rank}) live in the same neighborhood of the standings, {pf_gap} apart.",
            "Neighbors in the table, {hi} is {hi_rank} and {lo} is {lo_rank}, with {pf_gap} between them in points.",
            "{lo} trails {hi} by {pf_gap} in points scored, {lo_rank} to {hi_rank}, and watches closely.",
        ],
        "f.blow": [
            "Nothing sticks like a beating, and in Week {gwk}, {w} {verb} {l}, {wp} to {lp}, by {m}.",
            "I was struck by Week {gwk}, when {w} beat {l} by {m} points, {wp}-{lp}.",
            "{w}'s {m}-point win over {l} in Week {gwk} ({wp}-{lp}) is a margin people remember.",
            "In Week {gwk}, {w} won by {m} over {l}, and I have not forgotten it.",
        ],
        "f.sg": [
            "On the shotgun ledger, {a} has {a_sg} and {b} has {b_sg}, a small comfort or a large one.",
            "As for the beer, {a} owes {a_sg} and {b} owes {b_sg} this season.",
            "{a} stands at {a_sg} on the ledger, {b} at {b_sg}.",
        ],
        "f.story": [
            "The league has a name for it, {rv_name}, and a story to go with it. {backstory}",
            "This is {rv_name}. {backstory}",
            "Old-timers call it {rv_name}. {backstory}",
        ],
        "f.trait": [
            "{a} {a_trait}, and {b} {b_trait}, and I would say that tells you most of what you need to know.",
            "One owner {a_trait}; the other {b_trait}. Put them in a league and see.",
            "{a} {a_trait}. {b} {b_trait}. Draw your own conclusion.",
        ],
        "f.mid": [
            "Through Week {wk}, {a} is {a_rec} ({a_rank}), and {b} is {b_rec} ({b_rank}).",
            "As of Week {wk}, {a} stands {a_rank} at {a_rec} and {b} stands {b_rank} at {b_rec}.",
            "{a} ({a_rec}, {a_rank}) and {b} ({b_rec}, {b_rank}), through Week {wk}.",
        ],
        "f.close": [
            "I do not expect this to end soon, and I do not think either would want it to.",
            "Feuds, in my experience, outlast the seasons that begin them.",
            "We will see how it goes. We always do.",
        ],
        "h.v": [
            "{rv_name} returns in Week {wk}: {a} against {b}",
            "{a} and {b}, and the old business of {rv_name}",
            "Week {wk} and {rv_name}: a column",
            "On {rv_name}, and why Week {wk} matters",
        ],
        "v.lede": [
            "I have been waiting for this one. {rv_name} is back in {wl}, with {a} against {b}. {backstory}",
            "Some games have a history, and {rv_name} is one: {a} against {b} in {wl}. {backstory}",
            "{wl} brings {rv_name}, {a} against {b}. {backstory}",
        ],
        "v.form": [
            "{a} is {a_rec} ({a_rank}) and scoring {a_avg} a game; {b} is {b_rec} ({b_rank}) and scoring {b_avg}.",
            "{a} comes in {a_rank} at {a_rec} ({a_avg} a game), and {b} comes in {b_rank} at {b_rec} ({b_avg} a game).",
            "On form, {b} stands {b_rank} at {b_rec} with {b_avg} a game, and {a} stands {a_rank} at {a_rec} with {a_avg}.",
        ],
        "v.close": [
            "I will be watching in Week {wk}, as will {a} and {b}, no doubt.",
            "Week {wk} will add a chapter to the story of {a} and {b}.",
            "See you in Week {wk}, {a} and {b}.",
        ],
        "h.o": [
            "A look back at an offseason of {ntrades} and {npick}",
            "{ntrades} and {npick}: what a winter",
            "The offseason, remembered: {ntrades}, {npick}",
        ],
        "o.lede": [
            "Before a single snap of the season, the league logged {ntrades} and {npick}, and I am told it was a busy winter.",
            "The winter produced {ntrades} and {npick}, according to the log.",
            "Count them up: {ntrades}, {npick}, all before the opening kickoff.",
        ],
        "o.busy": [
            "The busiest traders were {busy_text}, and I salute their stamina.",
            "By number of trades: {busy_text}.",
            "The ones who could not sit still: {busy_text}.",
        ],
        "o.big": [
            "The largest deal sent {b_got} to {side_b} and {a_got} to {side_a}, and I imagine both of them thought they won.",
            "The biggest trade of the winter: {side_a} received {a_got}, and {side_b} received {b_got}.",
            "{side_a} took {a_got}, and {side_b} took {b_got}, in the largest deal of the offseason.",
        ],
        "o.close": [
            "{busiest} made the most trades, and I tip my cap.",
            "No one traded more than {busiest}.",
            "{busiest} led the winter in trades.",
        ],
        # ---------------- Sunday column ----------------
        "h.c": [
            "Sunday thoughts on {a} and {b}",
            "What {a} and {b} say, and what the standings say back",
            "{a}, {b}, and the old art of talking big",
            "On the fine tradition of {a} and {b} insulting each other",
        ],
        "h.c.rv": [
            "{rv_name}, and what {a} and {b} owe each other",
            "A Sunday with {a} and {b}, and the long shadow of {rv_name}",
            "Some things never change: {a}, {b}, and {rv_name}",
        ],
        "h.c.next": [
            "Before Week {nwk}: {a}, {b}, and a great deal of talk",
            "The quiet before {a} and {b} meet in Week {nwk}",
            "Sunday, and {a} and {b} have a game coming in Week {nwk}",
        ],
        "c.lede": [
            "It is Sunday, which is the day for taking stock, and through {wl} {a} stands {a_rank} at {a_rec} while {b} stands {b_rank} at {b_rec}.",
            "The table through {wl} has {a} ({a_rec}) at {a_rank} and {b} ({b_rec}) at {b_rank}, and I find I have opinions.",
            "Through {wl}, {a} is {a_rec} and {a_rank}, and {b} is {b_rec} and {b_rank}. Every argument in this column starts there.",
        ],
        "c.next": [
            "They meet in Week {nwk}, and I suspect each has been rehearsing for it.",
            "The schedule has {a} and {b} meeting in Week {nwk}, which is how these things usually get settled.",
            "Week {nwk} will have them across from each other, and the talk will be tested.",
        ],
        "c.recent": [
            "Lately, {a} {a_form}, and {b} {b_form}. A few games do not make a character, but they make a mood.",
            "In recent weeks {a} {a_form}, while {b} {b_form}, and I leave the reader to draw the moral.",
            "Look at how they have been playing: {a} {a_form}, and {b} {b_form}.",
        ],
        "c.gap": [
            "The table has {hi} {hi_rank} at {hi_rec} and {lo} {lo_rank} at {lo_rec}, with {pf_gap} between them in points scored, which is the distance between talking and doing.",
            "{hi} stands {hi_rank} and {lo} stands {lo_rank}, and in points scored there are {pf_gap} between them. I would not call that nothing.",
            "{hi} ({hi_rec}) is above {lo} ({lo_rec}) in the standings, {hi_rank} to {lo_rank}, and {pf_gap} of scoring comes between them.",
        ],
        "c.pick": [
            "If I must pick, and I am told I must, I pick {fav} over {dog}, going by {fav_why}.",
            "My pick is {fav}, on {fav_why}, and I make it without enthusiasm for {dog}'s prospects.",
            "I will take {fav} over {dog}, going by {fav_why}, and it is a hard thing to argue with.",
        ],
        "c.close": [
            "I expect {a} and {b} to say it all again next week, and I will be glad to hear it.",
            "That is how it stands between {a} and {b}, and it is how it has always stood.",
            "Say what you like, {a} and {b}. The standings are patient, and so am I.",
        ],
        # ---------------- Monday analytics ----------------
        "h.a.luck": [
            "A Monday word on luck: {lucky} has it, {unlucky} does not",
            "Fortune and its favorites: {lucky} at {lucky_luck}, {unlucky} at {unlucky_luck}",
            "{unlucky} deserved better, and {lucky} knows it",
        ],
        "h.a.eff": [
            "On setting lineups: {best_n} at {best_pct}, {worst_n} at {worst_pct}",
            "A Monday lesson in lineups, with {best_n} as teacher and {worst_n} as pupil",
            "The craft of the lineup: {best_n} has it, {worst_n} is still looking",
        ],
        "h.a.bench": [
            "{bench_n} and the points left on the bench",
            "What {bench_n} left on the bench: {bench_pts}",
            "A Monday reckoning with the bench, and {bench_n} first in line",
        ],
        "h.a.steady": [
            "In praise of the steady hand: {steady_n}, and the restless {wild_n}",
            "{steady_n} keeps a level head; {wild_n} does not",
            "Consistency, and who has it: {steady_n} yes, {wild_n} no",
        ],
        "a.lede": [
            "Monday is for the numbers, and these run through {wl}, {gp} to a team, which is enough to say something and not enough to say everything.",
            "I keep a little ledger on Mondays. Through {wl}, with {gp} played by each team, here is what it says.",
            "The figures below come through {wl}, after {gp} for every team, and I have tried to read them fairly.",
        ],
        "a.luck": [
            "Fortune has been uneven. {lucky} is {lucky_rec} where the all-play numbers say {lucky_exp} wins, a luck index of {lucky_luck}, while {unlucky} is {unlucky_rec} where they say {unlucky_exp}, which is {unlucky_luck}.",
            "I have never trusted a record without asking what luck had to do with it. {lucky} is {lucky_rec} on {lucky_exp} expected wins ({lucky_luck}); {unlucky} is {unlucky_rec} on {unlucky_exp} ({unlucky_luck}).",
            "{lucky} has been the beneficiary, {lucky_luck} wins above what the all-play record deserves ({lucky_rec}, expected {lucky_exp}). {unlucky} has paid for it, at {unlucky_luck} ({unlucky_rec}, expected {unlucky_exp}).",
        ],
        "a.eff": [
            "A lineup is a small act of judgment made every week, and judged by points scored against the best possible lineup, {best_n} makes it best at {best_pct} and {worst_n} worst at {worst_pct}. The league as a whole manages {lg_pct}.",
            "Taking the points scored as a share of the points that were there to be had, {best_n} leads at {best_pct}, {worst_n} trails at {worst_pct}, and the whole league sits at {lg_pct}.",
            "{best_n} gets {best_pct} of what a roster offers. {worst_n} gets {worst_pct}. The league, on average, gets {lg_pct}, and I find that humbling.",
        ],
        "a.bench": [
            "Nothing teaches regret like the bench. {bench_n} has left {bench_pts} there, measured against the best possible lineup, and {bench_low_n} only {bench_low_pts}.",
            "The bench keeps its own score. {bench_n} leads in points left on it ({bench_pts}); {bench_low_n} has left the fewest ({bench_low_pts}).",
            "Against the best lineup each roster could have set, {bench_n} fell {bench_pts} short and {bench_low_n} just {bench_low_pts}.",
        ],
        "a.blunder": [
            "The worst single afternoon belongs to {bl_n}, in Week {bl_wk}, when the lineup finished {bl_pts} below the best one available, and the bench's top scorer, {bl_player} ({bl_pos}), had {bl_player_pts}.",
            "In Week {bl_wk}, {bl_n} gave up {bl_pts} against the best possible lineup, the biggest such week yet, and I note that {bl_player} ({bl_pos}) scored {bl_player_pts} from the bench.",
            "Every owner has one week they would like back. For {bl_n} it was Week {bl_wk}: {bl_pts} short of the best lineup, with {bl_player} ({bl_pos}) at {bl_player_pts} on the bench.",
        ],
        "a.steady": [
            "Then there is consistency, which I admire more than I should. {steady_n} has averaged a weekly rank of {steady_avg}, ranging from {steady_band}, while {wild_n} has ranged from {wild_band}.",
            "By weekly rank, {steady_n} is the steady hand (average {steady_avg}, from {steady_band}), and {wild_n} the restless one, from {wild_band}.",
            "Some owners are weather and some are climate. {steady_n} is climate, from {steady_band} and averaging {steady_avg}; {wild_n} is weather, from {wild_band}.",
        ],
        "a.trade": [
            "And the trade of Week {twk}, since you ask: over {since_wk}, the players {lead} took in have scored {lead_pts}, and the players {trail} took in have scored {trail_pts}. Early days, but it is something.",
            "I have been watching the Week {twk} trade between {lead} and {trail}. In the {since_wk} since, {lead}'s side has the better of it, {lead_pts} to {trail_pts}.",
            "The early returns on the Week {twk} deal favor {lead}, {lead_pts} to {trail}'s {trail_pts}, across {since_wk}. Trades are judged slowly.",
        ],
        "a.close": [
            "That is the ledger through {wl}, and I will open it again next Monday.",
            "Numbers explain a good deal, and excuse nothing.",
            "Put the figures away for now, and enjoy the week.",
        ],
        "x.sig": [
            "Then {n} said what {n} always says: “{catch}”",
            "And {n}, as is the custom, added: “{catch}”",
            "{n} could not resist the old line: “{catch}”",
        ],
        "x.attr": [
            "“{qc}” {n} said to me, and not unkindly.",
            "{n} told me: “{qp}”",
            "“{qc}” {n} offered, and I could not argue.",
            "As {n} put it: “{qp}”",
            "“{qc}” {n} said, and left it at that.",
            "“{qc}” {n} said over the phone, and I let it stand.",
            "{n} put it to me this way: “{qp}”",
            "“{qc}” {n} said, with a straight face.",
            "“{qc}” {n} told me, and I wrote it down.",
            "I asked {n} about it. The answer: “{qp}”",
            "“{qc}” {n} said, which was more than I expected.",
        ],
    },
}
