"""Courtroom brief: findings of fact, exhibits, motions, verdicts. The box score is the transcript."""
FAMILY = {
    "id": "courtroom",
    "label": "Courtroom brief",
    "desc": "Legal-brief voice: findings of fact, exhibits, motions, rulings, 'the record reflects'. Formal and exact, with a straight face that makes the pettiest dispute sound like constitutional law.",
    "rhythm": "medium formal sentences, numbered in spirit",
    "formality": "very high, legalistic",
    "metaphors": "trials, evidence, motions, verdicts, appeals",
    "numbers": "exact, entered into evidence",
    "lex": {
        "verb": {
            "blowout": ["prevailed overwhelmingly over", "won a summary judgment against", "obliterated"],
            "comfortable": ["prevailed over", "won a clear judgment against", "was granted judgment against"],
            "normal": ["defeated", "beat", "prevailed against"],
            "close": ["narrowly prevailed over", "survived", "edged"],
        },
        "noun": {
            "blowout": ["a summary judgment", "a crushing verdict", "a total rout"],
            "comfortable": ["a clear verdict", "a decisive ruling", "a sound judgment"],
            "normal": ["an ordinary ruling", "a standard verdict", "a plain judgment"],
            "close": ["a split decision", "a narrow verdict", "a photo-finish ruling"],
        },
        "tier": {
            "hi": ["well-founded, the record shows", "vindicated by the evidence", "a sound investment"],
            "mid": ["adequate, per the record", "within reason", "unremarkable but sound"],
            "lo": ["unproven so far", "poorly supported by the evidence so far", "wanting to date"],
        },
    },
    "T": {
        "h.r.blow": [
            "Judgment in {wl}: {w} {verb} {l}, {wp}-{lp}",
            "Judgment for {w}: {m} points over {l}",
            "{w_team} v. {l_team}: {wp}-{lp}, {noun}",
        ],
        "h.r.upset": [
            "Verdict contrary to the standings: {w} ({w_rank0}) over {l} ({l_rank0})",
            "{w} defeats {l} in {wl}; the table is overruled",
            "Motion to reverse the standings granted: {w}, {wp}; {l}, {lp}",
        ],
        "h.r.close": [
            "Ruling in {wl}: {w} {verb} {l}, margin {m}",
            "Narrow verdict: {w} over {l}, {wp}-{lp}",
            "{m} points decide {w} v. {l}",
        ],
        "h.r.top": [
            "Exhibit A: {w}'s {wp}, the highest score of {wl}",
            "{w} posts {wp}, the week's top score, in judgment against {l}",
            "The record shows {wp} for {w} in {wl}: the week's best",
        ],
        "h.r.tie": [
            "Mistrial: {a} and {b} tie at {pts}",
            "No verdict: {a} and {b} each score {pts}",
            "Hung jury in {wl}: {a} and {b} at {pts} apiece",
        ],
        "r.lede.blow": [
            "The court has before it the results of {wl}. In the matter of {w} v. {l}, judgment was entered for {w}, {wp} to {lp}, by {m} points, the widest margin of the week.",
            "Let the record show that {w_team} ({w}) {verb} {l_team} ({l}) in {wl}, {wp}-{lp}. The margin, {m} points, was the largest of the period: {noun}.",
            "The finding of the court is plain: {w} won by {m} points over {l}, {wp} to {lp}, the largest margin in {wl}.",
        ],
        "r.lede.upset": [
            "In a result contrary to the standings, {w}, ranked {w_rank0} entering {wl}, {verb} {l}, ranked {l_rank0}, {wp} to {lp}. The record shows it was the largest ranking reversal of the week.",
            "The standings predicted {l} ({l_rank0}) over {w} ({w_rank0}). The court finds otherwise: {wp}-{lp} for {w} in {wl}.",
            "Let it be entered: {w}, {w_rank0}, defeated {l}, {l_rank0}, {wp} to {lp}, overturning the standings in {wl}.",
        ],
        "r.lede.close": [
            "The narrowest ruling of {wl} was in {w} v. {l}: {wp} to {lp}, by {m} points. The court describes it as {noun}.",
            "Exhibit A: {w}'s {wp}-{lp} win over {l_team} ({l}), by {m} points, the closest result of the period.",
            "By a margin of {m} points, {w} {verb} {l} in {wl}, {wp} to {lp}, the tightest verdict of the week.",
        ],
        "r.lede.top": [
            "Entered into evidence: {w}'s {wp} in {wl}, the highest score of the week (league average: {wavg}), which carried judgment against {l}, who scored {lp}.",
            "The highest figure in the record for {wl} is {wp}, scored by {w_team} ({w}). The opposing party, {l}, scored {lp}. The league average was {wavg}.",
            "The court notes that {w} posted the week's top score, {wp}, against a league average of {wavg}, in judgment over {l} ({lp}).",
        ],
        "r.lede.tie": [
            "The court declares a mistrial: {a_team} ({a}) and {b_team} ({b}) each scored {pts} in {wl}.",
            "No judgment is entered. {a} and {b} each scored {pts} in {wl}.",
            "The parties, {a} and {b}, tied at {pts} points apiece in {wl}, and the court has no winner to name.",
        ],
        "g.result": [
            "For the plaintiff, {w_team} ({w}): {verb} {l_team} ({l}), {wp}-{lp}.",
            "In {w} v. {l}, judgment was for {w}, {wp} to {lp}.",
            "In {wl}, {w_nick} {verb} {l}: {wp}-{lp}.",
            "{l_nick} lost to {w}, {lp}-{wp}, by {m}. The court classifies it as {noun}.",
            "The record: {w}, {wp}; {l}, {lp}. Margin: {m}. {noun}.",
            "{w} and {l} appeared in {wl}; the judgment went to {w}, {wp}-{lp}.",
            "{l} lost the case to {w}, {lp} to {wp}.",
            "The court enters {wp}-{lp} for {w} against {l}.",
            "{w} {verb} {l}; margin {m}.",
            "Verdict: {w}, {wp}; {l}, {lp}.",
        ],
        "g.tie": [
            "{a} and {b}: {pts} each. Mistrial.",
            "The court finds {a_team} ({a}) and {b_team} ({b}) level at {pts}.",
            "{pts} to {pts}: the parties, {a} and {b}, are tied.",
        ],
        "g.star": [
            "Exhibit: {star} ({spos}) produced {spts} for {w}, {sshare} of the {wp} total.",
            "The strongest witness for {w} was {star} ({spos}), who contributed {spts}.",
            "{star} ({spos}) accounted for {spts} of {w}'s {wp}, a {sshare} share.",
        ],
        "g.goat": [
            "The court notes that {gname} ({gpos}) produced only {gpts} for {l}.",
            "Testimony from {gname} ({gpos}), starting for {l}, amounted to {gpts}.",
            "{l}'s {gpos} slot was unsupported by the evidence: {gname}, {gpts}.",
        ],
        "g.bench": [
            "In mitigation, {l} left {bench_left} on the bench; {bench_name} ({bench_pos}) scored {bench_pts} without starting.",
            "The record reflects {bench_left} on {l}'s bench, including {bench_pts} from {bench_name} ({bench_pos}).",
            "{l}'s case is undermined by the bench: {bench_name} ({bench_pos}), {bench_pts}, unused. The optimal lineup was worth {bench_left} more.",
        ],
        "g.streak_w": [
            "{w} has now prevailed {k} consecutive times and stands {w_rank} at {w_rec}.",
            "The record shows {k} straight wins for {w}, now {w_rec} and {w_rank}.",
            "{w}'s record: {w_rec}, {w_rank}, with {k} consecutive victories.",
        ],
        "g.streak_l": [
            "{l} has now lost {k} consecutive times and stands {l_rank} at {l_rec}.",
            "The record shows {k} straight losses for {l}, now {l_rec} and {l_rank}.",
            "{l}'s record: {l_rec}, {l_rank}, with {k} consecutive defeats.",
        ],
        "g.record": [
            "{w} improves to {w_rec} ({w_rank}); {l} falls to {l_rec} ({l_rank}).",
            "The standings now show {w}, {w_rec}, {w_rank}, and {l}, {l_rec}, {l_rank}.",
            "After {wl}, the record stands: {w}, {w_rec}; {l}, {l_rec}.",
        ],
        "g.top": [
            "{w}'s {wp} was the highest score of {wl}. League average: {wavg}.",
            "No party scored more than {w} in {wl}: {wp}. The league average was {wavg}.",
            "{wp}: the week's high mark, entered by {w}. The average was {wavg}.",
        ],
        "g.low": [
            "{l}'s {lp} was the lowest score of {wl}. League average: {wavg}.",
            "No party scored less than {l} in {wl}: {lp}. The league average was {wavg}.",
            "{lp}: the week's low mark, entered by {l}. The average was {wavg}.",
        ],
        "g.luck_up": [
            "The court notes that {n} ({n_rec}) enjoys {luck} wins above its all-play expectation, a favorable circumstance.",
            "By all-play, {n} is {luck} wins to the good at {n_rec}, a fact the record does not dispute.",
            "{n}: {n_rec}, with {luck} wins above expectation. Fortune has been found in its favor.",
        ],
        "g.luck_down": [
            "The court notes that {n} ({n_rec}) suffers {luck} wins below its all-play expectation, an unfavorable circumstance.",
            "By all-play, {n} is {luck} wins behind at {n_rec}, a fact the record does not dispute.",
            "{n}: {n_rec}, with {luck} wins below expectation. Fortune has been found against it.",
        ],
        "g.upset": [
            "For the record, {w} was ranked {w_rank0} and {l} was ranked {l_rank0} entering the game.",
            "The prior standings had {l} at {l_rank0} and {w} at {w_rank0}.",
            "Pre-game ranking: {l}, {l_rank0}; {w}, {w_rank0}.",
        ],
        "g.shotgun": [
            "{n} is hereby ordered to pay {sgn}, for {why}.",
            "The ledger finds {n} liable for {sgn}: {why}.",
            "{n} owes {sgn} for {wl}, on the grounds of {why}.",
        ],
        "g.aside": [
            "{n}, who {trait}, bears {event}, as entered into the record.",
            "The court notes {n}, who {trait}, and what {wl} left behind: {event}.",
            "{n}, who {trait}, now stands charged with {event}.",
        ],
        "r.close_shift": [
            "The standings are amended as follows: {in_names} are now in the top six, and {out_names} are out. {leader} remains first at {leader_rec}.",
            "Following {wl}, {in_names} hold playoff positions and {out_names} do not. {leader} leads at {leader_rec}.",
            "By order of the table, {in_names} advance into the top six and {out_names} are removed from it after {wl}. {leader}: first, {leader_rec}.",
        ],
        "r.close_table": [
            "The standings after {wl}: {leader} leads at {leader_rec}, and {cut} holds the sixth and final playoff position at {cut_rec}.",
            "As of {wl}, {leader} is first ({leader_rec}), and {cut} is sixth ({cut_rec}).",
            "The record stands: {leader}, {leader_rec}, first; {cut}, {cut_rec}, sixth, after {wl}.",
        ],
        "r.close_po": [
            "The record for {wl}: {ngames}. The largest margin was {big_m} points, {big_w} over {big_l}. The highest score was {top_w}'s {top_pts}.",
            "In {wl}, {ngames} were decided. {big_w} prevailed over {big_l} by the widest margin, {big_m}; {top_w} entered the top score, {top_pts}.",
            "{ngames} were entered in {wl}: {big_w}'s {big_m}-point judgment against {big_l}, and {top_w}'s {top_pts}.",
        ],
        "h.p.fav": [
            "The court presumes for {fav} over {dog} in {wl}",
            "{wl}: the court finds for {fav} ({fav_odds}) over {dog} ({dog_odds})",
            "{fav} v. {dog}: the presumption favors {fav}",
        ],
        "h.p.even": [
            "{a} v. {b}: no presumption in {wl}",
            "{wl}: {a} and {b} presented as equals at {a_odds} and {b_odds}",
            "A toss-up in {wl}: {a} v. {b}",
        ],
        "h.p.lev": [
            "{a} v. {b}: the case of {wl}, with {swing} points at stake",
            "The matter of {wl}: {a} and {b}, playoff position in the balance",
            "Most consequential case on the {wl} docket: {a} v. {b}",
        ],
        "p.lede": [
            "The court calls the featured case of {wl}: {a_team} ({a}) v. {b_team} ({b}).",
            "On the docket for {wl}, the case of {a} v. {b}.",
            "The matter before the league in {wl} is {a} against {b}.",
            "{a} v. {b} carries {swing} points of combined playoff-odds swing in {wl}, the highest of any case on the docket.",
        ],
        "p.matchup": [
            "The parties: {a_team} ({a}, {a_rec}, {a_avg} per game) and {b_team} ({b}, {b_rec}, {b_avg}).",
            "{a} appears at {a_rec}, scoring {a_avg} per game. {b} appears at {b_rec}, scoring {b_avg}.",
            "Facts of the case: {a} ({a_rec}, {a_avg}) against {b} ({b_rec}, {b_avg}) in {wl}.",
            "{b_team} ({b}, {b_rec}, {b_avg}) is set against {a_team} ({a}, {a_rec}, {a_avg}) in {wl}.",
        ],
        "p.h2h_split": [
            "The prior record between the parties is split, {h2h_rec}.",
            "{a} and {b} are level in earlier meetings this season, {h2h_rec}.",
            "Precedent is divided: {h2h_rec} between {a} and {b} this season.",
        ],
        "p.h2h_lead": [
            "Precedent favors {lead}, who leads {trail} {h2h_rec} this season.",
            "{trail} trails {lead} {h2h_rec} in prior meetings this season.",
            "On the prior record, {lead} leads {h2h_rec}.",
        ],
        "p.h2h_none": [
            "There is no precedent: {a} and {b} have not met this season.",
            "The parties have not previously met this season.",
            "This is a case of first impression for {a} and {b}.",
        ],
        "p.stakes": [
            "The stakes, per the simulations: {a} stands at {a_win} playoff odds with a win and {a_loss} with a loss; {b} stands at {b_win} and {b_loss}.",
            "A win would carry {a} to {a_win}; a loss, to {a_loss}. For {b}, the figures are {b_win} and {b_loss}.",
            "Remedies available: {a} moves between {a_loss} and {a_win}, and {b} between {b_loss} and {b_win}.",
        ],
        "p.leverage": [
            "The matter is of consequence: {swing} points of combined playoff swing, the most on the docket.",
            "No case on the docket carries more weight than {a} v. {b}: {swing} points of swing.",
            "{a} and {b} contest {swing} points of playoff odds, more than any other case this week.",
        ],
        "p.favorite": [
            "The presumption favors {fav} on {fav_why}: {fav_odds} to {dog}'s {dog_odds}.",
            "On {fav_why}, the court finds {fav} ({fav_odds}) ahead of {dog} ({dog_odds}).",
            "{dog} bears the burden at {dog_odds}; {fav} stands at {fav_odds}.",
        ],
        "p.vol": [
            "The court notes that {vol_n} is the less predictable witness: {vol_std} points of weekly variation to {other_std} for {other}.",
            "{vol_n}'s scoring varies by {vol_std} points a week; {other}'s varies by {other_std}.",
            "{other} has been the steadier party ({other_std}); {vol_n} has not ({vol_std}).",
        ],
        "p.rivnote": [
            "For context, this case is also known as {rv_name}. {backstory}",
            "The parties have a history, entered as {rv_name}. {backstory}",
            "Note for the record: this is {rv_name}. {backstory}",
        ],
        "p.close": [
            "The court will reconvene for {a} and {b} in {wl}.",
            "{a} and {b} are summoned for {wl}.",
            "Both parties are expected in {wl}.",
        ],
        "h.t": [
            "{a} sends {gave_s} to {b} for {got_s}: terms of the agreement",
            "{a} and {b} execute a trade: {gave_s} for {got_s}",
            "{b} takes {gave_s} from {a} in consideration of {got_s}",
            "Agreement entered: {gave_s} passes from {a} to {b}, {got_s} returns",
        ],
        "t.sides": [
            "The parties, {a} and {b}, executed a trade in {wl}. {a} received {a_got}. {b} received {b_got}.",
            "Terms of the {wl} agreement: {a} takes {a_got}; {b} takes {b_got}.",
            "In {wl}, {a} conveyed {b_got} to {b} in consideration of {a_got}.",
            "{b} sent {a_got} to {a} in {wl}, and received {b_got}.",
        ],
        "t.returns": [
            "Evidence of performance: over {since_wk}, {a}'s consideration has produced {a_pts}, and {b}'s {b_pts}. {lead} leads on the record.",
            "Post-agreement production, {since_wk}: {lead}, {lead_pts}; {trail}, {trail_pts}.",
            "After {since_wk}, {a}'s side has {a_pts} and {b}'s has {b_pts}. The court finds early advantage for {lead}.",
        ],
        "t.pending": [
            "{pk_side} received {pk_got}; {pl_side} received {pl_got}. Picks have no production, and the court reserves judgment.",
            "A trade of picks for players: {pl_side} holds {pl_got}, and {pk_side} holds {pk_got}. The matter is not yet ripe.",
            "{pl_side} took {pl_got}; {pk_side} took {pk_got}. Judgment is deferred until the picks produce.",
        ],
        "t.fresh": [
            "The matter is not yet ripe for judgment.",
            "The court reserves judgment pending production.",
            "Insufficient evidence exists to grade the trade.",
        ],
        "t.count": [
            "The record shows this is {n}'s {nth} trade of the season.",
            "{n} has now executed the {nth} trade of this season.",
            "For {n}, this is the {nth} such agreement of the year.",
        ],
        "t.rec": [
            "At the time of the agreement, {a} was {a_rec} ({a_rank}) and {b} was {b_rec} ({b_rank}).",
            "The standings entering that week: {a}, {a_rank}, {a_rec}; {b}, {b_rank}, {b_rec}.",
            "For the record, {a} stood {a_rank} at {a_rec}, and {b} stood {b_rank} at {b_rec}.",
        ],
        "t.close": [
            "The league log lists the trade as complete and binding.",
            "The agreement is final and entered into the record.",
            "No appeal has been logged.",
        ],
        "h.w.big": [
            "{n} bids {bid} for {player}, the week's largest",
            "Motion granted: {player} ({pos}) to {n} for {bid}",
            "{n} is granted {player} upon payment of {bid}",
        ],
        "h.w.small": [
            "{n} claims {player} for {bid}",
            "{player} ({pos}) awarded to {n}, {bid}",
            "{n} files a successful {bid} claim for {player}",
        ],
        "h.w.free": [
            "{n} files for free agent {player}, no consideration given",
            "{player} ({pos}) goes to {n} without consideration",
            "{n} takes {player} from the waiver pool",
        ],
        "w.top_bid": [
            "{n} bid {bid} for {player} ({pos}) in {wl}, the largest claim of the week.",
            "The largest waiver bid in {wl} was {bid}, by {n}, for {player} ({pos}).",
            "{n} was awarded {player} ({pos}) at a price of {bid}, the highest of {wl}.",
        ],
        "w.top_free": [
            "{n} added {player} ({pos}) in {wl}, without consideration.",
            "The record shows {player} ({pos}) taken up by {n} in {wl}.",
            "The notable filing of {wl}: {player} ({pos}), by {n}.",
        ],
        "w.since": [
            "Evidence of value: {player} has scored {spts} over {since_wk}, {tier}.",
            "Evidence since the filing, {since_wk}: {n} has received {spts} from {player}, which the court deems {tier}.",
            "{player} has produced {spts} in the {since_wk} since filing, {tier}.",
        ],
        "w.others": [
            "Other claims on the docket: {others_text}.",
            "Additional filings: {others_text}.",
            "Also entered: {others_text}.",
        ],
        "w.total": [
            "In total, {total_owners} filed for {total_n} in {wl}.",
            "{total_n} changed hands among {total_owners} in {wl}.",
            "The docket for {wl} shows {total_n} awarded to {total_owners}.",
        ],
        "w.budget": [
            "{n} has used {spent} of a {budget} FAAB allowance.",
            "FAAB on the record: {n}, {spent} of {budget}.",
            "{n}'s expenditure to date is {spent} against {budget}.",
        ],
        "w.close": [
            "{player} is now on {n}'s roster, per the record.",
            "The league log shows {player} with {n}.",
            "{n} holds {player}. So entered.",
        ],
        "h.s": [
            "Shotgun docket, Week {wk}: {total_n} owed",
            "{top} is liable for {topn} in Week {wk}",
            "Week {wk} ledger: {total_n} found owing",
            "{top} heads the Week {wk} judgment list with {topn}",
        ],
        "s.total": [
            "The Week {wk} ledger lists {total_n} against {owners_n}.",
            "{owners_n} are liable for a combined {total_n} for Week {wk}.",
            "Judgment for Week {wk}: {total_n}, owed by {owners_n}.",
        ],
        "s.owner": [
            "{n} is liable for {sgn}: {list}.",
            "{sgn} against {n}, on the grounds of {list}.",
            "{n}: {sgn}. Grounds: {list}.",
            "The court finds {n} owes {sgn} ({list}).",
        ],
        "s.low": [
            "The lowest exhibit on the ledger: {player} ({pos}), {pts}, in {n}'s lineup.",
            "{n}'s {player} ({pos}) produced {pts}, the week's lowest figure.",
            "At {pts}, {player} ({pos}) set the floor for {n}.",
        ],
        "s.leader": [
            "{leader} leads the season docket with {ltotal} through Week {wk}.",
            "Through Week {wk}, no party is liable for more than {leader}: {ltotal}.",
            "The season total is highest against {leader}: {ltotal}.",
        ],
        "s.close": [
            "{top} is named first on the Week {wk} list. So ordered.",
            "{top} heads the Week {wk} ledger. Payment is expected.",
            "The Week {wk} list begins with {top}.",
        ],
        "h.n": [
            "Standings through {wl}: {top} first, {six} at the line",
            "{alive} teams retain standing for {spots} playoff places through {wl}",
            "{top} first, {bottom} last: the record through {wl}",
            "Through {wl}, the court seats {six} in the final playoff position",
        ],
        "h.nf": [
            "Final judgment: {top} is awarded the top seed",
            "{six} is in; {seven} is out: the final judgment",
            "{top} first, {bottom} last: the record of the regular season",
            "The playoff field is decided: {six} in, {seven} out",
        ],
        "n.top": [
            "Through {wl}, the court finds {top} first in the standings at {top_rec}.",
            "As of {wl}, the record places {top} first at {top_rec}.",
            "The record through {wl}: {top}, {top_rec}, first.",
            "{top} leads at {top_rec}, and the odds, per the simulations, are {top_odds} for the playoffs.",
            "Through {wl}, {top} leads at {top_rec}, with {top_odds} playoff odds and {bye} odds of a bye.",
        ],
        "n.cut": [
            "{six} ({six_rec}) holds the sixth and final playoff position; {seven} ({seven_rec}) is first out.",
            "The line is drawn between {six} ({six_rec}) and {seven} ({seven_rec}).",
            "{seven} ({seven_rec}) stands just outside, behind {six} ({six_rec}).",
        ],
        "n.luck": [
            "Fortune, as entered: {lucky} is {lucky_luck} wins above all-play expectation, and {unlucky} is {unlucky_luck}.",
            "By all-play, {lucky} holds {lucky_luck} wins it has not earned; {unlucky} holds {unlucky_luck}.",
            "{lucky} ({lucky_luck}) is the beneficiary of fortune; {unlucky} ({unlucky_luck}) is its victim.",
        ],
        "n.clinch": [
            "Having clinched, the following are admitted: {names}.",
            "The court finds the following have clinched: {names}.",
            "{names} have secured playoff positions.",
        ],
        "n.elim": [
            "Eliminated from contention: {names}. The motion is denied.",
            "Mathematically out: {names}.",
            "{names} may no longer qualify.",
        ],
        "n.bottom": [
            "The court sets {bottom} in last place at {bottom_rec}.",
            "At the bottom of the record: {bottom}, {bottom_rec}.",
            "The lowest standing on the record belongs to {bottom} ({bottom_rec}).",
        ],
        "n.eff": [
            "On lineup efficiency, {best_n} captured {best_pct} of available points; {worst_n} captured {worst_pct}.",
            "On efficiency, the court finds {best_n} highest at {best_pct}, and {worst_n} lowest at {worst_pct}.",
            "Efficiency, per the record: {best_n}, {best_pct}; {worst_n}, {worst_pct}.",
        ],
        "n.records": [
            "League records on the books: highest score {hi_pts} ({hi_n}, Week {hi_wk}); largest margin {blow_m} ({blow_w} over {blow_l}, Week {blow_wk}).",
            "{hi_n}'s {hi_pts} in Week {hi_wk} stands as the high score, and {blow_w}'s {blow_m}-point judgment against {blow_l} in Week {blow_wk} as the widest margin.",
            "The marks of record: {hi_pts} ({hi_n}, Week {hi_wk}) and {blow_m} points ({blow_w} over {blow_l}, Week {blow_wk}).",
        ],
        "n.ftop": [
            "The regular-season record: {top} first at {top_rec}, with {top_pf} scored.",
            "Top seed, per the record: {top}, {top_rec}, {top_pf}.",
            "{top} closed the regular season in first place, {top_rec}, {top_pf}.",
        ],
        "n.fcut": [
            "{six} took the sixth and final seed at {six_rec}; {seven} finished seventh at {seven_rec}.",
            "The line fell between {six} ({six_rec}) and {seven} ({seven_rec}).",
            "{six} ({six_rec}) qualified. {seven} ({seven_rec}) did not. The appeal is denied.",
        ],
        "n.fpts": [
            "On points scored, the court notes {pf_n} at the top ({pf_pts}) and {low_n} at the bottom ({low_pts}).",
            "On points scored, {pf_n} leads the record ({pf_pts}) and {low_n} trails it ({low_pts}).",
            "{pf_pts} for {pf_n} is the high mark; {low_pts} for {low_n} is the low.",
        ],
        "n.fbottom": [
            "The record ranks {bottom} last at {bottom_rec}.",
            "Last place, per the record: {bottom}, {bottom_rec}.",
            "{bottom} closed the season at {bottom_rec}, the lowest record.",
        ],
        "n.close": [
            "The standings are entered through {wl}, with {top} first.",
            "Through {wl}, {top} leads. So ordered.",
            "{top} remains the record leader through {wl}.",
        ],
        "h.f": [
            "{a} v. {b}: the grievance on record",
            "In the matter of {a} and {b}",
            "{a} and {b}: a summary of grievances",
            "The case against {b}, as filed by {a}",
        ],
        "f.h2h": [
            "Exhibit A is Week {gwk}: {w} {verb} {l}, {wp} to {lp}, by {m} points.",
            "In Week {gwk}, {w} prevailed over {l}, {wp}-{lp}, by {m}, and the matter has not been forgotten.",
            "{l} lost to {w} in Week {gwk}, {lp} to {wp}. The court classifies the result as {noun}.",
        ],
        "f.trade": [
            "Exhibit A is a transaction: in Week {twk}, {a} acquired {a_got} and {b} acquired {b_got}.",
            "The parties entered a trade in Week {twk}. {a} received {a_got}; {b} received {b_got}.",
            "In Week {twk}, {b_got} passed to {b} and {a_got} to {a}, as the log reflects.",
        ],
        "f.adj": [
            "In the standings, {hi} ({hi_rec}, {hi_rank}) stands adjacent to {lo} ({lo_rec}, {lo_rank}), with {pf_gap} between them in points scored.",
            "{hi} ranks {hi_rank} and {lo} ranks {lo_rank}, separated by {pf_gap} in points scored.",
            "{lo} trails {hi} by {pf_gap} in points scored ({lo_rank} to {hi_rank}).",
        ],
        "f.blow": [
            "Exhibit A is Week {gwk}: {w} {verb} {l}, {wp} to {lp}, by {m} points.",
            "In Week {gwk}, {w} beat {l}, {wp}-{lp}, by {m} points, a margin the record does not forgive.",
            "{w}'s {m}-point judgment against {l} in Week {gwk} ({wp}-{lp}) is among the largest margins on the record.",
        ],
        "f.sg": [
            "On the shotgun docket, {a} owes {a_sg} and {b} owes {b_sg}.",
            "The ledger shows {a} liable for {a_sg}, and {b} for {b_sg}.",
            "The ledger charges {a} with {a_sg} and {b} with {b_sg}.",
        ],
        "f.story": [
            "The dispute is catalogued as {rv_name}. {backstory}",
            "For the record, the pairing is {rv_name}. {backstory}",
            "The league's files list this as {rv_name}. {backstory}",
        ],
        "f.trait": [
            "Character evidence: {a} {a_trait}; {b} {b_trait}.",
            "Per the profiles on file, {a} {a_trait}, and {b} {b_trait}.",
            "{a} {a_trait}. {b} {b_trait}. The court takes notice.",
        ],
        "f.mid": [
            "Through Week {wk}, {a} stands {a_rank} at {a_rec}, and {b} stands {b_rank} at {b_rec}.",
            "The standings through Week {wk}: {a}, {a_rank}, {a_rec}; {b}, {b_rank}, {b_rec}.",
            "Standing of the parties through Week {wk}: {a} ({a_rec}, {a_rank}); {b} ({b_rec}, {b_rank}).",
        ],
        "f.close": [
            "The grievance remains on the docket.",
            "No settlement has been entered.",
            "The matter is adjourned, not resolved.",
        ],
        "h.v": [
            "{rv_name} on the docket: {a} v. {b}, Week {wk}",
            "Rematch in Week {wk}: {a} v. {b}, {rv_name}",
            "Week {wk} docket: {rv_name}",
            "{a} and {b} appear again in {rv_name}",
        ],
        "v.lede": [
            "The court calls {rv_name} for {wl}: {a} v. {b}. {backstory}",
            "On the docket for {wl}: {rv_name}, with {a} against {b}. {backstory}",
            "{a} and {b} return to court in {wl}, in the matter known as {rv_name}. {backstory}",
        ],
        "v.form": [
            "{a} appears at {a_rec} ({a_rank}), scoring {a_avg}; {b} appears at {b_rec} ({b_rank}), scoring {b_avg}.",
            "For {a}: {a_rec}, ranked {a_rank}, {a_avg} per game. For {b}: {b_rec}, ranked {b_rank}, {b_avg} per game.",
            "{b} stands {b_rank} at {b_rec} ({b_avg}); {a} stands {a_rank} at {a_rec} ({a_avg}).",
        ],
        "v.close": [
            "The court will reconvene in Week {wk} for {a} and {b}.",
            "{a} and {b} are summoned for Week {wk}.",
            "Both parties are expected in Week {wk}.",
        ],
        "h.o": [
            "Offseason docket: {ntrades} and {npick} on the record",
            "{ntrades} and {npick}: the offseason in evidence",
            "Before the season: {ntrades}, {npick}",
        ],
        "o.lede": [
            "The record of the offseason shows {ntrades} and {npick} before the first game.",
            "Entered into evidence: {ntrades} and {npick} before the season began.",
            "The transaction log lists {ntrades} and {npick} prior to kickoff.",
        ],
        "o.busy": [
            "The most active parties were {busy_text}.",
            "By the count of executed trades: {busy_text}.",
            "The trade docket is led by {busy_text}.",
        ],
        "o.big": [
            "The largest agreement: {side_a} received {a_got}, and {side_b} received {b_got}.",
            "The biggest deal conveyed {b_got} to {side_b} and {a_got} to {side_a}.",
            "Largest transaction on the record: {side_a}, {a_got}; {side_b}, {b_got}.",
        ],
        "o.close": [
            "{busiest} executed the most trades, as the record shows.",
            "The record names {busiest} as the busiest trader.",
            "{busiest} led the offseason in trades.",
        ],
        "x.sig": [
            "{n} then entered a familiar statement into the record: “{catch}”",
            "{n} concluded with the usual: “{catch}”",
            "For the record, {n} added: “{catch}”",
        ],
        "x.attr": [
            "“{qc}” {n} stated for the record.",
            "{n} testified: “{qp}”",
            "“{qc}” {n} said from the stand.",
            "{n}, in a statement: “{qp}”",
            "“{qc}” {n} told the court.",
        ],
    },
}
