"""Deadpan minimalist: very short declarative sentences. The numbers do the joking. Nothing is emphasized."""
FAMILY = {
    "id": "deadpan",
    "label": "Deadpan minimalist",
    "desc": "Four-to-nine-word sentences, flat affect, no adjectives where a number will do. Funny because it declines to react. Occasionally one dry understatement.",
    "rhythm": "short, flat, declarative",
    "formality": "plain",
    "metaphors": "none; occasionally a bureaucratic shrug",
    "numbers": "exact, stated without comment",
    "lex": {
        "verb": {
            "blowout": ["flattened", "ran over", "buried"],
            "comfortable": ["beat", "outscored", "got past"],
            "normal": ["beat", "defeated", "bested"],
            "close": ["barely beat", "edged", "narrowly beat"],
        },
        "noun": {
            "blowout": ["a rout", "a mismatch", "a thrashing"],
            "comfortable": ["a clear win", "a fine win", "a comfortable win"],
            "normal": ["a win", "an ordinary win", "a regular win"],
            "close": ["a close one", "a narrow one", "a tight one"],
        },
        "tier": {
            "hi": ["good", "a good buy", "fine value"],
            "mid": ["fine", "okay", "adequate"],
            "lo": ["not good", "poor", "disappointing"],
        },
    },
    "T": {
        "h.r.blow": [
            "{w} {verb} {l}, {wp}-{lp}",
            "{m} points. {w} over {l}",
            "{wl}: {w} wins by {m}",
        ],
        "h.r.upset": [
            "{w_rank0} beat {l_rank0}",
            "{w} beat {l}. The standings expected otherwise",
            "{w} won. The standings disagreed",
        ],
        "h.r.close": [
            "{w} wins by {m}",
            "{w} {verb} {l}, {wp}-{lp}",
            "{m} points decide {w}-{l}",
        ],
        "h.r.top": [
            "{w} scores {wp}",
            "{wp} points for {w}, the week's best",
            "High score: {w}, {wp}",
        ],
        "h.r.tie": [
            "{a} and {b} tie",
            "{pts} each for {a} and {b}",
            "Tie in {wl}: {a}, {b}",
        ],
        "r.lede.blow": [
            "{w} {verb} {l}, {wp} to {lp}. The margin was {m}. It was the widest of the week.",
            "{wl}. {w_team} ({w}) played {l_team} ({l}). {w_team} won by {m}. That was the most of the week.",
            "{w} won {wp}-{lp}. {l} lost by {m}, the week's widest margin.",
        ],
        "r.lede.upset": [
            "{w} was {w_rank0}. {l} was {l_rank0}. {w} won, {wp} to {lp}. That was the biggest upset of {wl}.",
            "Before {wl}, {l} ranked {l_rank0} and {w} ranked {w_rank0}. {w} won, {wp}-{lp}.",
            "{w}, {w_rank0}, {verb} {l}, {l_rank0}. {wp} to {lp}. No other result crossed more places.",
        ],
        "r.lede.close": [
            "{w} {verb} {l}, {wp} to {lp}. The margin was {m}. It was the closest game of {wl}.",
            "{m} points. That is what separated {w_team} ({w}) and {l_team} ({l}). {wp}-{lp}. The closest of the week.",
            "{wl}'s tightest game: {w} {wp}, {l} {lp}. A margin of {m}.",
        ],
        "r.lede.top": [
            "{w} scored {wp}. It was the top score of {wl}. {l} scored {lp} and lost. The average was {wavg}.",
            "The high score in {wl} was {wp}, by {w}. {w} {verb} {l}. The league average was {wavg}.",
            "{wp} points. {w_team} ({w}), {wl}. The most anyone scored. {l} had {lp}.",
        ],
        "r.lede.tie": [
            "{a} and {b} tied. {pts} each. {wl}.",
            "No winner in {a}-{b}. Both scored {pts}.",
            "{a_team} ({a}) and {b_team} ({b}) finished at {pts} apiece. It was a tie.",
        ],
        "g.result": [
            "{w} {verb} {l}, {wp}-{lp}.",
            "{w} won against {l}. {wp} to {lp}.",
            "{l} lost to {w_nick}, {lp}-{wp}.",
            "{w} beat {l_nick} by {m}. {wp}-{lp}.",
            "{wl}: {w} {wp}, {l} {lp}. {noun}.",
            "{w} {wp}. {l} {lp}.",
            "{l} lost by {m} to {w}.",
            "{w} won. {l} did not. {wp}-{lp}.",
            "{wl}: {w} over {l}. {m} points.",
            "{w} {verb} {l}. That is {noun}.",
        ],
        "g.tie": [
            "{a} and {b} tied at {pts}.",
            "{a} and {b}: {pts} each. No winner.",
            "{a_team} ({a}), {b_team} ({b}): level at {pts}.",
        ],
        "g.star": [
            "{star} ({spos}) scored {spts}. That was {sshare} of {w}'s {wp}.",
            "{w}'s best was {star} ({spos}). {spts}.",
            "{star} did the most for {w}. {spts}, {spos}.",
        ],
        "g.goat": [
            "{gname} ({gpos}) scored {gpts} for {l}.",
            "{l} started {gname} ({gpos}). {gpts}.",
            "{gpts} from {gname} ({gpos}). {l} started them.",
        ],
        "g.bench": [
            "{l}'s bench held {bench_left}. {bench_name} ({bench_pos}) had {bench_pts} of it.",
            "{bench_name} ({bench_pos}) scored {bench_pts} on {l}'s bench. Better lineup: {bench_left} more.",
            "{l}'s bench had {bench_pts} from {bench_name} ({bench_pos}). It stayed there.",
        ],
        "g.streak_w": [
            "{w} has won {k} straight. {w_rec}, {w_rank}.",
            "{k} in a row for {w}. {w_rec}. {w_rank} in the standings.",
            "{w} is {w_rec} and {w_rank}. {k} wins in a row.",
        ],
        "g.streak_l": [
            "{l} has lost {k} straight. {l_rec}, {l_rank}.",
            "{k} in a row for {l}. {l_rec}. {l_rank} in the standings.",
            "{l} is {l_rec} and {l_rank}. {k} losses in a row.",
        ],
        "g.record": [
            "{w} is {w_rec}, {w_rank}. {l} is {l_rec}, {l_rank}.",
            "After {wl}: {w}, {w_rec}. {l}, {l_rec}.",
            "{w} moved to {w_rec}. {l} moved to {l_rec}.",
        ],
        "g.top": [
            "{wp} was the highest score of {wl}. Average: {wavg}.",
            "Nobody scored more than {w}. {wp}. The average was {wavg}.",
            "{w} had the top score. {wp}. League average: {wavg}.",
        ],
        "g.low": [
            "{lp} was the lowest score of {wl}. Average: {wavg}.",
            "Nobody scored less than {l}. {lp}. The average was {wavg}.",
            "{l} had the lowest score. {lp}. League average: {wavg}.",
        ],
        "g.luck_up": [
            "{n} is {n_rec}. The luck index is {luck}.",
            "{n}'s luck index: {luck}. Record: {n_rec}.",
            "By all-play, {n} is {luck} wins ahead. {n_rec}.",
        ],
        "g.luck_down": [
            "{n} is {n_rec}. The luck index is {luck}.",
            "{n}'s luck index: {luck}. Record: {n_rec}.",
            "By all-play, {n} is {luck} wins behind. {n_rec}.",
        ],
        "g.upset": [
            "{w} was {w_rank0} going in. {l} was {l_rank0}.",
            "Before the game: {l}, {l_rank0}. {w}, {w_rank0}.",
            "Rankings beforehand: {l_rank0} and {w_rank0}. {w} won.",
        ],
        "g.shotgun": [
            "{n}: {sgn}. {why}.",
            "{sgn} for {n}: {why}.",
            "{n} incurred {sgn}. Reason: {why}.",
        ],
        "g.aside": [
            "{n}, who {trait}, took {event}.",
            "{n} {trait}. {n} also took {event}.",
            "Of note: {n}, who {trait}, now has {event}.",
        ],
        "r.close_shift": [
            "{in_names} moved into the top six. {out_names} moved out. {leader} leads at {leader_rec}.",
            "Top six after {wl}: {in_names} in, {out_names} out. {leader} first, {leader_rec}.",
            "The top six changed. {in_names} are in. {out_names} are out. {leader} leads, {leader_rec}.",
        ],
        "r.close_table": [
            "{leader} leads at {leader_rec}. {cut} is sixth at {cut_rec}.",
            "After {wl}: {leader} first, {leader_rec}. {cut} sixth, {cut_rec}.",
            "{leader}, {leader_rec}, is first. {cut}, {cut_rec}, is sixth.",
        ],
        "r.close_po": [
            "{ngames} in {wl}. Widest margin: {big_m}, {big_w} over {big_l}. Top score: {top_w}, {top_pts}.",
            "{wl} is done. {big_w} won by {big_m} over {big_l}. {top_w} scored {top_pts}. {ngames} total.",
            "{ngames}. {big_w} beat {big_l} by {big_m}. {top_w} had the top score, {top_pts}.",
        ],
        "h.p.fav": [
            "{fav} favored over {dog}",
            "{wl}: {fav}, {fav_odds}. {dog}, {dog_odds}",
            "{fav} is the favorite against {dog}",
        ],
        "h.p.even": [
            "{a} plays {b}. Odds are close",
            "{wl}: {a}, {b}. No favorite",
            "{a}, {b}: {a_odds} and {b_odds}",
        ],
        "h.p.lev": [
            "{a} plays {b}. {swing} points of playoff swing",
            "{wl}'s biggest game: {a}, {b}",
            "{a} and {b} play for playoff position",
        ],
        "p.lede": [
            "The game of the week is {a} against {b}.",
            "{a_team} plays {b_team} in {wl}. It is the featured game.",
            "{wl}'s featured game: {a} versus {b}.",
            "{a} plays {b}. {swing} points of playoff swing. The most this week.",
        ],
        "p.matchup": [
            "{a} is {a_rec}. Averages {a_avg}. {b} is {b_rec}. Averages {b_avg}.",
            "{a_team} ({a}): {a_rec}, {a_avg} per game. {b_team} ({b}): {b_rec}, {b_avg} per game.",
            "{a} ({a_rec}) plays {b} ({b_rec}) in {wl}. {a_avg} against {b_avg}.",
            "{b} is {b_rec}, {b_avg}. {a} is {a_rec}, {a_avg}. They play in {wl}.",
        ],
        "p.h2h_split": [
            "They are {h2h_rec} this season.",
            "{a} and {b} are even this year, {h2h_rec}.",
            "Season series: {h2h_rec}. Level.",
        ],
        "p.h2h_lead": [
            "{lead} leads {h2h_rec} this season.",
            "{trail} is {h2h_rec} behind {lead} this year.",
            "Season series: {lead}, {h2h_rec}.",
        ],
        "p.h2h_none": [
            "They have not met this season.",
            "{a} and {b} have not played yet this year.",
            "First meeting of the season.",
        ],
        "p.stakes": [
            "{a}'s playoff odds: {a_win} with a win, {a_loss} with a loss. {b}'s: {b_win} and {b_loss}.",
            "A win puts {a} at {a_win}. A loss, {a_loss}. {b}: {b_win} or {b_loss}.",
            "{a}, {a_win} or {a_loss}. {b}, {b_win} or {b_loss}. Depends on the game.",
        ],
        "p.leverage": [
            "{swing} points of combined playoff swing. The most this week.",
            "No game moves the odds more. {swing} points.",
            "{swing} points of swing. {a} and {b}. That is the most.",
        ],
        "p.favorite": [
            "{fav} is the favorite on {fav_why}. {fav_odds} to {dog}'s {dog_odds}.",
            "{fav}: {fav_odds}. {dog}: {dog_odds}. {fav} is favored.",
            "{dog} is the underdog. {dog_odds} against {fav_odds}.",
        ],
        "p.vol": [
            "{vol_n} varies more. {vol_std} points a week, against {other_std} for {other}.",
            "Volatility: {vol_n}, {vol_std}. {other}, {other_std}.",
            "{other} is steadier. {other_std}. {vol_n} is {vol_std}.",
        ],
        "p.rivnote": [
            "It is also {rv_name}. {backstory}",
            "The pairing is {rv_name}. {backstory}",
            "{rv_name}. {backstory}",
        ],
        "p.close": [
            "They play in {wl}.",
            "{a} and {b} play in {wl}. That is all.",
            "{wl}. {a}, {b}.",
        ],
        "h.t": [
            "{a} gives {gave_s}. {b} gives {got_s}.",
            "{a} trades {gave_s} for {got_s} with {b}",
            "{b} gets {gave_s} from {a}",
            "{a} and {b} trade: {gave_s} for {got_s}",
        ],
        "t.sides": [
            "{a} and {b} traded in {wl}. {a} got {a_got}. {b} got {b_got}.",
            "{wl}: {a} received {a_got}. {b} received {b_got}.",
            "{a} gave {b_got} to {b} and got {a_got}.",
            "{b} sent {a_got} to {a}. {b} received {b_got}.",
        ],
        "t.returns": [
            "Since the trade, {a}'s side has scored {a_pts}. {b}'s side has scored {b_pts}. {since_wk}. {lead} leads.",
            "{lead}'s players: {lead_pts}. {trail}'s: {trail_pts}. Over {since_wk}.",
            "{a}'s new players have {a_pts}. {b}'s have {b_pts}. {lead} is ahead.",
        ],
        "t.pending": [
            "{pk_side} got {pk_got}. {pl_side} got {pl_got}. Picks have no points. It cannot be graded.",
            "Picks for players. {pl_side} has {pl_got}. {pk_side} has {pk_got}. No verdict yet.",
            "{pl_side} took the players. {pk_side} took the picks. Nothing to grade.",
        ],
        "t.fresh": [
            "Nothing to grade yet.",
            "Too early to grade.",
            "No games played. No grade.",
        ],
        "t.count": [
            "It is {n}'s {nth} trade this season.",
            "{n}'s {nth} trade of the year.",
            "The {nth} trade for {n}.",
        ],
        "t.rec": [
            "Before the trade: {a}, {a_rec}, {a_rank}. {b}, {b_rec}, {b_rank}.",
            "{a} was {a_rec}. {b} was {b_rec}.",
            "At the time, {a} was {a_rank}. {b} was {b_rank}.",
        ],
        "t.close": [
            "The trade is complete.",
            "The log lists it as done.",
            "It cleared.",
        ],
        "h.w.big": [
            "{n} pays {bid} for {player}",
            "{n} spends {bid} on {player} ({pos})",
            "{bid} bid on {player} wins",
        ],
        "h.w.small": [
            "{n} gets {player}. {bid}.",
            "{player}, {n}, {bid}",
            "{n} claims {player} ({pos}), {bid}",
        ],
        "h.w.free": [
            "{n} adds {player}",
            "{player} ({pos}) joins {n}",
            "{n} picks up {player}",
        ],
        "w.top_bid": [
            "{n} bid {bid} for {player} ({pos}). It was the top bid of {wl}.",
            "The top bid was {bid}. {n}. {player} ({pos}).",
            "{n} paid {bid} for {player} ({pos}).",
        ],
        "w.top_free": [
            "{n} added {player} ({pos}).",
            "{player} ({pos}) went to {n}.",
            "The notable add of {wl}: {player} ({pos}), by {n}.",
        ],
        "w.since": [
            "{player} has scored {spts} since. {since_wk}. {tier}.",
            "Over {since_wk}, {player} has {spts}. That is {tier}.",
            "{n} has {spts} from {player} in {since_wk}. {tier}.",
        ],
        "w.others": [
            "Others: {others_text}.",
            "Others: {others_text}.",
            "Elsewhere: {others_text}.",
        ],
        "w.total": [
            "{wl}: {total_n}. {total_owners}.",
            "{wl}: {total_n}, {total_owners}.",
            "{total_owners} added {total_n}.",
        ],
        "w.budget": [
            "{n} has spent {spent} of {budget} in FAAB.",
            "FAAB: {n}, {spent} of {budget}.",
            "{n} has {budget} to work with. {spent} is gone.",
        ],
        "w.close": [
            "{player}: {n}.",
            "{n} has {player} now.",
            "{player}, {n}. Done.",
        ],
        "h.s": [
            "{total_n} owed in Week {wk}",
            "{top} owes {topn}",
            "Week {wk} beer report: {total_n}",
            "{top} leads Week {wk} with {topn}",
        ],
        "s.total": [
            "{total_n} owed in Week {wk}. {owners_n}.",
            "Week {wk}: {total_n} across {owners_n}.",
            "{owners_n} owe {total_n}.",
        ],
        "s.owner": [
            "{n}: {sgn}. {list}.",
            "{n} owes {sgn}. {list}.",
            "{sgn} for {n}. {list}.",
            "{n}, {sgn}: {list}.",
        ],
        "s.low": [
            "The lowest score: {player} ({pos}), {pts}, for {n}.",
            "{n} started {player} ({pos}). {pts}.",
            "{pts} from {player} ({pos}) in {n}'s lineup. The week's lowest.",
        ],
        "s.leader": [
            "{leader} leads the season with {ltotal}.",
            "Season total: {leader}, {ltotal}, through Week {wk}.",
            "Most this season: {leader}. {ltotal}.",
        ],
        "s.close": [
            "{top} is first on the list.",
            "{top} leads Week {wk}.",
            "Week {wk}. {top} first.",
        ],
        "h.n": [
            "{top} leads, {six} holds sixth",
            "Standings through {wl}: {top} first",
            "{alive} teams alive for {spots} spots",
            "{top} first, {bottom} last",
        ],
        "h.nf": [
            "Final standings: {top} first",
            "{six} is in. {seven} is out",
            "{top} first, {bottom} last: final",
            "The playoff field is set: {six} sixth, {seven} seventh",
        ],
        "n.top": [
            "{top} leads at {top_rec}.",
            "{top} is first. {top_rec}. Through {wl}.",
            "Through {wl}, {top}, {top_rec}, leads.",
            "{top} leads at {top_rec}. Playoff odds: {top_odds}.",
            "{top} leads at {top_rec}. Playoff odds {top_odds}. Bye odds {bye}.",
        ],
        "n.cut": [
            "{six} is sixth at {six_rec}. {seven} is seventh at {seven_rec}.",
            "The cut line: {six} ({six_rec}) in. {seven} ({seven_rec}) out.",
            "{seven}, {seven_rec}, is first out. {six}, {six_rec}, is last in.",
        ],
        "n.luck": [
            "Luckiest: {lucky}, {lucky_luck}. Unluckiest: {unlucky}, {unlucky_luck}.",
            "{lucky} has {lucky_luck} luck. {unlucky} has {unlucky_luck}.",
            "Luck index. {lucky}: {lucky_luck}. {unlucky}: {unlucky_luck}.",
        ],
        "n.clinch": [
            "Clinched: {names}.",
            "In: {names}.",
            "Clinched: {names}.",
        ],
        "n.elim": [
            "Eliminated: {names}.",
            "Out: {names}.",
            "{names} cannot make it.",
        ],
        "n.bottom": [
            "{bottom} is last. {bottom_rec}.",
            "Last: {bottom}, {bottom_rec}.",
            "{bottom} has {bottom_rec}. That is last.",
        ],
        "n.eff": [
            "Lineup efficiency: {best_n}, {best_pct}. {worst_n}, {worst_pct}.",
            "{best_n} is most efficient at {best_pct}. {worst_n} is least at {worst_pct}.",
            "Best lineups: {best_n}, {best_pct}. Worst: {worst_n}, {worst_pct}.",
        ],
        "n.records": [
            "Season high: {hi_pts}, {hi_n}, Week {hi_wk}. Biggest margin: {blow_m}, {blow_w} over {blow_l}, Week {blow_wk}.",
            "High score: {hi_n}, {hi_pts}. Widest win: {blow_w} over {blow_l} by {blow_m}.",
            "Records. Score: {hi_pts} ({hi_n}, Week {hi_wk}). Margin: {blow_m} ({blow_w}, Week {blow_wk}).",
        ],
        "n.ftop": [
            "{top} finished first. {top_rec}. {top_pf}.",
            "Top seed: {top}. {top_rec}.",
            "{top}, {top_rec}, first. {top_pf} scored.",
        ],
        "n.fcut": [
            "{six} took the last seed. {six_rec}. {seven} missed. {seven_rec}.",
            "{six} ({six_rec}) is in. {seven} ({seven_rec}) is out.",
            "Sixth: {six}, {six_rec}. Seventh: {seven}, {seven_rec}.",
        ],
        "n.fpts": [
            "Most points: {pf_n}, {pf_pts}. Fewest: {low_n}, {low_pts}.",
            "{pf_n} scored the most. {pf_pts}. {low_n} scored the fewest. {low_pts}.",
            "Points: {pf_n} led, {pf_pts}. {low_n} trailed, {low_pts}.",
        ],
        "n.fbottom": [
            "{bottom} finished last. {bottom_rec}.",
            "Last: {bottom}, {bottom_rec}.",
            "{bottom} had the worst record. {bottom_rec}.",
        ],
        "n.close": [
            "Through {wl}, {top} leads.",
            "{top} is first through {wl}.",
            "That is the table. {top} is first.",
        ],
        "h.f": [
            "{a} and {b}",
            "{a} versus {b}: the record",
            "On {a} and {b}",
            "{a}, {b}: facts",
        ],
        "f.h2h": [
            "In Week {gwk}, {w} {verb} {l}. {wp} to {lp}. The margin was {m}.",
            "{w} won in Week {gwk}. {wp}-{lp}. {l} lost by {m}.",
            "Week {gwk}: {w} {wp}, {l} {lp}. {noun}.",
        ],
        "f.trade": [
            "They traded in Week {twk}. {a} got {a_got}. {b} got {b_got}.",
            "Week {twk}: {a} received {a_got}. {b} received {b_got}.",
            "In Week {twk}, {b_got} went to {b}. {a_got} went to {a}.",
        ],
        "f.adj": [
            "{hi} is {hi_rank}, {hi_rec}. {lo} is {lo_rank}, {lo_rec}. {pf_gap} apart in points.",
            "In the standings they are neighbors. {pf_gap} separate them in points scored.",
            "{lo} trails {hi} by {pf_gap} in points scored.",
        ],
        "f.blow": [
            "In Week {gwk}, {w} {verb} {l}. {wp} to {lp}. {m} points.",
            "Week {gwk}: {w} beat {l} by {m}. {wp}-{lp}.",
            "{w} won by {m} over {l} in Week {gwk}. {wp}-{lp}.",
        ],
        "f.sg": [
            "Shotguns: {a}, {a_sg}. {b}, {b_sg}.",
            "{a} has {a_sg} on the ledger. {b} has {b_sg}.",
            "The ledger: {a} at {a_sg}, {b} at {b_sg}.",
        ],
        "f.story": [
            "The league calls it {rv_name}. {backstory}",
            "{rv_name}. {backstory}",
            "It is {rv_name}. {backstory}",
        ],
        "f.trait": [
            "{a} {a_trait}. {b} {b_trait}.",
            "Profiles: {a} {a_trait}. {b} {b_trait}.",
            "{a} {a_trait}; {b} {b_trait}. That is the background.",
        ],
        "f.mid": [
            "Through Week {wk}: {a}, {a_rec}, {a_rank}. {b}, {b_rec}, {b_rank}.",
            "{a} is {a_rank} at {a_rec}. {b} is {b_rank} at {b_rec}.",
            "{a} ({a_rec}) and {b} ({b_rec}) through Week {wk}.",
        ],
        "f.close": [
            "That is the situation.",
            "Nothing has been resolved.",
            "The record stands.",
        ],
        "h.v": [
            "{rv_name}: {a} plays {b} in Week {wk}",
            "{a} and {b} play in Week {wk}",
            "Week {wk}: {rv_name}",
            "{rv_name} is on the schedule",
        ],
        "v.lede": [
            "{rv_name} is in {wl}. {a} plays {b}. {backstory}",
            "{a} plays {b} in {wl}. It is {rv_name}. {backstory}",
            "{wl}: {rv_name}. {a}, {b}. {backstory}",
        ],
        "v.form": [
            "{a} is {a_rec}, {a_rank}, {a_avg} a game. {b} is {b_rec}, {b_rank}, {b_avg}.",
            "{a}: {a_rec}. {b}: {b_rec}. {a_avg} against {b_avg}.",
            "{b} is {b_rank} at {b_rec}. {a} is {a_rank} at {a_rec}.",
        ],
        "v.close": [
            "They play in Week {wk}.",
            "{a} and {b} meet in Week {wk}.",
            "Week {wk}. {a}, {b}.",
        ],
        "h.o": [
            "{ntrades}, {npick} before the season",
            "Offseason: {ntrades}, {npick}",
            "The offseason in {ntrades} and {npick}",
        ],
        "o.lede": [
            "The league logged {ntrades} and {npick} before the season.",
            "Before the season: {ntrades}, {npick}.",
            "Offseason total: {ntrades}. {npick}.",
        ],
        "o.busy": [
            "The busiest traders: {busy_text}.",
            "Most trades: {busy_text}.",
            "By trades: {busy_text}.",
        ],
        "o.big": [
            "The largest trade: {side_a} got {a_got}. {side_b} got {b_got}.",
            "Biggest deal. {side_a}: {a_got}. {side_b}: {b_got}.",
            "{side_a} received {a_got}. {side_b} received {b_got}. It was the largest.",
        ],
        "o.close": [
            "{busiest}: most trades.",
            "Most trades: {busiest}.",
            "{busiest} led in trades.",
        ],
        "x.sig": [
            "{n} added: “{catch}”",
            "{n} also said: “{catch}”",
            "{n}, as usual: “{catch}”",
        ],
        "x.attr": [
            "“{qc}” was {n}'s answer.",
            "{n}: “{qp}”",
            "“{qc}” {n}.",
            "{n}: “{qp}”",
            "{n} on the matter: “{qp}”",
        ],
    },
}
