"""Deadpan minimalist: very short declarative sentences. The numbers do the joking. Nothing is emphasized."""
FAMILY = {
    "id": "deadpan",
    "label": "Deadpan minimalist",
    "desc": "Four-to-nine-word sentences, flat affect, no adjectives where a number will do. Funny because it declines to react. Occasionally one dry understatement.",
    "rhythm": "short, flat, declarative",
    "formality": "plain",
    "metaphors": "none; occasionally a bureaucratic shrug",
    "numbers": "exact, stated without comment",
    "lex": {
        "verb": {
            "blowout": ["flattened", "ran over", "buried"],
            "comfortable": ["beat", "outscored", "got past"],
            "normal": ["beat", "defeated", "bested"],
            "close": ["barely beat", "edged", "narrowly beat"],
        },
        "noun": {
            "blowout": ["a rout", "a mismatch", "a thrashing"],
            "comfortable": ["a clear win", "a fine win", "a comfortable win"],
            "normal": ["a win", "an ordinary win", "a regular win"],
            "close": ["a close one", "a narrow one", "a tight one"],
        },
        "tier": {
            "hi": ["good", "a good buy", "fine value"],
            "mid": ["fine", "okay", "adequate"],
            "lo": ["not good", "poor", "disappointing"],
        },
    },
    "T": {
        "h.r.blow": [
            "{w} {verb} {l}, {wp}-{lp}",
            "{w} won by {m} points over {l}",
            "{wl}: {w} wins by {m}",
        ],
        "h.r.upset": [
            "{w} ({w_rank0}) beat {l} ({l_rank0})",
            "{w} beat {l}. The standings expected otherwise",
            "{w} won, and the standings disagreed",
        ],
        "h.r.close": [
            "{w} wins by {m}",
            "{w} {verb} {l}, {wp}-{lp}",
            "{m} points decide {w}-{l}",
        ],
        "h.r.top": [
            "{w} scores {wp}",
            "{w} scored {wp}, the week's best",
            "{w} had the high score, {wp}",
        ],
        "h.r.tie": [
            "{a} and {b} tie",
            "{a} and {b} each scored {pts}",
            "{a} and {b} tied in {wl}",
        ],
        "r.lede.blow": [
            "{w} {verb} {l}, {wp} to {lp}. The margin was {m}. It was the widest of the week.",
            "In {wl}, {w_team} ({w}) played {l_team} ({l}). {w_team} won by {m}. That was the most of the week.",
            "{w} won {wp}-{lp}. {l} lost by {m}. That was the week's widest margin.",
        ],
        "r.lede.upset": [
            "{w} was {w_rank0}. {l} was {l_rank0}. {w} won, {wp} to {lp}. That was the biggest upset of {wl}.",
            "Before {wl}, {l} ranked {l_rank0} and {w} ranked {w_rank0}. {w} won, {wp}-{lp}.",
            "{w}, ranked {w_rank0}, {verb} {l}, ranked {l_rank0}. The score was {wp} to {lp}. No other result crossed more places.",
        ],
        "r.lede.close": [
            "{w} {verb} {l}, {wp} to {lp}. The margin was {m}. It was the closest game of {wl}.",
            "{m} points separated {w_team} ({w}) and {l_team} ({l}). The score was {wp}-{lp}. It was the closest game of the week.",
            "{w} beat {l} in the closest game of {wl}. The score was {wp}-{lp}. The margin was {m}.",
        ],
        "r.lede.top": [
            "{w} scored {wp}. It was the top score of {wl}. {l} scored {lp} and lost. The average was {wavg}.",
            "The high score in {wl} was {wp}, by {w}. {w} {verb} {l}. The league average was {wavg}.",
            "{w_team} ({w}) scored {wp} in {wl}. That was the most anyone scored. {l} had {lp}.",
        ],
        "r.lede.tie": [
            "{a} and {b} tied in {wl}. Each scored {pts}.",
            "{a} and {b} had no winner. Both scored {pts}.",
            "{a_team} ({a}) and {b_team} ({b}) finished at {pts} apiece. It was a tie.",
        ],
        "g.result": [
            "{w} {verb} {l}, {wp}-{lp}.",
            "{w} won against {l}, {wp} to {lp}.",
            "{l} lost to {w_nick} by {m}, {lp}-{wp}.",
            "{w} beat {l_nick} by {m}, {wp}-{lp}.",
            "In {wl}, {w} scored {wp} and {l} scored {lp}. That is {noun}.",
            "{w} scored {wp}. {l} scored {lp}.",
            "{l} lost by {m} to {w}.",
            "{w} won, and {l} did not. The score was {wp}-{lp}.",
            "{w} won over {l} by {m} points.",
            "{w} {verb} {l}. That is {noun}.",
        ],
        "g.tie": [
            "{a} and {b} tied at {pts}.",
            "{a} and {b} each scored {pts}. There was no winner.",
            "{a_team} ({a}) and {b_team} ({b}) finished level at {pts}.",
        ],
        "g.star": [
            "{star} ({spos}) scored {spts}. That was {sshare} of {w}'s {wp}.",
            "{w}'s best starter was {star} ({spos}), with {spts}.",
            "{star} did the most for {w}, with {spts}.",
            "{star} ({spos}) was {w}'s top scorer. That was {spts}.",
            "{w}'s top score came from {star} ({spos}). It was {spts}.",
        ],
        "g.goat": [
            "{gname} ({gpos}) scored {gpts} for {l}.",
            "{l} started {gname} ({gpos}), who scored {gpts}.",
            "{l} started {gname} ({gpos}) and got {gpts}.",
        ],
        "g.bench": [
            "{l}'s bench held {bench_left}. {bench_name} ({bench_pos}) had {bench_pts} of it.",
            "{bench_name} ({bench_pos}) scored {bench_pts} on {l}'s bench. A better lineup would have scored {bench_left} more.",
            "{l}'s bench had {bench_pts} from {bench_name} ({bench_pos}). It stayed there.",
            "{l} benched {bench_name} ({bench_pos}). The player scored {bench_pts}.",
            "{bench_name} ({bench_pos}) sat on {l}'s bench and scored {bench_pts}. The unused total was {bench_left}.",
        ],
        "g.bench_total": [
            "{l}'s bench held {bench_left}. The best lineup would have used it.",
            "{l} left {bench_left} on the bench.",
            "The best lineup was {bench_left} better for {l}. It was not used.",
            "The bench cost {l} {bench_left}.",
            "{l}'s lineup was {bench_left} short of the best.",
        ],
        "g.streak_w": [
            "{w} has won {k} straight. {w} is {w_rec} and {w_rank}.",
            "{w} has won {k} in a row. {w} is {w_rank} in the standings.",
            "{w} is {w_rec} and {w_rank}. {w} has {k} wins in a row.",
        ],
        "g.streak_l": [
            "{l} has lost {k} straight. {l} is {l_rec} and {l_rank}.",
            "{l} has lost {k} in a row. {l} is {l_rank} in the standings.",
            "{l} is {l_rec} and {l_rank}. {l} has {k} losses in a row.",
        ],
        "g.record": [
            "{w} is {w_rec}, {w_rank}. {l} is {l_rec}, {l_rank}.",
            "After {wl}, {w} is {w_rec}. {l} is {l_rec}.",
            "{w} moved to {w_rec}. {l} moved to {l_rec}.",
        ],
        "g.top": [
            "{wp} was the highest score of {wl}. The average was {wavg}.",
            "Nobody scored more than {w}'s {wp}. The average was {wavg}.",
            "{w} had the top score, {wp}. The league average was {wavg}.",
        ],
        "g.low": [
            "{lp} was the lowest score of {wl}. The average was {wavg}.",
            "Nobody scored less than {l}'s {lp}. The average was {wavg}.",
            "{l} had the lowest score, {lp}. The league average was {wavg}.",
        ],
        "g.luck_up": [
            "{n} is {n_rec}. The luck index is {luck}.",
            "{n}'s luck index is {luck}. The record is {n_rec}.",
            "{n} is {n_rec}. All-play puts the luck at {luck}.",
        ],
        "g.luck_down": [
            "{n} is {n_rec}. The luck index is {luck}.",
            "{n}'s luck index is {luck}. The record is {n_rec}.",
            "{n} is {n_rec}. All-play puts the luck at {luck}.",
        ],
        "g.upset": [
            "{w} was {w_rank0} going in. {l} was {l_rank0}.",
            "Before the game, {l} was {l_rank0} and {w} was {w_rank0}.",
            "{l} ranked {l_rank0} beforehand, and {w} ranked {w_rank0}. {w} won.",
        ],
        "g.shotgun": [
            "{n} owes {sgn} for {why}.",
            "{n} owes {sgn}. The cause was {why}.",
            "{n} incurred {sgn} for {why}.",
        ],
        "g.aside": [
            "{n}, who {trait}, took {event}.",
            "{n} {trait}. {n} also took {event}.",
            "It is notable that {n}, who {trait}, now has {event}.",
        ],
        "r.close_shift": [
            "{in_names} moved into the top six. {out_names} moved out. {leader} leads at {leader_rec}.",
            "After {wl}, {in_names} are in the top six. {out_names} are out. {leader} leads at {leader_rec}.",
            "The top six changed. {in_names} are in. {out_names} are out. {leader} leads, {leader_rec}.",
        ],
        "r.close_table": [
            "{leader} leads at {leader_rec}. {cut} is sixth at {cut_rec}.",
            "After {wl}, {leader} is first at {leader_rec}. {cut} is sixth at {cut_rec}.",
            "{leader}, {leader_rec}, is first. {cut}, {cut_rec}, is sixth.",
        ],
        "r.close_po": [
            "The league played {ngames} in {wl}. {big_w} won by {big_m} over {big_l}. {top_w} had the top score, {top_pts}.",
            "{wl} is done. {big_w} won by {big_m} over {big_l}. {top_w} scored {top_pts}.",
            "{ngames} were played. {big_w} beat {big_l} by {big_m}. {top_w} had the top score, {top_pts}.",
        ],
        "h.p.fav": [
            "{fav} is favored over {dog}",
            "{fav} has {fav_win} to win. {dog} has {dog_win}",
            "{fav} is the favorite against {dog}",
        ],
        "h.p.even": [
            "{a} plays {b}. The odds are close",
            "{a} plays {b}. There is no favorite",
            "{a} has {a_win_pct} to win. {b} has {b_win_pct}",
        ],
        "h.p.lev": [
            "{a} plays {b}. There are {swing} points of playoff swing",
            "{a} and {b} play the biggest game of {wl}",
            "{a} and {b} play for playoff position",
        ],
        "p.lede": [
            "The game of the week is {a} against {b}.",
            "{a_team} plays {b_team} in {wl}. It is the featured game.",
            "The featured game of {wl} is {a} versus {b}.",
            "{a} plays {b}. The game carries {swing} points of playoff swing. That is the most this week.",
        ],
        "p.matchup": [
            "{a} is {a_rec} and averages {a_avg}. {b} is {b_rec} and averages {b_avg}.",
            "{a_team} ({a}) is {a_rec} and scores {a_avg} per game. {b_team} ({b}) is {b_rec} and scores {b_avg}.",
            "{a} ({a_rec}) plays {b} ({b_rec}) in {wl}. {a} averages {a_avg}. {b} averages {b_avg}.",
            "{b} is {b_rec} and averages {b_avg}. {a} is {a_rec} and averages {a_avg}. They play in {wl}.",
            "{a} is {a_rec}. {b} is {b_rec}. They average {a_avg} and {b_avg}.",
            "In {wl}, {a} faces {b}. {a} is {a_rec} at {a_avg}. {b} is {b_rec} at {b_avg}.",
        ],
        "p.h2h_split": [
            "They are {h2h_rec} this season.",
            "{a} and {b} are even this year, {h2h_rec}.",
            "The season series is {h2h_rec}. It is level.",
        ],
        "p.h2h_lead": [
            "{lead} leads {h2h_rec} this season.",
            "{trail} trails {lead}, {h2h_rec}, this year.",
            "{lead} leads the season series, {h2h_rec}.",
        ],
        "p.h2h_none": [
            "They have not met this season.",
            "{a} and {b} have not played yet this year.",
            "It is their first meeting of the season.",
        ],
        "p.stakes": [
            "{a}'s playoff odds are {a_win} with a win. They are {a_loss} with a loss. {b}'s are {b_win} and {b_loss}.",
            "A win puts {a} at {a_win}. A loss puts {a} at {a_loss}. {b} moves to {b_win} or {b_loss}.",
            "{a} will have {a_win} or {a_loss}. {b} will have {b_win} or {b_loss}. It depends on the game.",
        ],
        "p.leverage": [
            "The game has {swing} points of combined playoff swing. That is the most this week.",
            "No game moves the odds more. It moves them {swing} points.",
            "{a} and {b} share {swing} points of swing. That is the most.",
        ],
        "p.favorite": [
            "{fav} is the favorite on {fav_why}. {fav_win} to win, against {dog}'s {dog_win}.",
            "{fav} has {fav_win} to win. {dog} has {dog_win}. {fav} is favored.",
            "{dog} is the underdog, at {dog_win} to win against {fav}'s {fav_win}.",
        ],
        "p.vol": [
            "{vol_n} varies more, by {vol_std} points a week. {other} varies by {other_std}.",
            "{vol_n} has a volatility of {vol_std}. {other} has {other_std}.",
            "{other} is steadier, at {other_std}. {vol_n} is at {vol_std}.",
        ],
        "p.rivnote": [
            "It is also {rv_name}. {backstory}",
            "The pairing is {rv_name}. {backstory}",
            "This is {rv_name}. {backstory}",
        ],
        "p.close": [
            "They play in {wl}.",
            "{a} and {b} play in {wl}. That is all.",
            "{a} plays {b} in {wl}.",
        ],
        "h.t": [
            "{a} gives {gave_s}. {b} gives {got_s}.",
            "{a} trades {gave_s} for {got_s} with {b}",
            "{b} gets {gave_s} from {a}",
            "{a} and {b} trade: {gave_s} for {got_s}",
        ],
        "t.sides": [
            "{a} and {b} traded in {wl}. {a} got {a_got}. {b} got {b_got}.",
            "{wl}: {a} received {a_got}. {b} received {b_got}.",
            "{a} gave {b_got} to {b} and got {a_got}.",
            "{b} sent {a_got} to {a}. {b} received {b_got}.",
        ],
        "t.returns": [
            "Since the trade, {a}'s side has scored {a_pts}. {b}'s side has scored {b_pts}. {lead} leads over {since_wk}.",
            "{lead}'s players scored {lead_pts} over {since_wk}. {trail}'s scored {trail_pts}.",
            "{a}'s new players have {a_pts}. {b}'s have {b_pts}. {lead} is ahead.",
        ],
        "t.pending": [
            "Picks have no points. It cannot be graded.",
            "It is picks for players. There is no verdict yet.",
            "{pl_side} took the players. {pk_side} took the picks. There is nothing to grade.",
        ],
        "t.fresh": [
            "There is nothing to grade yet.",
            "It is too early to grade.",
            "No games have been played. There is no grade.",
            "The trade cannot be graded yet.",
            "The grade will come later.",
            "There is no grade without games.",
            "The picture will clear after a few games.",
            "It is too soon to say who won.",
            "The games have not told us anything yet.",
            "A verdict needs more games than this.",
        ],
        "t.count": [
            "It is {n}'s {nth} trade this season.",
            "That is {n}'s {nth} trade of the year.",
            "This is the {nth} trade for {n}.",
        ],
        "t.rec": [
            "Before the trade, {a} was {a_rec}, {a_rank}. {b} was {b_rec}, {b_rank}.",
            "{a} was {a_rec}. {b} was {b_rec}.",
            "At the time, {a} was {a_rank}. {b} was {b_rank}.",
        ],
        "t.close": [
            "The trade is complete.",
            "The log lists it as done.",
            "It cleared.",
        ],
        "h.w.big": [
            "{n} pays {bid} for {player}",
            "{n} spends {bid} on {player} ({pos})",
            "{bid} bid on {player} wins",
        ],
        "h.w.small": [
            "{n} gets {player} for {bid}",
            "{player} goes to {n} for {bid}",
            "{n} claims {player} ({pos}) for {bid}",
        ],
        "h.w.free": [
            "{n} adds {player}",
            "{player} ({pos}) joins {n}",
            "{n} picks up {player}",
        ],
        "w.top_bid": [
            "{n} bid {bid} for {player} ({pos}). It was the top bid of {wl}.",
            "The top bid was {bid}. {n} made it, for {player} ({pos}).",
            "{n} paid {bid} for {player} ({pos}).",
        ],
        "w.top_free": [
            "{n} added {player} ({pos}).",
            "{player} ({pos}) went to {n}.",
            "The notable add of {wl}: {player} ({pos}), by {n}.",
        ],
        "w.since": [
            "{player} has scored {spts} over {since_wk}. That is {tier}.",
            "Over {since_wk}, {player} has {spts}. That is {tier}.",
            "{n} has {spts} from {player} in {since_wk}. That is {tier}.",
        ],
        "w.others": [
            "The other claims were these: {others_text}.",
            "Elsewhere, {others_text}.",
            "Other owners were active too: {others_text}.",
        ],
        "w.total": [
            "In {wl}, {total_owners} added {total_n}.",
            "{total_owners} claimed {total_n} in {wl}.",
            "The wire moved {total_n} in {wl}. {total_owners} took part.",
        ],
        "w.budget": [
            "{n} has spent {spent} of {budget} in FAAB.",
            "{n} has used {spent} of the {budget} budget.",
            "{n} has {budget} to work with. {spent} is gone.",
        ],
        "w.close": [
            "{player} now belongs to {n}.",
            "{n} has {player} now.",
            "The claim for {player} is complete.",
        ],
        "h.s": [
            "{total_n} are owed for Week {wk}",
            "{top} owes {topn}",
            "The Week {wk} beer report lists {total_n}",
            "{top} leads Week {wk} with {topn}",
        ],
        "s.total": [
            "The league owes {total_n} for Week {wk}. {owners_n} are involved.",
            "Week {wk} had {total_n} across {owners_n}.",
            "{owners_n} owe {total_n}.",
        ],
        "s.owner": [
            "{n} owes {sgn}. The cause was {list}.",
            "{n} owes {sgn} for {list}.",
            "The ledger shows {sgn} for {n}: {list}.",
            "{n} has {sgn} on the ledger: {list}.",
        ],
        "s.low": [
            "The lowest score was {player} ({pos}), {pts}, for {n}.",
            "{n} started {player} ({pos}), who scored {pts}.",
            "{player} ({pos}) scored {pts} in {n}'s lineup. That was the week's lowest.",
        ],
        "s.leader": [
            "{leader} leads the season with {ltotal}.",
            "Through Week {wk}, {leader} has {ltotal} for the season.",
            "{leader} has the most this season, with {ltotal}.",
        ],
        "s.close": [
            "{top} is first on the list.",
            "{top} leads Week {wk}.",
            "{top} is first for Week {wk}.",
        ],
        "h.n": [
            "{top} leads, {six} holds sixth",
            "{top} is first through {wl}",
            "{alive} teams are alive for {spots} spots",
            "{top} is first and {bottom} is last",
        ],
        "h.nf": [
            "{top} finishes first",
            "{six} is in. {seven} is out",
            "{top} finished first and {bottom} finished last",
            "The playoff field is set, with {six} sixth and {seven} seventh",
        ],
        "n.top": [
            "{top} leads at {top_rec}.",
            "{top} is first at {top_rec} through {wl}.",
            "Through {wl}, {top} leads at {top_rec}.",
            "{top} leads at {top_rec}. Their playoff odds are {top_odds}.",
            "{top} leads at {top_rec}. Playoff odds are {top_odds}, and bye odds are {bye}.",
        ],
        "n.cut": [
            "{six} is sixth at {six_rec}. {seven} is seventh at {seven_rec}.",
            "At the cut line, {six} ({six_rec}) is in. {seven} ({seven_rec}) is out.",
            "{seven}, {seven_rec}, is first out. {six}, {six_rec}, is last in.",
        ],
        "n.luck": [
            "{lucky} is the luckiest at {lucky_luck}. {unlucky} is the unluckiest at {unlucky_luck}.",
            "{lucky} has a luck index of {lucky_luck}. {unlucky} has one of {unlucky_luck}.",
            "On the luck index, {lucky} is at {lucky_luck}. {unlucky} is at {unlucky_luck}.",
        ],
        "n.clinch": [
            "{names} have clinched a playoff spot.",
            "{names} are in the playoffs.",
            "{names} have clinched. That is settled.",
        ],
        "n.elim": [
            "{names} have been eliminated.",
            "{names} are out of the playoffs.",
            "{names} cannot make it.",
        ],
        "n.bottom": [
            "{bottom} is last at {bottom_rec}.",
            "{bottom} is in last place at {bottom_rec}.",
            "{bottom} has {bottom_rec}. That is last.",
        ],
        "n.eff": [
            "{best_n} has the best lineup efficiency, at {best_pct}. {worst_n} has the worst, at {worst_pct}.",
            "{best_n} is most efficient at {best_pct}. {worst_n} is least at {worst_pct}.",
            "{best_n} sets the best lineups at {best_pct}. {worst_n} uses {worst_pct}.",
        ],
        "n.records": [
            "The season high is {hi_pts}, by {hi_n} in Week {hi_wk}. The biggest margin is {blow_m}. {blow_w} won it over {blow_l} in Week {blow_wk}.",
            "{hi_n} has the high score, {hi_pts}. {blow_w} has the widest win, {blow_m} over {blow_l}.",
            "The scoring record is {hi_pts}. {hi_n} set it in Week {hi_wk}. The margin record is {blow_m}. {blow_w} set it in Week {blow_wk}.",
        ],
        "n.ftop": [
            "{top} finished first at {top_rec}. {top} scored {top_pf}.",
            "{top} is the top seed at {top_rec}.",
            "{top} finished first at {top_rec}, with {top_pf} scored.",
        ],
        "n.fcut": [
            "{six} took the last seed at {six_rec}. {seven} missed at {seven_rec}.",
            "{six} ({six_rec}) is in. {seven} ({seven_rec}) is out.",
            "{six} finished sixth at {six_rec}. {seven} finished seventh at {seven_rec}.",
        ],
        "n.fpts": [
            "{pf_n} scored the most, {pf_pts}. {low_n} scored the fewest, {low_pts}.",
            "{pf_n} led the league in points with {pf_pts}. {low_n} had the fewest, with {low_pts}.",
            "{pf_n} led in points, with {pf_pts}. {low_n} trailed, with {low_pts}.",
        ],
        "n.fbottom": [
            "{bottom} finished last at {bottom_rec}.",
            "{bottom} ended up last, at {bottom_rec}.",
            "{bottom} had the worst record, {bottom_rec}.",
        ],
        "n.close": [
            "Through {wl}, {top} leads.",
            "{top} is first through {wl}.",
            "That is the table. {top} is first.",
        ],
        "h.f": [
            "{a} and {b} have a history",
            "{a} versus {b}: the record",
            "A note on {a} and {b}",
            "{a} and {b}: the facts",
        ],
        "f.h2h": [
            "In Week {gwk}, {w} {verb} {l}, {wp} to {lp}. The margin was {m}.",
            "{w} won in Week {gwk}, {wp}-{lp}. {l} lost by {m}.",
            "In Week {gwk}, {w} scored {wp} and {l} scored {lp}. That was {noun}.",
        ],
        "f.trade": [
            "They traded in Week {twk}. {a} got {a_got}. {b} got {b_got}.",
            "Week {twk}: {a} received {a_got}. {b} received {b_got}.",
            "In Week {twk}, {b_got} went to {b}. {a_got} went to {a}.",
        ],
        "f.adj": [
            "{hi} is {hi_rank} at {hi_rec}. {lo} is {lo_rank} at {lo_rec}. They are {pf_gap} apart.",
            "In the standings they are neighbors. {pf_gap} separate them in points scored.",
            "{lo} trails {hi} by {pf_gap} in points scored.",
        ],
        "f.blow": [
            "Week {gwk}: {w} won by {m} over {l}.",
            "{w} won by {m} over {l} in Week {gwk}.",
            "{w} had a {m}-point win over {l} in Week {gwk}.",
        ],
        "f.sg": [
            "On shotguns, {a} has {a_sg} and {b} has {b_sg}.",
            "{a} has {a_sg} on the ledger. {b} has {b_sg}.",
            "The ledger puts {a} at {a_sg} and {b} at {b_sg}.",
        ],
        "f.story": [
            "The league calls it {rv_name}. {backstory}",
            "Their history is called {rv_name}. {backstory}",
            "It is {rv_name}. {backstory}",
        ],
        "f.trait": [
            "{a} {a_trait}. {b} {b_trait}.",
            "On the profiles, {a} {a_trait}. {b} {b_trait}.",
            "{a} {a_trait}; {b} {b_trait}. That is the background.",
        ],
        "f.mid": [
            "Through Week {wk}, {a} is {a_rec}, {a_rank}. {b} is {b_rec}, {b_rank}.",
            "{a} is {a_rank} at {a_rec}. {b} is {b_rank} at {b_rec}.",
            "Through Week {wk}, {a} is at {a_rec}. {b} is at {b_rec}.",
        ],
        "f.close": [
            "That is the situation.",
            "Nothing has been resolved.",
            "The record stands.",
        ],
        "h.v": [
            "{rv_name}: {a} plays {b} in Week {wk}",
            "{a} and {b} play in Week {wk}",
            "{rv_name} is in Week {wk}",
            "{rv_name} is on the schedule",
        ],
        "v.lede": [
            "{rv_name} is in {wl}. {a} plays {b}. {backstory}",
            "{a} plays {b} in {wl}. It is {rv_name}. {backstory}",
            "{wl} has {rv_name}. {a} plays {b}. {backstory}",
        ],
        "v.form": [
            "{a} is {a_rec}, {a_rank}, and scores {a_avg} a game. {b} is {b_rec}, {b_rank}, and scores {b_avg}.",
            "{a} is {a_rec} and {b} is {b_rec}. They average {a_avg} and {b_avg}.",
            "{b} is {b_rank} at {b_rec}. {a} is {a_rank} at {a_rec}.",
        ],
        "v.close": [
            "They play in Week {wk}.",
            "{a} and {b} meet in Week {wk}.",
            "{a} plays {b} in Week {wk}.",
        ],
        "h.o": [
            "The league made {ntrades} and {npick} before the season",
            "The offseason brought {ntrades} and {npick}",
            "The offseason produced {ntrades} and {npick}",
        ],
        "o.lede": [
            "The league logged {ntrades} and {npick} before the season.",
            "Before the season, there were {ntrades} and {npick}.",
            "The offseason had {ntrades}. It also had {npick}.",
        ],
        "o.busy": [
            "The busiest traders were {busy_text}.",
            "The most trades came from {busy_text}.",
            "Trade counts were {busy_text}.",
        ],
        "o.big": [
            "The largest trade: {side_a} got {a_got}. {side_b} got {b_got}.",
            "In the biggest deal, {side_a} got {a_got}. {side_b} got {b_got}.",
            "{side_a} received {a_got}. {side_b} received {b_got}. It was the largest.",
        ],
        "o.close": [
            "{busiest} made the most trades.",
            "The most trades belong to {busiest}.",
            "{busiest} led in trades.",
        ],
        # ---------------- Sunday column ----------------
        "h.c": [
            "{a} and {b} have said things",
            "{a} has remarks about {b}",
            "{b} has remarks about {a}",
            "{a} and {b} discuss each other",
        ],
        "h.c.rv": [
            "{rv_name}: {a} and {b} have spoken",
            "{a} and {b} continue {rv_name}",
            "There is more on {rv_name}",
        ],
        "h.c.next": [
            "{a} plays {b} in Week {nwk}. Both spoke.",
            "{a} and {b} have remarks for Week {nwk}",
            "Before Week {nwk}, {a} and {b} talked",
        ],
        "c.lede": [
            "Through {wl}, {a} is {a_rec} and ranked {a_rank}. {b} is {b_rec} and ranked {b_rank}.",
            "Through {wl}, {a} is {a_rank} at {a_rec}. {b} is {b_rank} at {b_rec}.",
            "The table through {wl} has {a} {a_rank}. It has {b} {b_rank}.",
        ],
        "c.next": [
            "They play in Week {nwk}.",
            "{a} and {b} meet in Week {nwk}.",
            "The schedule has them together in Week {nwk}.",
        ],
        "c.recent": [
            "Recently, {a} {a_form}. {b} {b_form}.",
            "{a} {a_form} lately. {b} {b_form}.",
            "In the last few games, {a} {a_form}. {b} {b_form}.",
        ],
        "c.gap": [
            "{hi} is {hi_rank} at {hi_rec}. {lo} is {lo_rank} at {lo_rec}. They are {pf_gap} apart.",
            "In points scored, {hi} and {lo} are {pf_gap} apart. The table has {hi} {hi_rank}.",
            "{hi} is {hi_rank}. {lo} is {lo_rank}. The points gap is {pf_gap}.",
        ],
        "c.pick": [
            "I pick {fav} over {dog}, on {fav_why}.",
            "{fav} is favored on {fav_why}. {dog} is not.",
            "I pick {fav} over {dog}. The basis is {fav_why}.",
        ],
        "c.close": [
            "{a} and {b} will play on.",
            "Nothing else was said by {a} or {b}.",
            "That covers {a} and {b}.",
        ],
        # ---------------- Monday analytics ----------------
        "h.a.luck": [
            "{lucky} has luck at {lucky_luck} and {unlucky} has {unlucky_luck}",
            "{lucky} is lucky. {unlucky} is not.",
            "{lucky} tops the luck index and {unlucky} is last",
        ],
        "h.a.eff": [
            "{best_n} is at {best_pct} efficiency and {worst_n} is at {worst_pct}",
            "{worst_n} is least efficient. {best_n} is most.",
            "{best_n} has the best lineups and {worst_n} has the worst",
        ],
        "h.a.bench": [
            "{bench_n} left {bench_pts} on the bench",
            "{bench_n} has the most bench points left, {bench_pts}",
            "The bench cost {bench_n} {bench_pts}",
        ],
        "h.a.steady": [
            "{steady_n} is the most consistent and {wild_n} is the least",
            "{steady_n} is steady. {wild_n} is not.",
            "{steady_n} has a narrow weekly rank range and {wild_n} has a wide one",
        ],
        "a.lede": [
            "These figures run through {wl}. Each team has played {gp}.",
            "The numbers follow. They run through {wl}, {gp} each.",
            "The data covers {wl}. Each team has played {gp}. Here are the numbers.",
        ],
        "a.luck": [
            "{lucky} is {lucky_rec} and should be at {lucky_exp} wins. The luck is {lucky_luck}. {unlucky} is {unlucky_rec} and should be at {unlucky_exp}. The luck is {unlucky_luck}.",
            "{lucky} is luckiest at {lucky_luck}. The record is {lucky_rec} on {lucky_exp} expected wins. {unlucky} is unluckiest at {unlucky_luck}. The record is {unlucky_rec} on {unlucky_exp}.",
            "{lucky} has a luck index of {lucky_luck}. {unlucky} has one of {unlucky_luck}. Their records are {lucky_rec} and {unlucky_rec}.",
        ],
        "a.eff": [
            "{best_n} used {best_pct} of the available points. {worst_n} used {worst_pct}. The league used {lg_pct}.",
            "{best_n} is at {best_pct}. {worst_n} is at {worst_pct}. The league is at {lg_pct}.",
            "{best_n} has the best lineups at {best_pct}. {worst_n} has the worst at {worst_pct}. The league average is {lg_pct}.",
        ],
        "a.bench": [
            "{bench_n} left {bench_pts} on the bench. {bench_low_n} left {bench_low_pts}.",
            "{bench_n} left the most points on the bench, {bench_pts}. {bench_low_n} left the fewest, {bench_low_pts}.",
            "The bench cost {bench_n} {bench_pts}. It cost {bench_low_n} {bench_low_pts}.",
        ],
        "a.blunder": [
            "{bl_n} had the worst week, in Week {bl_wk}. The lineup was {bl_pts} below the best. {bl_player} ({bl_pos}) scored {bl_player_pts} on the bench.",
            "In Week {bl_wk}, {bl_n} finished {bl_pts} short of the best. {bl_player} ({bl_pos}) was on the bench. That player scored {bl_player_pts}.",
            "In Week {bl_wk}, {bl_n} was {bl_pts} short. The bench's best was {bl_player} ({bl_pos}), with {bl_player_pts}.",
        ],
        "a.steady": [
            "{steady_n} was the most consistent. The average rank was {steady_avg}. The range was from {steady_band}. {wild_n} was the least, ranging from {wild_band}.",
            "{steady_n} ranged from {steady_band}. The average was {steady_avg}. {wild_n} ranged from {wild_band}.",
            "On weekly rank, {steady_n} ranged from {steady_band}, averaging {steady_avg}. {wild_n} ranged from {wild_band}.",
        ],
        "a.trade": [
            "In the Week {twk} trade, {lead}'s players scored {lead_pts}. {trail}'s players scored {trail_pts}. That covers {since_wk}.",
            "{lead} leads the Week {twk} trade, {lead_pts} to {trail_pts}. {trail} trails after {since_wk}.",
            "Since the Week {twk} trade, {lead} has {lead_pts}. {trail} has {trail_pts}. That covers {since_wk}.",
        ],
        "a.close": [
            "Those are the numbers.",
            "Figures are through {wl}.",
            "That is all.",
        ],
        "x.sig": [
            "{n} added: “{catch}”",
            "{n} also said: “{catch}”",
            "{n}, as usual: “{catch}”",
        ],
        "x.attr": [
            "“{qc}” was {n}'s answer.",
            "{n}: “{qp}”",
            "{n} on the matter: “{qp}”",
            "“{qc}” {n} said.",
            "“{qc}” {n} replied.",
            "“{qc}” {n} said, and stopped.",
            "{n} was asked. {n} said: “{qp}”",
            "“{qc}” {n} confirmed.",
            "“{qc}” {n} said. That was all.",
            "{n} commented: “{qp}”",
        ],
    },
}
