"""Finance analyst: tickers, valuations, upgrades and downgrades, volatility. Every roster move is a position."""
FAMILY = {
    "id": "finance",
    "label": "Finance analyst",
    "desc": "Markets desk voice: tickers, closes, upgrades and downgrades, volatility, FAAB as capital. Scores are earnings, playoff odds are probabilities of IPO, and every owner is a portfolio manager of questionable judgment.",
    "rhythm": "medium, clipped like a market report, with a rating at the end",
    "formality": "high, jargon-laden",
    "metaphors": "equities, valuations, volatility, capital, portfolios, ratings",
    "numbers": "exact, quoted like prices",
    "lex": {
        "verb": {
            "blowout": ["crushed", "wiped out", "bulldozed"],
            "comfortable": ["outperformed", "outpaced", "out-earned"],
            "normal": ["beat", "bested", "outscored"],
            "close": ["edged", "narrowly outperformed", "squeaked past"],
        },
        "noun": {
            "blowout": ["a market crash", "a total wipeout", "a liquidation event"],
            "comfortable": ["a solid quarter", "a clean beat", "a comfortable margin of safety"],
            "normal": ["an in-line print", "a standard session", "a flat session"],
            "close": ["a razor-thin margin", "a photo-finish session", "a near-flat close"],
        },
        "tier": {
            "hi": ["a strong buy", "outperforming the index", "a clear alpha play"],
            "mid": ["a hold", "in line with the index", "fairly valued"],
            "lo": ["underperforming so far", "a sell so far", "trading below cost so far"],
        },
    },
    "T": {
        "h.r.blow": [
            "{wl} close: {w} {verb} {l}, {wp}-{lp}",
            "{w_team} returns +{m} on the week against {l_team}: {noun}",
            "{w} posts {wp} against {l}'s {lp}: a {m}-point drawdown for {l} in {wl}",
        ],
        "h.r.upset": [
            "Biggest mover in {wl}: {w} ({w_rank0}) upends {l} ({l_rank0})",
            "{w} {verb} {l}, and the standings reprice",
            "{w_rank0} beats {l_rank0}: a major dislocation in {wl}",
        ],
        "h.r.close": [
            "{w} {verb} {l} by {m}, which the desk calls {noun}",
            "Photo-finish close in {wl}: {w}, {wp}; {l}, {lp}",
            "{m}-point spread: {w} edges {l}",
        ],
        "h.r.top": [
            "{w} prints {wp}, the high for {wl}",
            "Top earner of {wl}: {w}, {wp}, versus {l}",
            "{w} outperforms the field with {wp}",
        ],
        "h.r.tie": [
            "Flat close: {a} and {b} finish at {pts}",
            "{a} and {b} print identical results, {pts} each",
            "{pts}-{pts}: no spread between {a} and {b}",
        ],
        "r.lede.blow": [
            "Markets closed {wl} with one clear loser. {w} {verb} {l}, {wp} to {lp}, a {m}-point spread and the widest of the week. That is {noun}.",
            "In {wl}, {w_team} ({w}) posted {wp} against {l}'s {lp}: a {m}-point margin, the largest on the board.",
            "The largest move of {wl}: {w} over {l}, {wp}-{lp}, by {m}. Analysts called it {noun}.",
        ],
        "r.lede.upset": [
            "A major dislocation in {wl}. {l}, ranked {l_rank0} entering the week, was expected to beat {w}, ranked {w_rank0}. Instead, {w} {verb} {l}, {wp} to {lp}.",
            "The standings priced {l} ({l_rank0}) ahead of {w} ({w_rank0}). The market disagreed: {wp}-{lp} for {w} in {wl}, the biggest repricing of the week.",
            "{w}, {w_rank0} entering {wl}, beat {l}, {l_rank0}, {wp} to {lp}. The table is being revised.",
        ],
        "r.lede.close": [
            "A flat session for {wl}'s tightest game: {w} {verb} {l}, {wp} to {lp}, by {m} points. That is {noun}.",
            "{w_team} ({w}) edged {l_team} ({l}) by {m} points in {wl}, {wp}-{lp}, the narrowest spread of the week.",
            "{wp} against {lp}. A {m}-point margin separated {w} and {l} in {wl}, the closest close of the week.",
        ],
        "r.lede.top": [
            "The high of {wl}: {w} printed {wp}, well above the league average of {wavg}, and {verb} {l}, who printed {lp}.",
            "Top earner of the week: {w_team} ({w}), {wp}, against a league average of {wavg}. {l} printed {lp}.",
            "{w}'s {wp} led all teams in {wl} (average: {wavg}) and was enough to beat {l}, who scored {lp}.",
        ],
        "r.lede.tie": [
            "Flat close: {a_team} ({a}) and {b_team} ({b}) printed {pts} apiece in {wl}.",
            "No spread in {wl}: {a} and {b} each scored {pts}.",
            "{a} and {b} finished {wl} level at {pts}, a rare unchanged close.",
        ],
        "g.result": [
            "{w_team} ({w}) {verb} {l_team} ({l}); the close was {wp} to {lp}.",
            "{w} {verb} {l}: {wp}-{lp}, a spread of {m}.",
            "In {wl}, {w_nick} {verb} {l}, {wp} to {lp}. That's {noun}.",
            "{l_nick} printed {lp} against {w}'s {wp}, a gap of {m}. {noun}.",
            "Close: {w}, {wp}; {l}, {lp}. Spread: {m}. {noun}.",
            "{w} posted the better return over {l}, {wp} to {lp}.",
            "{l}'s position finished at {lp}; {w}'s finished at {wp}.",
            "Position closed: {w} over {l}, {wp}-{lp}.",
            "{w} {verb} {l}, a {m}-point spread.",
            "Earnings: {w}, {wp}; {l}, {lp}. {noun}.",
        ],
        "g.tie": [
            "{a} and {b} printed {pts} each.",
            "{a_team} ({a}) and {b_team} ({b}) closed flat at {pts}.",
            "{pts} apiece for {a} and {b}: no spread.",
        ],
        "g.star": [
            "{star} ({spos}) was the top contributor for {w}: {spts}, {sshare} of the {wp} total.",
            "Top position for {w}: {star} ({spos}), {spts}.",
            "{star} ({spos}) produced {spts}, or {sshare} of {w}'s {wp}.",
            "{star} ({spos}) was {w}'s best-performing holding at {spts}.",
            "{w}'s top return came from {star} ({spos}): {spts}.",
        ],
        "g.goat": [
            "The drag on {l}'s portfolio: {gname} ({gpos}), {gpts}.",
            "{gname} ({gpos}) delivered {gpts} for {l}, a dead position.",
            "{l}'s {gpos} slot was a write-down: {gname}, {gpts}.",
        ],
        "g.bench": [
            "{l} left {bench_left} of unrealized gains on the bench, including {bench_pts} from {bench_name} ({bench_pos}).",
            "{bench_name} ({bench_pos}) produced {bench_pts} on {l}'s bench. An optimal portfolio would have earned {bench_left} more.",
            "Opportunity cost for {l}: {bench_left} sat on the bench, {bench_pts} from {bench_name} ({bench_pos}).",
            "{l} left {bench_name} ({bench_pos}) off the lineup, a position that returned {bench_pts}; the optimal lineup would have earned {bench_left} more.",
            "{l}'s idle position in {bench_name} ({bench_pos}) produced {bench_pts}, and {bench_left} went unclaimed.",
        ],
        "g.bench_total": [
            "{l} left {bench_left} of unrealized gains on the bench.",
            "An optimal lineup would have booked {bench_left} more for {l}.",
            "{l} carried {bench_left} of idle capital on the bench.",
            "The bench left {l} {bench_left} short of the optimal lineup.",
            "{l}'s idle roster spots cost {bench_left}.",
        ],
        "g.streak_w": [
            "{w} has now posted {k} straight wins and sits {w_rank} at {w_rec}.",
            "A {k}-game run of positive returns for {w}: {w_rec}, {w_rank} in the table.",
            "{w} is {w_rec} ({w_rank}), on a {k}-win run.",
        ],
        "g.streak_l": [
            "{l} has now posted {k} straight losses and sits {l_rank} at {l_rec}.",
            "A {k}-game drawdown for {l}: {l_rec}, {l_rank} in the table.",
            "{l} is {l_rec} ({l_rank}), on a {k}-loss slump.",
        ],
        "g.record": [
            "{w} improves to {w_rec} ({w_rank}); {l} slips to {l_rec} ({l_rank}).",
            "The table reprices: {w}, {w_rec}, {w_rank}; {l}, {l_rec}, {l_rank}.",
            "After {wl}, {w} holds at {w_rec} and {l} at {l_rec}.",
        ],
        "g.top": [
            "{w}'s {wp} was the high of {wl}. The market average was {wavg}.",
            "No team beat {w}'s {wp} in {wl}. The market average was {wavg}.",
            "{wp} for {w}, the session high. Average: {wavg}.",
        ],
        "g.low": [
            "{l}'s {lp} was the low of {wl}. The market averaged {wavg}.",
            "No team printed lower than {l}'s {lp} in {wl}. The index average was {wavg}.",
            "{lp} for {l}, the session low. Average: {wavg}.",
        ],
        "g.luck_up": [
            "{n} ({n_rec}) is trading {luck_abs} wins above their all-play valuation, a premium that rarely holds.",
            "By all-play, {n} is {luck_abs} wins overvalued at {n_rec}.",
            "{n}: {n_rec}, with {luck_abs} wins of luck premium over fundamentals.",
        ],
        "g.luck_down": [
            "{n} ({n_rec}) is trading {luck_abs} wins below their all-play valuation, a discount that may close.",
            "By all-play, {n} is {luck_abs} wins undervalued at {n_rec}.",
            "{n}: {n_rec}, with {luck_abs} wins of unluck discount to fundamentals.",
        ],
        "g.upset": [
            "Entering the game, {w} was ranked {w_rank0} and {l} was ranked {l_rank0}.",
            "The pre-game table priced {l} at {l_rank0} and {w} at {w_rank0}.",
            "Pre-game rankings: {l}, {l_rank0}; {w}, {w_rank0}.",
        ],
        "g.shotgun": [
            "{n} owes {sgn}, a liability from {why}.",
            "The ledger charges {n} with {sgn}: {why}.",
            "{n} booked {sgn} in {wl} for {why}.",
        ],
        "g.aside": [
            "{n}, who {trait}, booked {event}.",
            "A footnote on {n}, who {trait}: {wl} brought {event}.",
            "{n}, who {trait}, now carries {event}.",
        ],
        "r.close_shift": [
            "In the table, {in_names} moved into the top six and {out_names} dropped out after {wl}. {leader} remains the leader at {leader_rec}.",
            "Playoff-zone rebalancing: {in_names} in, {out_names} out. {leader} holds first at {leader_rec}.",
            "After {wl}, {in_names} are above the playoff line and {out_names} below it. {leader} leads at {leader_rec}.",
        ],
        "r.close_table": [
            "After {wl}, {leader} leads at {leader_rec}, with {cut} holding the sixth and final playoff spot at {cut_rec}.",
            "The table after {wl}: {leader} on top ({leader_rec}), {cut} at the cut line ({cut_rec}).",
            "{leader} leads at {leader_rec}. {cut} sits at the playoff cut at {cut_rec}.",
        ],
        "r.close_po": [
            "{wl} close: {ngames}. The widest spread was {big_m}, {big_w} over {big_l}, and the high was {top_w}'s {top_pts}.",
            "In {wl}, {ngames}: {big_w} beat {big_l} by {big_m}, and {top_w} printed {top_pts}.",
            "{ngames} settled in {wl}. Largest margin: {big_w}, {big_m} over {big_l}. Top score: {top_w}, {top_pts}.",
        ],
        "h.p.fav": [
            "{wl} outlook: overweight {fav}, underweight {dog}",
            "{fav} ({fav_odds}) rated above {dog} ({dog_odds}) for {wl}",
            "Upgrade: {fav} over {dog} in {wl}",
        ],
        "h.p.even": [
            "{wl} outlook: {a} and {b} priced evenly",
            "{a} ({a_odds}) and {b} ({b_odds}): no edge in {wl}",
            "A hold on {a} vs. {b} in {wl}",
        ],
        "h.p.lev": [
            "High-volatility matchup in {wl}: {a} vs. {b}, {swing} points of swing",
            "{a} vs. {b}: the trade of the week in {wl}",
            "{wl}'s biggest catalyst: {a} against {b}",
        ],
        "p.lede": [
            "Our pick of the week in {wl}: {a_team} ({a}) against {b_team} ({b}).",
            "The featured matchup in {wl} is {a} versus {b}.",
            "All eyes on {a} and {b} in {wl}.",
            "{swing} points of combined playoff-odds swing: {a} vs. {b} is the highest-volatility matchup of {wl}.",
        ],
        "p.matchup": [
            "{a_team} ({a}, {a_rec}, {a_avg} per game) faces {b_team} ({b}, {b_rec}, {b_avg}) in {wl}.",
            "{a}: {a_rec}, {a_avg} ppg. {b}: {b_rec}, {b_avg} ppg. Fundamentals first.",
            "On the fundamentals: {a} ({a_rec}, {a_avg}) against {b} ({b_rec}, {b_avg}).",
            "{b_team} ({b}, {b_rec}, {b_avg}) meets {a_team} ({a}, {a_rec}, {a_avg}) in {wl}.",
            "In {wl}, {a} ({a_rec}, {a_avg}) takes on {b} ({b_rec}, {b_avg}).",
            "{a} trades at {a_rec} and {a_avg} a game; {b} trades at {b_rec} and {b_avg}. They meet in {wl}.",
        ],
        "p.h2h_split": [
            "The season series is level at {h2h_rec} between {a} and {b}.",
            "{a} and {b} are even head-to-head this season, {h2h_rec}.",
            "Prior meetings this season are a wash: {h2h_rec}.",
        ],
        "p.h2h_lead": [
            "{lead} leads the season series {h2h_rec}.",
            "{trail} is down {h2h_rec} to {lead} in prior meetings this season.",
            "Head-to-head, {lead} has the edge over {trail}, {h2h_rec}.",
        ],
        "p.h2h_none": [
            "{a} and {b} have not met this season, so there's no prior pricing.",
            "No head-to-head history this season between {a} and {b}.",
            "First meeting of the season for {a} and {b}.",
        ],
        "p.stakes": [
            "Scenario analysis: {a} moves to {a_win} playoff odds with a win and {a_loss} with a loss; {b} to {b_win} and {b_loss}.",
            "A win lifts {a} to {a_win}; a loss drops {a} to {a_loss}. For {b}: {b_win} or {b_loss}.",
            "The range of outcomes: {a} between {a_loss} and {a_win}, {b} between {b_loss} and {b_win}.",
        ],
        "p.leverage": [
            "Volatility alert: {swing} points of combined playoff swing, the widest on the {wl} board.",
            "No game this week carries more at stake: {swing} points of swing between {a} and {b}.",
            "{a} and {b} are playing for {swing} points of playoff odds. No other matchup compares.",
        ],
        "p.favorite": [
            "{fav} is the favorite on {fav_why}: {fav_odds} against {dog}'s {dog_odds}.",
            "On {fav_why}, {fav} ({fav_odds}) is rated above {dog} ({dog_odds}).",
            "{dog} is the underdog at {dog_odds}; {fav} is priced at {fav_odds}.",
        ],
        "p.vol": [
            "Risk note: {vol_n}'s weekly scoring has a volatility of {vol_std} points, against {other_std} for {other}.",
            "{vol_n} is the more volatile position ({vol_std} points a week); {other} is steadier ({other_std}).",
            "{other}'s returns are steadier ({other_std}) than {vol_n}'s ({vol_std}).",
        ],
        "p.rivnote": [
            "Note: the pairing is also {rv_name}, which the models do not price. {backstory}",
            "Off the balance sheet: {rv_name}. {backstory}",
            "Sentiment is elevated because this is {rv_name}. {backstory}",
        ],
        "p.close": [
            "Our rating on {a} and {b} will update after {wl}.",
            "{a} and {b} report in {wl}.",
            "We will revisit {a} and {b} after {wl}.",
        ],
        "h.t": [
            "Acquisition announced: {a} sends {gave_s} to {b} for {got_s}",
            "{a} and {b} agree terms: {gave_s} for {got_s}",
            "{b} completes the acquisition of {gave_s} from {a} for {got_s}",
            "Merger terms: {a} sells {gave_s} to {b} and takes {got_s} in return",
        ],
        "t.sides": [
            "{a} and {b} closed a deal in {wl}. {a} acquired {a_got}; {b} acquired {b_got}.",
            "The {wl} acquisition: {a} takes {a_got}, {b} takes {b_got}.",
            "{a} divested {b_got} and acquired {a_got} in {wl}.",
            "{b} sent {a_got} to {a} in {wl} and took {b_got} in return.",
        ],
        "t.returns": [
            "Post-merger integration after {since_wk}: {a}'s acquisitions have produced {a_pts}, and {b}'s {b_pts}. {lead} is ahead.",
            "Since the acquisition, {lead}'s additions have delivered {lead_pts} to {trail}'s {trail_pts} over {since_wk}.",
            "After {since_wk}, {a}'s side of the merger reads {a_pts}, and {b}'s reads {b_pts}. {lead} holds the early edge.",
        ],
        "t.pending": [
            "With picks on one side, due diligence on production is incomplete.",
            "Valuation of the picks-for-players deal is pending for {pk_side} and {pl_side}.",
            "The merger cannot be assessed until the picks produce.",
        ],
        "t.fresh": [
            "Due diligence on the acquisition is not complete.",
            "It's too early to assess the merger.",
            "No integration results to report yet.",
            "The acquisition is too new to assess.",
        ],
        "t.count": [
            "It is {n}'s {nth} acquisition of the season, a serial acquirer in the making.",
            "{n} has now closed the {nth} deal of the season.",
            "For {n}, this is the {nth} merger of the year.",
        ],
        "t.rec": [
            "Before the deal, {a} was {a_rec} ({a_rank}) and {b} was {b_rec} ({b_rank}).",
            "At the time, {a} stood {a_rank} at {a_rec}, and {b} stood {b_rank} at {b_rec}.",
            "Going into the deal: {a}, {a_rec}, {a_rank}; {b}, {b_rec}, {b_rank}.",
        ],
        "t.close": [
            "The league log shows the acquisition completed.",
            "The deal cleared due diligence and closed.",
            "Closed. The merger drew no objections.",
        ],
        "h.w.big": [
            "{n} commits {bid} to {player}",
            "{bid} for {player} ({pos}): {n} goes all in",
            "{n} pays up {bid} for {player}, a premium print",
        ],
        "h.w.small": [
            "{n} opens a {bid} position in {player}",
            "{player} ({pos}) lands with {n}, {bid}",
            "{n} takes a small {bid} position in {player}",
        ],
        "h.w.free": [
            "{n} adds free agent {player} at no cost",
            "{player} ({pos}) joins {n} at zero cost",
            "{n} takes a free position in {player}",
        ],
        "w.top_bid": [
            "{n} committed {bid} to {player} ({pos}) in {wl}, the largest FAAB position of the week.",
            "The week's largest bid was {bid}, from {n}, for {player} ({pos}).",
            "{n} took a {bid} position in {player} ({pos}), the biggest of {wl}.",
        ],
        "w.top_free": [
            "{n} took {player} ({pos}) at zero cost in {wl}, a free option.",
            "{player} ({pos}) joined {n} in {wl} at zero cost.",
            "The free-agent pickup of note in {wl}: {player} ({pos}), by {n}.",
        ],
        "w.since": [
            "Since then, {player} has returned {spts} over {since_wk}: {tier}.",
            "Over {since_wk}, {n} has received {spts} from {player}. That's {tier}.",
            "{player}: {spts} in the {since_wk} since entry. {tier}.",
        ],
        "w.others": [
            "Other positions: {others_text}.",
            "Secondary-market activity: {others_text}.",
            "Also on the wire: {others_text}.",
        ],
        "w.total": [
            "In all, {total_owners} took {total_n} in {wl}.",
            "Volume in {wl}: {total_n} traded among {total_owners}.",
            "Volume for {wl}: {total_n}, across {total_owners}.",
        ],
        "w.budget": [
            "{n} has deployed {spent} of a {budget} FAAB budget.",
            "Capital deployed: {n}, {spent} of {budget}.",
            "{n} has spent {spent} out of {budget} so far.",
        ],
        "w.close": [
            "{player} is now a holding in {n}'s portfolio.",
            "{n} holds {player}.",
            "{player} is in {n}'s portfolio.",
        ],
        "h.s": [
            "Beer Report, Week {wk}: {total_n} in liabilities",
            "{top} owes {topn} in Week {wk}",
            "Week {wk} ledger: {total_n} outstanding",
            "{top} carries the largest Week {wk} liability: {topn}",
        ],
        "s.total": [
            "The Week {wk} ledger shows {total_n} in liabilities across {owners_n}.",
            "The Week {wk} liabilities total {total_n}, split among {owners_n}.",
            "Week {wk} left {total_n} outstanding, across {owners_n}.",
        ],
        "s.owner": [
            "{n} books {sgn} in liabilities: {list}.",
            "{sgn} against {n}, due to {list}.",
            "{n}, {sgn} on the books ({list}).",
            "{n} booked {sgn} with {list}.",
        ],
        "s.low": [
            "The worst position on the ledger: {player} ({pos}), {pts}, in {n}'s lineup.",
            "{n}'s {player} ({pos}) returned {pts}, the week's lowest.",
            "At {pts}, {player} ({pos}) was the biggest drag on {n}.",
        ],
        "s.leader": [
            "{leader} leads the season in liabilities with {ltotal} through Week {wk}.",
            "Through Week {wk}, no one carries more than {leader}: {ltotal}.",
            "{leader} has the largest year-to-date shotgun exposure: {ltotal}.",
        ],
        "s.close": [
            "{top} carries the largest line item on the Week {wk} ledger.",
            "{top} heads the Week {wk} liabilities. Settle at your convenience.",
            "{top} leads the Week {wk} list.",
        ],
        "h.n": [
            "Standings through {wl}: {top} first, {six} at the playoff line",
            "{alive} names still trade above a 5% chance at {spots} playoff slots through {wl}",
            "{top} up, {bottom} down: the table through {wl}",
            "Through {wl}, {six} holds the last playoff spot",
        ],
        "h.nf": [
            "Year-end ranking: {top} closes at number one",
            "{six} makes the playoffs, {seven} does not: year-end table",
            "{top} first, {bottom} last: the regular-season close",
            "The playoff field is set: {six} in, {seven} out",
        ],
        "n.top": [
            "Through {wl}, {top} is the market leader at {top_rec}.",
            "{top} closes {wl} at the top of the board, {top_rec}.",
            "Top of the table through {wl}: {top}, {top_rec}.",
            "{top} leads at {top_rec} and is priced at {top_odds} to reach the playoffs.",
            "Through {wl}, {top} leads at {top_rec}, priced at {top_odds} for the playoffs and {bye} for a bye.",
        ],
        "n.cut": [
            "{six} ({six_rec}) holds the last playoff spot, with {seven} ({seven_rec}) just behind.",
            "The playoff cut-off prices out between {six} ({six_rec}) and {seven} ({seven_rec}).",
            "{seven} ({seven_rec}) is first out, with {six} ({six_rec}) hanging on.",
        ],
        "n.luck": [
            "Luck premium: {lucky} is {lucky_luck} wins above their all-play valuation, and {unlucky} is {unlucky_luck}.",
            "By all-play, {lucky} is overvalued by {lucky_luck} wins; {unlucky} is undervalued by {unlucky_luck}.",
            "{lucky} ({lucky_luck}) trades at a premium; {unlucky} ({unlucky_luck}) at a discount.",
        ],
        "n.clinch": [
            "Secured playoff spots: {names}.",
            "Locked in for the playoffs: {names}.",
            "{names} have locked in playoff positions.",
        ],
        "n.elim": [
            "Priced at zero: {names}.",
            "Delisted from contention: {names}.",
            "{names} cannot reach the playoffs now.",
        ],
        "n.bottom": [
            "{bottom} trades at the bottom of the board, {bottom_rec}.",
            "At the bottom of the table: {bottom}, {bottom_rec}.",
            "{bottom} is the weakest name on the board ({bottom_rec}).",
        ],
        "n.eff": [
            "Lineup efficiency: {best_n} captures {best_pct} of available points; {worst_n} captures {worst_pct}.",
            "{best_n} is the most efficient manager at {best_pct}, and {worst_n} the least at {worst_pct}.",
            "Efficiency ratings: {best_n}, {best_pct}; {worst_n}, {worst_pct}.",
        ],
        "n.records": [
            "League records: the high score is {hi_pts}, by {hi_n} in Week {hi_wk}, and the widest spread is {blow_m}, {blow_w} over {blow_l} in Week {blow_wk}.",
            "{hi_n}'s {hi_pts} in Week {hi_wk} is still the season high, and {blow_w}'s {blow_m}-point win over {blow_l} in Week {blow_wk} the widest margin.",
            "Benchmarks: {hi_pts} ({hi_n}, Week {hi_wk}) and {blow_m} points ({blow_w} over {blow_l}, Week {blow_wk}).",
        ],
        "n.ftop": [
            "{top} finished first at {top_rec}, with {top_pf} scored.",
            "The top seed goes to {top}: {top_rec}, {top_pf}.",
            "{top} ended the regular season on top, {top_rec}, {top_pf}.",
        ],
        "n.fcut": [
            "{six} took the last playoff spot at {six_rec}; {seven} finished at {seven_rec} and missed the cut.",
            "The cut-off settled between {six} ({six_rec}) and {seven} ({seven_rec}).",
            "{six} ({six_rec}) cleared the bar. {seven} ({seven_rec}) fell short of it.",
        ],
        "n.fpts": [
            "{pf_n} scored the most all season ({pf_pts}); {low_n} the fewest ({low_pts}).",
            "In scoring, {pf_n} led with {pf_pts}, and {low_n} trailed with {low_pts}.",
            "{pf_pts} for {pf_n} is the season high; {low_pts} for {low_n} is the low.",
        ],
        "n.fbottom": [
            "{bottom} closed the year at the floor, {bottom_rec}.",
            "At the bottom: {bottom}, {bottom_rec}.",
            "{bottom} took last place, {bottom_rec}.",
        ],
        "n.close": [
            "That is the table through {wl}, with {top} at the top.",
            "{top} sits on top of the {wl} tape.",
            "{top} holds the top rating through {wl}.",
        ],
        "h.f": [
            "Hostile situation: {a} and {b}",
            "{a} and {b}: a conflict of interest",
            "{a} vs. {b}: what the numbers say about the feud",
            "A bad relationship: {a} and {b}",
        ],
        "f.h2h": [
            "The relevant data point is Week {gwk}: {w} {verb} {l}, {wp} to {lp}, by {m}.",
            "In Week {gwk}, {w} beat {l}, {wp}-{lp}, by {m} points, and the loss is still on {l}'s books.",
            "{l} lost to {w} in Week {gwk}, {lp} to {wp}. That was {noun}.",
        ],
        "f.trade": [
            "The relevant acquisition is a Week {twk} trade: {a} bought {a_got} and {b} bought {b_got}.",
            "In Week {twk}, the two closed a merger of sorts: {a} received {a_got}; {b} received {b_got}.",
            "In Week {twk}, {b} acquired {b_got} and {a} acquired {a_got}.",
        ],
        "f.adj": [
            "In the standings, {hi} ({hi_rec}, {hi_rank}) trades just above {lo} ({lo_rec}, {lo_rank}), with {pf_gap} between them in points scored.",
            "{hi} ranks {hi_rank} and {lo} ranks {lo_rank}, a spread of {pf_gap} in points scored.",
            "{lo} is {pf_gap} behind {hi} in points scored, a {lo_rank}-to-{hi_rank} spread in the table.",
        ],
        "f.blow": [
            "The catalyst was Week {gwk}: {w} {verb} {l}, {wp} to {lp}, a {m}-point move.",
            "In Week {gwk}, {w} beat {l}, {wp}-{lp}, by {m}, a spread the market has not forgotten.",
            "{w}'s {m}-point win over {l} in Week {gwk} ({wp}-{lp}) is among the widest margins of the season.",
            "In Week {gwk}, {w} won by {m} over {l}, {wp}-{lp}, a large drawdown for {l}.",
        ],
        "f.sg": [
            "On the liabilities sheet, {a} carries {a_sg} and {b} carries {b_sg}.",
            "Liabilities to date: {a}, {a_sg}; {b}, {b_sg}.",
            "{a} is at {a_sg} and {b} at {b_sg} on the season ledger.",
        ],
        "f.story": [
            "The pairing is recorded as {rv_name}. {backstory}",
            "For background, the relationship is {rv_name}. {backstory}",
            "The league's files list it as {rv_name}. {backstory}",
        ],
        "f.trait": [
            "Profiles: {a} {a_trait}; {b} {b_trait}.",
            "Per available data, {a} {a_trait}, and {b} {b_trait}.",
            "{a} {a_trait}. {b} {b_trait}. The risk factors are clear.",
        ],
        "f.mid": [
            "Marks through Week {wk}: {a} {a_rec} ({a_rank}); {b} {b_rec} ({b_rank}).",
            "Rankings through Week {wk}: {a}, {a_rank}, {a_rec}; {b}, {b_rank}, {b_rec}.",
            "Positions through Week {wk}: {a} ({a_rec}, {a_rank}); {b} ({b_rec}, {b_rank}).",
        ],
        "f.close": [
            "Volatility is expected to remain elevated.",
            "We maintain a negative outlook on relations between {a} and {b}.",
            "No resolution is priced in.",
        ],
        "h.v": [
            "{rv_name} on the calendar: {a} vs. {b}, Week {wk}",
            "{a} and {b} meet in Week {wk}: {rv_name}",
            "Week {wk} catalyst: {rv_name}",
            "{rv_name} returns in Week {wk}",
        ],
        "v.lede": [
            "A high-volatility event is scheduled for {wl}: {rv_name}, with {a} against {b}. {backstory}",
            "On the calendar for {wl}: {rv_name}, {a} versus {b}. {backstory}",
            "{wl} brings {rv_name}, with {a} facing {b}. {backstory}",
        ],
        "v.form": [
            "{a} is {a_rec} ({a_rank}) and posts {a_avg} per game; {b} is {b_rec} ({b_rank}) and posts {b_avg}.",
            "{a}: {a_rec}, rank {a_rank}, {a_avg} ppg. {b}: {b_rec}, rank {b_rank}, {b_avg} ppg. Fundamentals only.",
            "{b} is ranked {b_rank} on a {b_rec} record and {b_avg} per game; {a} is ranked {a_rank} on {a_rec} and {a_avg}.",
        ],
        "v.close": [
            "We will revisit {a} and {b} after Week {wk}.",
            "{a} and {b} report in Week {wk}.",
            "Week {wk} is the catalyst for {a} and {b}.",
        ],
        "h.o": [
            "Offseason volume report: {ntrades}, {npick}",
            "{ntrades} and {npick}: a busy offseason tape",
            "Pre-season trading: {ntrades} and {npick}",
        ],
        "o.lede": [
            "Before the season opened, the league logged {ntrades} and {npick}, a heavy volume session.",
            "The offseason tape shows {ntrades} and {npick}, according to the log.",
            "{ntrades} and {npick}, all before the opening bell.",
        ],
        "o.busy": [
            "The most active traders by volume: {busy_text}.",
            "By trade count: {busy_text}.",
            "High-turnover desks: {busy_text}.",
        ],
        "o.big": [
            "The largest trade of the offseason: {side_a} received {a_got}, and {side_b} received {b_got}.",
            "The block trade of the offseason: {b_got} to {side_b}, {a_got} to {side_a}.",
            "Largest block trade: {side_a}, {a_got}; {side_b}, {b_got}.",
        ],
        "o.close": [
            "{busiest} made the most trades. High turnover.",
            "{busiest} posted the highest trade volume of the offseason.",
            "{busiest} led the offseason in trade volume.",
        ],
        # ---------------- Sunday column ----------------
        "h.c": [
            "{a} and {b} trade barbs: markets react",
            "{a} short-sells {b}: a Sunday note",
            "Sunday note: {a} and {b} in a public dispute",
            "{a}, {b}: what the talk is worth",
        ],
        "h.c.rv": [
            "{rv_name}: {a} and {b} reprice the feud",
            "{a} and {b} reopen {rv_name}, volatility expected",
            "Sunday note on {rv_name}: {a} and {b} talk their books",
        ],
        "h.c.next": [
            "Ahead of Week {nwk}: {a} and {b} talk their books",
            "{a} vs. {b} in Week {nwk}: the pre-game price discovery",
            "Week {nwk} preview: {a} and {b} issue guidance",
        ],
        "c.lede": [
            "Through {wl}, {a} is {a_rec} and rated {a_rank}, and {b} is {b_rec} and rated {b_rank}.",
            "Opening prices through {wl}: {a}, {a_rank}, {a_rec}; {b}, {b_rank}, {b_rec}.",
            "{a} ({a_rec}) closed {wl} ranked {a_rank}. {b} ({b_rec}) closed ranked {b_rank}.",
        ],
        "c.next": [
            "The two meet in Week {nwk}, where positions will be settled.",
            "{a} and {b} are scheduled to meet in Week {nwk}; expect volume.",
            "Week {nwk} is the catalyst, with {a} facing {b}.",
        ],
        "c.recent": [
            "Recent trading: {a} {a_form}, and {b} {b_form}.",
            "Over the trailing few games, {a} {a_form}, while {b} {b_form}.",
            "On the recent tape, {a} {a_form}, and {b} {b_form}.",
        ],
        "c.gap": [
            "{hi} ({hi_rank}, {hi_rec}) trades above {lo} ({lo_rank}, {lo_rec}), with a spread of {pf_gap} in points scored.",
            "The spread in points scored between {hi} and {lo} is {pf_gap}, with {hi} rated {hi_rank} and {lo} rated {lo_rank}.",
            "{hi} is rated {hi_rank} at {hi_rec}, {lo} is rated {lo_rank} at {lo_rec}, and {pf_gap} of scoring separates the two.",
        ],
        "c.pick": [
            "Rating: overweight {fav}, underweight {dog}, on {fav_why}.",
            "Our call is {fav} over {dog}, based on {fav_why}, with the usual caveats.",
            "On {fav_why}, {fav} is the buy and {dog} is the sell.",
        ],
        "c.close": [
            "We maintain a volatile outlook on {a} and {b}.",
            "No resolution between {a} and {b} is priced in.",
            "Neither {a} nor {b} has revised guidance. Past talk is no guarantee of future results.",
        ],
        # ---------------- Monday analytics ----------------
        "h.a.luck": [
            "Luck premium: {lucky} {lucky_luck}, {unlucky} {unlucky_luck}",
            "{lucky} trades at a luck premium ({lucky_luck}); {unlucky} at a discount ({unlucky_luck})",
            "Valuation check: {lucky} overvalued by {lucky_luck} wins, {unlucky} undervalued",
        ],
        "h.a.eff": [
            "Efficiency ratings: {best_n} {best_pct}, {worst_n} {worst_pct}",
            "{best_n} upgraded on {best_pct} efficiency; {worst_n} downgraded at {worst_pct}",
            "Lineup efficiency: {best_n} leads the sector at {best_pct}, {worst_n} lags at {worst_pct}",
        ],
        "h.a.bench": [
            "{bench_n} left {bench_pts} of capital idle on the bench",
            "Bench impairment: {bench_n}, {bench_pts}",
            "{bench_pts} in unrealized value: {bench_n}'s bench",
        ],
        "h.a.steady": [
            "Low volatility for {steady_n}, high volatility for {wild_n}",
            "Weekly rank volatility: {steady_n} stable, {wild_n} erratic",
            "{wild_n} the most volatile name in the league; {steady_n} the least",
        ],
        "a.lede": [
            "The Monday market summary, through {wl} and {gp} per team.",
            "All figures are as of the close of {wl}, after {gp} for each team.",
            "Here is the weekly scorecard through {wl}, {gp} per team.",
        ],
        "a.luck": [
            "On luck, {lucky} trades at a premium: {lucky_rec} against an all-play valuation of {lucky_exp} wins, a premium of {lucky_luck}. {unlucky} trades at a discount: {unlucky_rec} against {unlucky_exp}, a discount of {unlucky_luck}.",
            "Luck index (actual wins minus all-play expected wins): {lucky}, {lucky_luck} ({lucky_rec}, expected {lucky_exp}); {unlucky}, {unlucky_luck} ({unlucky_rec}, expected {unlucky_exp}).",
            "{lucky} is overvalued by {lucky_luck} wins ({lucky_rec} on {lucky_exp} expected). {unlucky} is undervalued ({unlucky_rec} on {unlucky_exp}, {unlucky_luck}).",
        ],
        "a.eff": [
            "Lineup efficiency, the share of available points captured: {best_n} leads at {best_pct}, {worst_n} lags at {worst_pct}, and the league index sits at {lg_pct}.",
            "{best_n} is upgraded at {best_pct} efficiency. {worst_n} is downgraded at {worst_pct}. The league benchmark is {lg_pct}.",
            "Efficiency ratings: {best_n}, {best_pct}; {worst_n}, {worst_pct}; league benchmark, {lg_pct}.",
        ],
        "a.bench": [
            "On idle capital, measured against each team's best possible lineup, {bench_n} left {bench_pts} on the bench, the most in the league. {bench_low_n} left {bench_low_pts}, the least.",
            "Bench impairment: {bench_n}, {bench_pts}; {bench_low_n}, {bench_low_pts}.",
            "{bench_n} wrote down {bench_pts} in unused bench value. {bench_low_n} wrote down {bench_low_pts}.",
        ],
        "a.blunder": [
            "The largest single-week write-down belongs to {bl_n}, in Week {bl_wk}: {bl_pts} below the best possible lineup. The top bench score was {bl_player_pts}, by {bl_player} ({bl_pos}).",
            "In Week {bl_wk}, {bl_n} finished {bl_pts} short of the best lineup, the biggest miss so far, while {bl_player} ({bl_pos}) posted {bl_player_pts} from the bench.",
            "{bl_n}, Week {bl_wk}: a shortfall of {bl_pts} against the optimal lineup. Best bench print: {bl_player} ({bl_pos}), {bl_player_pts}.",
        ],
        "a.steady": [
            "On volatility, {steady_n} is the low-risk name, averaging a weekly rank of {steady_avg} and ranging from {steady_band}. {wild_n} is the high-risk name, ranging from {wild_band}.",
            "Weekly rank volatility: {steady_n} (from {steady_band}, average {steady_avg}) against {wild_n} (from {wild_band}).",
            "{steady_n} has held a narrow range, from {steady_band}. {wild_n} has traded from {wild_band}.",
        ],
        "a.trade": [
            "On the Week {twk} trade: over {since_wk}, the players {lead} acquired have returned {lead_pts}, against {trail_pts} for the players {trail} acquired.",
            "Early returns on the Week {twk} trade favor {lead}, {lead_pts} to {trail_pts}, after {since_wk}. {trail} is underwater, for now.",
            "Since the Week {twk} deal, {lead}'s acquisitions have returned {lead_pts} and {trail}'s have returned {trail_pts}, over {since_wk}.",
        ],
        "a.close": [
            "Ratings are as of the close of {wl} and are subject to change.",
            "Past performance is not indicative of future lineups.",
            "We will update the scorecard next Monday.",
        ],
        "x.sig": [
            "And then, as always: “{catch}” The standard guidance from {n}.",
            "{n} ended the call with the standard disclaimer: “{catch}”",
            "{n}'s trademark, again: “{catch}”",
        ],
        "x.attr": [
            "“{qc}” {n} said in a note to clients.",
            "{n}, on the record: “{qp}”",
            "“{qc}” {n} told a client call.",
            "{n}'s guidance: “{qp}”",
            "“{qc}” {n} told the desk.",
            "“{qc}” {n} said on an earnings call.",
            "{n}, in a filing: “{qp}”",
            "“{qc}” {n} said, citing forward guidance.",
            "“{qc}” {n} told analysts.",
            "Asked to comment, {n} said: “{qp}”",
            "“{qc}” {n} said, noting the risks.",
        ],
    },
}
