"""Hype beat reporter: breathless, exclamatory, second person, stakes inflated but every number real."""
FAMILY = {
    "id": "hype",
    "label": "Hype beat reporter",
    "desc": "Short punchy sentences, exclamation points, ALL-CAPS emphasis, direct address to the reader. Everything is the biggest thing ever, but every number is exact and every claim traceable.",
    "rhythm": "short, staccato",
    "formality": "low",
    "metaphors": "fireworks, video games, primetime television",
    "numbers": "exact, usually followed by an exclamation point",
    "lex": {
        "verb": {
            "blowout": ["demolished", "steamrolled", "obliterated"],
            "comfortable": ["handled", "cruised past", "rolled past"],
            "normal": ["took down", "beat", "got past"],
            "close": ["survived", "edged", "squeaked past"],
        },
        "noun": {
            "blowout": ["an absolute massacre", "a full-on demolition", "a rout of epic proportions"],
            "comfortable": ["a statement win", "a business-like win", "a clean two-score win"],
            "normal": ["a solid W", "a legit win", "a W in the books"],
            "close": ["a total heart-stopper", "a photo finish", "a nail-biter"],
        },
        "tier": {
            "hi": ["an ABSOLUTE steal", "a home run", "worth every penny"],
            "mid": ["a nice little return", "a solid contribution", "a decent hit"],
            "lo": ["not quite fireworks yet", "a slow start", "still waiting on the payoff"],
        },
    },
    "T": {
        "h.r.blow": [
            "{w} {verb} {l}, {wp}-{lp}, and that's {noun}!",
            "{m} POINTS! {w} {verb} {l} in {wl}!",
            "{w_team} unleashes {noun} on {l_team}, {wp}-{lp}",
        ],
        "h.r.upset": [
            "UPSET ALERT: {w} ({w_rank0}) shocks {l} ({l_rank0})!",
            "{w} {verb} {l}, and the standings did NOT see it coming",
            "{w_rank0} beats {l_rank0}! {w} stuns {l} in {wl}",
        ],
        "h.r.close": [
            "{w} {verb} {l} by {m}!",
            "{m} points! {w} wins {noun} over {l}",
            "{wl}: {w} and {l} play {noun}, {wp}-{lp}!",
        ],
        "h.r.top": [
            "{wp}!!! {w} posts the week's top score",
            "{w} goes OFF for {wp}, the best score of {wl}",
            "Top score alert: {w} drops {wp} on {l}",
        ],
        "h.r.tie": [
            "TIE GAME! {a} and {b} both score {pts}!",
            "{pts} to {pts}! {a} and {b} can't be separated!",
            "Nobody wins! {a} and {b} tie in {wl}!",
        ],
        "r.lede.blow": [
            "{wl} delivered the biggest margin of the week, and it was UGLY: {w} {verb} {l}, {wp} to {lp}, by {m}!",
            "Stop what you're doing! {w_team} ({w}) {verb} {l_team} ({l}) by {m} points, the widest gap of {wl}, {wp}-{lp}! That's {noun}!",
            "{m} points! That's the margin by which {w} {verb} {l} in {wl}, and it's the biggest of the week! Final: {wp} to {lp}!",
        ],
        "r.lede.upset": [
            "Nobody expected this, at least not the standings! Going into {wl}, {w} was {w_rank0} and {l} was {l_rank0}, and {w} {verb} {l}, {wp} to {lp}!",
            "UPSET! {w}, sitting {w_rank0} before {wl}, took down {l}, who was {l_rank0}! {wp} to {lp}! The biggest table-jumper of the week!",
            "{l} was {l_rank0}. {w} was {w_rank0}. Then {wl} happened, and {w} won, {wp}-{lp}! The week's biggest upset!",
        ],
        "r.lede.close": [
            "{wp} to {lp}! {w} {verb} {l} by just {m} points in {wl}, the closest game of the week! That's {noun}!",
            "It came down to {m} points! {w_team} ({w}) {verb} {l_team} ({l}), {wp}-{lp}, in the tightest finish of {wl}!",
            "Pulse check! {w} beat {l} by {m} in the closest game of {wl}, {wp} to {lp}!",
        ],
        "r.lede.top": [
            "{wp}!!! That's the top score of {wl}, and it belongs to {w}, who {verb} {l} on the way! The league average was {wavg}!",
            "Somebody went OFF in {wl}, and it was {w}, with {wp} points, best in the league! {l} had {lp} and still lost!",
            "{w_team} ({w}) led everybody with {wp} in {wl}! The league average was {wavg}! {l} scored {lp} and got the loss!",
        ],
        "r.lede.tie": [
            "You can't make this up! {a_team} ({a}) and {b_team} ({b}) tied at {pts} points each in {wl}!",
            "A TIE! {a} and {b} both landed on {pts} in {wl}, and nobody gets the win!",
            "{pts} to {pts}! {a} and {b} played to a dead heat in {wl}!",
        ],
        "g.result": [
            "{w} {verb} {l}, {wp} to {lp}!",
            "{w_team} ({w}) {verb} {l_team} ({l}), and the final read is {wp}-{lp}.",
            "{l} fell to {w_nick}, {lp} to {wp}. That's {noun}!",
            "Final from {wl}: {w} {wp}, {l_nick} {lp}. That's {noun}!",
            "Margin: {m}. {w} {verb} {l}, {wp}-{lp}.",
            "{w} vs. {l}: {wp}-{lp}, and {w} walks away with the W!",
            "{l} put up {lp} against {w}'s {wp}, and that was that!",
            "{w} {verb} {l} by {m}! The final: {wp}-{lp}!",
            "{wp} for {w}, {lp} for {l}: {noun}!",
            "That's a wrap on {w} and {l}: {wp}-{lp}!",
        ],
        "g.tie": [
            "{a} and {b}? Dead even at {pts} apiece!",
            "{a_team} ({a}) and {b_team} ({b}) finished level at {pts} each. A tie!",
            "{pts} each for {a} and {b}, and the scoreboard has no winner!",
        ],
        "g.star": [
            "{star} ({spos}) went OFF for {spts}, which is {sshare} of {w}'s {wp}!",
            "The man, the myth, {star} ({spos}): {spts} for {w}!",
            "{star} ({spos}) put up {spts} to lead {w}'s lineup!",
        ],
        "g.goat": [
            "Meanwhile, {gname} ({gpos}) gave {l} {gpts} as a starter. Ouch!",
            "{l} got {gpts} from {gname} ({gpos}) in the starting lineup. Yikes!",
            "And {gname} ({gpos})? {gpts} for {l}. That's a rough one!",
        ],
        "g.bench": [
            "{l} left {bench_left} on the BENCH! {bench_name} ({bench_pos}) put up {bench_pts} while sitting!",
            "Lineup alert! {bench_name} ({bench_pos}) scored {bench_pts} on {l}'s bench. The best lineup would have added {bench_left}!",
            "Somebody check {l}'s lineup: {bench_left} sat on the bench, including {bench_pts} from {bench_name} ({bench_pos})!",
        ],
        "g.streak_w": [
            "{w} has now won {k} STRAIGHT! At {w_rec}, they sit {w_rank} in the standings!",
            "That's {k} in a row for {w}! The team is {w_rec} and {w_rank} in the league!",
            "{k} wins in a row! {w} is {w_rec}, {w_rank}, and flying!",
        ],
        "g.streak_l": [
            "{l} has dropped {k} in a row and sits {l_rank} at {l_rec}. Time for a big change!",
            "That's {k} straight losses for {l}, now {l_rec} and {l_rank} in the standings!",
            "{k} in a row on the wrong side for {l}. The team is {l_rec}, {l_rank}!",
        ],
        "g.record": [
            "{w} improves to {w_rec} ({w_rank})! {l} drops to {l_rec} ({l_rank})!",
            "Standings check! {w} is {w_rec} and {w_rank}. {l} is {l_rec} and {l_rank}!",
            "The result puts {w} at {w_rec} and {l} at {l_rec}!",
        ],
        "g.top": [
            "{wp} was the BEST score in the league in {wl}! The league average was {wavg}!",
            "Nobody scored more than {w} in {wl}: {wp}! The average was {wavg}!",
            "{w} led the league with {wp}! That's well clear of the {wavg} average!",
        ],
        "g.low": [
            "{lp} was the LOWEST score in the league in {wl}! The average was {wavg}!",
            "{l} brought up the rear with {lp} in {wl}, against a league average of {wavg}!",
            "Nobody scored less than {l} in {wl}: {lp}! The league average was {wavg}!",
        ],
        "g.luck_up": [
            "{n} ({n_rec}) is {luck} wins ahead of where the all-play numbers say! Somebody's got a horseshoe!",
            "By all-play, {n} has {luck} extra wins at {n_rec}! Luck is a real stat!",
            "{n} is living a charmed life: {luck} wins above expectation at {n_rec}!",
        ],
        "g.luck_down": [
            "{n} ({n_rec}) is {luck} wins behind where the all-play numbers say! The schedule is NOT being kind!",
            "By all-play, {n} should have more wins than {n_rec}: that's {luck} against expectation!",
            "{n} is cursed: {luck} wins below expectation at {n_rec}!",
        ],
        "g.upset": [
            "{w} was {w_rank0} entering {wl}. {l} was {l_rank0}. Table, meet turnaround!",
            "Before the game, {l} stood {l_rank0} and {w} stood {w_rank0}!",
            "{l_rank0} vs. {w_rank0}, and {w} won it!",
        ],
        "g.shotgun": [
            "And {n} owes {sgn}! The reason: {why}!",
            "Beer alert! {n} incurred {sgn} for {why}!",
            "{n}: {sgn} owed in {wl}, thanks to {why}!",
        ],
        "g.aside": [
            "Remember, {n}, who {trait}, took {event}!",
            "Of course, {n}, who {trait}, left {wl} with {event}!",
            "{n}, who {trait}, now has {event} to think about!",
        ],
        "r.close_shift": [
            "THE TABLE MOVED! {in_names} jumped into the top six and {out_names} fell out! {leader} still leads at {leader_rec}!",
            "Playoff picture alert! {in_names} are IN the top six now; {out_names} are OUT. {leader} sits first at {leader_rec}!",
            "After {wl}: {in_names} in, {out_names} out! {leader} leads the pack at {leader_rec}!",
        ],
        "r.close_table": [
            "{leader} leads at {leader_rec} after {wl}! {cut} holds the final playoff spot at {cut_rec}!",
            "Standings check after {wl}: {leader} on top at {leader_rec}, {cut} clinging to sixth at {cut_rec}!",
            "{leader} is first ({leader_rec}) and {cut} holds sixth ({cut_rec}) after {wl}!",
        ],
        "r.close_po": [
            "{wl} gave us {ngames}! The biggest margin: {big_m} points, {big_w} over {big_l}! The top score: {top_w}'s {top_pts}!",
            "That's a wrap on {wl}! {big_w} won by {big_m} over {big_l}, and {top_w} posted the high score, {top_pts}!",
            "{ngames} in the books! {big_w} beat {big_l} by the widest margin ({big_m}), and {top_w} led all scorers with {top_pts}!",
        ],
        "h.p.fav": [
            "{fav} is the favorite over {dog} in {wl}!",
            "{wl}: {fav} ({fav_odds}) vs. {dog} ({dog_odds}), and the odds say {fav}!",
            "Can {dog} pull the upset on {fav} in {wl}?",
        ],
        "h.p.even": [
            "{a} vs. {b} in {wl}: a TOSS-UP!",
            "{a_odds} vs. {b_odds}! {a} and {b} are neck and neck in {wl}",
            "Nobody's safe: {a} and {b} meet in {wl} with near-identical odds",
        ],
        "h.p.lev": [
            "{wl}'s BIGGEST game: {a} vs. {b}, with playoff odds on the line!",
            "{swing} points of playoff swing! {a} and {b} meet in {wl}",
            "{a} vs. {b}: the game that could swing the playoff race in {wl}",
        ],
        "p.lede": [
            "Your game of the week is {a_team} ({a}) against {b_team} ({b})! Mark it down!",
            "Circle {wl}'s game of the week: {a} vs. {b}!",
            "It's {a} vs. {b} in {wl}, and it's the game to watch!",
            "{swing} points of combined playoff swing ride on {a} vs. {b}! That's the game of {wl}!",
        ],
        "p.matchup": [
            "{a_team} ({a}, {a_rec}, {a_avg} per game) takes on {b_team} ({b}, {b_rec}, {b_avg})!",
            "{a} is {a_rec} and scoring {a_avg} a game. {b} is {b_rec} and scoring {b_avg}. Somebody has to win!",
            "{b_team} ({b}, {b_rec}, {b_avg} ppg) vs. {a_team} ({a}, {a_rec}, {a_avg} ppg)! Here we go!",
            "{a} ({a_rec}) meets {b} ({b_rec}) in {wl}, {a_avg} ppg versus {b_avg}!",
        ],
        "p.h2h_split": [
            "{a} and {b} have split their meetings this season, {h2h_rec}!",
            "The series is TIED at {h2h_rec} between {a} and {b}!",
            "{a} vs. {b} so far this season? Dead even, {h2h_rec}!",
        ],
        "p.h2h_lead": [
            "{lead} leads {trail} {h2h_rec} this season!",
            "{trail} is chasing, down {h2h_rec} to {lead} in the season series!",
            "Head to head, {lead} has the edge over {trail}: {h2h_rec}!",
        ],
        "p.h2h_none": [
            "{a} and {b} haven't met yet this season!",
            "First meeting of the year for {a} and {b}!",
            "This is {a} vs. {b} for the first time all season!",
        ],
        "p.stakes": [
            "A win sends {a} to {a_win} playoff odds; a loss drops {a} to {a_loss}! For {b}, it's {b_win} with a win and {b_loss} with a loss!",
            "{a}: {a_win} with a win, {a_loss} with a loss! {b}: {b_win} with a win, {b_loss} with a loss! That's what's at stake!",
            "Look at those swings! {a} goes from {a_loss} to {a_win}, and {b} goes from {b_loss} to {b_win}, depending on the result!",
        ],
        "p.leverage": [
            "{swing} points of combined playoff swing! No game on the slate has more at stake!",
            "This is THE leverage game of the week: {swing} points of swing between {a} and {b}!",
            "{a} and {b} are playing for {swing} points of playoff odds. Nothing else on the slate comes close!",
        ],
        "p.favorite": [
            "{fav} is the favorite on {fav_why}: {fav_odds} playoff odds to {dog}'s {dog_odds}!",
            "The numbers like {fav}: {fav_odds} to {dog}'s {dog_odds}, going by {fav_why}!",
            "{dog} is the underdog at {dog_odds}, with {fav} at {fav_odds}!",
        ],
        "p.vol": [
            "Fireworks warning! {vol_n} swings by {vol_std} points a week, while {other} is steadier at {other_std}!",
            "{vol_n} is the wild card, with a {vol_std}-point weekly swing. {other} is steadier, at {other_std}!",
            "Boom or bust! {vol_n}'s {vol_std}-point spread dwarfs {other}'s {other_std}!",
        ],
        "p.rivnote": [
            "And don't forget: it's {rv_name}! {backstory}",
            "It's {rv_name} week! {backstory}",
            "This one is {rv_name}, and the history is REAL. {backstory}",
        ],
        "p.close": [
            "Set your lineups! {a} and {b} kick off in {wl}!",
            "Don't miss {a} vs. {b} in {wl}!",
            "{wl} is coming, and {a} vs. {b} is must-see!",
        ],
        "h.t": [
            "BLOCKBUSTER! {a} ships {gave_s} to {b} for {got_s}",
            "{a} sends {gave_s} to {b} in exchange for {got_s}!",
            "{b} lands {gave_s} from {a}, and {a} gets {got_s}",
            "TRADE ALERT: {gave_s} goes from {a} to {b}, and {got_s} comes back!",
        ],
        "t.sides": [
            "It's DONE! {a} and {b} pulled the trigger in {wl}! {a} gets {a_got}, and {b} gets {b_got}!",
            "TRADE ALERT! In {wl}, {a} lands {a_got}, and {b} lands {b_got}!",
            "{b} sends {a_got} to {a} in {wl} and gets {b_got} back!",
            "{a} out, {b} in: {b_got} heads to {b}, and {a_got} goes to {a}!",
        ],
        "t.returns": [
            "And the early returns? In the {since_wk} since, {a}'s new guys have scored {a_pts} and {b}'s have scored {b_pts}! Early edge: {lead}!",
            "Scoreboard watch: {lead}'s incoming players have put up {lead_pts} to {trail}'s {trail_pts} over {since_wk}!",
            "After {since_wk}, {a}'s side has {a_pts} and {b}'s side has {b_pts}! {lead} is ahead!",
        ],
        "t.pending": [
            "{pk_side} gets {pk_got} and {pl_side} gets {pl_got}! Picks for players means we can't grade it on points yet!",
            "It's picks for players: {pl_side} gets {pl_got}, {pk_side} gets {pk_got}! Check back when the picks play a game!",
            "{pl_side} took {pl_got}; {pk_side} took {pk_got}! Not gradable yet, folks!",
        ],
        "t.fresh": [
            "Too early to grade it, folks!",
            "Check back soon: there's no production to grade yet!",
            "The jury is out, because the games haven't happened yet!",
        ],
        "t.count": [
            "That's the {nth} trade of the season for {n}!",
            "{n} is on the move! The {nth} trade of the year!",
            "It's the {nth} trade of the season for {n}!",
        ],
        "t.rec": [
            "Before the deal, {a} was {a_rec} ({a_rank}) and {b} was {b_rec} ({b_rank})!",
            "Entering that week: {a} at {a_rec} ({a_rank}), {b} at {b_rec} ({b_rank})!",
            "At the time, {a} stood {a_rank} at {a_rec}, and {b} stood {b_rank} at {b_rec}!",
        ],
        "t.close": [
            "The trade is OFFICIAL in the league log!",
            "It's processed, it's final, it's on the record!",
            "Done deal! The league log has it!",
        ],
        "h.w.big": [
            "{n} goes BIG: {bid} for {player}!",
            "{bid}! {n} breaks the bank for {player} ({pos})",
            "{n} bids {bid} to land {player}!",
        ],
        "h.w.small": [
            "{n} grabs {player} for {bid}!",
            "{player} ({pos}) lands in {n}'s lap for {bid}",
            "{n} adds {player} with a {bid} bid!",
        ],
        "h.w.free": [
            "{n} scoops up free agent {player}!",
            "{player} ({pos}) heads to {n}!",
            "{n} adds {player} off the wire!",
        ],
        "w.top_bid": [
            "{n} dropped {bid} on {player} ({pos}) in {wl}, the BIGGEST bid of the week!",
            "The biggest waiver bid of {wl}? {bid}, from {n}, for {player} ({pos})!",
            "{n} went all in: {bid} for {player} ({pos})!",
        ],
        "w.top_free": [
            "{n} added {player} ({pos}) in {wl}!",
            "The pickup to watch in {wl}: {player} ({pos}), added by {n}!",
            "{player} ({pos}) is now on {n}'s roster!",
        ],
        "w.since": [
            "Since then, {player} has put up {spts} over {since_wk}: {tier}!",
            "Over {since_wk}, {n} has gotten {spts} out of {player}. That's {tier}!",
            "{player}: {spts} in the {since_wk} since the move. {tier}!",
        ],
        "w.others": [
            "Elsewhere on the wire: {others_text}!",
            "Also on the move: {others_text}!",
            "Other adds: {others_text}!",
        ],
        "w.total": [
            "{total_n} changed hands across {total_owners} in {wl}!",
            "In all, {total_owners} added {total_n} in {wl}!",
            "{total_owners} grabbed {total_n} in {wl}!",
        ],
        "w.budget": [
            "{n} has used {spent} of a {budget} FAAB budget!",
            "FAAB check: {n} has spent {spent} out of {budget}!",
            "{spent} of {budget}: that's how much FAAB {n} has burned!",
        ],
        "w.close": [
            "{player} is on {n}'s roster now!",
            "The league log has {player} with {n}!",
            "It's official: {player} belongs to {n}!",
        ],
        "h.s": [
            "BEER REPORT, Week {wk}: {total_n} owed!",
            "{top} owes {topn} in Week {wk}!",
            "{total_n} owed in Week {wk}! Grab the cold ones!",
            "Shotgun alert: {top} leads Week {wk} with {topn}!",
        ],
        "s.total": [
            "The Week {wk} shotgun ledger is IN: {total_n} owed across {owners_n}!",
            "{owners_n} owe a combined {total_n} for Week {wk}!",
            "Pour some drinks! Week {wk} has {total_n} on the books, across {owners_n}!",
        ],
        "s.owner": [
            "{n} owes {sgn}! {list}!",
            "{n}: {sgn}. The damage: {list}!",
            "{sgn} for {n}! Here's why: {list}!",
            "{n} racked up {sgn}: {list}!",
        ],
        "s.low": [
            "LOWLIGHT: {player} ({pos}) scored {pts} in {n}'s lineup!",
            "The week's lowest ledger score: {player} ({pos}), {pts}, for {n}!",
            "{n} started {player} ({pos}), who put up {pts}. That's the lowest on the list!",
        ],
        "s.leader": [
            "{leader} leads the season ledger with {ltotal} through Week {wk}!",
            "Season-long leader: {leader}, with {ltotal} after Week {wk}!",
            "{leader} owns the most shotguns this season: {ltotal}!",
        ],
        "s.close": [
            "{top} is the first name on the Week {wk} list!",
            "Week {wk} is in the books, and {top} heads the ledger!",
            "{top} tops the Week {wk} list!",
        ],
        "h.n": [
            "STANDINGS through {wl}: {top} on top, {six} holding the sixth spot!",
            "{alive} teams are alive for {spots} playoff spots through {wl}!",
            "{top} leads, {bottom} trails: standings through {wl}",
            "Through {wl}, {six} holds the last playoff spot!",
        ],
        "h.nf": [
            "FINAL standings: {top} grabs the top seed!",
            "{six} gets the last spot, {seven} gets left out: final standings!",
            "{top} finishes first, {bottom} finishes last: the regular season is DONE",
            "The playoff field is SET: {top} first, {seven} just misses",
        ],
        "n.top": [
            "Through {wl}, {top} leads the league at {top_rec}!",
            "{top} is first at {top_rec} through {wl}!",
            "Through {wl}: {top}, {top_rec}, number one!",
            "{top} is on top at {top_rec} with {top_odds} playoff odds!",
            "{top} leads at {top_rec}, with {top_odds} playoff odds and a {bye} shot at a bye!",
        ],
        "n.cut": [
            "{six} ({six_rec}) holds the SIXTH and final spot, just ahead of {seven} ({seven_rec})!",
            "The cut line sits between {six} ({six_rec}) and {seven} ({seven_rec})!",
            "{seven} ({seven_rec}) is knocking on the door behind {six} ({six_rec})!",
        ],
        "n.luck": [
            "Luck check! {lucky} is {lucky_luck} wins above expectation, and {unlucky} is {unlucky_luck}!",
            "The luckiest team: {lucky} at {lucky_luck}! The unluckiest: {unlucky} at {unlucky_luck}!",
            "{lucky} ({lucky_luck}) has the horseshoe; {unlucky} ({unlucky_luck}) has the curse!",
        ],
        "n.clinch": [
            "CLINCHED: {names}!",
            "Playoff spots locked up by {names}!",
            "{names} are IN!",
        ],
        "n.elim": [
            "Eliminated: {names}. Next year!",
            "Mathematically out: {names}!",
            "{names} can't get in anymore!",
        ],
        "n.bottom": [
            "{bottom} is last at {bottom_rec}!",
            "The cellar belongs to {bottom} ({bottom_rec})!",
            "{bottom} sits dead last at {bottom_rec}!",
        ],
        "n.eff": [
            "Lineup watch! {best_n} gets {best_pct} of the max possible points; {worst_n} gets {worst_pct}!",
            "{best_n} sets the best lineups, at {best_pct} efficiency. {worst_n} is at {worst_pct}!",
            "Efficiency king: {best_n} ({best_pct}). Efficiency cellar: {worst_n} ({worst_pct})!",
        ],
        "n.records": [
            "The league's high score: {hi_pts}, by {hi_n} in Week {hi_wk}! The biggest blowout: {blow_m} points, {blow_w} over {blow_l}, Week {blow_wk}!",
            "Records alert! {hi_n} holds the top score at {hi_pts} (Week {hi_wk}), and {blow_w}'s {blow_m}-point win over {blow_l} (Week {blow_wk}) is the widest margin!",
            "{hi_pts} points by {hi_n} in Week {hi_wk} is the season high! {blow_w} over {blow_l} by {blow_m} is the biggest margin!",
        ],
        "n.ftop": [
            "{top} finished FIRST at {top_rec}, with {top_pf} scored!",
            "The top seed: {top}, {top_rec}, {top_pf}!",
            "{top} owned the regular season: {top_rec} and {top_pf}!",
        ],
        "n.fcut": [
            "{six} grabbed the sixth and final spot at {six_rec}! {seven} finished seventh at {seven_rec} and is OUT!",
            "The cut fell between {six} ({six_rec}) and {seven} ({seven_rec})!",
            "{seven} ({seven_rec}) missed by one spot while {six} ({six_rec}) snuck in!",
        ],
        "n.fpts": [
            "{pf_n} scored the MOST points in the regular season ({pf_pts})! {low_n} scored the fewest ({low_pts})!",
            "Scoring leader: {pf_n}, {pf_pts}! Scoring cellar: {low_n}, {low_pts}!",
            "{pf_pts} for {pf_n}, the league high! {low_n} had {low_pts}, the low!",
        ],
        "n.fbottom": [
            "{bottom} finished last at {bottom_rec}!",
            "Last place: {bottom}, {bottom_rec}!",
            "{bottom} ended up at the bottom, {bottom_rec}!",
        ],
        "n.close": [
            "Through {wl}, {top} is still on top!",
            "{top} leads the table through {wl}!",
            "{top} remains number one through {wl}!",
        ],
        "h.f": [
            "{a} vs. {b}: it's GETTING PERSONAL",
            "{a} and {b}: the tension is REAL",
            "Beef alert: {a} and {b}!",
            "{a} and {b} have HISTORY",
        ],
        "f.h2h": [
            "It started in Week {gwk}, when {w} {verb} {l}, {wp} to {lp}! The margin: {m}!",
            "In Week {gwk}, {w} beat {l}, {wp}-{lp}, by {m}! That was {noun}!",
            "{l} lost to {w} in Week {gwk}, {lp} to {wp}! A {m}-point margin!",
        ],
        "f.trade": [
            "The two did business in Week {twk}: {a} got {a_got}, and {b} got {b_got}!",
            "In Week {twk}, {a} and {b} traded! {a} landed {a_got}, and {b} landed {b_got}!",
            "Week {twk} trade alert: {b_got} to {b}, and {a_got} to {a}!",
        ],
        "f.adj": [
            "In the standings, {hi} ({hi_rec}, {hi_rank}) is right ahead of {lo} ({lo_rec}, {lo_rank}), and {pf_gap} separate them in points scored!",
            "{hi} is {hi_rank}, {lo} is {lo_rank}, and just {pf_gap} apart in points scored!",
            "{lo} is chasing {hi}! They're {lo_rank} and {hi_rank}, with {pf_gap} between them in points scored!",
        ],
        "f.blow": [
            "Remember Week {gwk}? {w} {verb} {l}, {wp} to {lp}, by {m} points!",
            "{m} POINTS! That's how much {w} beat {l} by in Week {gwk}, {wp}-{lp}!",
            "The scars from Week {gwk} are REAL: {w} won by {m} over {l}, {wp}-{lp}!",
        ],
        "f.sg": [
            "On the shotgun ledger, {a} has {a_sg} and {b} has {b_sg}!",
            "The beer count: {a} at {a_sg}, {b} at {b_sg}!",
            "{a} owes {a_sg} on the season; {b} owes {b_sg}!",
        ],
        "f.story": [
            "It's {rv_name}, and the history is REAL! {backstory}",
            "The league calls this one {rv_name}! {backstory}",
            "This is {rv_name}, folks! {backstory}",
        ],
        "f.trait": [
            "{a} {a_trait}! {b} {b_trait}! That's two people who were always going to clash!",
            "Think about it: {a} {a_trait}, and {b} {b_trait}!",
            "{a} {a_trait}. {b} {b_trait}. Do the math!",
        ],
        "f.mid": [
            "Through Week {wk}, {a} is {a_rec} ({a_rank}) and {b} is {b_rec} ({b_rank})!",
            "The standings through Week {wk}: {a} {a_rank} at {a_rec}, {b} {b_rank} at {b_rec}!",
            "{a} sits {a_rank} at {a_rec}; {b} sits {b_rank} at {b_rec} through Week {wk}!",
        ],
        "f.close": [
            "Buckle up, because this isn't over!",
            "The league better strap in!",
            "Keep your eyes on {a} and {b}!",
        ],
        "h.v": [
            "{rv_name} is BACK: {a} vs. {b} in Week {wk}!",
            "{a} vs. {b} in Week {wk}: it's {rv_name} time!",
            "Week {wk}: {a} and {b} renew {rv_name}!",
            "It's {rv_name} week! {a} meets {b}!",
        ],
        "v.lede": [
            "It's {rv_name} week! {a} plays {b} in {wl}, and you do NOT want to miss it! {backstory}",
            "Stop everything! {rv_name} is on the schedule in {wl}, with {a} against {b}! {backstory}",
            "{a} vs. {b} in {wl}: {rv_name}! {backstory}",
        ],
        "v.form": [
            "{a} is {a_rec} ({a_rank}) and putting up {a_avg} a game! {b} is {b_rec} ({b_rank}) at {b_avg}!",
            "{a}: {a_rec}, {a_rank}, {a_avg} ppg! {b}: {b_rec}, {b_rank}, {b_avg} ppg!",
            "Coming in hot: {b} at {b_rec} ({b_rank}, {b_avg} ppg) and {a} at {a_rec} ({a_rank}, {a_avg} ppg)!",
        ],
        "v.close": [
            "Week {wk} can't come fast enough for {a} and {b}!",
            "Mark Week {wk}: {a} vs. {b}!",
            "See you in Week {wk}, {a} and {b} fans!",
        ],
        "h.o": [
            "OFFSEASON WRAP: {ntrades}, {npick}, and a lot of drama!",
            "{ntrades} and {npick}: the offseason was BUSY!",
            "Before a single snap: {ntrades} and {npick}!",
        ],
        "o.lede": [
            "Before the season even started, the league logged {ntrades} and {npick}! That's a LOT!",
            "The offseason was NOT quiet: {ntrades} and {npick}!",
            "{ntrades}! {npick}! And the opening whistle hasn't even blown!",
        ],
        "o.busy": [
            "The busiest traders: {busy_text}! Those phones were HOT!",
            "Leading the trade count: {busy_text}!",
            "Most trades: {busy_text}!",
        ],
        "o.big": [
            "The biggest deal of the offseason! {side_a} got {a_got}, and {side_b} got {b_got}!",
            "Blockbuster alert: {side_a} landed {a_got}, and {side_b} landed {b_got}!",
            "The largest trade: {side_a} receives {a_got}, {side_b} receives {b_got}!",
        ],
        "o.close": [
            "{busiest} made the most trades! Respect!",
            "{busiest} led the league in trades, and it wasn't close!",
            "Hat tip to {busiest}, the trade king of the offseason!",
        ],
        "x.sig": [
            "And then, as always: “{catch}” That's {n}, folks!",
            "{n} signed off the only way {n} knows how: “{catch}”",
            "You knew it was coming! {n}: “{catch}”",
        ],
        "x.attr": [
            "“{qc}” said {n}!",
            "{n} grabbed the mic: “{qp}”",
            "“{qc}” {n} told us!",
            "{n} let it fly: “{qp}”",
            "“{qc}” {n} said, and we believe every word!",
        ],
    },
}
