"""Corporate memo: stakeholders, deliverables, variances, action items. Sincere, passive, relentlessly constructive."""
FAMILY = {
    "id": "memo",
    "label": "Corporate memo",
    "desc": "Internal-communications voice: executive summaries, KPIs, variances, action items, 'circle back'. Euphemism for everything bad, enthusiasm for everything neutral. Numbers come with a label and a target.",
    "rhythm": "medium, bulleted in spirit, many nominalizations",
    "formality": "very high, euphemistic",
    "metaphors": "quarterly results, headcount, roadmaps, stakeholder alignment",
    "numbers": "exact, framed as KPIs and variances",
    "lex": {
        "verb": {
            "blowout": ["dramatically outperformed", "decisively out-executed", "completely restructured"],
            "comfortable": ["outperformed", "out-executed", "outpaced"],
            "normal": ["beat", "bested", "outscored"],
            "close": ["narrowly outperformed", "edged", "narrowly beat"],
        },
        "noun": {
            "blowout": ["a significant variance", "a material outperformance", "an unambiguous result"],
            "comfortable": ["a solid quarter", "a favorable variance", "an on-target result"],
            "normal": ["an in-line result", "a standard deliverable", "an expected result"],
            "close": ["a within-tolerance result", "a marginal variance", "a razor-thin variance"],
        },
        "tier": {
            "hi": ["well above target", "a strong return on investment", "ahead of forecast"],
            "mid": ["in line with forecast", "roughly on target", "within tolerance"],
            "lo": ["below target to date", "a weak return to date", "behind forecast"],
        },
    },
    "T": {
        "h.r.blow": [
            "{wl} results: {w} {verb} {l} by {m} points",
            "Material variance in {wl}: {w}, {wp}; {l}, {lp}",
            "{w_team} exceeds target against {l_team}: {wp} to {lp}",
        ],
        "h.r.upset": [
            "Forecast miss: {w} ({w_rank0}) outperforms {l} ({l_rank0}) in {wl}",
            "Unexpected result: {w} {verb} {l}, {wp}-{lp}",
            "{w_rank0} over {l_rank0}: variance to plan in {wl}",
        ],
        "h.r.close": [
            "{w} {verb} {l} by {m}: within tolerance",
            "{wl} outcome: {w}, {wp}; {l}, {lp}; margin {m}",
            "Narrow variance of {m} points: {w} over {l}",
        ],
        "h.r.top": [
            "{w} achieves {wp}: the week's top KPI",
            "Top performer in {wl}: {w}, {wp}",
            "{w} posts {wp}, highest in the league for {wl}",
        ],
        "h.r.tie": [
            "{wl} outcome: {a} and {b} at parity, {pts} each",
            "Result in line with both forecasts: {a} and {b} tie at {pts}",
            "{a} and {b}: shared result, {pts}",
        ],
        "r.lede.blow": [
            "Team: please find below the {wl} results. The headline is the largest variance of the week: {w} {verb} {l}, {wp} to {lp}, a margin of {m} points. We recommend that stakeholders note this.",
            "Executive summary: in {wl}, {w_team} ({w}) {verb} {l_team} ({l}) by {m} points ({wp}-{lp}). This was the largest margin of the period.",
            "Key takeaway for {wl}: {noun}. {w} outperformed {l}, {wp} to {lp}, by {m}. It is the widest margin in the weekly report.",
        ],
        "r.lede.upset": [
            "Executive summary: results in {wl} diverged from forecast. {w}, ranked {w_rank0} entering the period, {verb} {l}, ranked {l_rank0}, {wp} to {lp}. This was the largest ranking variance in the period.",
            "Please note an unexpected outcome. Going into {wl}, the standings forecast {l} ({l_rank0}) over {w} ({w_rank0}). The actual result was {wp}-{lp} in {w}'s favor.",
            "Key takeaway: {w} ({w_rank0}) outperformed expectation by defeating {l} ({l_rank0}), {wp} to {lp}, in {wl}. Our models will be updated.",
        ],
        "r.lede.close": [
            "Executive summary: the narrowest outcome of {wl} was {w}'s {wp}-{lp} result over {l}, a margin of {m} points. We classify this as {noun}.",
            "In {wl}, {w_team} ({w}) {verb} {l_team} ({l}) by {m} points ({wp}-{lp}), the closest result of the period. Stakeholders may wish to monitor.",
            "Key takeaway: {m} points separated {w} and {l} in {wl}, {wp} to {lp}. This was the tightest result on the schedule.",
        ],
        "r.lede.top": [
            "Executive summary: the highest individual output of {wl} was {w}'s {wp} (league average: {wavg}), which delivered a win over {l} ({lp}).",
            "Key takeaway: {w_team} ({w}) led all teams with {wp} in {wl}, against a league average of {wavg}. {l} produced {lp}.",
            "Team, please note the top performance of {wl}: {w}, {wp}. The league average was {wavg}. {l} delivered {lp}.",
        ],
        "r.lede.tie": [
            "Executive summary: {a_team} ({a}) and {b_team} ({b}) tied at {pts} each in {wl}. Both teams met the other's target exactly.",
            "Please note a rare outcome. {a} and {b} each delivered {pts} in {wl}. No further action is required, as no action is possible.",
            "{wl} produced one tie: {a} and {b}, {pts} apiece. We consider this a shared deliverable.",
        ],
        "g.result": [
            "Result for {w_team} ({w}): {verb} {l_team} ({l}), {wp} to {lp}.",
            "{w} {verb} {l}: {wp}-{lp}, a margin of {m}.",
            "In {wl}, {w_nick} {verb} {l}, {wp} to {lp}. We classify the result as {noun}.",
            "{l_team} ({l_nick}) delivered {lp} against {w}'s {wp}, a gap of {m}.",
            "Result: {w}, {wp}; {l}, {lp}. Variance: {m}. Classification: {noun}.",
            "{w} delivered {wp} against {l}'s {lp}, a variance of {m}.",
            "{l} fell short of {w}'s target: {lp} against {wp}.",
            "Matchup closed: {w} over {l}, {wp}-{lp}.",
            "{w} {verb} {l}; the gap of {m} is {noun}.",
            "Outcome logged: {w}, {wp}; {l}, {lp}.",
        ],
        "g.tie": [
            "{a} and {b} delivered {pts} each.",
            "{a_team} ({a}) and {b_team} ({b}) finished at parity, {pts} apiece.",
            "Outcome for {a} and {b}: {pts}, {pts}. No winner has been identified.",
        ],
        "g.star": [
            "Top individual contributor for {w}: {star} ({spos}), {spts}, or {sshare} of the {wp} total.",
            "{star} ({spos}) delivered {spts} for {w}, representing {sshare} of team output.",
            "Please recognize {star} ({spos}), who produced {spts} toward {w}'s {wp}.",
        ],
        "g.goat": [
            "Of concern: {gname} ({gpos}) delivered {gpts} in a starting role for {l}.",
            "{l}'s {gpos} slot underperformed: {gname}, {gpts}.",
            "A review is recommended for {gname} ({gpos}), who produced {gpts} for {l}.",
        ],
        "g.bench": [
            "Resource allocation note: {l} left {bench_left} on the bench, including {bench_pts} from {bench_name} ({bench_pos}).",
            "{bench_name} ({bench_pos}) delivered {bench_pts} while unassigned on {l}'s bench. Optimal staffing would have added {bench_left}.",
            "Opportunity cost for {l}: {bench_left} on the bench, {bench_pts} of them from {bench_name} ({bench_pos}).",
        ],
        "g.streak_w": [
            "{w} has now delivered {k} consecutive wins and stands {w_rank} at {w_rec}.",
            "{k} consecutive wins for {w}, currently {w_rec} and {w_rank}.",
            "Trend: {w} is {w_rec} ({w_rank}), with {k} straight wins.",
        ],
        "g.streak_l": [
            "{l} has now experienced {k} consecutive losses and stands {l_rank} at {l_rec}.",
            "{k} consecutive losses for {l}, currently {l_rec} and {l_rank}.",
            "Trend: {l} is {l_rec} ({l_rank}), with {k} straight losses. A review is recommended.",
        ],
        "g.record": [
            "{w} advances to {w_rec} ({w_rank}); {l} moves to {l_rec} ({l_rank}).",
            "Year-to-date: {w}, {w_rec}, {w_rank}; {l}, {l_rec}, {l_rank}.",
            "After {wl}, {w} is {w_rec} and {l} is {l_rec} on a year-to-date basis.",
        ],
        "g.top": [
            "{w}'s {wp} was the highest output of {wl}, against a league average of {wavg}.",
            "No team exceeded {w}'s {wp} in {wl}. League average: {wavg}.",
            "{wp}: top performance of {wl}, from {w}. The league average was {wavg}.",
        ],
        "g.low": [
            "{l}'s {lp} was the lowest output of {wl}, against a league average of {wavg}.",
            "No team delivered less than {l}'s {lp} in {wl}. League average: {wavg}.",
            "{lp}: bottom performance of {wl}, from {l}. The league average was {wavg}.",
        ],
        "g.luck_up": [
            "{n} ({n_rec}) is {luck} wins above its expected-wins forecast, a favorable variance that may not repeat.",
            "Year-to-date, {n} has {luck} wins more than all-play output supports, at {n_rec}.",
            "{n}: {n_rec}, with {luck} wins of favorable variance.",
        ],
        "g.luck_down": [
            "{n} ({n_rec}) is {luck} wins below its expected-wins forecast, an unfavorable variance that may reverse.",
            "Year-to-date, {n} has {luck} wins fewer than all-play output supports, at {n_rec}.",
            "{n}: {n_rec}, with {luck} wins of unfavorable variance.",
        ],
        "g.upset": [
            "For context, {w} was ranked {w_rank0} and {l} was ranked {l_rank0} going into the period.",
            "Pre-period rankings had {l} at {l_rank0} and {w} at {w_rank0}.",
            "Forecast ranking: {l_rank0} over {w_rank0}. Actual result: {w}.",
        ],
        "g.shotgun": [
            "Compliance note: {n} owes {sgn} for {why}.",
            "{n} has incurred {sgn} under league policy, due to {why}.",
            "Per policy, {n} owes {sgn} for {wl} ({why}).",
        ],
        "g.aside": [
            "{n}, who {trait}, absorbed {event}. This has been flagged.",
            "For awareness: {n}, who {trait}, closed {wl} with {event}.",
            "{n}, who {trait}, now has {event} as an open item.",
        ],
        "r.close_shift": [
            "Standings update: {in_names} have moved into the top six, and {out_names} have moved out, effective after {wl}. {leader} remains first at {leader_rec}.",
            "Please note the following changes to the top six: {in_names} in, {out_names} out. {leader} leads at {leader_rec}.",
            "Effective {wl}, {in_names} occupy playoff positions vacated by {out_names}. {leader} is first at {leader_rec}.",
        ],
        "r.close_table": [
            "Standings update after {wl}: {leader} leads at {leader_rec}; {cut} holds the sixth and final playoff position at {cut_rec}.",
            "Year-to-date, {leader} is first ({leader_rec}) and {cut} is sixth ({cut_rec}) after {wl}.",
            "After {wl}, the playoff cut-off is held by {cut} ({cut_rec}), with {leader} ({leader_rec}) leading.",
        ],
        "r.close_po": [
            "Summary of {wl}: {ngames} completed. Largest margin: {big_m} points, {big_w} over {big_l}. Highest output: {top_w}, {top_pts}.",
            "{wl} is now closed: {ngames}; the widest variance was {big_w}'s {big_m}-point result over {big_l}; the top performer was {top_w} ({top_pts}).",
            "Closing note for {wl}: {ngames}, with {big_w} beating {big_l} by {big_m} and {top_w} delivering {top_pts}.",
        ],
        "h.p.fav": [
            "{wl} outlook: {fav} favored over {dog}",
            "Forecast for {wl}: {fav} ({fav_odds}) ahead of {dog} ({dog_odds})",
            "{fav} projected to outperform {dog} in {wl}",
        ],
        "h.p.even": [
            "{wl} outlook: {a} and {b} projected at parity",
            "Forecast for {wl}: {a} ({a_odds}) and {b} ({b_odds}) too close to call",
            "{a} vs. {b}: no clear projection for {wl}",
        ],
        "h.p.lev": [
            "{wl} priority item: {a} vs. {b}, {swing} points of playoff swing",
            "High-impact matchup in {wl}: {a} and {b}",
            "{a} and {b}: the most consequential game of {wl}",
        ],
        "p.lede": [
            "Team: please note the priority matchup for {wl}: {a_team} ({a}) versus {b_team} ({b}).",
            "Executive summary: the featured game in {wl} is {a} against {b}.",
            "For visibility, {wl}'s featured matchup is {a} vs. {b}.",
            "Key takeaway: {a} vs. {b} carries {swing} points of combined playoff-odds swing in {wl}, the highest on the schedule.",
        ],
        "p.matchup": [
            "{a_team} ({a}) is {a_rec} year-to-date with {a_avg} points per game; {b_team} ({b}) is {b_rec} with {b_avg}.",
            "{a}: {a_rec}, {a_avg} ppg. {b}: {b_rec}, {b_avg} ppg. Both are included in the {wl} schedule.",
            "Matchup profile: {a} ({a_rec}, {a_avg}) against {b} ({b_rec}, {b_avg}).",
            "In {wl}, {b_team} ({b}, {b_rec}, {b_avg}) is scheduled against {a_team} ({a}, {a_rec}, {a_avg}).",
        ],
        "p.h2h_split": [
            "The teams are {h2h_rec} against each other this season, a split.",
            "Head-to-head this season: {a} and {b} are even, {h2h_rec}.",
            "Prior meetings this season are level at {h2h_rec}.",
        ],
        "p.h2h_lead": [
            "{lead} leads the head-to-head {h2h_rec} this season.",
            "Prior meetings favor {lead} over {trail}, {h2h_rec}.",
            "{trail} trails {lead} {h2h_rec} in head-to-head results this season.",
        ],
        "p.h2h_none": [
            "No prior meeting this season between {a} and {b}.",
            "{a} and {b} have not yet been scheduled against each other this season.",
            "This will be the first head-to-head of the season for {a} and {b}.",
        ],
        "p.stakes": [
            "Impact assessment: a win would raise {a}'s playoff odds to {a_win}; a loss would lower them to {a_loss}. For {b}, the figures are {b_win} and {b_loss}.",
            "Playoff odds scenarios: {a}, {a_win} with a win and {a_loss} with a loss; {b}, {b_win} and {b_loss}.",
            "The stakes: {a} moves between {a_loss} and {a_win}; {b} moves between {b_loss} and {b_win}.",
        ],
        "p.leverage": [
            "Priority flag: {swing} points of combined playoff-odds swing, the highest on the {wl} schedule.",
            "Of all games this week, {a} vs. {b} carries the most leverage: {swing} points of swing.",
            "{a} and {b} are playing for {swing} points of playoff odds. No other game is comparable.",
        ],
        "p.favorite": [
            "{fav} is the projected favorite on {fav_why}: {fav_odds} against {dog}'s {dog_odds}.",
            "Based on {fav_why}, {fav} ({fav_odds}) is ahead of {dog} ({dog_odds}).",
            "{dog} is the underdog at {dog_odds}; {fav} is at {fav_odds}. Risks are noted.",
        ],
        "p.vol": [
            "Risk factor: {vol_n}'s weekly output varies by {vol_std} points, compared with {other_std} for {other}.",
            "{vol_n} shows higher volatility ({vol_std}) than {other} ({other_std}), which introduces forecast risk.",
            "{other} has been more predictable ({other_std}) than {vol_n} ({vol_std}).",
        ],
        "p.rivnote": [
            "Note: this matchup is also {rv_name}. {backstory}",
            "For context, the pairing is designated {rv_name}. {backstory}",
            "Stakeholders should be aware this is {rv_name}. {backstory}",
        ],
        "p.close": [
            "Please set lineups ahead of {wl}. {a} and {b} are scheduled.",
            "More information on {a} and {b} will be shared after {wl}.",
            "Action item: monitor {a} and {b} in {wl}.",
        ],
        "h.t": [
            "Transaction notice: {a} sends {gave_s} to {b} for {got_s}",
            "{a} and {b} finalize trade: {gave_s} for {got_s}",
            "Transaction summary: {b} receives {gave_s} from {a}; {a} receives {got_s}",
            "Asset reallocation: {gave_s} moves from {a} to {b}, {got_s} returns",
        ],
        "t.sides": [
            "Please be advised that {a} and {b} completed a trade in {wl}. {a} received {a_got}. {b} received {b_got}.",
            "Transaction summary for {wl}: {a} acquired {a_got}; {b} acquired {b_got}.",
            "In {wl}, {a} transferred {b_got} to {b} in exchange for {a_got}.",
            "{b} sent {a_got} to {a} in {wl} and received {b_got}.",
        ],
        "t.returns": [
            "Early performance review: over {since_wk}, {a}'s acquisitions have delivered {a_pts} and {b}'s have delivered {b_pts}. {lead} is ahead of plan.",
            "Return on the transaction after {since_wk}: {lead}, {lead_pts}; {trail}, {trail_pts}.",
            "Post-trade output over {since_wk}: {a}, {a_pts}; {b}, {b_pts}. {lead} holds the early advantage.",
        ],
        "t.pending": [
            "{pk_side} received {pk_got}; {pl_side} received {pl_got}. As one side received picks only, a performance review is not yet possible.",
            "A trade of picks for players: {pl_side} has {pl_got}, and {pk_side} has {pk_got}. Evaluation is deferred.",
            "{pl_side} took delivery of {pl_got}; {pk_side} took delivery of {pk_got}. Deliverables from picks are not yet available.",
        ],
        "t.fresh": [
            "A performance review is premature at this time.",
            "Insufficient data exists to evaluate the transaction.",
            "We will circle back once there is production to review.",
        ],
        "t.count": [
            "This is {n}'s {nth} trade this season.",
            "{n} has now completed the {nth} trade of this season.",
            "For {n}, this marks the {nth} trade of the year.",
        ],
        "t.rec": [
            "At the time of the trade, {a} was {a_rec} ({a_rank}) and {b} was {b_rec} ({b_rank}).",
            "Entering that week, {a} held {a_rank} at {a_rec}; {b} held {b_rank} at {b_rec}.",
            "Status prior to the transaction: {a}, {a_rec}, {a_rank}; {b}, {b_rec}, {b_rank}.",
        ],
        "t.close": [
            "The transaction is logged as complete. No further action is required.",
            "The deal has cleared. Please update your records.",
            "Status: closed.",
        ],
        "h.w.big": [
            "{n} commits {bid} to acquire {player}",
            "Major FAAB allocation: {n} spends {bid} on {player} ({pos})",
            "{n} invests {bid} in {player}",
        ],
        "h.w.small": [
            "{n} onboards {player} at a cost of {bid}, pending performance review",
            "{n} acquires {player} ({pos}) at a cost of {bid}",
            "Low-cost acquisition: {player} joins {n} for {bid}",
        ],
        "h.w.free": [
            "{n} onboards free agent {player}",
            "{player} ({pos}) joins {n} at no cost",
            "{n} adds {player} from the waiver pool",
        ],
        "w.top_bid": [
            "{n} allocated {bid} to {player} ({pos}) in {wl}, the largest FAAB commitment of the period.",
            "The largest bid of {wl} was {bid}, from {n}, for {player} ({pos}).",
            "{n} invested {bid} in {player} ({pos}), the biggest single claim of {wl}.",
        ],
        "w.top_free": [
            "{n} onboarded {player} ({pos}) in {wl}.",
            "{player} ({pos}) joined {n} in {wl} at no cost.",
            "The notable acquisition of {wl}: {player} ({pos}), by {n}.",
        ],
        "w.since": [
            "Return to date: {player} has delivered {spts} over {since_wk}, {tier}.",
            "Over {since_wk}, {n} has received {spts} from {player}: {tier}.",
            "{player} has produced {spts} in the {since_wk} since onboarding, {tier}.",
        ],
        "w.others": [
            "Other acquisitions: {others_text}.",
            "Additional waiver activity: {others_text}.",
            "Also noted: {others_text}.",
        ],
        "w.total": [
            "In total, {total_owners} made {total_n} in {wl}.",
            "{total_n} were onboarded by {total_owners} in {wl}.",
            "{wl} saw {total_n} acquired across {total_owners}.",
        ],
        "w.budget": [
            "FAAB utilization: {n} has spent {spent} of {budget}.",
            "{n} has used {spent} of a {budget} FAAB budget year-to-date.",
            "Budget status for {n}: {spent} spent, against {budget} allocated.",
        ],
        "w.close": [
            "{player} has been onboarded to {n}'s roster, effective immediately.",
            "{n} has onboarded {player}. No further action required.",
            "Status: {player}, with {n}.",
        ],
        "h.s": [
            "Compliance report, Week {wk}: {total_n} owed",
            "{top} owes {topn} for Week {wk}",
            "Week {wk} shotgun ledger: {total_n} outstanding",
            "{top} leads Week {wk} compliance items with {topn}",
        ],
        "s.total": [
            "Compliance summary for Week {wk}: {total_n} across {owners_n}.",
            "Outstanding items for Week {wk}: {total_n}, owed by {owners_n}.",
            "Week {wk} has {total_n} outstanding, across {owners_n}.",
        ],
        "s.owner": [
            "Action item for {n}: settle {sgn} ({list}).",
            "{n}: {sgn} outstanding ({list}).",
            "Item for {n}: {sgn}, owing to {list}.",
            "{n} has incurred {sgn} ({list}).",
        ],
        "s.low": [
            "Lowest output on the ledger: {player} ({pos}), {pts}, for {n}.",
            "{n}'s {player} ({pos}) delivered {pts}, the week's lowest figure.",
            "Low-water mark for Week {wk}: {player} ({pos}), {pts}, in {n}'s lineup.",
        ],
        "s.leader": [
            "{leader} leads the season in shotguns owed, {ltotal}, through Week {wk}.",
            "Year-to-date, {leader} has the highest total: {ltotal}.",
            "The season ledger is led by {leader} at {ltotal}.",
        ],
        "s.close": [
            "{top} is listed first on the Week {wk} compliance list.",
            "{top} heads the Week {wk} ledger. Please settle accordingly.",
            "Action item: {top} to settle the Week {wk} balance.",
        ],
        "h.n": [
            "Standings update through {wl}: {top} first, {six} at the cut-off",
            "{alive} teams remain viable for {spots} playoff positions through {wl}",
            "{top} leads, {bottom} trails: year-to-date through {wl}",
            "Through {wl}, {six} holds the final playoff position",
        ],
        "h.nf": [
            "Final standings: {top} secures top seed",
            "{six} makes the playoffs; {seven} does not: final regular-season report",
            "{top} first, {bottom} last: year-end summary",
            "Playoff field finalized: {six} in, {seven} out",
        ],
        "n.top": [
            "Standings update through {wl}: {top} holds first place at {top_rec}.",
            "{top} is first at {top_rec} year-to-date through {wl}.",
            "Through {wl}: {top}, {top_rec}, in first place.",
            "{top} leads at {top_rec}, with {top_odds} playoff odds.",
            "Through {wl}, {top} leads at {top_rec}, with {top_odds} playoff odds and {bye} odds of a first-round bye.",
        ],
        "n.cut": [
            "{six} ({six_rec}) holds the sixth and final playoff position, ahead of {seven} ({seven_rec}).",
            "The playoff cut-off falls between {six} ({six_rec}) and {seven} ({seven_rec}).",
            "{seven} ({seven_rec}) is first out, immediately behind {six} ({six_rec}).",
        ],
        "n.luck": [
            "Variance report: {lucky} is {lucky_luck} wins above all-play expectation; {unlucky} is {unlucky_luck}.",
            "Luck index: {lucky} at {lucky_luck}, {unlucky} at {unlucky_luck}, relative to all-play forecast.",
            "{lucky} has benefited ({lucky_luck}); {unlucky} has not ({unlucky_luck}).",
        ],
        "n.clinch": [
            "Playoff positions secured: {names}.",
            "The following have clinched: {names}.",
            "Clinched, effective immediately: {names}.",
        ],
        "n.elim": [
            "Eliminated from contention: {names}.",
            "The following can no longer qualify: {names}.",
            "No remaining path to the playoffs: {names}.",
        ],
        "n.bottom": [
            "{bottom} is in last place at {bottom_rec}.",
            "At the bottom of the standings: {bottom}, {bottom_rec}.",
            "{bottom} holds last place ({bottom_rec}).",
        ],
        "n.eff": [
            "Lineup efficiency: {best_n} captured {best_pct} of available points; {worst_n} captured {worst_pct}.",
            "{best_n} leads in efficiency at {best_pct}. {worst_n} is lowest at {worst_pct}.",
            "Efficiency KPI: {best_n}, {best_pct}; {worst_n}, {worst_pct}.",
        ],
        "n.records": [
            "League records: highest score {hi_pts} ({hi_n}, Week {hi_wk}); largest margin {blow_m} ({blow_w} over {blow_l}, Week {blow_wk}).",
            "Benchmarks: {hi_n}'s {hi_pts} in Week {hi_wk} (high score); {blow_w}'s {blow_m}-point result over {blow_l} in Week {blow_wk} (largest margin).",
            "For reference, the season high is {hi_pts} ({hi_n}, Week {hi_wk}), and the widest margin is {blow_m} ({blow_w}, Week {blow_wk}).",
        ],
        "n.ftop": [
            "{top} finished the regular season in first at {top_rec}, with {top_pf} scored.",
            "Top seed: {top}, {top_rec}, {top_pf}.",
            "{top} concluded the regular season in first place, {top_rec}, {top_pf}.",
        ],
        "n.fcut": [
            "{six} secured the sixth and final playoff position at {six_rec}; {seven} finished seventh at {seven_rec}.",
            "The playoff cut-off fell between {six} ({six_rec}) and {seven} ({seven_rec}).",
            "{six} ({six_rec}) qualified. {seven} ({seven_rec}) did not.",
        ],
        "n.fpts": [
            "{pf_n} led the league in points scored ({pf_pts}); {low_n} had the fewest ({low_pts}).",
            "Points-for ranking: {pf_n} first ({pf_pts}), {low_n} last ({low_pts}).",
            "Points-for ranking: {pf_n} first at {pf_pts}; {low_n} last at {low_pts}.",
        ],
        "n.fbottom": [
            "{bottom} placed last in the year-end ranking at {bottom_rec}.",
            "Last place: {bottom}, {bottom_rec}.",
            "{bottom} concluded the season at {bottom_rec}, the lowest record.",
        ],
        "n.close": [
            "Through {wl}, {top} leads. Please reach out with questions.",
            "The standings are current through {wl}; {top} is first.",
            "{top} remains in first place through {wl}.",
        ],
        "h.f": [
            "Interpersonal update: {a} and {b}",
            "Stakeholder alignment issue: {a} and {b}",
            "{a} and {b}: a conflict summary",
            "Notes on {a} and {b}",
        ],
        "f.h2h": [
            "The most recent interaction occurred in Week {gwk}: {w} {verb} {l}, {wp} to {lp}, by {m} points.",
            "In Week {gwk}, {w} outperformed {l}, {wp}-{lp}, by {m}, and the result remains on the record.",
            "{l} lost to {w} in Week {gwk}, {lp} to {wp}, a variance of {m}.",
        ],
        "f.trade": [
            "A relevant transaction: in Week {twk}, {a} acquired {a_got} and {b} acquired {b_got}.",
            "The two parties completed a trade in Week {twk}. {a} took {a_got}; {b} took {b_got}.",
            "In Week {twk}, {b_got} was transferred to {b} and {a_got} to {a}.",
        ],
        "f.adj": [
            "In the standings, {hi} ({hi_rec}, {hi_rank}) is adjacent to {lo} ({lo_rec}, {lo_rank}), with {pf_gap} separating them in points scored.",
            "{hi} ranks {hi_rank} and {lo} ranks {lo_rank}, a gap of {pf_gap} in points scored.",
            "{lo} trails {hi} by {pf_gap} in points scored ({lo_rank} vs. {hi_rank}).",
        ],
        "f.blow": [
            "A contributing factor is Week {gwk}: {w} {verb} {l}, {wp} to {lp}, by {m} points.",
            "In Week {gwk}, {w} defeated {l}, {wp}-{lp}, by {m} points, a variance that remains on the record.",
            "{w}'s {m}-point result over {l} in Week {gwk} ({wp}-{lp}) is among the widest margins of the period.",
        ],
        "f.sg": [
            "Compliance record: {a} has {a_sg}; {b} has {b_sg}.",
            "On the shotgun ledger, {a} owes {a_sg} and {b} owes {b_sg}.",
            "{a} stands at {a_sg} on the ledger, and {b} at {b_sg}.",
        ],
        "f.story": [
            "The relationship is documented as {rv_name}. {backstory}",
            "For background, the pairing is designated {rv_name}. {backstory}",
            "Please note the history: {rv_name}. {backstory}",
        ],
        "f.trait": [
            "Profile review: {a} {a_trait}; {b} {b_trait}.",
            "Per available profile data, {a} {a_trait}, and {b} {b_trait}.",
            "{a} {a_trait}. {b} {b_trait}. This may be relevant.",
        ],
        "f.mid": [
            "Status through Week {wk}: {a} is at {a_rec} (ranked {a_rank}); {b} is at {b_rec} (ranked {b_rank}).",
            "Standings through Week {wk}: {a}, {a_rank}, {a_rec}; {b}, {b_rank}, {b_rec}.",
            "{a} ({a_rec}, {a_rank}) and {b} ({b_rec}, {b_rank}) as of Week {wk}.",
        ],
        "f.close": [
            "Please escalate through the appropriate channels.",
            "This item will remain open.",
            "We will circle back on {a} and {b} as the situation develops.",
        ],
        "h.v": [
            "Scheduled event: {rv_name}, {a} vs. {b}, Week {wk}",
            "{a} and {b} to meet in Week {wk}: {rv_name}",
            "Week {wk} calendar: {rv_name}",
            "Reminder: {rv_name} is in Week {wk}",
        ],
        "v.lede": [
            "Team: please note that {rv_name} is scheduled for {wl}, with {a} against {b}. {backstory}",
            "Calendar update: {a} and {b} meet in {wl} for {rv_name}. {backstory}",
            "Executive summary: {rv_name} returns in {wl} ({a} vs. {b}). {backstory}",
        ],
        "v.form": [
            "{a} is {a_rec} ({a_rank}) with {a_avg} points per game; {b} is {b_rec} ({b_rank}) with {b_avg}.",
            "{a}: {a_rec}, {a_rank}, {a_avg} ppg. {b}: {b_rec}, {b_rank}, {b_avg} ppg.",
            "Current status: {b}, {b_rank} at {b_rec} ({b_avg}); {a}, {a_rank} at {a_rec} ({a_avg}).",
        ],
        "v.close": [
            "Please block off Week {wk} for {a} and {b}.",
            "{a} and {b} are scheduled for Week {wk}.",
            "Action item: attend {a} vs. {b} in Week {wk}.",
        ],
        "h.o": [
            "Offseason summary: {ntrades}, {npick}",
            "Pre-season activity report: {ntrades} and {npick}",
            "{ntrades} and {npick}: offseason recap",
        ],
        "o.lede": [
            "Team: prior to the season, the league recorded {ntrades} and {npick}. A summary follows.",
            "Offseason activity totaled {ntrades} and {npick}, per the transaction log.",
            "Executive summary: {ntrades}, {npick}, completed before kickoff.",
        ],
        "o.busy": [
            "The most active participants were {busy_text}.",
            "Trade activity, ranked by volume: {busy_text}.",
            "Leading the trade count: {busy_text}.",
        ],
        "o.big": [
            "The largest transaction: {side_a} received {a_got}, and {side_b} received {b_got}.",
            "The biggest deal moved {b_got} to {side_b} and {a_got} to {side_a}.",
            "Largest single trade: {side_a}, {a_got}; {side_b}, {b_got}.",
        ],
        "o.close": [
            "{busiest} completed the most trades. Thank you for your engagement.",
            "{busiest} led the offseason in trade activity.",
            "Recognition goes to {busiest} for the highest trade volume.",
        ],
        # ---------------- Sunday column ----------------
        "h.c": [
            "Interpersonal communications update: {a} and {b}",
            "Feedback exchange between {a} and {b}: summary and next steps",
            "{a} and {b}: alignment on messaging",
            "Weekend communications summary: {a} and {b}",
        ],
        "h.c.rv": [
            "{rv_name}: {a} and {b} issue statements",
            "{a} and {b} reopen {rv_name}: communications summary",
            "Open item {rv_name}: updated positions from {a} and {b}",
        ],
        "h.c.next": [
            "Pre-read for Week {nwk}: {a} and {b} share positions",
            "{a} and {b} meet in Week {nwk}; stakeholder messaging attached",
            "Week {nwk} readiness: {a} and {b} align on their disagreement",
        ],
        "c.lede": [
            "Executive summary: through {wl}, {a} is {a_rec} and ranked {a_rank}, and {b} is {b_rec} and ranked {b_rank}.",
            "Current standing through {wl}: {a}, {a_rec} ({a_rank}); {b}, {b_rec} ({b_rank}).",
            "For context, {a} ({a_rec}) is ranked {a_rank} and {b} ({b_rec}) is ranked {b_rank} as of {wl}.",
        ],
        "c.next": [
            "Next milestone: {a} and {b} meet in Week {nwk}.",
            "Action item: both parties are scheduled to play in Week {nwk}.",
            "The two stakeholders meet in Week {nwk}, per the calendar.",
        ],
        "c.recent": [
            "Recent performance: {a} {a_form}; {b} {b_form}.",
            "Over the last few periods, {a} {a_form}, and {b} {b_form}.",
            "Trailing results show {a} {a_form}, and {b} {b_form}.",
        ],
        "c.gap": [
            "Variance to note: {hi} ({hi_rank}, {hi_rec}) is ahead of {lo} ({lo_rank}, {lo_rec}), with a points-scored differential of {pf_gap}.",
            "{hi} is ranked {hi_rank} and {lo} is ranked {lo_rank}; the points-scored gap is {pf_gap}.",
            "The standings show {hi} at {hi_rec} ({hi_rank}) and {lo} at {lo_rec} ({lo_rank}), with {pf_gap} of points-scored variance between them.",
        ],
        "c.pick": [
            "Recommendation: favor {fav} over {dog}, based on {fav_why}.",
            "On {fav_why}, {fav} is the projected favorite over {dog}. Risks are noted.",
            "{fav} is recommended over {dog} on {fav_why}, pending further alignment.",
        ],
        "c.close": [
            "Next steps: {a} and {b} to continue the conversation offline.",
            "We will circle back with {a} and {b} as the situation develops.",
            "This item remains open. Please direct feedback to {a} and {b}.",
        ],
        # ---------------- Monday analytics ----------------
        "h.a.luck": [
            "Variance report: {lucky} favorable at {lucky_luck}, {unlucky} unfavorable at {unlucky_luck}",
            "Luck KPI: {lucky} ({lucky_luck}) outperforms forecast; {unlucky} ({unlucky_luck}) underperforms",
            "Wins versus forecast: {lucky} {lucky_luck}, {unlucky} {unlucky_luck}",
        ],
        "h.a.eff": [
            "Efficiency KPI: {best_n} at {best_pct}, {worst_n} at {worst_pct}",
            "Lineup optimization: {best_n} leads at {best_pct}; {worst_n} has an opportunity at {worst_pct}",
            "Growth area: {worst_n}'s lineup efficiency ({worst_pct})",
        ],
        "h.a.bench": [
            "Resource utilization: {bench_n} left {bench_pts} idle",
            "Bench points: {bench_n} has {bench_pts} of unrealized value",
            "{bench_n} reports {bench_pts} of underutilized bench capacity",
        ],
        "h.a.steady": [
            "Consistency report: {steady_n} on target, {wild_n} volatile",
            "Weekly rank variance: {steady_n} low, {wild_n} high",
            "{wild_n} shows high week-to-week variability; {steady_n} is steady",
        ],
        "a.lede": [
            "This report covers key metrics through {wl}, based on {gp} per team.",
            "Scope: results through {wl}, {gp} per team. All figures are final unless corrected.",
            "Below is the weekly metrics review, through {wl} and {gp} per team.",
        ],
        "a.luck": [
            "Wins versus forecast: {lucky} is {lucky_rec} against an expected {lucky_exp}, a favorable variance of {lucky_luck}. {unlucky} is {unlucky_rec} against an expected {unlucky_exp}, an unfavorable variance of {unlucky_luck}.",
            "Luck index (actual wins minus all-play expected wins): {lucky} {lucky_luck} ({lucky_rec}, forecast {lucky_exp}); {unlucky} {unlucky_luck} ({unlucky_rec}, forecast {unlucky_exp}).",
            "{lucky} has benefited from schedule variance ({lucky_rec} against a forecast of {lucky_exp}, {lucky_luck}). {unlucky} has not ({unlucky_rec} against {unlucky_exp}, {unlucky_luck}).",
        ],
        "a.eff": [
            "Lineup efficiency (points scored over the best possible lineup): {best_n} is highest at {best_pct}; {worst_n} is lowest at {worst_pct}. The league KPI stands at {lg_pct}.",
            "Efficiency KPI: {best_n}, {best_pct} (above target); {worst_n}, {worst_pct} (below target); league, {lg_pct}.",
            "{best_n} captured {best_pct} of available points, {worst_n} captured {worst_pct}, and the league captured {lg_pct}. Opportunity identified.",
        ],
        "a.bench": [
            "Resource utilization: {bench_n} left {bench_pts} on the bench against the best possible lineup, the highest in the league. {bench_low_n} left {bench_low_pts}, the lowest.",
            "Bench points left: {bench_n}, {bench_pts}; {bench_low_n}, {bench_low_pts}. Leadership may wish to review lineup processes.",
            "{bench_n} reported {bench_pts} of unrealized bench value. {bench_low_n} reported {bench_low_pts}.",
        ],
        "a.blunder": [
            "Incident of note: in Week {bl_wk}, {bl_n} finished {bl_pts} below the best possible lineup, the largest single-week gap to date. The top bench score was {bl_player_pts}, by {bl_player} ({bl_pos}).",
            "Largest single-week variance: {bl_n}, Week {bl_wk}, {bl_pts} below optimal. {bl_player} ({bl_pos}) contributed {bl_player_pts} from the bench.",
            "{bl_n} experienced a {bl_pts} shortfall against the best lineup in Week {bl_wk}. The bench's top contributor was {bl_player} ({bl_pos}) at {bl_player_pts}.",
        ],
        "a.steady": [
            "Consistency: {steady_n} shows the lowest week-to-week variance, averaging a weekly rank of {steady_avg} and ranging from {steady_band}. {wild_n} shows the highest, ranging from {wild_band}.",
            "Weekly rank variance is lowest for {steady_n} (from {steady_band}, average {steady_avg}) and highest for {wild_n} (from {wild_band}).",
            "{steady_n} remains on target (from {steady_band}). {wild_n} has been volatile, ranging from {wild_band}.",
        ],
        "a.trade": [
            "Trade performance review, Week {twk} deal: the players {lead} received have produced {lead_pts} over {since_wk}, against {trail_pts} for the players {trail} received.",
            "Early returns on the Week {twk} trade favor {lead}, {lead_pts} to {trail_pts}, after {since_wk}. {trail} will be notified of the gap.",
            "The Week {twk} trade between {lead} and {trail} is tracking ahead for {lead} ({lead_pts}) and behind for {trail} ({trail_pts}) over {since_wk}.",
        ],
        "a.close": [
            "Metrics are current through {wl}. Next review: next Monday.",
            "Please reach out with any questions about methodology.",
            "This report is for internal circulation only.",
        ],
        "x.sig": [
            "{n} then added the standard sign-off: “{catch}”",
            "As usual, {n} concluded: “{catch}”",
            "{n} closed with the familiar line: “{catch}”",
        ],
        "x.attr": [
            "“{qc}” {n} said in a statement.",
            "{n} commented: “{qp}”",
            "“{qc}” {n} wrote in a follow-up.",
            "In {n}'s words: “{qp}”",
            "“{qc}” {n} added.",
        ],
    },
}
