"""Nature documentary narrator: hushed, reverent, scientific. The league is an ecosystem; the owners are species."""
FAMILY = {
    "id": "nature",
    "label": "Nature documentary",
    "desc": "A hushed narrator observing the league as an ecosystem: territories, migrations, predators and prey. Reverent, precise, faintly amused. The numbers are field observations.",
    "rhythm": "long, slow, ceremonial, with one short sentence of awe",
    "formality": "high, scientific, soothing",
    "metaphors": "savanna, hunt, migration, habitat, food chain",
    "numbers": "exact, reported as observations",
    "lex": {
        "verb": {
            "blowout": ["devoured", "overpowered", "dismantled"],
            "comfortable": ["outmaneuvered", "outpaced", "outlasted"],
            "normal": ["bested", "outcompeted", "prevailed over"],
            "close": ["narrowly outlasted", "edged", "scraped past"],
        },
        "noun": {
            "blowout": ["a ruthless display of dominance", "a total rout", "a kill of startling efficiency"],
            "comfortable": ["a confident victory", "an orderly victory", "a clear victory"],
            "normal": ["a routine victory", "an ordinary victory", "a modest victory"],
            "close": ["a delicate balance", "a tense standoff", "a narrow escape"],
        },
        "tier": {
            "hi": ["a thriving adaptation", "a rich feeding ground", "a bountiful return"],
            "mid": ["adequate foraging", "a moderate yield", "a steady yield"],
            "lo": ["slim pickings so far", "a barren yield so far", "a meager yield so far"],
        },
    },
    "T": {
        "h.r.blow": [
            "A rout on the plains: {w} {verb} {l}, {wp}-{lp}",
            "{w} asserts dominance over {l} by {m} points in {wl}",
            "{w_team} takes {l_team} by {m}: {noun}",
        ],
        "h.r.upset": [
            "The established order is disturbed: {w} ({w_rank0}) fells {l} ({l_rank0})",
            "{w} challenges the hierarchy and wins, {wp}-{lp}",
            "{l_rank0} falls to {w_rank0} in {wl}: nature finds a way",
        ],
        "h.r.close": [
            "A standoff resolved by {m} points: {w} over {l}",
            "{w} and {l} circle each other, and {w} wins {wp}-{lp}",
            "A narrow margin of {m}: {w} survives {l} in {wl}",
        ],
        "h.r.top": [
            "{w} stands tallest in {wl}, with {wp} points",
            "The largest display of the week: {w}, {wp}",
            "{wp} points: {w} claims the highest ground in {wl}",
        ],
        "h.r.tie": [
            "A rare stalemate: {a} and {b} each score {pts}",
            "Two rivals, one result: {a} and {b} tie at {pts}",
            "{a} and {b} part ways with {pts} apiece",
        ],
        "r.lede.blow": [
            "Here, in {wl}, we witness something rare: {w} {verb} {l}, {wp} to {lp}. A margin of {m} points, the widest of the week, and {noun}.",
            "The herd has scattered. {w_team} ({w}) has overpowered {l_team} ({l}) by {m} points in {wl}, {wp} to {lp}, the largest margin observed all week.",
            "And in the open ground of {wl}, {w} {verb} {l}, {wp}-{lp}. At {m} points, it is the widest gap recorded this week.",
        ],
        "r.lede.upset": [
            "The established order is a fragile thing. Entering {wl}, {l} held the {l_rank0} position and {w} the {w_rank0}. Remarkably, {w} {verb} {l}, {wp} to {lp}, the greatest inversion observed all week.",
            "Rank is rarely questioned, yet {w}, {w_rank0} in the standings, {verb} {l}, {l_rank0}, {wp}-{lp}, in {wl}. Nature, it seems, ignores the table.",
            "{l} stood {l_rank0}; {w} stood {w_rank0}. And yet, in {wl}, it was {w} who prevailed, {wp} to {lp}.",
        ],
        "r.lede.close": [
            "Observe the tension. In {wl}, {w} {verb} {l}, {wp} to {lp}, by only {m} points, the narrowest margin observed all week. It was {noun}.",
            "A moment of delicate balance: {w_team} ({w}) and {l_team} ({l}) finished within {m} points in {wl}, {wp}-{lp}, the closest contest of the week.",
            "Rarely are two contenders so evenly matched. {w} prevailed over {l}, {wp} to {lp}, by {m} points: the week's closest result.",
        ],
        "r.lede.top": [
            "And here, in {wl}, we find the week's most formidable specimen: {w}, with {wp} points, against a league average of {wavg}. {l}, with {lp}, could not compete.",
            "The highest ground in {wl} was claimed by {w}, whose {wp} stood well above the {wavg} average. {l} managed {lp}.",
            "{w_team} ({w}) dominated the landscape of {wl} with {wp} points, the largest display of the week. {l} could answer with only {lp}.",
        ],
        "r.lede.tie": [
            "A rare sight on the plains: {a_team} ({a}) and {b_team} ({b}) finished {wl} with {pts} points apiece.",
            "Two evenly matched creatures. {a} and {b} each scored {pts} in {wl}, and neither could claim the territory.",
            "In {wl}, {a} and {b} reached a stalemate at {pts} points each.",
        ],
        "g.result": [
            "{w_team} ({w}) {verb} {l_team} ({l}), {wp} to {lp}, as the light faded.",
            "{w} {verb} {l}, {wp}-{lp}: {noun}.",
            "By the end of {wl}, {w_nick} had {verb} {l}, {wp} to {lp}.",
            "{l_nick} could not hold its ground against {w}, {lp} to {wp}. It was {noun}.",
            "The result: {w}, {wp}; {l}, {lp}. A margin of {m}, {noun}.",
            "{w} met {l} in {wl}, and prevailed, {wp} to {lp}.",
            "{l} could not match {w}'s {wp}, falling {lp} to {wp}.",
            "Observe: {w} {verb} {l}, by {m}, in {noun}.",
            "{wp} against {lp}: {w} claimed the contest with {l}.",
            "{w} held the ground against {l}, finishing {wp} to {lp}.",
        ],
        "g.tie": [
            "{a} and {b} each scored {pts}. Neither prevailed.",
            "{a_team} ({a}) and {b_team} ({b}) reached a stalemate at {pts}.",
            "{pts} points apiece, and neither {a} nor {b} claimed the field.",
        ],
        "g.star": [
            "The strongest of {w}'s lineup was {star} ({spos}), contributing {spts}, some {sshare} of the {wp}.",
            "{star} ({spos}) led the pack for {w}, with {spts}.",
            "Observe {star}, the {spos}: {spts} for {w}, {sshare} of the team total.",
        ],
        "g.goat": [
            "{l}'s weakest member was {gname} ({gpos}), who produced only {gpts}.",
            "From the {gpos} slot, {gname} contributed {gpts} for {l}. A poor foraging day.",
            "{gname} ({gpos}) was a drain on {l}'s resources: {gpts}.",
        ],
        "g.bench": [
            "{l} left {bench_left} unclaimed on the bench, among them {bench_pts} from {bench_name} ({bench_pos}).",
            "On {l}'s bench, {bench_name} ({bench_pos}) scored {bench_pts}, unobserved. A better lineup was worth {bench_left}.",
            "{bench_left} lay unclaimed on {l}'s bench; {bench_name} ({bench_pos}) accounted for {bench_pts}.",
        ],
        "g.streak_w": [
            "{w} has now prevailed {k} times in succession, and stands {w_rank} at {w_rec}.",
            "{k} victories in a row for {w}, now {w_rec} and {w_rank} in the hierarchy.",
            "A thriving run: {w} is {w_rec}, {w_rank}, and has won {k} straight.",
        ],
        "g.streak_l": [
            "{l} has now fallen {k} times in succession, and stands {l_rank} at {l_rec}.",
            "{k} defeats in a row for {l}, now {l_rec} and {l_rank} in the hierarchy.",
            "A difficult stretch: {l} is {l_rec}, {l_rank}, and has lost {k} straight.",
        ],
        "g.record": [
            "{w} advances to {w_rec} ({w_rank}); {l} retreats to {l_rec} ({l_rank}).",
            "After {wl}, {w} holds {w_rank} place at {w_rec}, and {l} holds {l_rank} at {l_rec}.",
            "The hierarchy now reads {w}, {w_rec}, and {l}, {l_rec}.",
        ],
        "g.top": [
            "{w}'s {wp} was the largest display of {wl}. The league average was {wavg}.",
            "No creature stood taller in {wl} than {w}, with {wp}. The average was {wavg}.",
            "{wp} for {w}, the highest ground of the week. The average: {wavg}.",
        ],
        "g.low": [
            "{l}'s {lp} was the smallest display of {wl}. The league average was {wavg}.",
            "No creature stood lower in {wl} than {l}, with {lp}. The average was {wavg}.",
            "{lp} for {l}, the lowest ground of the week. The average: {wavg}.",
        ],
        "g.luck_up": [
            "{n} ({n_rec}) has {luck} wins more than its foraging deserves, as the all-play numbers show. Fortune is, in nature, never permanent.",
            "By all-play, {n} is {luck} wins ahead at {n_rec}. A fortunate territory.",
            "{n}: {n_rec}, and {luck} wins above expectation. A blessed habitat.",
        ],
        "g.luck_down": [
            "{n} ({n_rec}) has {luck} wins fewer than its foraging deserves, as the all-play numbers show. Fortune, in nature, is never fair.",
            "By all-play, {n} is {luck} wins behind at {n_rec}. A harsh territory.",
            "{n}: {n_rec}, and {luck} wins below expectation. A difficult habitat.",
        ],
        "g.upset": [
            "Entering the contest, {l} stood {l_rank0} in the hierarchy and {w} stood {w_rank0}.",
            "The pecking order had {l} at {l_rank0} and {w} at {w_rank0}.",
            "{w_rank0} confronts {l_rank0}, and the order is disturbed.",
        ],
        "g.shotgun": [
            "{n}, by league custom, now owes {sgn} for {why}.",
            "A ritual is owed: {sgn} from {n}, for {why}.",
            "{n} must observe the tradition of {sgn}, owing to {why}.",
        ],
        "g.aside": [
            "{n}, who {trait}, bears {event}, as the species must.",
            "{n}, who {trait}, departs {wl} with {event}.",
            "One observes {n}, who {trait}, now carrying {event}.",
        ],
        "r.close_shift": [
            "And so the hierarchy shifts: {in_names} have entered the top six, and {out_names} have left it. {leader} remains the dominant presence at {leader_rec}.",
            "In the standings, {in_names} now occupy the top six, as {out_names} depart it. {leader} leads at {leader_rec}.",
            "After {wl}, the top six rearranges itself: {in_names} in, {out_names} out. {leader} presides at {leader_rec}.",
        ],
        "r.close_table": [
            "After {wl}, {leader} presides at {leader_rec}, while {cut} clings to the last of the six playoff territories at {cut_rec}.",
            "The hierarchy after {wl}: {leader} at the top ({leader_rec}), {cut} holding sixth ({cut_rec}).",
            "{leader} commands the table at {leader_rec}; {cut} holds sixth place at {cut_rec}, tenuously.",
        ],
        "r.close_po": [
            "And so {wl} ends. {ngames} observed: the widest margin, {big_m} points, {big_w} over {big_l}; the highest display, {top_w}'s {top_pts}.",
            "In {wl}, {ngames}. {big_w} prevailed over {big_l} by {big_m}, and {top_w} produced the largest display, {top_pts}.",
            "{wl}: {ngames}. {big_w}'s {big_m}-point victory over {big_l} was the widest margin, and {top_w}'s {top_pts} the highest score.",
        ],
        "h.p.fav": [
            "{fav} is the stronger contender against {dog} in {wl}",
            "{wl}: {fav} ({fav_odds}) approaches {dog} ({dog_odds}) as the likelier survivor",
            "The odds favor {fav} over {dog} in {wl}",
        ],
        "h.p.even": [
            "Two evenly matched contenders: {a} and {b} in {wl}",
            "{wl}: {a} and {b} meet with nearly equal odds",
            "{a} and {b} circle each other in {wl}",
        ],
        "h.p.lev": [
            "A confrontation of consequence: {a} and {b} in {wl}",
            "{swing} points of playoff odds ride on {a} against {b} in {wl}",
            "{wl}'s decisive encounter: {a} and {b}",
        ],
        "p.lede": [
            "In {wl}, our attention turns to a meeting of two notable contenders: {a_team} ({a}) and {b_team} ({b}).",
            "The encounter of the week: {a} and {b}, in {wl}.",
            "Here, in {wl}, {a} and {b} will meet at the watering hole.",
            "Some {swing} points of combined playoff odds depend on the meeting of {a} and {b} in {wl}.",
        ],
        "p.matchup": [
            "{a_team} ({a}) is {a_rec} and averages {a_avg} points per game; {b_team} ({b}) is {b_rec} and averages {b_avg}.",
            "{a} stands at {a_rec}, scoring {a_avg} a game. {b} stands at {b_rec}, scoring {b_avg}.",
            "Here, a pair of contenders: {a} ({a_rec}, {a_avg}) and {b} ({b_rec}, {b_avg}).",
            "{b_team} ({b}, {b_rec}, {b_avg} per game) approaches {a_team} ({a}, {a_rec}, {a_avg} per game) in {wl}.",
        ],
        "p.h2h_split": [
            "The two have already met this season and divided the spoils, {h2h_rec}.",
            "{a} and {b} have split their encounters, {h2h_rec}.",
            "In earlier meetings this season, neither has proved superior: {h2h_rec}.",
        ],
        "p.h2h_lead": [
            "In earlier encounters this season, {lead} has had the better of {trail}, {h2h_rec}.",
            "{trail} is behind {lead} {h2h_rec} in their meetings this season.",
            "{lead} leads the series {h2h_rec}.",
        ],
        "p.h2h_none": [
            "The two have not yet met this season; the territory is unclaimed.",
            "{a} and {b} are strangers this season, as far as the record shows.",
            "This will be the first encounter of the season between {a} and {b}.",
        ],
        "p.stakes": [
            "Should {a} win, its playoff odds rise to {a_win}; should it lose, they fall to {a_loss}. For {b}, the figures are {b_win} and {b_loss}.",
            "The stakes for {a}: {a_win} with a victory, {a_loss} with a defeat. For {b}: {b_win} and {b_loss}.",
            "Survival odds for {a} range between {a_loss} and {a_win}; for {b}, between {b_loss} and {b_win}.",
        ],
        "p.leverage": [
            "No encounter this week moves the playoff odds more: {swing} points of combined swing.",
            "{swing} points of playoff swing hinge on this meeting, more than any other this week.",
            "{a} and {b} contest {swing} points of playoff odds, the greatest stake of the week.",
        ],
        "p.favorite": [
            "{fav} is the stronger contender on {fav_why}, with {fav_odds} to {dog}'s {dog_odds}.",
            "By {fav_why}, {fav} ({fav_odds}) holds the advantage over {dog} ({dog_odds}).",
            "{dog} is the weaker contender at {dog_odds}, while {fav} stands at {fav_odds}.",
        ],
        "p.vol": [
            "{vol_n} is unpredictable, its weekly scoring swinging {vol_std} points, while {other}'s is steadier at {other_std}.",
            "Note the temperament: {vol_n} varies by {vol_std} points a week, and {other} by {other_std}.",
            "{other} is a creature of habit ({other_std} points of swing); {vol_n} is far less so ({vol_std}).",
        ],
        "p.rivnote": [
            "These two share a long-standing enmity, known as {rv_name}. {backstory}",
            "It is also {rv_name}, an old territorial dispute. {backstory}",
            "Observers know this pairing as {rv_name}. {backstory}",
        ],
        "p.close": [
            "We will return to observe {a} and {b} in {wl}.",
            "Quietly, {a} and {b} prepare for {wl}.",
            "The encounter between {a} and {b} awaits in {wl}.",
        ],
        "h.t": [
            "{a} surrenders {gave_s} to {b} in exchange for {got_s}",
            "{a} trades {gave_s} to {b} for {got_s}: an exchange of resources",
            "{b} acquires {gave_s} from {a}, and sends {got_s} in return",
            "{a} and {b} exchange {gave_s} for {got_s}",
        ],
        "t.sides": [
            "In {wl}, {a} and {b} exchanged resources. {a} took {a_got}; {b} took {b_got}.",
            "A rare act of cooperation in {wl}: {a} received {a_got}, and {b} received {b_got}.",
            "{a} gave up {b_got} and received {a_got} in {wl}.",
            "{b} sent {a_got} to {a}, and took {b_got} in return.",
        ],
        "t.returns": [
            "Over the {since_wk} since, {a}'s new acquisitions have yielded {a_pts}, and {b}'s {b_pts}. {lead} appears the early beneficiary.",
            "Early observations: {lead}'s acquisitions have produced {lead_pts}, {trail}'s {trail_pts}, over {since_wk}.",
            "After {since_wk}, {a}'s side of the exchange has yielded {a_pts}, and {b}'s {b_pts}. {lead} is ahead.",
        ],
        "t.pending": [
            "{pk_side} received {pk_got}, and {pl_side} received {pl_got}. Picks are seeds, not yet fruit; the exchange cannot be judged.",
            "{pl_side} took the established players ({pl_got}); {pk_side} took the seeds ({pk_got}). It is too early to say which will thrive.",
            "A trade of picks for players: {pl_side} holds {pl_got}, {pk_side} holds {pk_got}. The yield is yet to be observed.",
        ],
        "t.fresh": [
            "It is too early to observe the results of the exchange.",
            "Time must pass before the yield can be measured.",
            "No games have been played since; there is nothing to measure.",
        ],
        "t.count": [
            "It is {n}'s {nth} trade of the season, a restless creature.",
            "{n} has completed the {nth} exchange of the season, a restless forager.",
            "For {n}, this is the {nth} exchange of the season.",
        ],
        "t.rec": [
            "Before the exchange, {a} stood {a_rank} at {a_rec}, and {b} stood {b_rank} at {b_rec}.",
            "At the time, {a} was {a_rec} ({a_rank}) and {b} was {b_rec} ({b_rank}).",
            "Before the exchange, {a} occupied {a_rank} at {a_rec}; {b} occupied {b_rank} at {b_rec}.",
        ],
        "t.close": [
            "The league's log records the exchange as complete.",
            "The deal is done, and entered in the record.",
            "And so the exchange is complete.",
        ],
        "h.w.big": [
            "{n} spends {bid} to secure {player}",
            "{n} stakes {bid} on {player} ({pos})",
            "A bold investment: {n} pays {bid} for {player}",
        ],
        "h.w.small": [
            "{n} forages {player} for {bid}",
            "{player} ({pos}) enters {n}'s range for {bid}",
            "{n} claims {player} with a {bid} bid",
        ],
        "h.w.free": [
            "{n} gathers {player} from the wire",
            "{player} ({pos}) wanders into {n}'s territory at no cost",
            "{n} adds {player} without spending",
        ],
        "w.top_bid": [
            "{n} spent {bid} to claim {player} ({pos}) in {wl}, the largest investment of the week.",
            "The largest bid of {wl}, {bid}, came from {n}, who claimed {player} ({pos}).",
            "{n} committed {bid} to {player} ({pos}), the biggest single claim of {wl}.",
        ],
        "w.top_free": [
            "{n} gathered {player} ({pos}) from the wire in {wl}, at no cost.",
            "{player} ({pos}) found a new territory with {n} in {wl}.",
            "The notable arrival of {wl}: {player} ({pos}), with {n}.",
        ],
        "w.since": [
            "Across {since_wk} of observation, {player} has yielded {spts} for {n}: {tier}.",
            "{player} has yielded {spts} over {since_wk}. That is {tier}.",
            "Over {since_wk}, {n} has taken {spts} from {player}: {tier}.",
        ],
        "w.others": [
            "Elsewhere in the habitat, foraging continued: {others_text}.",
            "Others foraging that week: {others_text}.",
            "And among the rest: {others_text}.",
        ],
        "w.total": [
            "In all, {total_owners} gathered {total_n} in {wl}.",
            "{total_n} found new territory among {total_owners} in {wl}.",
            "The wire saw {total_n} claimed by {total_owners} in {wl}.",
        ],
        "w.budget": [
            "{n} has used {spent} of a {budget} FAAB reserve.",
            "Of its {budget} reserve, {n} has spent {spent}.",
            "{n}'s FAAB stores stand at {spent} spent of {budget}.",
        ],
        "w.close": [
            "{player} is now part of {n}'s roster.",
            "{n} has gained {player}. The ecosystem adapts.",
            "{player} now belongs to {n}.",
        ],
        "h.s": [
            "The Beer Report, Week {wk}: {total_n} owed in the ancient ritual",
            "{top} observes the ritual {topn} times in Week {wk}",
            "Week {wk} yields {total_n} for the ritual",
            "In Week {wk}, {top} leads the ritual with {topn}",
        ],
        "s.total": [
            "In Week {wk}, the ritual ledger lists {total_n} across {owners_n}.",
            "In Week {wk}, {owners_n} observe the ritual {total_n} times over.",
            "Week {wk} leaves {total_n} to be settled by {owners_n}.",
        ],
        "s.owner": [
            "{n} must observe the ritual {sgn}: {list}.",
            "{sgn} from {n}, for {list}.",
            "The ledger notes, for {n}, {sgn}: {list}.",
            "The ledger notes {sgn} for {n}: {list}.",
        ],
        "s.low": [
            "The lowest figure observed was {player} ({pos}), {pts}, in {n}'s lineup.",
            "{n}'s {player} ({pos}) managed only {pts}, the week's lowest.",
            "At {pts}, {player} ({pos}) marked the floor for {n}.",
        ],
        "s.leader": [
            "{leader} leads the season's ritual count with {ltotal} through Week {wk}.",
            "Through Week {wk}, no member has owed more than {leader}: {ltotal}.",
            "The season's tally belongs to {leader}, at {ltotal}.",
        ],
        "s.close": [
            "{top} heads the Week {wk} ledger.",
            "The Week {wk} ritual begins with {top}.",
            "{top} is first among the week's debtors.",
        ],
        "h.n": [
            "The hierarchy through {wl}: {top} dominant, {six} clinging to sixth",
            "{alive} teams still contend for {spots} playoff places through {wl}",
            "{top} leads the pack, {bottom} trails: standings through {wl}",
            "Through {wl}, {six} holds the last playoff territory",
        ],
        "h.nf": [
            "The final hierarchy: {top} dominant, {seven} shut out",
            "{six} claims the last place, {seven} does not: the final standings",
            "{top} first, {bottom} last: the regular season concludes",
            "The playoff field settles: {six} in, {seven} out",
        ],
        "n.top": [
            "Through {wl}, {top} commands the standings at {top_rec}.",
            "{top} leads the pack at {top_rec} through {wl}.",
            "At the top of the hierarchy through {wl}: {top}, {top_rec}.",
            "{top} leads at {top_rec}, with {top_odds} playoff odds through {wl}.",
            "Through {wl}, {top} presides at {top_rec}, with {top_odds} playoff odds and {bye} to earn a bye.",
        ],
        "n.cut": [
            "{six} ({six_rec}) holds the last playoff territory, with {seven} ({seven_rec}) just behind.",
            "The line falls between {six} ({six_rec}) and {seven} ({seven_rec}).",
            "{seven} ({seven_rec}) is first out, and {six} ({six_rec}) last in.",
        ],
        "n.luck": [
            "Fortune favors the few: {lucky} is {lucky_luck} wins above the all-play expectation, and {unlucky} is {unlucky_luck}.",
            "By all-play, {lucky} has {lucky_luck} wins it has not earned; {unlucky} has {unlucky_luck}.",
            "{lucky} ({lucky_luck}) enjoys fortune; {unlucky} ({unlucky_luck}) endures its absence.",
        ],
        "n.clinch": [
            "Secure in the playoffs: {names}.",
            "These have claimed their places: {names}.",
            "{names} have secured their place in the next season's migration.",
        ],
        "n.elim": [
            "No longer able to reach the playoffs: {names}.",
            "The migration cannot include: {names}.",
            "For {names}, the season is, in effect, over.",
        ],
        "n.bottom": [
            "At the foot of the hierarchy: {bottom}, {bottom_rec}.",
            "{bottom} occupies last place at {bottom_rec}.",
            "The lowest ground is occupied by {bottom} ({bottom_rec}).",
        ],
        "n.eff": [
            "In lineup efficiency, {best_n} captures {best_pct} of available points; {worst_n} captures {worst_pct}.",
            "{best_n} makes the most of its resources ({best_pct}); {worst_n} the least ({worst_pct}).",
            "Efficiency: {best_n}, {best_pct}; {worst_n}, {worst_pct}.",
        ],
        "n.records": [
            "The records of the season: the highest score is {hi_pts}, by {hi_n} in Week {hi_wk}; the widest margin is {blow_m}, by {blow_w} over {blow_l} in Week {blow_wk}.",
            "{hi_n}'s {hi_pts} in Week {hi_wk} remains the highest score, and {blow_w}'s {blow_m}-point victory over {blow_l} in Week {blow_wk} the widest margin.",
            "Two marks stand: {hi_pts} ({hi_n}, Week {hi_wk}) and {blow_m} points ({blow_w} over {blow_l}, Week {blow_wk}).",
        ],
        "n.ftop": [
            "{top} finished as the apex of the season at {top_rec}, with {top_pf} scored.",
            "The top seed belongs to {top}: {top_rec}, {top_pf}.",
            "{top} completed the regular season on top, {top_rec}, {top_pf}.",
        ],
        "n.fcut": [
            "{six} claimed the last playoff place at {six_rec}. {seven}, at {seven_rec}, was left outside.",
            "The treeline fell between {six} ({six_rec}) and {seven} ({seven_rec}).",
            "{six} ({six_rec}) survives. {seven} ({seven_rec}) does not.",
        ],
        "n.fpts": [
            "{pf_n} foraged the most all season ({pf_pts}); {low_n} foraged the least ({low_pts}).",
            "In the contest for resources, {pf_n} gathered {pf_pts}, and {low_n} gathered {low_pts}.",
            "{pf_pts} for {pf_n} marks the high ground; {low_pts} for {low_n} the low.",
        ],
        "n.fbottom": [
            "{bottom} finished at the foot of the food chain, {bottom_rec}.",
            "On the forest floor: {bottom}, {bottom_rec}.",
            "{bottom} claimed the lowest rung of the food chain, {bottom_rec}.",
        ],
        "n.close": [
            "So stands the hierarchy through {wl}, with {top} at its head.",
            "Through {wl}, {top} leads the pack.",
            "{top} remains the dominant presence through {wl}.",
        ],
        "h.f": [
            "{a} and {b}: a territorial dispute",
            "Rivals of the plains: {a} and {b}",
            "{a} and {b}, observed in the wild",
            "A dispute of long standing: {a} and {b}",
        ],
        "f.h2h": [
            "The dispute was settled, for the moment, in Week {gwk}, when {w} {verb} {l}, {wp} to {lp}, by {m} points.",
            "In Week {gwk}, {w} prevailed over {l}, {wp}-{lp}, by {m}. {l} will not soon forget.",
            "{l} lost to {w} in Week {gwk}, {lp} to {wp}: {noun}.",
        ],
        "f.trade": [
            "In Week {twk}, the two exchanged resources: {a} took {a_got}, and {b} took {b_got}. Such exchanges often breed resentment.",
            "A trade in Week {twk} binds them: {a} received {a_got}, and {b} received {b_got}.",
            "In Week {twk}, {b_got} passed to {b}, and {a_got} to {a}.",
        ],
        "f.adj": [
            "In the hierarchy, {hi} ({hi_rec}, {hi_rank}) holds ground just above {lo} ({lo_rec}, {lo_rank}), {pf_gap} apart in points scored.",
            "{hi} stands {hi_rank} and {lo} stands {lo_rank}, separated by {pf_gap} in points scored: close neighbors.",
            "{lo} lags {hi} by {pf_gap} of resources, {lo_rank} to {hi_rank} on the ladder.",
        ],
        "f.blow": [
            "Memories are long on the plains. In Week {gwk}, {w} {verb} {l}, {wp} to {lp}, by {m} points.",
            "In Week {gwk}, {w} overpowered {l}, {wp}-{lp}, by {m}.",
            "{w}'s {m}-point victory over {l} in Week {gwk} ({wp}-{lp}) is the kind of margin a rival remembers.",
        ],
        "f.sg": [
            "By the ritual ledger, {a} owes {a_sg} and {b} owes {b_sg}.",
            "The ritual count: {a}, {a_sg}; {b}, {b_sg}.",
            "Among the ritual-bound, {a} stands at {a_sg}, and {b} at {b_sg}.",
        ],
        "f.story": [
            "The league calls the dispute {rv_name}. {backstory}",
            "Its elders know it as {rv_name}. {backstory}",
            "The enmity has a name: {rv_name}. {backstory}",
        ],
        "f.trait": [
            "{a} {a_trait}; {b} {b_trait}. Two temperaments, one habitat.",
            "Observe the temperaments: {a} {a_trait}, and {b} {b_trait}.",
            "{a} {a_trait}. {b} {b_trait}. They were never likely to share a watering hole.",
        ],
        "f.mid": [
            "Through Week {wk}, {a} holds {a_rank} at {a_rec}, and {b} holds {b_rank} at {b_rec}.",
            "The hierarchy through Week {wk}: {a}, {a_rank}, {a_rec}; {b}, {b_rank}, {b_rec}.",
            "Field notes through Week {wk}: {a} ({a_rec}, {a_rank}) and {b} ({b_rec}, {b_rank}).",
        ],
        "f.close": [
            "The dispute, like all such disputes, will continue.",
            "Neither has yielded. Nature takes its course.",
            "We will watch, from a respectful distance.",
        ],
        "h.v": [
            "{rv_name} resumes: {a} and {b} meet in Week {wk}",
            "Old rivals return: {a} and {b}, Week {wk}",
            "Week {wk}: {rv_name} on the plains",
            "{a} and {b} renew an ancient dispute, {rv_name}",
        ],
        "v.lede": [
            "And now, in {wl}, an old rivalry resumes: {rv_name}, with {a} facing {b}. {backstory}",
            "Some feuds are older than the season. {rv_name} returns in {wl}, {a} against {b}. {backstory}",
            "In {wl}, {a} and {b} meet once more in {rv_name}. {backstory}",
        ],
        "v.form": [
            "{a} comes in {a_rec} ({a_rank}), averaging {a_avg}; {b} comes in {b_rec} ({b_rank}), averaging {b_avg}.",
            "Specimen {a}: {a_rec}, rank {a_rank}, {a_avg} per game. Specimen {b}: {b_rec}, rank {b_rank}, {b_avg} per game.",
            "{b} stands {b_rank} at {b_rec}, averaging {b_avg}; {a} stands {a_rank} at {a_rec}, averaging {a_avg}.",
        ],
        "v.close": [
            "We will return in Week {wk} to observe {a} and {b}.",
            "Week {wk} will decide the next chapter for {a} and {b}.",
            "The two meet again in Week {wk}, as they must.",
        ],
        "h.o": [
            "The offseason migration: {ntrades} and {npick}",
            "{ntrades} and {npick}: movements before the season",
            "A winter of exchanges: {ntrades}, {npick}",
        ],
        "o.lede": [
            "Before the season began, the league recorded {ntrades} and {npick}, a flurry of movement as the herd prepared.",
            "The quiet months saw {ntrades} and {npick}, according to the field log.",
            "In the quiet months, {ntrades} and {npick} were recorded.",
        ],
        "o.busy": [
            "The most active traders were {busy_text}, restless creatures.",
            "The most restless traders of the season: {busy_text}.",
            "Those who could not sit still: {busy_text}.",
        ],
        "o.big": [
            "The largest exchange: {side_a} received {a_got}, and {side_b} received {b_got}.",
            "The greatest deal of the winter sent {b_got} to {side_b} and {a_got} to {side_a}.",
            "{side_a} took {a_got}; {side_b} took {b_got}. It was the winter's largest trade.",
        ],
        "o.close": [
            "{busiest} made the most trades, a remarkable appetite.",
            "No creature traded more than {busiest}.",
            "{busiest} foraged hardest through the winter, in trades.",
        ],
        "x.sig": [
            "And then, as {n} always does: “{catch}”",
            "{n} gave the familiar call: “{catch}”",
            "The call of {n}, heard again: “{catch}”",
        ],
        "x.attr": [
            "“{qc}” said {n}, in a low voice.",
            "{n}, approached carefully, said: “{qp}”",
            "“{qc}” {n} said, unbothered.",
            "From {n}, a response: “{qp}”",
            "“{qc}” {n} remarked, and moved on.",
        ],
    },
}
