"""Analytics nerd: all-play, luck, efficiency, variance, odds. Hedges everything, rounds nothing."""
FAMILY = {
    "id": "nerd",
    "label": "Analytics nerd",
    "desc": "Cites all-play record, expected wins, luck index, lineup efficiency, standard deviation and playoff odds. Parentheticals, hedges, and a faint disappointment in anyone who trusts a single game.",
    "rhythm": "long, clause-heavy with parentheticals",
    "formality": "medium-high",
    "metaphors": "statistics, probability, spreadsheets",
    "numbers": "exact, with context (percentages, shares, deviations)",
    "lex": {
        "verb": {
            "blowout": ["obliterated", "dismantled", "pummeled"],
            "comfortable": ["outscored", "outproduced", "beat"],
            "normal": ["outpaced", "beat", "defeated"],
            "close": ["edged", "narrowly outscored", "squeezed past"],
        },
        "noun": {
            "blowout": ["a tail-of-the-distribution result", "an extreme outlier of a game", "a lopsided outlier"],
            "comfortable": ["a comfortable two-score result", "an above-median margin", "a clear win"],
            "normal": ["a median result", "a typical margin", "an unremarkable result"],
            "close": ["a coin-flip-sized margin", "a within-the-noise result", "a one-possession game"],
        },
        "tier": {
            "hi": ["well above replacement level", "a clearly positive return on the bid", "a high-leverage hit"],
            "mid": ["roughly what the price implied", "a fair return", "about market value"],
            "lo": ["below replacement level so far", "a negative return so far", "underwater on the bid"],
        },
    },
    "T": {
        "h.r.blow": [
            "{w} {verb} {l} by {m}: {noun}",
            "Margin of {m} in {wl}: {w}'s {wp} against {l}'s {lp} is {noun}",
            "{wp} to {lp}: {w_team} posts {noun} against {l_team}",
        ],
        "h.r.upset": [
            "{w_rank0} over {l_rank0}: {w} beats the standings in {wl}",
            "The table said {l}, the box score said {w}: {wp}-{lp}",
            "{w} ({w_rank0}) {verb} {l} ({l_rank0}), and the priors take a hit",
        ],
        "h.r.close": [
            "{m} points, {noun}: {w} {verb} {l}, {wp}-{lp}",
            "Within the noise: {w} over {l} by {m} in {wl}",
            "{w} wins by {m}, which tells us very little about who is better",
        ],
        "h.r.top": [
            "{wp}: {w} posts the week's high score, well above the {wavg} mean",
            "{w}'s {wp} leads {wl} against a league average of {wavg}",
            "High score of {wl}: {w}, {wp}, against {l}",
        ],
        "h.r.tie": [
            "{pts}-{pts}: {a} and {b} tie, a result the model treats as half a win each",
            "A tie in {wl}: {a} and {b} both score {pts}",
            "{a} and {b} finish equal at {pts}, a rare cell in the table",
        ],
        "r.lede.blow": [
            "The week's most extreme result was {w}'s {wp}-{lp} win over {l} in {wl}: a margin of {m}, {noun}, and the largest on the schedule.",
            "Start with the tail. {w_team} ({w}) {verb} {l_team} ({l}) by {m} points in {wl} ({wp}-{lp}), the biggest margin of the week by a distance.",
            "{wl}'s outlier belongs to {w}, who {verb} {l}, {wp} to {lp}. A {m}-point margin is the widest of the slate and a reminder that scoring variance has fat tails.",
        ],
        "r.lede.upset": [
            "Before {wl}, the table (a noisy estimate, but the one we have) ranked {l} {l_rank0} and {w} {w_rank0}. {w} {verb} {l}, {wp} to {lp}, which is the largest rank inversion of the week.",
            "The standings predicted {l} ({l_rank0}) over {w} ({w_rank0}) in {wl}. The box score disagreed, {wp}-{lp}. One game is one sample, but it was the biggest surprise on the slate.",
            "{w} entered {wl} at {w_rank0} and {l} at {l_rank0}. {w} won, {wp} to {lp}, the widest gap in the table crossed all week.",
        ],
        "r.lede.close": [
            "The week's smallest margin was {m} points: {w} {verb} {l}, {wp} to {lp}, in {wl}. That is {noun}, and a reminder to not read much into it.",
            "{w_team} ({w}) and {l_team} ({l}) finished within {m} points in {wl}, {wp}-{lp}, the closest game of the week. Call it {noun}.",
            "{wp}-{lp}. A {m}-point difference separated {w} and {l} in {wl}, the narrowest of the slate; the underlying scoring distributions barely tell them apart.",
        ],
        "r.lede.top": [
            "The highest score of {wl} was {w}'s {wp} (league mean: {wavg}), a total that carried the win over {l}, who scored {lp}. High scores win at a very high rate, so this one carries limited information.",
            "{w_team} ({w}) led all teams with {wp} in {wl}, against a league mean of {wavg}. {l} scored {lp} and lost.",
            "Top of the distribution in {wl}: {w}, {wp}, against a mean of {wavg}. The win over {l} ({lp}) was close to automatic.",
        ],
        "r.lede.tie": [
            "{a_team} ({a}) and {b_team} ({b}) tied at {pts} each in {wl}, which the standings count as half a win for both.",
            "A tie in {wl}: {a} and {b} both scored {pts}. The scoring distributions have a lot of resolution; this was a collision anyway.",
            "{a} and {b} landed on {pts} points apiece in {wl}, a draw that adds a half win to each side's total.",
        ],
        "g.result": [
            "{w_team} ({w}) {verb} {l_team} ({l}), {wp}-{lp}, a margin of {m}.",
            "{w} scored {wp} to {l}'s {lp} (margin {m}), {noun}.",
            "In {wl}, {w_nick} {verb} {l}, {wp} to {lp}.",
            "{l_team} ({l_nick}) scored {lp} and lost to {w}'s {wp}: {noun} at {m} points.",
            "Final: {w} {wp}, {l} {lp}. The margin of {m} is {noun}.",
            "{w} beat {l} {wp}-{lp}, a margin of {m}, which is {noun}.",
            "Box score: {w} {wp}, {l} {lp}.",
            "{l}'s {lp} was not enough against {w}'s {wp}.",
            "{w} {verb} {l}; the {m}-point gap is {noun}.",
            "The {w}-{l} game finished {wp} to {lp}, a {m}-point margin.",
        ],
        "g.tie": [
            "{a} and {b} scored {pts} each, a draw that counts as half a win apiece.",
            "{a_team} ({a}) and {b_team} ({b}) tied at {pts}, adding a half win to each record.",
            "The scoring ended level at {pts} for {a} and {b}.",
        ],
        "g.star": [
            "{star} ({spos}) provided {spts} for {w}, {sshare} of the {wp} total, so most of the win came from elsewhere in the lineup.",
            "{w}'s top starter was {star} ({spos}) at {spts}, a {sshare} share of the team score.",
            "{star} ({spos}) scored {spts}, which is {sshare} of {w}'s {wp}. Concentration like that is a variance source.",
        ],
        "g.goat": [
            "{gname} ({gpos}) returned {gpts} in a starting slot for {l}, a drag on the total.",
            "{l}'s lineup carried a dud: {gname} ({gpos}), {gpts}.",
            "One starter for {l}, {gname} ({gpos}), produced {gpts}, which is below any reasonable expectation.",
        ],
        "g.bench": [
            "{l} left {bench_left} on the table: {bench_name} ({bench_pos}) scored {bench_pts} on the bench, and the optimal lineup was {bench_left} better.",
            "An optimal lineup would have scored {bench_left} more for {l}, including {bench_pts} from {bench_name} ({bench_pos}), who sat.",
            "{bench_name} ({bench_pos}) scored {bench_pts} on {l}'s bench. Measured against the best lineup available, {l} gave up {bench_left}.",
        ],
        "g.streak_w": [
            "{w} has won {k} straight (now {w_rec}, {w_rank}), though streaks are mostly noise.",
            "That makes {k} consecutive wins for {w}, at {w_rec} and {w_rank} in the table.",
            "{w} ({w_rec}, {w_rank}) is on a {k}-game win streak, which the model discounts heavily.",
        ],
        "g.streak_l": [
            "{l} has lost {k} straight (now {l_rec}, {l_rank}), which says more about the schedule than it might seem.",
            "That makes {k} consecutive losses for {l}, at {l_rec} and {l_rank} in the table.",
            "{l} ({l_rec}, {l_rank}) is on a {k}-game losing streak; whether it persists is a question for the scoring average.",
        ],
        "g.record": [
            "{w} moves to {w_rec} ({w_rank}); {l} moves to {l_rec} ({l_rank}).",
            "The result leaves {w} at {w_rec}, {w_rank} in the table, and {l} at {l_rec}, {l_rank}.",
            "After {wl}: {w}, {w_rec}, {w_rank}; {l}, {l_rec}, {l_rank}.",
        ],
        "g.top": [
            "{w}'s {wp} was the highest score of {wl}, against a league mean of {wavg}.",
            "No team beat {wp} in {wl}. The mean score was {wavg}.",
            "{wp} puts {w} at the top of the weekly distribution (mean {wavg}).",
        ],
        "g.low": [
            "{l}'s {lp} was the lowest score of {wl}, against a league mean of {wavg}.",
            "No team scored fewer than {lp} in {wl}. The mean score was {wavg}.",
            "{lp} puts {l} at the bottom of the weekly distribution (mean {wavg}).",
        ],
        "g.luck_up": [
            "{n}'s luck index stands at {luck} wins ({n_rec}): the weekly scoring says the team has won more games than it earned.",
            "By all-play expectation, {n} is {luck} wins to the good at {n_rec}. That tends to regress.",
            "{n} ({n_rec}) is {luck} wins above its all-play expectation, which is the kind of gap that usually closes.",
        ],
        "g.luck_down": [
            "{n}'s luck index stands at {luck} wins ({n_rec}): the weekly scoring says the team has earned more than it got.",
            "By all-play expectation, {n} is {luck} wins to the bad at {n_rec}. That tends to regress too.",
            "{n} ({n_rec}) is {luck} wins below its all-play expectation, a gap the schedule may eventually repay.",
        ],
        "g.upset": [
            "Before the game, {w} ranked {w_rank0} and {l} ranked {l_rank0}.",
            "The table had {l} at {l_rank0} and {w} at {w_rank0} entering {wl}.",
            "Prior rank: {l}, {l_rank0}; {w}, {w_rank0}.",
        ],
        "g.shotgun": [
            "{n} also owes {sgn}: {why}.",
            "Shotgun ledger: {sgn} for {n} ({why}).",
            "{n} incurred {sgn} in {wl} ({why}), a small but nonzero tax on the lineup.",
        ],
        "g.aside": [
            "{n}, who {trait}, took {event} (n = 1, so draw no conclusions).",
            "A note on {n}, who {trait}: the week produced {event}.",
            "{n}, who {trait}, now owns {event}.",
        ],
        "r.close_shift": [
            "In the standings, {in_names} moved into the top six after {wl} and {out_names} dropped out. {leader} leads at {leader_rec}.",
            "The top-six set changed: {in_names} in, {out_names} out. {leader} remains first at {leader_rec}.",
            "After {wl}, the playoff positions now hold {in_names} where {out_names} used to be. {leader} is first at {leader_rec}.",
        ],
        "r.close_table": [
            "After {wl}, {leader} leads at {leader_rec} and {cut} holds the sixth and final spot at {cut_rec}.",
            "The top of the table: {leader}, {leader_rec}. The cut line: {cut}, {cut_rec}.",
            "{leader} ({leader_rec}) is first through {wl}; {cut} ({cut_rec}) sits at the cut line.",
        ],
        "r.close_po": [
            "{wl}: {ngames}, a largest margin of {big_m} ({big_w} over {big_l}), and a top score of {top_pts} from {top_w}.",
            "Summary of {wl}: {ngames}; widest margin {big_m} points ({big_w} over {big_l}); highest score {top_w}, {top_pts}.",
            "{ngames} in {wl}. The tails: {big_w}'s {big_m}-point win over {big_l}, and {top_w}'s {top_pts}.",
        ],
        "h.p.fav": [
            "{fav} ({fav_odds}) over {dog} ({dog_odds}): what the model says about {wl}",
            "{wl}: the model favors {fav} over {dog}",
            "{fav} has the edge on {dog} in {wl}, {fav_odds} to {dog_odds} in playoff odds",
        ],
        "h.p.even": [
            "{a} vs. {b} in {wl}: indistinguishable at {a_odds} and {b_odds}",
            "{wl}: the model cannot separate {a} from {b}",
            "{a} and {b} meet in {wl} with near-identical playoff odds",
        ],
        "h.p.lev": [
            "{wl}'s highest-leverage game: {a} vs. {b}, {swing} points of swing",
            "{swing} points of playoff swing: {a} vs. {b}, {wl}",
            "The model's pick for most important game in {wl}: {a} vs. {b}",
        ],
        "p.lede": [
            "The game of the week is {a_team} ({a}) against {b_team} ({b}) in {wl}.",
            "By the numbers, {wl}'s featured game is {a} vs. {b}.",
            "{a} and {b} meet in {wl}, the game the model flags for attention.",
            "{a} vs. {b} carries {swing} points of combined playoff-odds swing in {wl}, the most of any game on the slate.",
        ],
        "p.matchup": [
            "{a_team} ({a}) is {a_rec} with {a_avg} points per game; {b_team} ({b}) is {b_rec} with {b_avg}.",
            "{a}: {a_rec}, {a_avg} ppg. {b}: {b_rec}, {b_avg} ppg. (Records lag scoring; both are small samples.)",
            "Scoring first: {a} averages {a_avg}, {b} averages {b_avg}. Records: {a_rec} and {b_rec}.",
            "In {wl}, {b_team} ({b}, {b_rec}, {b_avg}) faces {a_team} ({a}, {a_rec}, {a_avg}).",
        ],
        "p.h2h_split": [
            "{a} and {b} are {h2h_rec} against each other this season, a sample of tiny size.",
            "Head to head this season, {a} and {b} are even at {h2h_rec}.",
            "The season series is {h2h_rec} (a coin flip with extra steps).",
        ],
        "p.h2h_lead": [
            "{lead} leads the season series {h2h_rec}, which carries little predictive weight.",
            "Head to head, {lead} is {h2h_rec} against {trail} this season.",
            "{trail} is {h2h_rec} down to {lead} in games between the two, a small sample.",
        ],
        "p.h2h_none": [
            "{a} and {b} have not played each other this season, so there is no head-to-head sample.",
            "No head-to-head data exists for {a} and {b} this season.",
            "The two have yet to meet, so the series sample is zero.",
        ],
        "p.stakes": [
            "The simulations give {a} {a_win} playoff odds with a win and {a_loss} with a loss, and {b} {b_win} with a win and {b_loss} with a loss.",
            "Conditional playoff odds: {a}, {a_win} if win and {a_loss} if loss; {b}, {b_win} if win and {b_loss} if loss.",
            "Leverage in numbers: {a} moves between {a_loss} and {a_win}, and {b} moves between {b_loss} and {b_win}.",
        ],
        "p.leverage": [
            "Summing the conditional swings gives {swing} points of playoff odds, the highest of the slate.",
            "{swing} points of combined swing makes this the highest-leverage game of {wl}'s slate, by the model.",
            "Of every game this week, {a} vs. {b} moves the most playoff probability: {swing} points.",
        ],
        "p.favorite": [
            "{fav} is the model favorite on {fav_why} ({fav_odds} to {dog}'s {dog_odds}).",
            "On {fav_why}, {fav} ({fav_odds}) rates ahead of {dog} ({dog_odds}), though the margin of error is wide.",
            "The model has {dog} at {dog_odds} and {fav} at {fav_odds}, which makes {dog} the underdog.",
        ],
        "p.vol": [
            "{vol_n}'s weekly scoring has a standard deviation of {vol_std}, against {other_std} for {other}, so the higher-variance team has the better shot at an upset.",
            "Variance note: {vol_n} swings by {vol_std} points a week; {other} swings by {other_std}.",
            "The spread in {vol_n}'s scores ({vol_std}) dwarfs {other}'s ({other_std}).",
        ],
        "p.rivnote": [
            "(The pairing is {rv_name}, which the model ignores and the owners do not.) {backstory}",
            "It is also {rv_name}, a variable the data does not capture. {backstory}",
            "Off the spreadsheet: {rv_name}. {backstory}",
        ],
        "p.close": [
            "Treat any single prediction here as one draw from a wide distribution.",
            "{a} and {b} will play {wl}; the model will be revised afterward.",
            "The model will update after {a} and {b} play.",
        ],
        "h.t": [
            "{a} sends {gave_s} to {b} for {got_s}: grading the trade",
            "{a} trades {gave_s} to {b} for {got_s}",
            "{b} acquires {gave_s} from {a} in exchange for {got_s}",
            "The {a}-{b} trade, parsed: {gave_s} out, {got_s} back",
        ],
        "t.sides": [
            "In {wl}, {a} received {a_got} and {b} received {b_got}.",
            "The {wl} trade between {a} and {b} moved {b_got} to {b} and {a_got} to {a}.",
            "{a} gave up {b_got} for {a_got} in {wl}.",
            "{b} received {b_got} and sent {a_got} to {a} in the {wl} deal.",
        ],
        "t.returns": [
            "Over the {since_wk} since the trade, {a}'s incoming players scored {a_pts} and {b}'s scored {b_pts}. {lead} leads on production; the sample is small.",
            "Production check: {lead}'s new players have {lead_pts} to {trail}'s {trail_pts} across {since_wk}.",
            "{a}'s side has produced {a_pts} and {b}'s side {b_pts} in {since_wk}. {lead} is ahead, but production in small samples is unstable.",
        ],
        "t.pending": [
            "{pk_side} received {pk_got} and {pl_side} received {pl_got}. With picks on one side, there is no production to compare.",
            "{pl_side} took {pl_got}; {pk_side} took {pk_got}. A picks-for-players deal has no points to analyze yet.",
            "Picks have no scoring history, so this deal ({pk_side}: {pk_got}; {pl_side}: {pl_got}) cannot be graded on production.",
        ],
        "t.fresh": [
            "There is no production to grade yet.",
            "The sample is zero games; the grade will have to wait.",
            "Nothing to measure yet.",
        ],
        "t.count": [
            "It is the {nth} trade of the season for {n}.",
            "That is {n}'s {nth} trade of the season, a small sample of a large appetite.",
            "For {n}, this is the {nth} trade of the season.",
        ],
        "t.rec": [
            "Entering that week, {a} was {a_rec} ({a_rank}) and {b} was {b_rec} ({b_rank}).",
            "Before the trade, {a} sat {a_rank} at {a_rec}; {b} sat {b_rank} at {b_rec}.",
            "At the time, the table had {a} {a_rank} ({a_rec}) and {b} {b_rank} ({b_rec}).",
        ],
        "t.close": [
            "The transaction is logged as complete.",
            "The league log marks the deal complete.",
            "It cleared and is in the log.",
        ],
        "h.w.big": [
            "{n} pays {bid} for {player}, the week's biggest bid",
            "A {bid} price tag for {player} ({pos}): {n}'s bet",
            "{n} bids {bid} on {player}",
        ],
        "h.w.small": [
            "{n} spends {bid} on {player}, a bet with unknown variance",
            "{n} claims {player} ({pos}) for {bid}",
            "A {bid} bid lands {player} with {n}",
        ],
        "h.w.free": [
            "{n} adds free agent {player}",
            "{player} ({pos}) joins {n} off the wire",
            "{n} picks up {player} at no FAAB cost",
        ],
        "w.top_bid": [
            "{n} paid {bid} for {player} ({pos}) in {wl}, the highest bid of the week.",
            "The top FAAB bid of {wl}: {bid}, from {n}, for {player} ({pos}).",
            "{n} spent {bid} on {player} ({pos}), the week's largest single claim.",
        ],
        "w.top_free": [
            "{n} added {player} ({pos}) in {wl} at no cost.",
            "{n} added {player} ({pos}) in {wl}, at a cost we can price later.",
            "The pickup of note in {wl} was {player} ({pos}), by {n}.",
        ],
        "w.since": [
            "In the {since_wk} since, {player} has scored {spts} for {n}: {tier}.",
            "{player} has produced {spts} over {since_wk}, {tier}.",
            "Over {since_wk}, {n} has gotten {spts} from {player}. That is {tier}.",
        ],
        "w.others": [
            "The remaining sample of adds: {others_text}.",
            "The rest of the wire: {others_text}.",
            "Also added: {others_text}.",
        ],
        "w.total": [
            "{total_n} were added by {total_owners} in {wl}.",
            "{total_owners} accounted for {total_n} in {wl}.",
            "The wire saw {total_n} added by {total_owners} in {wl}.",
        ],
        "w.budget": [
            "{n} has used {spent} of a {budget} FAAB budget.",
            "FAAB use: {n}, {spent} of {budget}.",
            "On the season, {n} has spent {spent} against a {budget} cap.",
        ],
        "w.close": [
            "{player} is on {n}'s roster.",
            "{n} now carries {player}.",
            "The log shows {player} with {n}.",
        ],
        "h.s": [
            "Beer Report, Week {wk}: {total_n} owed, tabulated",
            "{top} leads Week {wk}'s shotgun count with {topn}",
            "Week {wk} ledger: {total_n}, and a long tail",
            "Shotgun distribution, Week {wk}: {top} at the top with {topn}",
        ],
        "s.total": [
            "The Week {wk} ledger has {total_n} across {owners_n}.",
            "{owners_n} account for {total_n} in Week {wk}.",
            "Week {wk}'s shotgun total: {total_n}, spread over {owners_n}.",
        ],
        "s.owner": [
            "{n}: {sgn} ({list}).",
            "{n} owes {sgn}, from {list}.",
            "{sgn} for {n}: {list}.",
            "{n} contributes {sgn}: {list}.",
        ],
        "s.low": [
            "The lowest score in the ledger: {player} ({pos}), {pts}, in {n}'s lineup.",
            "{n}'s {player} ({pos}) posted {pts}, the floor of the week.",
            "At {pts}, {player} ({pos}) set the Week {wk} floor for {n}.",
        ],
        "s.leader": [
            "{leader} leads the season ledger at {ltotal} through Week {wk}.",
            "Cumulative leader: {leader}, {ltotal}, through Week {wk}.",
            "Through Week {wk}, the season count is highest for {leader} ({ltotal}).",
        ],
        "s.close": [
            "{top} is first on the Week {wk} ledger.",
            "{top} leads the Week {wk} list; counts are as logged.",
            "Counts for Week {wk} are as logged, starting with {top}.",
        ],
        "h.n": [
            "Standings through {wl}: {top} first, {six} at the cut line",
            "{alive} teams with better than a 5% shot at {spots} spots through {wl}",
            "{top} leads, {bottom} trails: the table through {wl}",
            "Through {wl}, the cut line runs through {six}",
        ],
        "h.nf": [
            "Final standings: {top} takes the top seed",
            "{six} grabs the last seed, {seven} misses: final regular-season table",
            "{top} first, {bottom} last: the regular season by the numbers",
            "The cut line sits between {six} and {seven}: final table",
        ],
        "n.top": [
            "Sorted by record through {wl}: {top} first at {top_rec}.",
            "The table through {wl} has {top} first, {top_rec}.",
            "At the top through {wl}: {top}, {top_rec}.",
            "{top} (first, {top_rec}) has {top_odds} playoff odds through {wl}.",
            "{top} leads at {top_rec} through {wl}, with {top_odds} playoff odds and {bye} bye odds.",
        ],
        "n.cut": [
            "The cut line: {six} ({six_rec}) in, {seven} ({seven_rec}) out.",
            "{six} ({six_rec}) holds the sixth and final spot, one place ahead of {seven} ({seven_rec}).",
            "{seven} ({seven_rec}) is the first team out, behind {six} ({six_rec}).",
        ],
        "n.luck": [
            "The luck index: {lucky} at {lucky_luck} wins relative to all-play expectation, {unlucky} at {unlucky_luck}.",
            "{lucky} has {lucky_luck} wins above all-play expectation; {unlucky} has {unlucky_luck}.",
            "Luck, measured as actual wins minus all-play expected wins: {lucky} {lucky_luck}, {unlucky} {unlucky_luck}.",
        ],
        "n.clinch": [
            "Clinched (exact): {names}.",
            "Playoff spots clinched by {names}, mathematically.",
            "{names} have clinched.",
        ],
        "n.elim": [
            "Eliminated (exact): {names}.",
            "{names} are mathematically out.",
            "No path remains for {names}.",
        ],
        "n.bottom": [
            "The bottom of the table is {bottom}, at {bottom_rec}.",
            "The bottom of the table: {bottom}, {bottom_rec}.",
            "{bottom} ({bottom_rec}) is at the bottom.",
        ],
        "n.eff": [
            "Lineup efficiency (actual points over optimal): {best_n} leads at {best_pct}; {worst_n} trails at {worst_pct}.",
            "{best_n} captures {best_pct} of the available points; {worst_n} captures {worst_pct}.",
            "Efficiency spread: {best_n} {best_pct}, {worst_n} {worst_pct}.",
        ],
        "n.records": [
            "League records: high score {hi_pts} ({hi_n}, Week {hi_wk}); widest margin {blow_m} ({blow_w} over {blow_l}, Week {blow_wk}).",
            "The tails so far: {hi_pts} by {hi_n} (Week {hi_wk}), and a {blow_m}-point margin, {blow_w} over {blow_l} (Week {blow_wk}).",
            "Extremes: {hi_n}'s {hi_pts} in Week {hi_wk} is the high; {blow_w}'s {blow_m}-point win over {blow_l} in Week {blow_wk} is the widest.",
        ],
        "n.ftop": [
            "{top} finished first at {top_rec} with {top_pf} scored.",
            "The top seed: {top}, {top_rec}, {top_pf}.",
            "{top} ended on top: {top_rec}, {top_pf}.",
        ],
        "n.fcut": [
            "The cut line: {six} ({six_rec}) took seed six; {seven} ({seven_rec}) finished just outside.",
            "{six} ({six_rec}) made it; {seven} ({seven_rec}) did not.",
            "Seed six went to {six} at {six_rec}, and {seven} at {seven_rec} missed.",
        ],
        "n.fpts": [
            "{pf_n} scored the most ({pf_pts}); {low_n} scored the fewest ({low_pts}).",
            "Scoring extremes: {pf_n}, {pf_pts}, and {low_n}, {low_pts}.",
            "Points for: high {pf_n} ({pf_pts}), low {low_n} ({low_pts}).",
        ],
        "n.fbottom": [
            "Sorted ascending, {bottom} comes first: {bottom_rec}.",
            "The last-place finisher was {bottom}, {bottom_rec}.",
            "{bottom} ended at the bottom: {bottom_rec}.",
        ],
        "n.close": [
            "Through {wl}, {top} is first.",
            "The table is current through {wl}; {top} leads.",
            "{top} leads through {wl}.",
        ],
        "h.f": [
            "{a} and {b}: what the data says about the grudge",
            "A statistical look at {a} and {b}",
            "{a}-{b}: the numbers behind the tension",
            "Quantifying {a} versus {b}",
        ],
        "f.h2h": [
            "The data point is Week {gwk}: {w} {verb} {l}, {wp}-{lp}, by {m}. That is {noun}.",
            "In their Week {gwk} meeting, {w} won by {m} ({wp}-{lp}), {noun}.",
            "{l} lost to {w} in Week {gwk}, {lp} to {wp}, a margin of {m}.",
        ],
        "f.trade": [
            "The relevant transaction: in Week {twk}, {a} received {a_got} and {b} received {b_got}.",
            "A Week {twk} trade links them: {a} took {a_got}, and {b} took {b_got}.",
            "In Week {twk}, {b_got} went to {b} and {a_got} went to {a}.",
        ],
        "f.adj": [
            "{hi} ({hi_rec}, {hi_rank}) and {lo} ({lo_rec}, {lo_rank}) are neighbors in the table, separated by {pf_gap} in points scored.",
            "The table puts {hi} {hi_rank} and {lo} {lo_rank}, with {pf_gap} of points separating them.",
            "{lo} trails {hi} by {pf_gap} in points for, {lo_rank} to {hi_rank}.",
        ],
        "f.blow": [
            "The outlier is Week {gwk}: {w} {verb} {l}, {wp} to {lp}, a margin of {m}.",
            "In Week {gwk}, {w}'s {m}-point win over {l} ({wp}-{lp}) sat far in the tail of the margin distribution.",
            "{w} beat {l} by {m} in Week {gwk}, {wp}-{lp}, among the widest margins of the season.",
        ],
        "f.sg": [
            "The shotgun ledger shows {a} at {a_sg} and {b} at {b_sg}.",
            "Season shotguns: {a}, {a_sg}; {b}, {b_sg}.",
            "{a} has {a_sg} on the ledger; {b} has {b_sg}.",
        ],
        "f.story": [
            "The league tracks it as {rv_name}. {backstory}",
            "Record-keeping aside, the owners call it {rv_name}. {backstory}",
            "The pairing's name in the league file is {rv_name}. {backstory}",
        ],
        "f.trait": [
            "Profile data: {a} {a_trait}; {b} {b_trait}.",
            "Per their profiles, {a} {a_trait}, while {b} {b_trait}.",
            "Qualitatively, {a} {a_trait} and {b} {b_trait}.",
        ],
        "f.mid": [
            "Records through Week {wk}: {a}, {a_rec} (rank {a_rank}); {b}, {b_rec} (rank {b_rank}).",
            "Table through Week {wk}: {a}, {a_rank}, {a_rec}; {b}, {b_rank}, {b_rec}.",
            "{a} ({a_rec}, {a_rank}) and {b} ({b_rec}, {b_rank}) through Week {wk}.",
        ],
        "f.close": [
            "Whether the tension is signal or noise is not something the data can say.",
            "More games will improve the estimate.",
            "The sample is small; the grudge, apparently, is not.",
        ],
        "h.v": [
            "{rv_name} in Week {wk}: {a} vs. {b}, by the numbers",
            "{rv_name}, Week {wk}: {a} and {b}, one more data point",
            "Week {wk}: {rv_name} and what the model thinks",
            "{a}-{b} ({rv_name}), Week {wk}: the stat sheet",
        ],
        "v.lede": [
            "{rv_name} is on the schedule in {wl}, with {a} playing {b}. {backstory}",
            "{wl} brings {rv_name}: {a} against {b}. {backstory}",
            "The model has no variable for {rv_name}, which returns in {wl} ({a} vs. {b}). {backstory}",
        ],
        "v.form": [
            "{a}: {a_rec}, {a_rank} in the table, {a_avg} per game. {b}: {b_rec}, {b_rank}, {b_avg} per game.",
            "{a} is {a_rec} ({a_rank}) and scores {a_avg}; {b} is {b_rec} ({b_rank}) and scores {b_avg}.",
            "By the numbers: {b} {b_rec}, {b_rank}, {b_avg} ppg; {a} {a_rec}, {a_rank}, {a_avg} ppg.",
        ],
        "v.close": [
            "The model will update after {a} and {b} play in Week {wk}.",
            "{a} and {b} play in Week {wk}; one game will not settle anything.",
            "Week {wk} adds one data point to the {a}-{b} file.",
        ],
        "h.o": [
            "The offseason in numbers: {ntrades}, {npick}",
            "{ntrades} and {npick}: an offseason summary",
            "Offseason transaction count: {ntrades}, {npick}",
        ],
        "o.lede": [
            "Before the season began, the league logged {ntrades} and {npick}.",
            "Offseason volume: {ntrades} and {npick}, per the transaction log.",
            "The raw counts: {ntrades}, {npick}.",
        ],
        "o.busy": [
            "By trade count, the most active were {busy_text}.",
            "Trade leaders: {busy_text}.",
            "The distribution of trades is skewed toward {busy_text}.",
        ],
        "o.big": [
            "The largest deal by volume: {side_a} received {a_got} and {side_b} received {b_got}.",
            "The biggest single trade sent {b_got} to {side_b} and {a_got} to {side_a}.",
            "Largest transaction: {side_a}, {a_got}; {side_b}, {b_got}.",
        ],
        "o.close": [
            "The mode of the trade distribution is {busiest}.",
            "{busiest} is the outlier in trade volume.",
            "{busiest} sits at the top of the trade-count histogram.",
        ],
        "x.sig": [
            "{n}'s standard sign-off, which the model treats as noise: “{catch}”",
            "{n} added the usual: “{catch}”",
            "As always, {n} closed with: “{catch}”",
        ],
        "x.attr": [
            "“{qc}” said {n}, with no controls.",
            "{n}, asked for a comment, said: “{qp}”",
            "“{qc}” {n} told reporters, the sample being one.",
            "{n}'s response: “{qp}”",
            "“{qc}” {n} said, n = 1.",
        ],
    },
}
