"""Noir: first-person hardboiled narration. Rain, bad coffee, worse decisions; the numbers are the evidence."""
FAMILY = {
    "id": "noir",
    "label": "Noir",
    "desc": "Hardboiled first person. Similes about rain, whiskey and alleys; the box score is a crime scene and the standings are a rap sheet. Short hits, then a long slow sentence.",
    "rhythm": "mixed: clipped fragments followed by a long simile",
    "formality": "informal, stylized",
    "metaphors": "detective work, crime, rain, bars, back alleys",
    "numbers": "exact, laid out like evidence",
    "lex": {
        "verb": {
            "blowout": ["flattened", "buried", "dismantled"],
            "comfortable": ["handled", "outran", "shook off"],
            "normal": ["beat", "got the better of", "bested"],
            "close": ["edged", "slipped past", "outlasted"],
        },
        "noun": {
            "blowout": ["a massacre", "a clean kill", "a hit job"],
            "comfortable": ["a clean job", "a quiet win", "a tidy job"],
            "normal": ["a plain win", "an honest win", "a routine job"],
            "close": ["a close shave", "a knife-edge job", "a photo finish"],
        },
        "tier": {
            "hi": ["a good bet, the kind you brag about in bars", "money well spent", "a payoff"],
            "mid": ["an even-money bet", "a fair return", "about what the street said"],
            "lo": ["a loser's bet so far", "money down a sewer", "a bad bet so far"],
        },
    },
    "T": {
        "h.r.blow": [
            "{w} {verb} {l}: {m} points of bad news",
            "A {m}-point body in {wl}: {w} over {l}",
            "{w_team} leaves {l_team} in the alley, {wp}-{lp}",
        ],
        "h.r.upset": [
            "The table lied: {w} ({w_rank0}) put {l} ({l_rank0}) down",
            "{w_rank0} took {l_rank0} in a back room: {wp}-{lp}",
            "{w} {verb} {l}, and the standings never saw it coming",
        ],
        "h.r.close": [
            "{w} {verb} {l} by {m}, and somebody's hands were shaking",
            "{m} points of daylight: {w} over {l}",
            "A photo finish in {wl}: {w}, {wp}; {l}, {lp}",
        ],
        "h.r.top": [
            "{wp} points, one name: {w}",
            "The big score of {wl}: {w}, {wp}, and nobody else close",
            "{w} comes in hot with {wp} and {l} pays for it",
        ],
        "h.r.tie": [
            "Nobody walked away: {a} and {b} tie at {pts}",
            "A dead heat, {pts} each: {a} and {b}",
            "{a} and {b} tied. The kind of ending nobody likes",
        ],
        "r.lede.blow": [
            "{w} {verb} {l}, {wp} to {lp}. {m} points. It was the kind of margin that makes a man check the door.",
            "It was {noun}. {w_team} ({w}) put {l_team} ({l}) away by {m} in {wl}, {wp}-{lp}, and nobody else came close to that number all week.",
            "The week had one body, and it was {l}'s. {w} won by {m}, {wp} to {lp}, the widest margin on the board.",
        ],
        "r.lede.upset": [
            "On the books, {l} was {l_rank0} and {w} was {w_rank0}. On the field, {w} won, {wp} to {lp}. The books were wrong, and nobody likes being told that.",
            "The standings said {l}, {l_rank0}. {w}, {w_rank0}, didn't read the standings. {wp}-{lp}, {wl}, and the biggest upset on the board.",
            "I'd have put money on {l}, who stood {l_rank0} to {w}'s {w_rank0}. It's a good thing I keep my money in a drawer. {w} won, {wp}-{lp}.",
        ],
        "r.lede.close": [
            "{m} points. That's all that separated {w} and {l}, {wp} to {lp}, in {wl}. It was the closest one of the week, and I felt every point.",
            "It was {noun}. {w} {verb} {l}, {wp}-{lp}, by {m}, the narrowest margin on the board.",
            "You could have slid a playing card between them. {w_team} ({w}) won by {m} over {l}, {wp} to {lp}, and the week's closest game was in the books.",
        ],
        "r.lede.top": [
            "{wp} points. That's the number I couldn't stop looking at. {w} put it up in {wl}, best on the board by a mile, and {l} had {lp} to answer. The league average was {wavg}.",
            "Somebody turned up the lights in {wl}. {w_team} ({w}) scored {wp}, the top number of the week, against a {wavg} average. {l} scored {lp} and went home.",
            "The week's big money was {w}'s {wp}. {l} came up with {lp}. The average was {wavg}. The math was never in question.",
        ],
        "r.lede.tie": [
            "Nobody won. {a_team} ({a}) and {b_team} ({b}) both scored {pts} in {wl}, and that kind of ending leaves a sour taste.",
            "A tie: {a} and {b}, {pts} apiece, {wl}. I've seen better endings in worse bars.",
            "{pts} to {pts}. {a} and {b} walked away even, and nobody liked it.",
        ],
        "g.result": [
            "{w_team} ({w}) {verb} {l_team} ({l}). The tape said {wp}-{lp}.",
            "{w} {verb} {l}, {wp} to {lp}. Call it {noun}.",
            "By the end of {wl}, {w_nick} had {verb} {l}: {wp}-{lp}.",
            "{l_nick} lost to {w}, {lp}-{wp}. {noun}.",
            "The scoreboard read {wp}-{lp}. {w} over {l} by {m}. {noun}.",
            "{w} and {l} met under the lights. {w} walked out, {wp} to {lp}.",
            "{l} came up short against {w}, {lp} to {wp}.",
            "I watched {w} {verb} {l}, {wp}-{lp}, and wrote it down.",
            "{wp} for {w}. {lp} for {l}. {m} points between them, and a story.",
            "The box score had {w} over {l}, {wp}-{lp}. Cold fact.",
        ],
        "g.tie": [
            "{a} and {b}: {pts} each. No winner, no loser, no peace.",
            "{a_team} ({a}) and {b_team} ({b}) tied at {pts}. I stared at it a long time.",
            "{pts}-{pts}. {a} and {b}. Nobody got the last word.",
        ],
        "g.star": [
            "{star} ({spos}) was the one with the gun: {spts} for {w}, {sshare} of the {wp}.",
            "{w}'s best man was {star} ({spos}), who dropped {spts} like it was nothing.",
            "{star} ({spos}) went for {spts}, {sshare} of {w}'s total. Clean work.",
        ],
        "g.goat": [
            "{l} had a hole in the lineup: {gname} ({gpos}), {gpts}.",
            "The weak link on {l}'s side was {gname} ({gpos}), who gave them {gpts}.",
            "{gname} ({gpos}) started for {l} and brought back {gpts}. That's the kind of thing that gets noticed.",
        ],
        "g.bench": [
            "{bench_left} stayed on {l}'s bench, and {bench_name} ({bench_pos}) scored {bench_pts} watching from the pine.",
            "The evidence was on {l}'s bench: {bench_name} ({bench_pos}), {bench_pts}. A better lineup was worth {bench_left}.",
            "{bench_left} sat on {l}'s bench, {bench_pts} of them from {bench_name} ({bench_pos}). Somebody made a bad call.",
        ],
        "g.streak_w": [
            "{w} has won {k} straight. {w_rec}, {w_rank}. That kind of run makes people nervous.",
            "{k} in a row for {w}, now {w_rec} and {w_rank} in the table. A hot streak, like a bad cough.",
            "{w} is {w_rec}, {w_rank}, and has not lost in {k}.",
        ],
        "g.streak_l": [
            "{l} has dropped {k} straight. {l_rec}, {l_rank}. That kind of run leaves a mark.",
            "{k} losses in a row for {l}, now {l_rec} and {l_rank} in the table. A cold streak, like a bad winter.",
            "{l} is {l_rec}, {l_rank}, and hasn't won in {k}.",
        ],
        "g.record": [
            "{w} moves to {w_rec} ({w_rank}). {l} slides to {l_rec} ({l_rank}).",
            "After {wl}: {w}, {w_rec}, {w_rank}. {l}, {l_rec}, {l_rank}. The standings keep their own books.",
            "The result puts {w} at {w_rec} and {l} at {l_rec}.",
        ],
        "g.top": [
            "{w}'s {wp} was the best score of {wl}. League average: {wavg}. Nobody else was close.",
            "Nobody put up more than {w} in {wl}: {wp}. The room averaged {wavg}.",
            "{wp} for {w}, top of the board. The average sat at {wavg}.",
        ],
        "g.low": [
            "{l}'s {lp} was the worst number on the board in {wl}. League average: {wavg}.",
            "Nobody dragged less than {l} in {wl}: {lp}. The room averaged {wavg}.",
            "{lp} for {l}, the bottom of the board. The average sat at {wavg}.",
        ],
        "g.luck_up": [
            "{n} is {n_rec} and {luck} wins ahead of what the all-play numbers say. Somebody up there likes them.",
            "By all-play, {n} owes the universe {luck} wins at {n_rec}. The universe hasn't called yet.",
            "{n}: {n_rec}, and {luck} wins above the line. Luck like that always comes with a bill.",
        ],
        "g.luck_down": [
            "{n} is {n_rec} and {luck} wins behind what the all-play numbers say. The schedule has a grudge.",
            "By all-play, the universe owes {n} {luck} wins at {n_rec}. It's slow to pay.",
            "{n}: {n_rec}, and {luck} wins under the line. Bad luck never knocks first.",
        ],
        "g.upset": [
            "Going in, {l} stood {l_rank0} and {w} stood {w_rank0}. The streets had other ideas.",
            "{w_rank0} against {l_rank0}, and the {w_rank0} walked out. That's how it was.",
            "The table had {l} at {l_rank0} and {w} at {w_rank0} before {wl}. The table was wrong.",
        ],
        "g.shotgun": [
            "{n} owes {sgn}. The reason: {why}. The ledger doesn't forget.",
            "The ledger had {n} down for {sgn}: {why}.",
            "{n} walked away from {wl} owing {sgn} for {why}.",
        ],
        "g.aside": [
            "{n}, who {trait}, took {event}. It sounds about right.",
            "I thought about {n}, who {trait}, and what {wl} had dealt: {event}.",
            "{n}, who {trait}, left {wl} holding {event}.",
        ],
        "r.close_shift": [
            "The table shifted after {wl}: {in_names} slipped into the top six, and {out_names} fell out of it. {leader} still sat on top at {leader_rec}.",
            "In the standings, {in_names} were now inside the top six, and {out_names} were outside. {leader}, {leader_rec}, ran the room.",
            "After {wl}, {in_names} were in the top six and {out_names} were out in the cold. {leader} led at {leader_rec}.",
        ],
        "r.close_table": [
            "After {wl}, {leader} led the table at {leader_rec}, and {cut} was holding the last of the six playoff seats at {cut_rec}.",
            "The table after {wl}: {leader}, {leader_rec}, on top; {cut}, {cut_rec}, hanging by a thread at sixth.",
            "{leader} ran the table at {leader_rec}. {cut}, {cut_rec}, held sixth, and not tightly.",
        ],
        "r.close_po": [
            "That was {wl}: {ngames}. {big_w} put {big_l} away by {big_m}, and {top_w} had the top number, {top_pts}.",
            "{wl} was over. {ngames}. The widest margin was {big_m}, {big_w} over {big_l}. The best score was {top_w}'s {top_pts}.",
            "{ngames}, and the file closed: {big_w} by {big_m} over {big_l}, and {top_w} with {top_pts}.",
        ],
        "h.p.fav": [
            "The smart money is on {fav} over {dog} in {wl}",
            "{wl}: {fav}, {fav_odds}, against {dog}, {dog_odds}",
            "{dog} is the long shot against {fav} in {wl}",
        ],
        "h.p.even": [
            "{a} and {b}, {wl}: a game with no clear winner",
            "Even money in {wl}: {a} against {b}",
            "{a} and {b} meet in {wl}, and the odds won't pick a side",
        ],
        "h.p.lev": [
            "{wl}'s big game: {a} and {b}, with {swing} points of odds on the table",
            "{a} and {b}: the game in {wl} that decides things",
            "High stakes in {wl}: {a} against {b}",
        ],
        "p.lede": [
            "The game to watch in {wl} is {a_team} ({a}) against {b_team} ({b}). I'd say watch it with the lights low.",
            "{a} and {b} meet in {wl}. It's the one I keep coming back to.",
            "There's one game in {wl} that smells like trouble: {a} against {b}.",
            "{a} and {b} are playing for {swing} points of playoff odds in {wl}. That's the biggest pot on the table.",
        ],
        "p.matchup": [
            "{a_team} ({a}) comes in {a_rec}, scoring {a_avg}; {b_team} ({b}) comes in {b_rec}, scoring {b_avg}.",
            "{a}: {a_rec}, {a_avg} a game. {b}: {b_rec}, {b_avg} a game. That's the file on both of them.",
            "{b} walks in at {b_rec} and {b_avg} a game, and {a} walks in at {a_rec} and {a_avg}.",
            "In {wl}, {a} ({a_rec}, {a_avg}) meets {b} ({b_rec}, {b_avg}). Both of them know it.",
        ],
        "p.h2h_split": [
            "They've met this season, and it was a split, {h2h_rec}. Nobody got the last word.",
            "{a} and {b} are even this season, {h2h_rec}.",
            "The score between {a} and {b} this year is {h2h_rec}. Level.",
        ],
        "p.h2h_lead": [
            "{lead} has had the better of {trail} this season, {h2h_rec}, and neither has stopped thinking about it.",
            "{trail} is down {h2h_rec} against {lead} this season and hasn't forgotten.",
            "The season series was {lead}'s by {h2h_rec}.",
        ],
        "p.h2h_none": [
            "They haven't met this season. There's no history, only suspicion.",
            "{a} and {b} have yet to play. The first meeting is always the worst.",
            "{a} and {b} had never shared a room this season.",
        ],
        "p.stakes": [
            "A win moves {a} to {a_win} playoff odds; a loss, {a_loss}. For {b}, {b_win} or {b_loss}. That's the pot.",
            "The odds read: {a}, {a_win} with a win, {a_loss} with a loss. {b}, {b_win} and {b_loss}.",
            "{a} sits between {a_loss} and {a_win}. {b} sits between {b_loss} and {b_win}. The game decides who goes where.",
        ],
        "p.leverage": [
            "{swing} points of playoff swing. The biggest pot on the table this week.",
            "No game moves the odds like this one. {swing} points.",
            "{a} and {b} are playing for {swing} points of playoff odds. Nothing else this week comes close.",
        ],
        "p.favorite": [
            "{fav} is the favorite on {fav_why}: {fav_odds} to {dog}'s {dog_odds}.",
            "The street says {fav} ({fav_odds}) over {dog} ({dog_odds}), going by {fav_why}.",
            "{dog} is the long shot at {dog_odds}. {fav} is at {fav_odds}.",
        ],
        "p.vol": [
            "{vol_n} is the one that keeps me up at night: {vol_std} points of weekly swing against {other}'s {other_std}.",
            "Nerves: {vol_n} swings {vol_std} points a week, {other} only {other_std}.",
            "{other} is steady, {other_std} points of swing. {vol_n}, {vol_std}, is anybody's guess.",
        ],
        "p.rivnote": [
            "And there's the history: {rv_name}. {backstory}",
            "It's {rv_name}, and that name has a story behind it. {backstory}",
            "The pairing has a name, {rv_name}. {backstory}",
        ],
        "p.close": [
            "{wl} is coming. {a} and {b} will be there.",
            "I'll be watching {a} and {b} in {wl}, from the back of the room.",
            "The lights go up on {a} and {b} in {wl}.",
        ],
        "h.t": [
            "{a} slides {gave_s} to {b} for {got_s}",
            "A back-room deal: {gave_s} from {a} to {b}, {got_s} back",
            "{b} walks off with {gave_s}; {a} takes {got_s}",
            "{a} and {b} make a trade: {gave_s} for {got_s}",
        ],
        "t.sides": [
            "In {wl}, {a} and {b} shook hands on a deal. {a} took {a_got}. {b} took {b_got}.",
            "The details were simple. {a} got {a_got}. {b} got {b_got}. It happened in {wl}.",
            "{a} gave up {b_got} and walked away with {a_got} in {wl}.",
            "{b} sent {a_got} to {a} and took {b_got} in return, in {wl}.",
        ],
        "t.returns": [
            "Since the handshake, {a}'s new players have scored {a_pts} and {b}'s have scored {b_pts}, over {since_wk}. {lead} has the early edge, but the night is young.",
            "The books after {since_wk}: {lead}'s side has {lead_pts}, {trail}'s side {trail_pts}.",
            "{a}'s end of the deal is worth {a_pts}. {b}'s end is worth {b_pts}. {lead} is up.",
        ],
        "t.pending": [
            "{pk_side} took {pk_got}. {pl_side} took {pl_got}. Picks for players. Nobody can say who won until the picks play.",
            "It's picks for players: {pl_side} got {pl_got}, {pk_side} got {pk_got}. The verdict's on ice.",
            "{pl_side} walked off with the players ({pl_got}), {pk_side} with the picks ({pk_got}). It can't be graded yet.",
        ],
        "t.fresh": [
            "Too early to tell who got the better end.",
            "The ink's still wet. No grade yet.",
            "Nobody's played a down since. There's nothing to grade.",
        ],
        "t.count": [
            "It's {n}'s {nth} trade of the season. That's a lot of handshakes.",
            "That makes the {nth} trade of the year for {n}, and the year has some way to go.",
            "The {nth} trade for {n}, and the season still young.",
        ],
        "t.rec": [
            "Before the handshake, {a} stood {a_rec} ({a_rank}) and {b} stood {b_rec} ({b_rank}).",
            "By the books that week, {a} was {a_rank} at {a_rec}, {b} was {b_rank} at {b_rec}.",
            "Entering that week: {a}, {a_rec}, {a_rank}. {b}, {b_rec}, {b_rank}.",
        ],
        "t.close": [
            "The league log has it: the deal is done.",
            "It cleared. No takebacks.",
            "The transaction is closed.",
        ],
        "h.w.big": [
            "{n} puts {bid} on {player} and doesn't blink",
            "{n} pushed {bid} across the table for {player} ({pos}) and didn't look back",
            "{n} drops {bid} to land {player}",
        ],
        "h.w.small": [
            "{n} grabs {player} for {bid}",
            "{player} ({pos}) landed in {n}'s corner for {bid}",
            "{n} quietly picks up {player}, {bid}",
        ],
        "h.w.free": [
            "{n} picks {player} off the wire for nothing",
            "{player} ({pos}) comes home with {n}",
            "{n} adds {player} without spending a dime",
        ],
        "w.top_bid": [
            "{n} dropped {bid} on {player} ({pos}) in {wl}, the biggest bid of the week. I'd call that a statement.",
            "The big bid of {wl} was {bid}, from {n}, for {player} ({pos}).",
            "{n} laid {bid} on {player} ({pos}), the largest claim of {wl}.",
        ],
        "w.top_free": [
            "{n} picked up {player} ({pos}) in {wl}. It cost nothing.",
            "{player} ({pos}) landed with {n} in {wl}, quiet as a stray cat.",
            "The pickup worth a second look in {wl}: {player} ({pos}), by {n}.",
        ],
        "w.since": [
            "Since then, {player} has put up {spts} over {since_wk}. Call it {tier}.",
            "Over {since_wk}, {n} has gotten {spts} out of {player}. That's {tier}.",
            "{player} had {spts} in the {since_wk} since. Call it {tier}.",
        ],
        "w.others": [
            "Others on the wire: {others_text}.",
            "The rest of the action: {others_text}.",
            "The rest of the night's business: {others_text}.",
        ],
        "w.total": [
            "In all, {total_owners} picked up {total_n} in {wl}.",
            "{total_n} changed hands in the dark between {total_owners} in {wl}.",
            "The wire shuffled {total_n} between {total_owners} in {wl}, quietly, the way it does.",
        ],
        "w.budget": [
            "{n} has burned {spent} of a {budget} FAAB budget.",
            "The bankroll: {n} was out {spent} of {budget} by now.",
            "So far, {n} has spent {spent} out of {budget}.",
        ],
        "w.close": [
            "{player} is on {n}'s roster now. The log says so.",
            "{n} has {player}. That's the story.",
            "{player} belongs to {n} now. Don't ask how.",
        ],
        "h.s": [
            "The Beer Report, Week {wk}: {total_n} on the tab",
            "{top} left Week {wk} owing {topn}",
            "Week {wk} left {total_n} on the ledger",
            "{top} leads the Week {wk} bar tab with {topn}",
        ],
        "s.total": [
            "The Week {wk} ledger had {total_n} on it, spread over {owners_n}.",
            "{owners_n} walked out of Week {wk} owing a combined {total_n}.",
            "Week {wk}'s tab came to {total_n} across {owners_n}.",
        ],
        "s.owner": [
            "{n} owed {sgn}: {list}.",
            "{sgn} on {n}'s tab. The reason: {list}.",
            "{n}: {sgn}, thanks to {list}.",
            "{n} ran up a tab of {sgn}: {list}.",
        ],
        "s.low": [
            "The worst number on the ledger was {player}'s ({pos}) {pts} in {n}'s lineup.",
            "{n} started {player} ({pos}). {pts}. That was the low point of the week.",
            "At {pts}, {player} ({pos}) hit the floor for {n}, and kept going.",
        ],
        "s.leader": [
            "{leader} led the season tab at {ltotal} through Week {wk}.",
            "Through Week {wk}, nobody owed more than {leader}: {ltotal}.",
            "The season's biggest tab belonged to {leader}, {ltotal}.",
        ],
        "s.close": [
            "{top} headed the Week {wk} list. The bar was open.",
            "The Week {wk} ledger began with {top}.",
            "{top} was first on the tab in Week {wk}.",
        ],
        "h.n": [
            "The table through {wl}: {top} on top, {six} on a ledge",
            "{alive} teams still in the hunt for {spots} spots through {wl}",
            "{top} runs the room, {bottom} is in the cellar: through {wl}",
            "Through {wl}, {six} holds the last playoff seat",
        ],
        "h.nf": [
            "Final table: {top} on top, {seven} on the street",
            "{six} gets the last seat, {seven} doesn't: the final standings",
            "{top} first, {bottom} last: the regular season's closed",
            "The cut fell between {six} and {seven}",
        ],
        "n.top": [
            "Through {wl}, {top} sat on top of the table at {top_rec}.",
            "{top} led at {top_rec} through {wl}. Nobody was taking it away.",
            "At the head of the table through {wl}: {top}, {top_rec}.",
            "{top} led at {top_rec}, with {top_odds} playoff odds through {wl}.",
            "Through {wl}, {top} led at {top_rec}, with {top_odds} playoff odds and {bye} for a bye.",
        ],
        "n.cut": [
            "{six} ({six_rec}) held the last playoff seat, and {seven} ({seven_rec}) was one step behind and watching.",
            "The line was drawn between {six} ({six_rec}) and {seven} ({seven_rec}), in chalk.",
            "{seven} ({seven_rec}) was first out, and {six} ({six_rec}) was last in, and neither felt safe.",
        ],
        "n.luck": [
            "The luck ledger: {lucky} at {lucky_luck} wins above the all-play line, {unlucky} at {unlucky_luck}. Fortune plays favorites.",
            "By all-play, {lucky} had {lucky_luck} wins it hadn't earned. {unlucky} had {unlucky_luck}.",
            "{lucky} ({lucky_luck}) had the luck. {unlucky} ({unlucky_luck}) had the bill.",
        ],
        "n.clinch": [
            "Clinched: {names}. Some people sleep well.",
            "In for good: {names}.",
            "{names} had their seats locked up.",
        ],
        "n.elim": [
            "Out for good: {names}.",
            "Mathematically dead: {names}.",
            "{names} wouldn't be getting in.",
        ],
        "n.bottom": [
            "Down at the bottom of the heap: {bottom}, {bottom_rec}.",
            "{bottom} sat in the cellar at {bottom_rec}.",
            "Last place belonged to {bottom}, {bottom_rec}.",
        ],
        "n.eff": [
            "On lineups: {best_n} squeezed {best_pct} out of the points available. {worst_n} managed {worst_pct}.",
            "{best_n} set the sharpest lineups ({best_pct}). {worst_n} set the dullest ({worst_pct}).",
            "Efficiency: {best_n}, {best_pct}. {worst_n}, {worst_pct}.",
        ],
        "n.records": [
            "For the record: the top score was {hi_pts}, {hi_n}, Week {hi_wk}. The widest margin was {blow_m}, {blow_w} over {blow_l}, Week {blow_wk}.",
            "{hi_n}'s {hi_pts} in Week {hi_wk} still stood as the high mark. {blow_w}'s {blow_m}-point job on {blow_l} in Week {blow_wk} was the widest margin.",
            "The marks on the wall: {hi_pts} ({hi_n}, Week {hi_wk}) and {blow_m} points ({blow_w} over {blow_l}, Week {blow_wk}).",
        ],
        "n.ftop": [
            "{top} finished first at {top_rec}, with {top_pf} on the board.",
            "The top seed went to {top}: {top_rec}, {top_pf}.",
            "{top} ended the regular season on top of the heap, {top_rec}, {top_pf}.",
        ],
        "n.fcut": [
            "{six} took the last seat at {six_rec}. {seven} finished at {seven_rec} and was left standing.",
            "The line was drawn between {six} ({six_rec}) and {seven} ({seven_rec}), in chalk.",
            "{six} ({six_rec}) got in. {seven} ({seven_rec}) got the door.",
        ],
        "n.fpts": [
            "{pf_n} scored the most all season ({pf_pts}). {low_n} scored the fewest ({low_pts}).",
            "The scoring books: {pf_n}, {pf_pts}, at the top, and {low_n}, {low_pts}, at the bottom.",
            "{pf_pts} for {pf_n} was the high. {low_pts} for {low_n} was the low.",
        ],
        "n.fbottom": [
            "{bottom} finished where the lights don't reach: {bottom_rec}.",
            "Down at the bottom of the heap: {bottom}, {bottom_rec}.",
            "{bottom} drew last place, {bottom_rec}, and the short straw.",
        ],
        "n.close": [
            "That's the table through {wl}, with {top} up top.",
            "Through {wl}, {top} led. The rest were chasing.",
            "{top} sat first through {wl}.",
        ],
        "h.f": [
            "{a} and {b}: the file on a bad feeling",
            "Bad blood between {a} and {b}",
            "What {a} and {b} know about each other",
            "{a} and {b}: the evidence",
        ],
        "f.h2h": [
            "It starts in Week {gwk}, when {w} {verb} {l}, {wp} to {lp}, by {m}. That kind of thing doesn't wash off.",
            "In Week {gwk}, {w} beat {l}, {wp}-{lp}, by {m}. {l} remembers it.",
            "{l} lost to {w} in Week {gwk}, {lp} to {wp}. {noun}, and people hold a grudge about that.",
        ],
        "f.trade": [
            "In Week {twk}, they did business: {a} took {a_got}, and {b} took {b_got}. Somebody walked away thinking they'd been had.",
            "The two shook hands in Week {twk}. {a} got {a_got}. {b} got {b_got}.",
            "Week {twk}: {b_got} went to {b}, {a_got} went to {a}. The log doesn't say who regrets it.",
        ],
        "f.adj": [
            "In the standings, {hi} ({hi_rec}, {hi_rank}) sat just ahead of {lo} ({lo_rec}, {lo_rank}), {pf_gap} apart in points scored. Close enough to feel the breath.",
            "{hi} was {hi_rank}. {lo} was {lo_rank}. {pf_gap} apart in points. Neighbors don't always get along.",
            "{lo} trailed {hi} by {pf_gap} in points scored, {lo_rank} to {hi_rank}.",
        ],
        "f.blow": [
            "There's Week {gwk} to think about: {w} {verb} {l}, {wp} to {lp}, by {m}.",
            "In Week {gwk}, {w} put {m} points on {l}, {wp}-{lp}. That kind of number lingers.",
            "{w}'s {m}-point win over {l} in Week {gwk} ({wp}-{lp}) is the kind of margin people carry around.",
        ],
        "f.sg": [
            "The tab at the bar read {a_sg} for {a} and {b_sg} for {b}.",
            "The beer tab: {a}, {a_sg}. {b}, {b_sg}.",
            "{a} was down for {a_sg}, {b} for {b_sg}, on the season ledger.",
        ],
        "f.story": [
            "The league has a name for it: {rv_name}. {backstory}",
            "They call it {rv_name}. {backstory}",
            "This one's {rv_name}. {backstory}",
        ],
        "f.trait": [
            "{a} {a_trait}. {b} {b_trait}. Put them in the same room and see.",
            "Look at the files: {a} {a_trait}, and {b} {b_trait}.",
            "{a} {a_trait}. {b} {b_trait}. I drew my own conclusions and kept them in a drawer.",
        ],
        "f.mid": [
            "Through Week {wk}, {a} was {a_rec} ({a_rank}) and {b} was {b_rec} ({b_rank}).",
            "The table through Week {wk} had {a} {a_rank} at {a_rec} and {b} {b_rank} at {b_rec}.",
            "The file through Week {wk}: {a}, {a_rec}, {a_rank}; {b}, {b_rec}, {b_rank}.",
        ],
        "f.close": [
            "That's the file. The case isn't closed.",
            "Neither of them has said it's over.",
            "I've seen quarrels like this last longer than the season.",
        ],
        "h.v": [
            "{rv_name}: {a} and {b} meet in Week {wk}",
            "Old grudges die hard: {a} and {b} in Week {wk}",
            "{a} and {b} and the night of {rv_name}, Week {wk}",
            "Week {wk}: {rv_name} returns",
        ],
        "v.lede": [
            "Some games have a history. {rv_name} returns in {wl}: {a} against {b}. {backstory}",
            "{a} and {b} meet again in {wl}, in the game they call {rv_name}. {backstory}",
            "{rv_name} is on the schedule in {wl}. {a}, {b}. {backstory}",
        ],
        "v.form": [
            "{a} comes in {a_rec}, {a_rank}, scoring {a_avg}. {b} comes in {b_rec}, {b_rank}, scoring {b_avg}.",
            "The numbers on the pair: {a}, {a_rec}, {a_rank}, {a_avg} a game; {b}, {b_rec}, {b_rank}, {b_avg} a game.",
            "{b} stands {b_rank} at {b_rec}, {b_avg} a game. {a} stands {a_rank} at {a_rec}, {a_avg}.",
        ],
        "v.close": [
            "I'll see {a} and {b} in Week {wk}.",
            "Week {wk} is the next chapter for {a} and {b}.",
            "Same room, Week {wk}: {a} and {b}.",
        ],
        "h.o": [
            "The offseason file: {ntrades}, {npick}",
            "{ntrades} and {npick}: what went down before the season",
            "Before kickoff, {ntrades} and {npick}",
        ],
        "o.lede": [
            "Before the season began, the league's log had {ntrades} and {npick}. It was a busy winter, and nobody was asking questions.",
            "The offseason left {ntrades} and {npick} in the log.",
            "The log read {ntrades}, {npick}. All before kickoff.",
        ],
        "o.busy": [
            "The busiest hands in the winter's trading: {busy_text}.",
            "Counting the handshakes: {busy_text}.",
            "The ones who couldn't leave well enough alone: {busy_text}.",
        ],
        "o.big": [
            "The biggest deal of the winter: {side_a} got {a_got}, and {side_b} got {b_got}.",
            "The big deal moved {b_got} to {side_b} and {a_got} to {side_a}, under a streetlamp.",
            "{side_a} took {a_got}. {side_b} took {b_got}. It was the biggest deal of the offseason.",
        ],
        "o.close": [
            "{busiest} made the most trades, and slept fine.",
            "{busiest} worked the winter harder than anyone.",
            "{busiest} did more business than anyone in town.",
        ],
        # ---------------- Sunday column ----------------
        "h.c": [
            "{a} and {b}: words in a back alley",
            "What {a} said about {b}, and what the table said back",
            "{a}, {b}, and a Sunday that smelled like trouble",
            "Two owners, one grudge: {a} and {b}",
        ],
        "h.c.rv": [
            "{rv_name}: {a} and {b} do their talking in the dark",
            "The night {a} and {b} brought {rv_name} up again",
            "Old grudge, new whiskey: {a}, {b}, {rv_name}",
        ],
        "h.c.next": [
            "{a} and {b} meet in Week {nwk}, and the talk is already cheap",
            "Week {nwk}: {a}, {b}, and a lot of smoke before the fire",
            "Before {a} faces {b} in Week {nwk}, a few words in the rain",
        ],
        "c.lede": [
            "It was Sunday and the rain wouldn't quit. Through {wl}, {a} was {a_rec}, {a_rank} in the table. {b} was {b_rec}, {b_rank}.",
            "The table through {wl} tells it plain. {a}, {a_rank}, {a_rec}. {b}, {b_rank}, {b_rec}. Everything else is talk.",
            "I got the standings the way I get everything: late and wet. {a} was {a_rank} at {a_rec}. {b} was {b_rank} at {b_rec}. That was {wl}.",
        ],
        "c.next": [
            "They meet in Week {nwk}. I'd put money on bad manners.",
            "The schedule says {a} and {b} play in Week {nwk}. The schedule doesn't know what it's doing.",
            "Week {nwk}. Same room, same two names, and one of them leaves unhappy.",
        ],
        "c.recent": [
            "Lately, {a} {a_form}. {b} {b_form}. Form like that follows a person into a room.",
            "The last few games tell a story. {a} {a_form}, and {b} {b_form}.",
            "{a} {a_form}. {b} {b_form}. I've read worse evidence in front of better juries.",
        ],
        "c.gap": [
            "{hi} was {hi_rank} at {hi_rec}, and {lo} was {lo_rank} at {lo_rec}. {pf_gap} of scoring stood between them like a closed door.",
            "In the table, {hi} sat {hi_rank} and {lo} sat {lo_rank}. In points scored, {pf_gap} separated them, which is how far a grudge can travel.",
            "{hi}, {hi_rank}, {hi_rec}. {lo}, {lo_rank}, {lo_rec}. {pf_gap} apart in points, and neither would admit it mattered.",
        ],
        "c.pick": [
            "If I had to put a dollar down, and I always do, it goes on {fav} over {dog}, on {fav_why}.",
            "The street says {fav}. The {fav_why} agrees. {dog} can take that up with the street.",
            "I like {fav} over {dog}. {fav_why}, and a hunch I won't explain.",
        ],
        "c.close": [
            "That's the file on {a} and {b}. I've seen worse. Not often.",
            "{a} and {b} will go on talking. Talk's cheap in this town.",
            "The rain kept falling, and {a} and {b} kept at it. I lit another one and watched.",
        ],
        # ---------------- Monday analytics ----------------
        "h.a.luck": [
            "The luck ledger: {lucky} had it, {unlucky} paid for it",
            "{lucky} at {lucky_luck}. {unlucky} at {unlucky_luck}. Luck doesn't care who it lands on",
            "Who got the breaks: {lucky}. Who got the bill: {unlucky}",
        ],
        "h.a.eff": [
            "{best_n} read the board right at {best_pct}; {worst_n} didn't, at {worst_pct}",
            "Lineup efficiency: {best_n}, {best_pct}. {worst_n}, {worst_pct}. The numbers don't blink",
            "{worst_n} left money on the table, {worst_pct} of what was there",
        ],
        "h.a.bench": [
            "{bench_n} left {bench_pts} sitting in the dark",
            "The bench on {bench_n}: {bench_pts} that never saw the light",
            "{bench_pts} on the bench, and {bench_n} had the keys",
        ],
        "h.a.steady": [
            "{steady_n} never changes. {wild_n} never stays the same",
            "A steady man and a restless one: {steady_n} and {wild_n}",
            "{wild_n} runs hot and cold; {steady_n} just runs",
        ],
        "a.lede": [
            "Monday. Coffee, a ledger, and {gp} per team through {wl}. The numbers don't care how you feel.",
            "I spent Monday with the books. Through {wl}, {gp} played by each team, and the books were honest, which is more than I can say for most of you.",
            "The figures run through {wl}, {gp} per team. I read them under a bad lamp, and they still made sense.",
        ],
        "a.luck": [
            "Luck is a dame who picks favorites. {lucky} was {lucky_rec} where the all-play math said {lucky_exp} wins, a luck index of {lucky_luck}. {unlucky} was {unlucky_rec} where it said {unlucky_exp}, which came to {unlucky_luck}.",
            "{lucky} had the luck: {lucky_rec} on {lucky_exp} expected wins, {lucky_luck}. {unlucky} had the bill: {unlucky_rec} on {unlucky_exp}, {unlucky_luck}.",
            "Fortune walked in and sat down next to {lucky}, {lucky_luck} wins above the all-play line ({lucky_rec}, expected {lucky_exp}). It walked right past {unlucky}, at {unlucky_luck} ({unlucky_rec}, expected {unlucky_exp}).",
        ],
        "a.eff": [
            "Points scored against the best lineup a roster could set. {best_n} took {best_pct} of what was there. {worst_n} took {worst_pct}. The league took {lg_pct}, and I've seen emptier tables.",
            "{best_n} set the sharpest lineups at {best_pct}. {worst_n} set the dullest at {worst_pct}. The league ran at {lg_pct} on average.",
            "Efficiency. {best_n}, {best_pct}. {worst_n}, {worst_pct}. League, {lg_pct}. Somebody out there knows how to set a lineup, and somebody doesn't.",
        ],
        "a.bench": [
            "The bench is where good points go to die. {bench_n} left {bench_pts} there against the best possible lineup. {bench_low_n} left {bench_low_pts}.",
            "{bench_n} left {bench_pts} on the bench, the most in the league. {bench_low_n} left only {bench_low_pts}. Clean hands, mostly.",
            "Against the best lineup each roster could have set: {bench_n}, {bench_pts} short. {bench_low_n}, {bench_low_pts}.",
        ],
        "a.blunder": [
            "The worst night of the season so far belongs to {bl_n}. Week {bl_wk}. {bl_pts} below the best lineup available, and {bl_player} ({bl_pos}) sat there with {bl_player_pts}.",
            "In Week {bl_wk}, {bl_n} finished {bl_pts} short of the best lineup. {bl_player} ({bl_pos}) scored {bl_player_pts} from the bench. That's the kind of detail that keeps a man up.",
            "{bl_n}, Week {bl_wk}, {bl_pts} short. The best of the bench was {bl_player} ({bl_pos}), {bl_player_pts}. I've seen men hanged on less.",
        ],
        "a.steady": [
            "Then there's the quiet ones. {steady_n} averaged a weekly rank of {steady_avg}, from {steady_band}. {wild_n} ranged from {wild_band}, and you never knew which one would show up.",
            "{steady_n}, from {steady_band}, averaging {steady_avg}: steady as a stopped clock. {wild_n}, from {wild_band}: nobody's idea of steady.",
            "By weekly rank, {steady_n} stayed in a narrow lane, from {steady_band}, average {steady_avg}. {wild_n} ran from {wild_band}.",
        ],
        "a.trade": [
            "And the trade from Week {twk}? Over {since_wk}, the players {lead} took in scored {lead_pts}. The players {trail} took in scored {trail_pts}. Somebody got the better end of the handshake.",
            "The Week {twk} deal between {lead} and {trail} reads clear enough: {lead_pts} to {trail_pts}, in {lead}'s favor, after {since_wk}.",
            "Early returns on the Week {twk} trade: {lead}, {lead_pts}. {trail}, {trail_pts}. {since_wk} in, and the ledger leans one way.",
        ],
        "a.close": [
            "The numbers stand through {wl}. The rest is rain.",
            "That's the ledger. Close the book and pour one.",
            "Numbers don't lie. They just wait.",
        ],
        "x.sig": [
            "Then {n} said the thing {n} always says: “{catch}”",
            "{n} had a line for every occasion, and this was the usual: “{catch}”",
            "And {n}, because {n} can't help it: “{catch}”",
        ],
        "x.attr": [
            "“{qc}” {n} muttered, to nobody in particular.",
            "{n} leaned in and said, “{qp}”",
            "“{qc}” {n} told me, not looking up.",
            "{n}'s answer: “{qp}”",
            "“{qc}” {n} said, and lit another one.",
        ],
    },
}
