"""Tabloid gossip column: teases, rhetorical questions, 'sources' that turn out to be the box score."""
FAMILY = {
    "id": "tabloid",
    "label": "Tabloid / gossip",
    "desc": "Breathless gossip with a wink. Teasers, rhetorical questions, ellipses, 'sources close to the box score'. Every scandal is a real number, every rumor a real result.",
    "rhythm": "short teasers followed by a longer dish",
    "formality": "low, catty",
    "metaphors": "red carpets, scandal, the group chat as a courtroom of public opinion",
    "numbers": "exact, delivered like a punchline",
    "lex": {
        "verb": {
            "blowout": ["humiliated", "annihilated", "shellacked"],
            "comfortable": ["bested", "outclassed", "schooled"],
            "normal": ["beat", "topped", "got the better of"],
            "close": ["scraped past", "survived", "edged out"],
        },
        "noun": {
            "blowout": ["a public humiliation", "a bloodbath", "a massacre"],
            "comfortable": ["a tidy win", "a smug little win", "a stylish win"],
            "normal": ["a plain old win", "a workmanlike win", "a quiet win"],
            "close": ["a cliffhanger", "a heart-stopper", "a squeaker"],
        },
        "tier": {
            "hi": ["a total steal, darling", "the bargain of the year", "worth every dollar"],
            "mid": ["not bad, not bad", "a fair return", "okay, we'll allow it"],
            "lo": ["a bit of a flop so far", "money down the drain so far", "not exactly a blockbuster"],
        },
    },
    "T": {
        "h.r.blow": [
            "BLOODBATH! {w} {verb} {l} by {m} and the group chat has questions",
            "{l} left in tatters after {wp}-{lp} defeat by {w}",
            "{m} POINTS: {w} hands {l} {noun}",
        ],
        "h.r.upset": [
            "SHOCK RESULT: {w} ({w_rank0}) topples {l} ({l_rank0})!",
            "{l_rank0}? Not anymore! {w} {verb} {l} in {wl}",
            "Nobody saw {w} coming, least of all {l}",
        ],
        "h.r.close": [
            "WHEW! {w} {verb} {l} by a mere {m}",
            "{w} and {l} deliver {noun}, {wp}-{lp}",
            "{m} points: how {w} narrowly dodged {l} in {wl}",
        ],
        "h.r.top": [
            "{w} HITS {wp}: the week's biggest score and a message to {l}",
            "{wp} points! {w} steals the spotlight in {wl}",
            "Top score alert: {w} puts up {wp} while {l} is left with {lp}",
        ],
        "h.r.tie": [
            "AWKWARD! {a} and {b} tie at {pts}",
            "Nobody wins! {a} and {b} deadlocked at {pts}",
            "{pts}-{pts}: {a} and {b} can't be separated in {wl}",
        ],
        "r.lede.blow": [
            "Oh, it was brutal, darlings. {w} {verb} {l}, {wp} to {lp}, in {wl}, a {m}-point margin that is the widest of the week and, frankly, rude.",
            "You'll want to sit down. {w_team} ({w}) put {m} points on {l_team} ({l}) in {wl}, {wp}-{lp}, the biggest margin of the week. That's {noun}.",
            "The scoreboard says {wp}-{lp}. We say {noun}. {w} beat {l} by {m} in {wl}, the widest gap of the week.",
        ],
        "r.lede.upset": [
            "Rankings schmankings! Going into {wl}, {l} sat {l_rank0} and {w} sat {w_rank0}, and {w} {verb} {l}, {wp} to {lp}. Biggest upset on the slate, darlings.",
            "Did you SEE it? {w}, {w_rank0} in the table, took down {l}, {l_rank0}, {wp}-{lp}, in {wl}. The standings are not amused.",
            "{l} was {l_rank0}. {w} was {w_rank0}. In {wl}, {w} won, {wp} to {lp}, and the table is being very quiet about it.",
        ],
        "r.lede.close": [
            "Hearts were in mouths! {w} {verb} {l}, {wp} to {lp}, in {wl}, by just {m} points. The closest game of the week, and we are not over it.",
            "{m} points. That is all that separated {w_team} ({w}) and {l_team} ({l}) in {wl}, {wp} to {lp}. The tightest finish of the week.",
            "It was {noun}, darlings: {w} over {l}, {wp}-{lp}, by {m}. The closest result of {wl}.",
        ],
        "r.lede.top": [
            "Somebody put on a show. {w} dropped {wp} in {wl}, the top score of the week (league average: {wavg}), and {verb} {l}, who managed {lp}.",
            "The score of the week? {w}'s {wp}, against {l}'s {lp}. The league as a whole averaged {wavg}, so you do the math.",
            "{w_team} ({w}) outscored everybody in {wl} with {wp}. {l} had {lp} and still lost. The average was {wavg}.",
        ],
        "r.lede.tie": [
            "Awkward! {a_team} ({a}) and {b_team} ({b}) tied at {pts} points each in {wl}, and nobody knows where to look.",
            "{a} and {b} both scored {pts} in {wl}. Nobody wins, everybody sulks.",
            "A TIE in {wl}: {a} and {b}, {pts} apiece. We have so many questions.",
        ],
        "g.result": [
            "{w_team} ({w}) {verb} {l_team} ({l}), {wp}-{lp}, and the whole group chat saw it.",
            "{w} {verb} {l}, {wp} to {lp}, and that, darlings, is {noun}.",
            "In {wl}, {w_nick} {verb} {l}, {wp}-{lp}, and wasn't shy about it.",
            "{l_nick} fell to {w}, {lp} to {wp}. Oof. {noun}.",
            "{w} won by {m}, {wp}-{lp}, over {l}, and we are calling it {noun}.",
            "{w} and {l} went head to head, and {w} came out on top, {wp}-{lp}.",
            "{l} lost to {w} by {m}, and we have thoughts: {noun}.",
            "{wp} to {lp}: {w} over {l}. Next!",
            "{w} {verb} {l} in {wl}, {wp}-{lp}. Oof.",
            "Final score, darlings: {w} {wp}, {l} {lp}.",
        ],
        "g.tie": [
            "{a} and {b}: {pts} each. Awkward.",
            "{a_team} ({a}) and {b_team} ({b}) tied at {pts}. Who blinks first?",
            "{pts}-{pts} between {a} and {b}. A draw. Yawn. Gasp. Both.",
        ],
        "g.star": [
            "Sources close to the box score say {star} ({spos}) was the star: {spts}, a whopping {sshare} of {w}'s {wp}.",
            "{star} ({spos}) put up {spts} for {w}. That's {sshare} of the team's total, and we're told the group chat noticed.",
            "Let's hear it for {star} ({spos}), who dropped {spts} on {w}'s behalf.",
        ],
        "g.goat": [
            "Meanwhile, {gname} ({gpos}) gave {l} {gpts}. Ouch, darling.",
            "And {l}'s starter {gname} ({gpos})? {gpts}. Just a tragedy.",
            "Poor {gname} ({gpos}): {gpts} in {l}'s starting lineup. We would say sorry, but we don't mean it.",
        ],
        "g.bench": [
            "{bench_left} just sat there on {l}'s bench! {bench_name} ({bench_pos}) scored {bench_pts} while watching. Tell us you saw that.",
            "The tea: {bench_name} ({bench_pos}) scored {bench_pts} on {l}'s bench, and a better lineup would have added {bench_left}.",
            "{l}'s lineup is a scandal: {bench_left} sat on the bench, {bench_pts} of them from {bench_name} ({bench_pos}).",
        ],
        "g.streak_w": [
            "{w} has won {k} STRAIGHT and sits {w_rank} at {w_rec}. Somebody is on a heater, darlings.",
            "That's {k} in a row for {w}, now {w_rec} and {w_rank}. Smug? Very.",
            "{k} wins on the bounce: {w} is {w_rec}, {w_rank}, and insufferable.",
        ],
        "g.streak_l": [
            "{l} has dropped {k} straight and sits {l_rank} at {l_rec}. Somebody check on {l}.",
            "That's {k} losses in a row for {l}, now {l_rec} and {l_rank}. Awkward.",
            "{k} defeats on the bounce: {l} is {l_rec}, {l_rank}, and not taking calls.",
        ],
        "g.record": [
            "{w} goes to {w_rec} ({w_rank}); {l} sinks to {l_rec} ({l_rank}).",
            "Standings tea: {w}, {w_rec}, {w_rank}. {l}, {l_rec}, {l_rank}.",
            "After {wl}, it's {w} at {w_rec} and {l} at {l_rec}. Just saying.",
        ],
        "g.top": [
            "{w}'s {wp} was the top score of {wl}. The league average was {wavg}, so yes, someone is showing off.",
            "Nobody scored more than {w} in {wl}: {wp}, against a {wavg} average. Show-off.",
            "{wp}: the biggest score of {wl}, and it belongs to {w}. The average was {wavg}.",
        ],
        "g.low": [
            "{l}'s {lp} was the lowest score of {wl}. The league average was {wavg}. Ouch.",
            "Nobody scored less than {l} in {wl}: {lp}, against a {wavg} average. Brutal.",
            "{lp}: the smallest score of {wl}, and it belongs to {l}. The average was {wavg}.",
        ],
        "g.luck_up": [
            "{n} ({n_rec}) is {luck} wins ahead of what the all-play numbers say. Lucky? Very. Suspicious? We'll allow it.",
            "By all-play, {n} has {luck} more wins than {n_rec} deserves. Somebody's got a horseshoe.",
            "{n}: {n_rec}, and {luck} wins above expectation. Charmed life, darling.",
        ],
        "g.luck_down": [
            "{n} ({n_rec}) is {luck} wins behind what the all-play numbers say. Poor thing.",
            "By all-play, {n} should have more wins than {n_rec}: {luck}. The schedule is not being kind.",
            "{n}: {n_rec}, and {luck} wins below expectation. Cursed, darling.",
        ],
        "g.upset": [
            "Remember, {w} came in {w_rank0} and {l} came in {l_rank0}. The standings are fuming.",
            "Pre-game, {l} stood {l_rank0} and {w} stood {w_rank0}. Plot twist!",
            "{l_rank0} lost to {w_rank0}, darlings. Let that sink in.",
        ],
        "g.shotgun": [
            "And {n} owes {sgn}! The reason? {why}.",
            "Drink up, {n}: {sgn} owed in {wl} for {why}.",
            "The league ledger says {n} owes {sgn}, thanks to {why}.",
        ],
        "g.aside": [
            "Of course, {n}, who {trait}, is now left with {event}.",
            "{n}, who {trait}, left {wl} with {event}. Make of that what you will.",
            "We can't help noticing that {n}, who {trait}, now has {event} to explain.",
        ],
        "r.close_shift": [
            "And the playoff picture got a shake-up! {in_names} are now in the top six, and {out_names} are out. {leader} is still first at {leader_rec}.",
            "Standings drama: {in_names} jumped into the top six, while {out_names} fell out. {leader} leads at {leader_rec}.",
            "After {wl}, {in_names} are in and {out_names} are out of the top six. {leader} sits on top at {leader_rec}.",
        ],
        "r.close_table": [
            "After {wl}, {leader} leads at {leader_rec}, and {cut} is hanging on to sixth at {cut_rec}.",
            "The table after {wl}: {leader} on top ({leader_rec}), {cut} barely in at sixth ({cut_rec}).",
            "{leader} is first at {leader_rec}; {cut} is sixth at {cut_rec}. Tension!",
        ],
        "r.close_po": [
            "That's {wl}: {ngames}, a {big_m}-point blowout from {big_w} over {big_l}, and a top score of {top_pts} from {top_w}.",
            "{wl} in the books! {big_w} beat {big_l} by the widest margin ({big_m}), and {top_w} scored the most ({top_pts}) in {ngames}.",
            "{ngames} played in {wl}. The gossip: {big_w}'s {big_m}-point win over {big_l}, and {top_w}'s {top_pts}.",
        ],
        "h.p.fav": [
            "{fav} favored over {dog}, but is {dog} hiding something?",
            "{wl}: {fav} ({fav_odds}) expected to beat {dog} ({dog_odds})",
            "Will {dog} spoil it for {fav}? The odds say no, darling",
        ],
        "h.p.even": [
            "{a} vs. {b}: too close to call!",
            "{wl}: {a} and {b} even at {a_odds} and {b_odds}. Anything could happen!",
            "A coin flip for {a} and {b} in {wl}",
        ],
        "h.p.lev": [
            "{wl}'s biggest showdown: {a} vs. {b}, with {swing} points of playoff swing!",
            "{a} and {b} have everything to lose in {wl}",
            "Playoff drama: {a} vs. {b} in {wl}",
        ],
        "p.lede": [
            "The game everyone's whispering about in {wl}: {a_team} ({a}) vs. {b_team} ({b}).",
            "Gossip central this week is {a} vs. {b}, the featured game of {wl}.",
            "Don't look now, but {a} and {b} meet in {wl}.",
            "{swing} points of playoff swing ride on {a} vs. {b} in {wl}. Scandalous.",
        ],
        "p.matchup": [
            "{a_team} ({a}, {a_rec}, {a_avg} a game) plays {b_team} ({b}, {b_rec}, {b_avg}) in {wl}.",
            "{a} is {a_rec} and scoring {a_avg}; {b} is {b_rec} and scoring {b_avg}. Sparks, darlings.",
            "{b_team} ({b}, {b_rec}, {b_avg}) vs. {a_team} ({a}, {a_rec}, {a_avg}): the matchup the group chat is buzzing about.",
            "In {wl}, {a} ({a_rec}) meets {b} ({b_rec}), {a_avg} ppg versus {b_avg}.",
        ],
        "p.h2h_split": [
            "Their history this season? Split down the middle at {h2h_rec}.",
            "{a} and {b} have split their meetings, {h2h_rec}. Awkward.",
            "It's {h2h_rec} between {a} and {b} this season. Drama.",
        ],
        "p.h2h_lead": [
            "{lead} is up {h2h_rec} on {trail} this season, and has not let {trail} forget it.",
            "{trail} is down {h2h_rec} to {lead} in meetings this season. Revenge, anyone?",
            "{lead} leads {trail} {h2h_rec} this season. The tension is palpable.",
        ],
        "p.h2h_none": [
            "{a} and {b} haven't met this season, so the tension is untested.",
            "The first meeting of the year for {a} and {b}. Pop the popcorn.",
            "{a} and {b} have yet to face each other. Sparks are expected.",
        ],
        "p.stakes": [
            "A win sends {a} to {a_win} playoff odds; a loss, {a_loss}. {b} goes {b_win} with a win and {b_loss} with a loss. High stakes, darlings.",
            "{a}: {a_win} if they win, {a_loss} if they lose. {b}: {b_win} if they win, {b_loss} if they lose. Yikes.",
            "The playoff swings are wild: {a} between {a_loss} and {a_win}, {b} between {b_loss} and {b_win}.",
        ],
        "p.leverage": [
            "{swing} points of combined playoff swing, the most on the slate. Nobody is relaxed.",
            "No game this week carries more drama than {a} vs. {b}: {swing} points of playoff swing.",
            "{a} and {b} are playing for {swing} points of playoff odds, more than any other game. Gulp.",
        ],
        "p.favorite": [
            "{fav} is the favorite on {fav_why}, at {fav_odds} to {dog}'s {dog_odds}. {dog} is quietly furious.",
            "By {fav_why}, {fav} ({fav_odds}) leads {dog} ({dog_odds}). Whether it holds is another matter.",
            "{dog} is the underdog at {dog_odds}, {fav} the favorite at {fav_odds}. Underdogs love a grudge.",
        ],
        "p.vol": [
            "Word is {vol_n} is wildly unpredictable, swinging {vol_std} points a week to {other}'s steadier {other_std}.",
            "{vol_n} is the wild card: {vol_std} points of weekly swing, against {other_std} for {other}.",
            "{other} is dependable ({other_std} points of swing). {vol_n} is chaos ({vol_std}).",
        ],
        "p.rivnote": [
            "And let's not forget the history: this is {rv_name}. {backstory}",
            "It's {rv_name}, and the gossip is deep. {backstory}",
            "Oh, and it's {rv_name}. {backstory}",
        ],
        "p.close": [
            "Stay tuned, darlings: {a} and {b} meet in {wl}.",
            "We'll be watching {a} and {b} in {wl}, popcorn in hand.",
            "More on {a} and {b} after {wl}.",
        ],
        "h.t": [
            "TRADE SHOCKER: {a} ships {gave_s} to {b} for {got_s}",
            "{a} and {b} do the dirty: {gave_s} for {got_s}",
            "{b} lands {gave_s} from {a}, who gets {got_s}",
            "{a} dumps {gave_s} on {b} and takes {got_s}",
        ],
        "t.sides": [
            "Scandal! In {wl}, {a} got {a_got} and {b} got {b_got}.",
            "The league's transaction log shows {a} landing {a_got} and {b} landing {b_got} in {wl}.",
            "{a} out with {b_got}, in with {a_got}: the {wl} trade between {a} and {b}.",
            "{b} slipped {a_got} to {a} in {wl} and walked off with {b_got}.",
        ],
        "t.returns": [
            "The early verdict? Over {since_wk}, {a}'s new guys scored {a_pts} and {b}'s scored {b_pts}. {lead} is winning the gossip war.",
            "Since the deal, {lead}'s haul has produced {lead_pts}, and {trail}'s {trail_pts}, over {since_wk}. Whoops.",
            "{a}'s side: {a_pts} over {since_wk}. {b}'s side: {b_pts}. {lead} has the early edge, darlings.",
        ],
        "t.pending": [
            "{pk_side} got {pk_got}, and {pl_side} got {pl_got}. Picks for players means we can't grade it yet. Drama delayed.",
            "{pl_side} has the players ({pl_got}); {pk_side} has the picks ({pk_got}). Verdict: pending, darlings.",
            "Picks for players: {pl_side} took {pl_got}, {pk_side} took {pk_got}. We'll know who blinked later.",
        ],
        "t.fresh": [
            "It's too early to say who won, darlings. Stay tuned.",
            "No verdict yet. The games haven't happened.",
            "The jury's out, and so is the production.",
        ],
        "t.count": [
            "It's {n}'s {nth} trade of the season. Somebody likes a deal.",
            "{n} just made the {nth} trade of the year. Can't sit still.",
            "That's the {nth} trade for {n} this season.",
        ],
        "t.rec": [
            "Before the deal, {a} was {a_rec} ({a_rank}) and {b} was {b_rec} ({b_rank}). Context matters, darlings.",
            "Back then, {a} was {a_rank} at {a_rec} and {b} was {b_rank} at {b_rec}. Interesting timing.",
            "Entering that week, {a} stood {a_rec} ({a_rank}) and {b} stood {b_rec} ({b_rank}).",
        ],
        "t.close": [
            "The league log has it all: the deal is complete.",
            "It's official and on the record.",
            "The trade cleared. You can't take it back.",
        ],
        "h.w.big": [
            "{n} SPLASHES {bid} on {player}!",
            "{bid}?! {n} goes big for {player} ({pos})",
            "{n} drops {bid} on {player}",
        ],
        "h.w.small": [
            "{n} quietly adds {player} for {bid}",
            "{player} ({pos}) lands with {n} for {bid}",
            "{n} snags {player} with a {bid} bid",
        ],
        "h.w.free": [
            "{n} sneaks {player} off the wire",
            "{player} ({pos}) lands with {n} for free",
            "{n} sneaks {player} in without opening a wallet",
        ],
        "w.top_bid": [
            "{n} dropped {bid} on {player} ({pos}) in {wl}, the biggest bid of the week. Somebody has a crush.",
            "The week's top bid? {bid}, from {n}, for {player} ({pos}). Bold.",
            "{n} splashed {bid} on {player} ({pos}), the biggest claim of {wl}.",
        ],
        "w.top_free": [
            "{n} quietly added {player} ({pos}) in {wl}.",
            "Spotted: {player} ({pos}) joining {n} in {wl}.",
            "The pickup everyone's whispering about in {wl}: {player} ({pos}), by {n}.",
        ],
        "w.since": [
            "Since the move, {player} has coughed up {spts} in {since_wk}. That's {tier}.",
            "Over {since_wk}, {player} has handed {n} {spts}, which is {tier}.",
            "And {player}? {spts} in the {since_wk} since. {tier}.",
        ],
        "w.others": [
            "Also spotted on the wire: {others_text}.",
            "Others in on the action: {others_text}.",
            "Meanwhile, on the side streets: {others_text}.",
        ],
        "w.total": [
            "Total damage on the wire in {wl}: {total_n} snapped up by {total_owners}.",
            "{total_n} traded hands among {total_owners} in {wl}. The paper trail is wild.",
            "{total_owners} were spotted working the wire in {wl}, taking {total_n}.",
        ],
        "w.budget": [
            "{n} has burned through {spent} of a {budget} FAAB budget. Spendy.",
            "{n}'s FAAB: {spent} of {budget} gone.",
            "So far, {n} has spent {spent} out of {budget} in FAAB.",
        ],
        "w.close": [
            "{player} is now on {n}'s roster. You heard it here.",
            "{n} has {player}. The league log doesn't lie.",
            "It's official: {player} belongs to {n}.",
        ],
        "h.s": [
            "BEER REPORT: {total_n} owed in Week {wk}",
            "{top} owes {topn} in Week {wk}! Cheers?",
            "Week {wk} shotgun scandal: {total_n} on the ledger",
            "{top} leads the Week {wk} drinking list with {topn}",
        ],
        "s.total": [
            "The Week {wk} shotgun ledger is in, darlings: {total_n} across {owners_n}.",
            "{owners_n} owe a combined {total_n} for Week {wk}. Bottoms up.",
            "Week {wk} left {total_n} on the books, spread across {owners_n}.",
        ],
        "s.owner": [
            "{n} owes {sgn}, courtesy of {list}.",
            "{sgn} on {n}'s tab: {list}.",
            "{n}: {sgn}. The damage: {list}.",
            "{n} ran up {sgn} with {list}. Cheers, darling.",
        ],
        "s.low": [
            "Lowlight: {player} ({pos}) managed {pts} in {n}'s lineup.",
            "The week's ugliest number was {player}'s ({pos}) {pts} for {n}.",
            "{n} started {player} ({pos}), who scored {pts}. Cringe.",
        ],
        "s.leader": [
            "{leader} leads the season with {ltotal} through Week {wk}. A true professional.",
            "The season's biggest drinker, by the ledger: {leader}, {ltotal}, through Week {wk}.",
            "{leader} has the most shotguns this season, {ltotal}.",
        ],
        "s.close": [
            "{top} is first on the Week {wk} list. Cheers, darling.",
            "{top} heads the Week {wk} ledger. We'll bring the cups.",
            "Pour one for {top}, who leads the Week {wk} list.",
        ],
        "h.n": [
            "STANDINGS SHAKE-UP through {wl}: {top} on top, {six} clinging to sixth",
            "{alive} teams are still in it for {spots} playoff spots through {wl}",
            "{top} rules and {bottom} suffers: standings through {wl}",
            "Through {wl}, {six} is barely clinging to the last spot",
        ],
        "h.nf": [
            "FINAL standings: {top} on top, {seven} on the outside",
            "{six} sneaks in; {seven} is out: the final table",
            "{top} first, {bottom} last: the regular season wraps",
            "The playoff cut: {six} is in, {seven} is out. Drama!",
        ],
        "n.top": [
            "Through {wl}, {top} sits on top at {top_rec}, and isn't shy about it.",
            "{top} is first at {top_rec} through {wl}. Smug.",
            "{top}, {top_rec}, number one through {wl}.",
            "{top} leads at {top_rec} with {top_odds} playoff odds. Insufferable.",
            "Through {wl}, {top} leads at {top_rec}, with {top_odds} playoff odds and {bye} to snag a bye. Naturally.",
        ],
        "n.cut": [
            "{six} ({six_rec}) is clinging to the sixth and final spot, with {seven} ({seven_rec}) breathing down their neck.",
            "The cut line runs between {six} ({six_rec}) and {seven} ({seven_rec}). Nervous?",
            "{seven} ({seven_rec}) is first out, just behind {six} ({six_rec}).",
        ],
        "n.luck": [
            "The luck scandal: {lucky} is {lucky_luck} wins over expectation, and {unlucky} is {unlucky_luck}. Somebody's got the horseshoe.",
            "By all-play, {lucky} ({lucky_luck}) is the luckiest team alive; {unlucky} ({unlucky_luck}) is the unluckiest.",
            "{lucky} has {lucky_luck} wins more than it deserves. {unlucky} has {unlucky_luck}. Unfair? Very.",
        ],
        "n.clinch": [
            "CLINCHED: {names}. Smug looks all round.",
            "In, and unbearable about it: {names}.",
            "{names} have locked up a playoff spot.",
        ],
        "n.elim": [
            "Eliminated: {names}. Our thoughts are with them. Mostly.",
            "Out, mathematically: {names}. Awkward.",
            "{names} can no longer get in.",
        ],
        "n.bottom": [
            "At the very bottom: {bottom}, {bottom_rec}. Ouch.",
            "{bottom} is dead last at {bottom_rec}.",
            "Last place goes to {bottom} ({bottom_rec}). Tragic.",
        ],
        "n.eff": [
            "Lineup scandal: {best_n} gets {best_pct} of the available points; {worst_n} gets {worst_pct}.",
            "{best_n} sets the best lineups ({best_pct}), and {worst_n} the worst ({worst_pct}). Hmm.",
            "Efficiency tea: {best_n} at {best_pct}, {worst_n} at {worst_pct}.",
        ],
        "n.records": [
            "For the record books: the top score is {hi_pts} by {hi_n} in Week {hi_wk}, and the widest margin is {blow_m}, {blow_w} over {blow_l} in Week {blow_wk}.",
            "Record watch: {hi_n}'s {hi_pts} (Week {hi_wk}) and {blow_w}'s {blow_m}-point demolition of {blow_l} (Week {blow_wk}).",
            "{hi_pts} points for {hi_n} in Week {hi_wk} is the high; {blow_m} points for {blow_w} over {blow_l} in Week {blow_wk} is the widest margin.",
        ],
        "n.ftop": [
            "{top} finished first at {top_rec}, with {top_pf} to brag about.",
            "Your top seed, and don't they know it: {top}, {top_rec}, {top_pf}.",
            "{top} ended on top, {top_rec} and {top_pf}. Naturally.",
        ],
        "n.fcut": [
            "{six} snuck in at {six_rec}, and {seven} ({seven_rec}) is out by a hair.",
            "The cut fell between {six} ({six_rec}) and {seven} ({seven_rec}). Heartbreak.",
            "{seven} ({seven_rec}) missed out. {six} ({six_rec}) took the last spot.",
        ],
        "n.fpts": [
            "{pf_n} outscored the rest all season with {pf_pts}, while {low_n} limped in with {low_pts}.",
            "Points leaders: {pf_n}, {pf_pts}. Points cellar: {low_n}, {low_pts}.",
            "{pf_pts} for {pf_n} is the top. {low_pts} for {low_n} is the bottom.",
        ],
        "n.fbottom": [
            "{bottom} finished last at {bottom_rec}. Tragic.",
            "Dead last: {bottom}, {bottom_rec}.",
            "{bottom} wrapped up at the bottom, {bottom_rec}.",
        ],
        "n.close": [
            "That's the table through {wl}, with {top} on top. Stay tuned.",
            "Through {wl}, {top} leads. Everyone else is plotting.",
            "{top} is first through {wl}. For now.",
        ],
        "h.f": [
            "FEUD ALERT: {a} and {b}",
            "{a} vs. {b}: the beef, explained",
            "What's REALLY going on between {a} and {b}?",
            "{a} and {b}: it's getting personal",
        ],
        "f.h2h": [
            "It all began in Week {gwk}, when {w} {verb} {l}, {wp}-{lp}. The margin? {m} points. Cold.",
            "In Week {gwk}, {w} beat {l}, {wp} to {lp}, by {m}, and sources say {l} remembers every point.",
            "{l} lost to {w} in Week {gwk}, {lp}-{wp}, by {m}. That was {noun}, darlings.",
        ],
        "f.trade": [
            "Here's the thing: in Week {twk}, {a} and {b} did a trade. {a} got {a_got} and {b} got {b_got}. Awkward.",
            "The two swapped in Week {twk}: {a} took {a_got}, and {b} took {b_got}. Receipts don't lie.",
            "In Week {twk}, {b_got} went to {b} and {a_got} to {a}. And now this.",
        ],
        "f.adj": [
            "In the standings, {hi} ({hi_rec}, {hi_rank}) is just ahead of {lo} ({lo_rec}, {lo_rank}), a mere {pf_gap} apart in points scored. Sparks!",
            "{hi} is {hi_rank}. {lo} is {lo_rank}. {pf_gap} apart in points scored. Anybody feeling tense?",
            "{lo} trails {hi} by {pf_gap} in points scored, {lo_rank} to {hi_rank} in the table. They can see each other.",
        ],
        "f.blow": [
            "The wound is Week {gwk}: {w} {verb} {l}, {wp} to {lp}, by {m} points.",
            "Remember Week {gwk}? {w} beat {l} by {m}, {wp}-{lp}, and the group chat does.",
            "{w}'s {m}-point win over {l} in Week {gwk} ({wp}-{lp}) is the kind of margin that starts grudges.",
        ],
        "f.sg": [
            "On the shotgun ledger, {a} owes {a_sg} and {b} owes {b_sg}. Who's drinking more?",
            "The beer tab: {a}, {a_sg}; {b}, {b_sg}.",
            "{a} has {a_sg} on the ledger, and {b} has {b_sg}. Cheers?",
        ],
        "f.story": [
            "And it has a name: {rv_name}. {backstory}",
            "Insiders whisper that it's called {rv_name}. {backstory}",
            "This is {rv_name}, darlings. {backstory}",
        ],
        "f.trait": [
            "{a} {a_trait}. {b} {b_trait}. Is it any wonder?",
            "Consider the evidence: {a} {a_trait}, and {b} {b_trait}.",
            "{a} {a_trait}; {b} {b_trait}. We rest our case.",
        ],
        "f.mid": [
            "Through Week {wk}, {a} is sitting pretty at {a_rec} ({a_rank}) while {b} is {b_rec} ({b_rank}). Make of that what you will.",
            "The pecking order through Week {wk}: {a}, {a_rank}, {a_rec}; {b}, {b_rank}, {b_rec}.",
            "Through Week {wk}: {a} is {a_rec} ({a_rank}), {b} is {b_rec} ({b_rank}), and the group chat can count.",
        ],
        "f.close": [
            "We'll keep you posted, darlings.",
            "More as the group chat develops.",
            "Neither side has backed down. Stay tuned.",
        ],
        "h.v": [
            "{rv_name} IS BACK: {a} vs. {b}, Week {wk}",
            "{rv_name} is back! {a} and {b} in Week {wk}",
            "Week {wk}: the {rv_name} grudge match",
            "{rv_name}: {a} and {b} meet again",
        ],
        "v.lede": [
            "It's {rv_name} week, darlings! {a} plays {b} in {wl}. {backstory}",
            "Pass the popcorn: {rv_name} returns in {wl}, with {a} against {b}. {backstory}",
            "{a} vs. {b} in {wl}: {rv_name}. {backstory}",
        ],
        "v.form": [
            "{a} is {a_rec} ({a_rank}) and scoring {a_avg}; {b} is {b_rec} ({b_rank}) and scoring {b_avg}.",
            "The stats on the pair: {a}, {a_rec}, {a_rank}, {a_avg} a game; {b}, {b_rec}, {b_rank}, {b_avg} a game.",
            "{b} comes in {b_rank} at {b_rec} ({b_avg} a game); {a} comes in {a_rank} at {a_rec} ({a_avg} a game).",
        ],
        "v.close": [
            "Pass the popcorn: {a} vs. {b} in Week {wk}.",
            "See you in Week {wk}, {a} and {b}. We'll be watching.",
            "Week {wk} is going to be an absolute zoo for {a} and {b}.",
        ],
        "h.o": [
            "OFFSEASON SCANDAL: {ntrades}, {npick}, and a lot of questions",
            "{ntrades} and {npick}: who was up to what",
            "Before kickoff: {ntrades} and {npick}",
        ],
        "o.lede": [
            "Before the season even started, the league logged {ntrades} and {npick}. Somebody was busy, darlings.",
            "The offseason log is wild: {ntrades} and {npick}.",
            "{ntrades}! {npick}! All before kickoff!",
        ],
        "o.busy": [
            "The busiest deal-makers: {busy_text}. Those phones were smoking.",
            "Whose phone was smoking? {busy_text}.",
            "The ones who couldn't stop: {busy_text}.",
        ],
        "o.big": [
            "The deal everyone whispered about all winter: {side_a} got {a_got}, and {side_b} got {b_got}.",
            "Blockbuster alert: {side_a} landed {a_got}, and {side_b} landed {b_got}.",
            "The largest trade: {side_a} receives {a_got}, {side_b} receives {b_got}.",
        ],
        "o.close": [
            "{busiest} made the most trades. Can't sit still.",
            "Nobody wheeled and dealed like {busiest}. Nobody.",
            "{busiest} led the offseason in trades. Naturally.",
        ],
        # ---------------- Sunday column ----------------
        "h.c": [
            "SUNDAY SCANDAL: {a} and {b} are talking",
            "Did {a} REALLY say that about {b}?",
            "{a} vs. {b}: the trash talk, ranked",
            "The things {a} and {b} said about each other",
        ],
        "h.c.rv": [
            "{rv_name} gets NASTY: {a} and {b}",
            "{a} and {b}: {rv_name}, the sequel",
            "Inside {rv_name}: what {a} and {b} won't say on the record",
        ],
        "h.c.next": [
            "{a} and {b} meet in Week {nwk}, and the claws are OUT",
            "Week {nwk} showdown: {a} vs. {b}, and they are NOT being nice",
            "Trouble brewing before {a} meets {b} in Week {nwk}",
        ],
        "c.lede": [
            "Pour yourself something, because through {wl} {a} is {a_rec} and {a_rank}, and {b} is {b_rec} and {b_rank}. Oh, there's tea.",
            "Let's start with the table, darlings: through {wl}, {a} ({a_rec}) is {a_rank} and {b} ({b_rec}) is {b_rank}.",
            "{a} is {a_rank} at {a_rec}. {b} is {b_rank} at {b_rec}. Through {wl}. Now, to the dish...",
        ],
        "c.next": [
            "And they meet in Week {nwk}. Popcorn, anyone?",
            "The schedule says {a} and {b} play in Week {nwk}. The schedule has a sense of humor.",
            "Week {nwk}. {a} and {b}. Mark your calendars, gossips.",
        ],
        "c.recent": [
            "Recent form, and it's JUICY: {a} {a_form}, and {b} {b_form}.",
            "Lately, {a} {a_form}. And {b}? {b} {b_form}. Draw your own conclusions...",
            "In their last games, {a} {a_form}, while {b} {b_form}. Hmm.",
        ],
        "c.gap": [
            "In the table, {hi} ({hi_rec}, {hi_rank}) is looking down at {lo} ({lo_rec}, {lo_rank}), with {pf_gap} between them in points scored. Awkward.",
            "{pf_gap}! That's the points gap between {hi} ({hi_rank}) and {lo} ({lo_rank}). Somebody's feeling it.",
            "{hi} sits {hi_rank} at {hi_rec}, {lo} sits {lo_rank} at {lo_rec}, and {pf_gap} of scoring sits between them.",
        ],
        "c.pick": [
            "Our pick? {fav} over {dog}, going by {fav_why}. Sorry, {dog}, darling.",
            "The numbers whisper {fav} over {dog}, on {fav_why}.",
            "{fav} gets our vote on {fav_why}. {dog} may want to sit down.",
        ],
        "c.close": [
            "Neither {a} nor {b} is backing down. More as the group chat develops.",
            "You heard it here first, {a} and {b}. Kisses.",
            "Stay tuned, because {a} and {b} are just getting started.",
        ],
        # ---------------- Monday analytics ----------------
        "h.a.luck": [
            "LUCKY or LOADED? {lucky} is {lucky_luck}, {unlucky} is {unlucky_luck}",
            "The luck scandal: {lucky} has it, {unlucky} has the bill",
            "Who's been getting away with it? {lucky} ({lucky_luck}), that's who",
        ],
        "h.a.eff": [
            "Lineup LIES: {best_n} at {best_pct}, {worst_n} at {worst_pct}",
            "{worst_n} is leaving points EVERYWHERE, at just {worst_pct}",
            "Efficiency exposed: {best_n} {best_pct}, {worst_n} {worst_pct}",
        ],
        "h.a.bench": [
            "{bench_n}'s BENCH SECRET: {bench_pts} left behind",
            "Benchgate: {bench_n} left {bench_pts} on the pine",
            "{bench_pts} wasted on the bench, and {bench_n} did it",
        ],
        "h.a.steady": [
            "Steady {steady_n}, scandalous {wild_n}: the weekly rank files",
            "{wild_n} is ALL OVER THE PLACE, and {steady_n} is suspiciously calm",
            "{steady_n} is suspiciously consistent and {wild_n} suspiciously not",
        ],
        "a.lede": [
            "Monday. The numbers. Through {wl}, {gp} per team, and they are not kind to everyone...",
            "Grab the smelling salts, darlings, because these figures cover {gp} per team through {wl}.",
            "We pulled the receipts, {gp} per team, through {wl}. Brace yourselves.",
        ],
        "a.luck": [
            "{lucky} is {lucky_rec}, but the all-play math says it should be around {lucky_exp} wins. That's {lucky_luck} of pure luck. Meanwhile {unlucky} is {unlucky_rec} and should be at {unlucky_exp}, a luck index of {unlucky_luck}. Unfair? Very.",
            "The luck index doesn't lie, and neither do we: {lucky}, {lucky_luck} ({lucky_rec}, expected {lucky_exp}). {unlucky}, {unlucky_luck} ({unlucky_rec}, expected {unlucky_exp}).",
            "Somebody's been blessed. {lucky} is {lucky_rec} on {lucky_exp} expected wins ({lucky_luck}). Somebody's been cursed. {unlucky} is {unlucky_rec} on {unlucky_exp} ({unlucky_luck}).",
        ],
        "a.eff": [
            "On lineups: {best_n} squeezes out {best_pct} of the points that were there. {worst_n}? Just {worst_pct}. The whole league is at {lg_pct}. Yikes.",
            "Efficiency tea: {best_n} at {best_pct}, {worst_n} at {worst_pct}, and a league average of {lg_pct}. Somebody should check their lineup.",
            "{worst_n} left a LOT behind at {worst_pct}, while {best_n} got {best_pct}. League average: {lg_pct}.",
        ],
        "a.bench": [
            "The bench is where secrets go to score. {bench_n} left {bench_pts} there, and {bench_low_n} left only {bench_low_pts}.",
            "{bench_n}: {bench_pts} left on the bench against the best lineup. {bench_low_n}: {bench_low_pts}. Tidy, darling.",
            "Bench confessions: {bench_n} wasted {bench_pts}, and {bench_low_n} wasted just {bench_low_pts}.",
        ],
        "a.blunder": [
            "THE BIGGEST BENCH BLUNDER of the season so far? {bl_n}, Week {bl_wk}, a whopping {bl_pts} below the best possible lineup, with {bl_player} ({bl_pos}) scoring {bl_player_pts} on the bench. Ouch.",
            "Week {bl_wk} was a nightmare for {bl_n}: {bl_pts} short of the best lineup, and {bl_player} ({bl_pos}) had {bl_player_pts} just sitting there...",
            "Oh, {bl_n}. Week {bl_wk}. {bl_pts} below perfection. {bl_player} ({bl_pos}) managed {bl_player_pts} from the bench.",
        ],
        "a.steady": [
            "And the consistency files! {steady_n} averages a weekly rank of {steady_avg}, ranging from {steady_band}. {wild_n}? Ranging from {wild_band}. Chaos, darling.",
            "{steady_n} is the picture of calm (average {steady_avg}, from {steady_band}), while {wild_n} is a mess, from {wild_band}.",
            "Who's reliable? {steady_n}, from {steady_band}. Who isn't? {wild_n}, from {wild_band}.",
        ],
        "a.trade": [
            "And that Week {twk} trade? Over {since_wk}, the players {lead} got have scored {lead_pts}, while the ones {trail} got have managed {trail_pts}. Somebody got fleeced...",
            "The trade report card for Week {twk}: {lead} is ahead, {lead_pts} to {trail_pts}, over {since_wk}. {trail} is not telling.",
            "Early returns on the Week {twk} deal: {lead} {lead_pts}, {trail} {trail_pts}, after {since_wk}. Whoops.",
        ],
        "a.close": [
            "That's the tea through {wl}, darlings.",
            "Receipts don't lie. Kisses.",
            "More numbers, more scandal, next Monday.",
        ],
        "x.sig": [
            "And then, because of course: “{catch}” Pure {n}.",
            "{n} just had to add: “{catch}”",
            "{n}'s signature line, darlings: “{catch}”",
        ],
        "x.attr": [
            "“{qc}” {n} dished.",
            "{n}, speaking on the record and off the rails: “{qp}”",
            "“{qc}” said {n}, unprompted.",
            "{n} spilled: “{qp}”",
            "“{qc}” {n} told us, and we gasped.",
        ],
    },
}
