"""Weather forecaster: fronts, pressure systems, highs and lows. Playoff odds are chances of precipitation."""
FAMILY = {
    "id": "weather",
    "label": "Weather forecaster",
    "desc": "TV meteorologist: fronts, pressure systems, gusts, highs and lows, 'chance of'. Scores are temperatures, playoff odds are precipitation chances, upsets are unseasonable weather. Cheerful about disasters.",
    "rhythm": "medium, forecast-shaped, with a bright sign-off",
    "formality": "medium, broadcast-friendly",
    "metaphors": "fronts, systems, radar, barometers, seasons, storms",
    "numbers": "exact, read like readings off an instrument",
    "lex": {
        "verb": {
            "blowout": ["washed out", "buried", "swamped"],
            "comfortable": ["moved past", "blew past", "rolled over"],
            "normal": ["beat", "passed through", "outlasted"],
            "close": ["edged", "narrowly outlasted", "squeaked past"],
        },
        "noun": {
            "blowout": ["a full-blown hurricane", "a category-five blowout", "a flash flood"],
            "comfortable": ["a steady front", "a clear-skies win", "a comfortable high-pressure win"],
            "normal": ["a partly sunny win", "a seasonal result", "a normal weather pattern"],
            "close": ["a near miss", "a razor-thin front", "a squall that barely held"],
        },
        "tier": {
            "hi": ["a clear and sunny forecast", "a heat wave", "a bumper harvest"],
            "mid": ["partly sunny", "seasonable", "mild"],
            "lo": ["cloudy so far", "a dry spell so far", "overcast so far"],
        },
    },
    "T": {
        "h.r.blow": [
            "{wl} forecast: {w} {verb} {l}, {wp}-{lp}",
            "A {m}-point storm system: {w} over {l}",
            "{w_team} brings {noun} to {l_team}, {wp}-{lp}",
        ],
        "h.r.upset": [
            "Unseasonable weather: {w} ({w_rank0}) topples {l} ({l_rank0})",
            "The models missed it: {w} {verb} {l} in {wl}",
            "Surprise system: {w_rank0} over {l_rank0}",
        ],
        "h.r.close": [
            "Barely a breeze: {w} {verb} {l} by {m}",
            "{m} points of pressure difference: {w} over {l}",
            "{wl}: {w} and {l} produce {noun}, {wp}-{lp}",
        ],
        "h.r.top": [
            "Record high: {w} scores {wp} in {wl}",
            "A heat wave for {w}: {wp} points, the week's high",
            "{w} hits {wp}, the high of {wl}, and {l} cools off",
        ],
        "h.r.tie": [
            "Dead calm: {a} and {b} tie at {pts}",
            "Matching readings: {a} and {b}, {pts} apiece",
            "{pts}-{pts}: {a} and {b} meet at the same temperature",
        ],
        "r.lede.blow": [
            "Good evening, and here is your {wl} forecast. A major system moved through: {w} {verb} {l}, {wp} to {lp}, a {m}-point margin, the strongest of the week. That's {noun}.",
            "A powerful front hit in {wl}. {w_team} ({w}) {verb} {l_team} ({l}) by {m} points, {wp} to {lp}, the biggest swing on the radar all week.",
            "The week's biggest storm: {w} over {l}, {wp}-{lp}, a margin of {m} points in {wl}. Widespread damage reported.",
        ],
        "r.lede.upset": [
            "Forecast models called for {l}, {l_rank0} in the standings, to move past {w}, {w_rank0}. Instead, {w} {verb} {l}, {wp} to {lp}, the biggest forecast miss of {wl}.",
            "An unseasonable system in {wl}: {w}, {w_rank0} in the table, beat {l}, {l_rank0}, {wp}-{lp}. The meteorologists are reviewing the data.",
            "Entering {wl}, the standings had {l} at {l_rank0} and {w} at {w_rank0}. The result, {wp} to {lp} for {w}, was the week's biggest surprise.",
        ],
        "r.lede.close": [
            "Barely a ripple. {w} {verb} {l}, {wp} to {lp}, in {wl}, by just {m} points, the closest game on the radar. That was {noun}.",
            "A near-stalemate in the pressure systems: {w_team} ({w}) beat {l_team} ({l}) by {m} points in {wl}, {wp}-{lp}, the narrowest margin of the week.",
            "Winds were light and the game was tight: {w} over {l}, {wp} to {lp}, by {m}, the closest result of {wl}.",
        ],
        "r.lede.top": [
            "A record high for {wl}: {w} scored {wp}, the hottest reading of the week against a league average of {wavg}, and {verb} {l} (reading: {lp}).",
            "It was hot out there. {w_team} ({w}) reached {wp} in {wl}, the high of the week, while {l} hit {lp}. The league average was {wavg}.",
            "The high temperature for {wl} was {w}'s {wp}, well above the {wavg} average. {l} reached {lp}.",
        ],
        "r.lede.tie": [
            "Dead calm in one corner of the map: {a_team} ({a}) and {b_team} ({b}) both reached {pts} in {wl}.",
            "Matching readings: {a} and {b} each scored {pts} in {wl}.",
            "{a} and {b} finished {wl} at the same temperature, {pts} apiece. No winner today.",
        ],
        "g.result": [
            "{w_team} ({w}) {verb} {l_team} ({l}), {wp} to {lp}, per today's readings.",
            "{w} {verb} {l}, {wp}-{lp}. That's {noun}.",
            "In {wl}, {w_nick} {verb} {l}: {wp} to {lp}.",
            "{l_nick} fell to {w}, {lp}-{wp}, a {m}-point difference. {noun}.",
            "Readings: {w}, {wp}; {l}, {lp}. A spread of {m}, {noun}.",
            "{w} and {l} collided in {wl}, and {w} came out sunnier, {wp}-{lp}.",
            "{l} dipped to {lp} against {w}'s {wp}.",
            "A {m}-point front pushed {w} past {l}, {wp} to {lp}.",
            "{w} {verb} {l}. {noun}.",
            "Readings for {w} and {l}: {wp} and {lp}.",
        ],
        "g.tie": [
            "{a} and {b} each read {pts}.",
            "{a_team} ({a}) and {b_team} ({b}) finished at the same temperature, {pts}.",
            "{pts} each for {a} and {b}: dead calm.",
        ],
        "g.star": [
            "The high pressure came from {star} ({spos}), who produced {spts}, {sshare} of {w}'s {wp}.",
            "{star} ({spos}) was the warm front for {w}: {spts}.",
            "{w}'s hottest reading was {star} ({spos}) at {spts}, {sshare} of the total.",
        ],
        "g.goat": [
            "A cold spot in {l}'s forecast: {gname} ({gpos}), {gpts}.",
            "{gname} ({gpos}) brought {gpts} for {l}, a real chill.",
            "{l} got a low reading from {gname} ({gpos}): {gpts}.",
        ],
        "g.bench": [
            "{l} left {bench_left} on the bench; {bench_name} ({bench_pos}) scored {bench_pts} sitting out the storm.",
            "{bench_name} ({bench_pos}) read {bench_pts} on {l}'s bench, and a better lineup was worth {bench_left}.",
            "{bench_left} sat sheltered on {l}'s bench, including {bench_pts} from {bench_name} ({bench_pos}).",
        ],
        "g.streak_w": [
            "A warm streak: {w} has won {k} straight and sits {w_rank} at {w_rec}.",
            "{k} sunny days in a row for {w}, now {w_rec} and {w_rank}.",
            "{w} is {w_rec}, {w_rank}, riding a {k}-game high-pressure system.",
        ],
        "g.streak_l": [
            "A cold snap: {l} has lost {k} straight and sits {l_rank} at {l_rec}.",
            "{k} cloudy days in a row for {l}, now {l_rec} and {l_rank}.",
            "{l} is {l_rec}, {l_rank}, stuck under a {k}-game low-pressure system.",
        ],
        "g.record": [
            "{w} rises to {w_rec} ({w_rank}); {l} drops to {l_rec} ({l_rank}).",
            "The standings barometer now reads {w}, {w_rec}, {w_rank}, and {l}, {l_rec}, {l_rank}.",
            "After {wl}, {w} sits at {w_rec} and {l} at {l_rec}.",
        ],
        "g.top": [
            "{w}'s {wp} was the high of {wl}. The league average was {wavg}.",
            "No one was hotter than {w} in {wl}: {wp}. The average was {wavg}.",
            "{wp} for {w}, the week's high. Average temperature: {wavg}.",
        ],
        "g.low": [
            "{l}'s {lp} was the low of {wl}. The league average was {wavg}.",
            "No one was colder than {l} in {wl}: {lp}. The average was {wavg}.",
            "{lp} for {l}, the week's low. Average temperature: {wavg}.",
        ],
        "g.luck_up": [
            "{n} ({n_rec}) is sitting {luck} wins above what the all-play radar shows. Sunny skies, for now.",
            "By all-play, {n} has {luck} extra wins at {n_rec}. Fair weather doesn't last.",
            "{n}: {n_rec}, and {luck} wins above expectation. Enjoy the sunshine.",
        ],
        "g.luck_down": [
            "{n} ({n_rec}) is sitting {luck} wins below what the all-play radar shows. A stubborn cloud bank.",
            "By all-play, {n} should have more than {n_rec}: {luck}. Clearing is expected, eventually.",
            "{n}: {n_rec}, and {luck} wins below expectation. Bring an umbrella.",
        ],
        "g.upset": [
            "Before the game, {w} stood {w_rank0} and {l} stood {l_rank0} on the barometer.",
            "The standings had {l} at {l_rank0} and {w} at {w_rank0} entering {wl}.",
            "Pre-game readings: {l}, {l_rank0}; {w}, {w_rank0}.",
        ],
        "g.shotgun": [
            "And a shower of {sgn} for {n}, owing to {why}.",
            "{n} faces {sgn} in the forecast, due to {why}.",
            "Rain on the way for {n}: {sgn}, for {why}.",
        ],
        "g.aside": [
            "{n}, who {trait}, stood under {event}.",
            "In other news, {n}, who {trait}, closed {wl} with {event}.",
            "{n}, who {trait}, now has {event} in the forecast.",
        ],
        "r.close_shift": [
            "In the standings, the pressure shifted: {in_names} moved into the top six, and {out_names} moved out. {leader} remains the high at {leader_rec}.",
            "A front moved through the top six after {wl}: {in_names} in, {out_names} out. {leader} leads at {leader_rec}.",
            "After {wl}, {in_names} are in the playoff zone, and {out_names} are out of it. {leader} holds first at {leader_rec}.",
        ],
        "r.close_table": [
            "After {wl}, {leader} is the high at {leader_rec}, and {cut} holds the sixth and final playoff spot at {cut_rec}.",
            "The standings after {wl}: {leader} on top ({leader_rec}), {cut} barely in at sixth ({cut_rec}).",
            "{leader} leads at {leader_rec}. {cut} is clinging to sixth at {cut_rec}.",
        ],
        "r.close_po": [
            "That's your {wl} summary: {ngames}. The strongest system was {big_w}'s {big_m}-point win over {big_l}, and the hottest reading was {top_w}'s {top_pts}.",
            "{wl} is in the books: {ngames}. {big_w} beat {big_l} by {big_m}, and {top_w} hit {top_pts}.",
            "{ngames} in {wl}. The widest spread was {big_m} points ({big_w} over {big_l}), and the high was {top_w}'s {top_pts}.",
        ],
        "h.p.fav": [
            "{wl} forecast: {fav} favored over {dog}",
            "{fav} ({fav_odds}) on the sunny side against {dog} ({dog_odds}) in {wl}",
            "Sunny skies for {fav}, clouds for {dog} in {wl}",
        ],
        "h.p.even": [
            "{wl} forecast: {a} and {b} too close to call",
            "A coin flip of a front: {a} vs. {b} in {wl}",
            "{a} and {b} meet in {wl} with matching odds, {a_odds} and {b_odds}",
        ],
        "h.p.lev": [
            "Storm watch in {wl}: {a} vs. {b}, {swing} points of playoff swing",
            "{wl}'s biggest system: {a} and {b}",
            "High stakes on the radar: {a} vs. {b} in {wl}",
        ],
        "p.lede": [
            "Your featured system of {wl} is {a_team} ({a}) against {b_team} ({b}).",
            "The big front in {wl}: {a} meets {b}.",
            "Keep an eye on the radar for {a} and {b} in {wl}.",
            "{swing} points of combined playoff swing on the radar: {a} vs. {b} in {wl}.",
        ],
        "p.matchup": [
            "{a_team} ({a}, {a_rec}, {a_avg} a game) meets {b_team} ({b}, {b_rec}, {b_avg}) in {wl}.",
            "{a} is {a_rec} and averaging {a_avg}. {b} is {b_rec} and averaging {b_avg}. A collision of fronts.",
            "On one side, {a} ({a_rec}, {a_avg}); on the other, {b} ({b_rec}, {b_avg}).",
            "{b_team} ({b}, {b_rec}, {b_avg}) and {a_team} ({a}, {a_rec}, {a_avg}) are on a collision course in {wl}.",
        ],
        "p.h2h_split": [
            "They've met this season and split it, {h2h_rec}, a stalemate of fronts.",
            "{a} and {b} are {h2h_rec} against each other this season, level.",
            "The head-to-head forecast between {a} and {b} is a dead heat, {h2h_rec}.",
        ],
        "p.h2h_lead": [
            "{lead} has had the sunnier side of this series with {trail}, {h2h_rec}.",
            "{trail} is down {h2h_rec} to {lead} in earlier meetings, and a storm may be brewing.",
            "{lead} holds the head-to-head edge, {h2h_rec}, like a lingering high.",
        ],
        "p.h2h_none": [
            "They haven't met this season, so no data is available.",
            "{a} and {b} are yet to cross paths this season.",
            "This will be the first meeting of the season for {a} and {b}.",
        ],
        "p.stakes": [
            "Conditions: a win lifts {a}'s playoff odds to {a_win}; a loss lowers them to {a_loss}. For {b}, it's {b_win} or {b_loss}.",
            "{a}'s chance of playoff sunshine: {a_win} with a win, {a_loss} with a loss. {b}: {b_win} and {b_loss}.",
            "The pressure swing: {a} between {a_loss} and {a_win}, {b} between {b_loss} and {b_win}.",
        ],
        "p.leverage": [
            "{swing} points of combined playoff swing, the biggest pressure drop on the board this week.",
            "No system this week has more riding on it: {swing} points of swing between {a} and {b}.",
            "{a} and {b} are fighting over {swing} points of playoff odds. Nothing else comes close.",
        ],
        "p.favorite": [
            "{fav} is the favorite on {fav_why}: a {fav_odds} chance to {dog}'s {dog_odds}.",
            "By {fav_why}, {fav} ({fav_odds}) has the sunnier outlook over {dog} ({dog_odds}).",
            "{dog} faces cloudy skies at {dog_odds}; {fav} is at {fav_odds}.",
        ],
        "p.vol": [
            "Expect turbulence from {vol_n}: {vol_std} points of weekly swing, against {other_std} for {other}.",
            "{vol_n} is gusty, swinging {vol_std} points a week. {other} is calmer, at {other_std}.",
            "{other} is a steady breeze ({other_std}); {vol_n} is a storm front ({vol_std}).",
        ],
        "p.rivnote": [
            "Also on the radar: this is {rv_name}. {backstory}",
            "Pressure is building because it's {rv_name}. {backstory}",
            "It's {rv_name}, and the history is stormy. {backstory}",
        ],
        "p.close": [
            "That's the outlook for {a} and {b} in {wl}. Set your lineups.",
            "We'll check the radar after {wl} for {a} and {b}.",
            "{a} and {b} are on the forecast for {wl}.",
        ],
        "h.t": [
            "Trade front moves in: {a} sends {gave_s} to {b} for {got_s}",
            "{a} and {b} swap: {gave_s} for {got_s}",
            "{b} gets {gave_s} from {a}, who take {got_s}",
            "A shift in the winds: {gave_s} from {a} to {b}, {got_s} back",
        ],
        "t.sides": [
            "A trade front moved through in {wl}: {a} took {a_got}, and {b} took {b_got}.",
            "In {wl}, a trade system formed: {a} drew in {a_got}, and {b} drew in {b_got}.",
            "{a} sent out {b_got} and took in {a_got} in {wl}.",
            "{b} pushed {a_got} toward {a} in {wl} and drew {b_got} back.",
        ],
        "t.returns": [
            "Early conditions: over {since_wk}, {a}'s new players have produced {a_pts}, and {b}'s {b_pts}. {lead} has the sunnier outlook.",
            "Since the front moved through, {lead}'s side has {lead_pts} to {trail}'s {trail_pts}, over {since_wk}.",
            "After {since_wk}, {a}'s side of the deal reads {a_pts}, and {b}'s reads {b_pts}. {lead} is ahead.",
        ],
        "t.pending": [
            "{pk_side} took {pk_got}, and {pl_side} took {pl_got}. Picks for players: no readings yet.",
            "It's picks for players: {pl_side} has {pl_got}, {pk_side} has {pk_got}. Check back when the picks play.",
            "{pl_side} has the players ({pl_got}); {pk_side} has the picks ({pk_got}). The forecast is not yet available.",
        ],
        "t.fresh": [
            "It's too early to forecast who won that one.",
            "No readings yet. Check back after a few games.",
            "The forecast for the trade is: unclear.",
        ],
        "t.count": [
            "That's the {nth} trade of the season for {n}. Plenty of movement.",
            "{n} has now made the {nth} trade of this season.",
            "The {nth} trade for {n} this season.",
        ],
        "t.rec": [
            "Before the system moved in, {a} read {a_rec} ({a_rank}) and {b} read {b_rec} ({b_rank}).",
            "At last report, {a} held {a_rank} at {a_rec}, and {b} held {b_rank} at {b_rec}.",
            "Conditions heading in: {a}, {a_rec}, {a_rank}; {b}, {b_rec}, {b_rank}.",
        ],
        "t.close": [
            "The league log shows the deal as complete.",
            "The front has passed: the trade is done.",
            "It cleared, and it's in the record.",
        ],
        "h.w.big": [
            "{n} makes a big splash: {bid} for {player}",
            "{bid} for {player} ({pos}): a downpour from {n}",
            "{n} lays a {bid} bid on {player}, and the forecast gets interesting",
        ],
        "h.w.small": [
            "{player} drifts to {n} on a {bid} bid",
            "{player} ({pos}) joins {n}, {bid}",
            "A light shower: {n} claims {player} for {bid}",
        ],
        "h.w.free": [
            "A free-agent breeze blows {player} toward {n}",
            "{player} ({pos}) drifts to {n}",
            "{n} adds {player} off the wire",
        ],
        "w.top_bid": [
            "{n} made a big splash in {wl}: {bid} for {player} ({pos}), the largest bid of the week.",
            "The heaviest downpour of the week was {n}'s {bid} on {player} ({pos}).",
            "{n} dropped {bid} on {player} ({pos}), the heaviest rain of {wl}.",
        ],
        "w.top_free": [
            "{n} added {player} ({pos}) in {wl}, at no cost.",
            "{player} ({pos}) drifted to {n} in {wl}.",
            "The pickup of {wl}: {player} ({pos}), by {n}.",
        ],
        "w.since": [
            "Since then, {player} has produced {spts} over {since_wk}: {tier}.",
            "Over {since_wk}, {player} has returned {spts} to {n}: {tier}.",
            "{player}: {spts} in the {since_wk} since the move. {tier}.",
        ],
        "w.others": [
            "Scattered activity elsewhere: {others_text}.",
            "Also in the forecast: {others_text}.",
            "Other showers: {others_text}.",
        ],
        "w.total": [
            "In all, {total_owners} made {total_n} in {wl}.",
            "{total_n} drifted among {total_owners} in {wl}.",
            "The wire logged {total_n} in scattered showers among {total_owners} in {wl}.",
        ],
        "w.budget": [
            "{n} has drawn down {spent} of a {budget} FAAB reservoir.",
            "FAAB reservoir: {n}, {spent} of {budget} gone.",
            "{n} has let {spent} of {budget} evaporate so far.",
        ],
        "w.close": [
            "{player} has settled into {n}'s forecast area.",
            "{n} has {player}. Clear skies ahead, or not.",
            "{player} belongs to {n}.",
        ],
        "h.s": [
            "Beer Report, Week {wk}: {total_n} owed, with {top} on the forecast",
            "A {topn} shower parks over {top} in Week {wk}",
            "Week {wk} brings {total_n}: a shower of beer",
            "{top} leads the Week {wk} drizzle with {topn}",
        ],
        "s.total": [
            "The Week {wk} ledger forecasts {total_n} across {owners_n}.",
            "A front of {total_n} is moving across {owners_n} in Week {wk}.",
            "Week {wk} left {total_n} on the books, across {owners_n}.",
        ],
        "s.owner": [
            "{n} is under a {sgn} advisory: {list}.",
            "{n} is in line for {sgn}, courtesy of {list}.",
            "{n}: {sgn}. The cause: {list}.",
            "{n} collected {sgn} in the downpour: {list}.",
        ],
        "s.low": [
            "The lowest reading: {player} ({pos}), {pts}, in {n}'s lineup.",
            "{n}'s {player} ({pos}) managed {pts}, the week's coldest number.",
            "At {pts}, {player} ({pos}) set the low for {n}.",
        ],
        "s.leader": [
            "{leader} leads the season's shotgun forecast with {ltotal} through Week {wk}.",
            "Through Week {wk}, the heaviest accumulation sits over {leader}: {ltotal}.",
            "The season's heaviest total belongs to {leader}: {ltotal}.",
        ],
        "s.close": [
            "{top} is at the head of the Week {wk} list. Expect showers.",
            "{top} heads the Week {wk} ledger. Bring a cooler.",
            "The heaviest rain in Week {wk} falls on {top}.",
        ],
        "h.n": [
            "Standings through {wl}: {top} in the sun, {six} on the edge",
            "Through {wl}, {alive} teams still show better than a 5% chance of {spots} playoff spots",
            "{top} on top, {bottom} under the clouds: through {wl}",
            "Through {wl}, {six} sits on the playoff line, barely",
        ],
        "h.nf": [
            "Final forecast: {top} takes the top seed, {seven} misses out",
            "{six} gets the last spot, {seven} gets rained out: final standings",
            "{top} first, {bottom} last: the regular season clears",
            "The long-range outlook is set: {six} in the clear, {seven} rained out",
        ],
        "n.top": [
            "Through {wl}, {top} sits on top of the standings at {top_rec}.",
            "{top} is first at {top_rec} through {wl}, with clear skies ahead.",
            "At the high end through {wl}: {top}, {top_rec}.",
            "{top} leads at {top_rec}, with a {top_odds} chance of reaching the playoffs.",
            "Through {wl}, {top} leads at {top_rec}, with a {top_odds} chance of the playoffs and a {bye} chance of a bye.",
        ],
        "n.cut": [
            "{six} ({six_rec}) hangs on to the final playoff slot as {seven} ({seven_rec}) closes in from the west.",
            "The cold front lies between {six} ({six_rec}) and {seven} ({seven_rec}).",
            "{seven} ({seven_rec}) is the first team left out in the rain, with {six} ({six_rec}) just inside the door.",
        ],
        "n.luck": [
            "Fair weather and foul: {lucky} is {lucky_luck} wins above all-play expectation, and {unlucky} is {unlucky_luck}.",
            "By all-play, {lucky} has {lucky_luck} wins it hasn't earned; {unlucky} has {unlucky_luck}.",
            "{lucky} ({lucky_luck}) has had the sunshine; {unlucky} ({unlucky_luck}) has had the rain.",
        ],
        "n.clinch": [
            "Safe from the storm: {names}.",
            "Skies are clear for {names}, who have clinched.",
            "{names} have secured playoff spots.",
        ],
        "n.elim": [
            "Mathematically out: {names}. Better skies ahead next year.",
            "A permanent overcast has settled over {names}, who are eliminated.",
            "{names} can't reach the playoffs now.",
        ],
        "n.bottom": [
            "At the bottom of the barometer: {bottom}, {bottom_rec}.",
            "The lowest pressure reading belongs to {bottom}, at {bottom_rec}.",
            "The deepest low in the standings is parked over {bottom} ({bottom_rec}).",
        ],
        "n.eff": [
            "On lineups: {best_n} captures {best_pct} of the available points; {worst_n} captures {worst_pct}.",
            "{best_n} sets the clearest lineups at {best_pct}, and {worst_n} the cloudiest at {worst_pct}.",
            "Lineup visibility: {best_n} at {best_pct}, {worst_n} socked in at {worst_pct}.",
        ],
        "n.records": [
            "The records: the high is {hi_pts}, by {hi_n} in Week {hi_wk}, and the widest spread is {blow_m}, {blow_w} over {blow_l} in Week {blow_wk}.",
            "The record high is {hi_n}'s {hi_pts} from Week {hi_wk}, and the widest front on the books is {blow_w}'s {blow_m}-point win over {blow_l} in Week {blow_wk}.",
            "Two marks on the chart: {hi_pts} ({hi_n}, Week {hi_wk}) and {blow_m} points ({blow_w} over {blow_l}, Week {blow_wk}).",
        ],
        "n.ftop": [
            "{top} finished as the season's clearest high pressure, {top_rec}, with {top_pf} scored.",
            "The one-seed forecast reads {top}: {top_rec}, {top_pf}.",
            "{top} closed the regular season under blue skies, {top_rec}, {top_pf}.",
        ],
        "n.fcut": [
            "{six} took the last playoff spot at {six_rec}; {seven} finished at {seven_rec} and got rained out.",
            "The playoff line ran like a front between {six} ({six_rec}) and {seven} ({seven_rec}).",
            "{six} ({six_rec}) got in. {seven} ({seven_rec}) did not.",
        ],
        "n.fpts": [
            "{pf_n} ran the hottest all season ({pf_pts}); {low_n} ran the coolest ({low_pts}).",
            "In scoring, {pf_n} was hottest with {pf_pts}, and {low_n} coldest with {low_pts}.",
            "The season's hot reading was {pf_n}'s {pf_pts}; the chilly one was {low_n}'s {low_pts}.",
        ],
        "n.fbottom": [
            "{bottom} bottomed out at {bottom_rec}, the lowest reading of the season.",
            "The season's cellar temperature: {bottom}, {bottom_rec}.",
            "{bottom} settled into the deep freeze at {bottom_rec}.",
        ],
        "n.close": [
            "That's the standings through {wl}, with {top} at the top.",
            "The high pressure through {wl} is {top}.",
            "{top} is still the clearest sky in the league through {wl}.",
        ],
        "h.f": [
            "Storm warning: {a} and {b}",
            "A front is building between {a} and {b}",
            "{a} vs. {b}: a stormy history",
            "Tension rising: {a} and {b}",
        ],
        "f.h2h": [
            "The front started in Week {gwk}, when {w} {verb} {l}, {wp} to {lp}, by {m}.",
            "In Week {gwk}, {w} beat {l}, {wp}-{lp}, by {m}, and the skies have been dark since.",
            "{l} was caught in {w}'s Week {gwk} weather, {lp} to {wp}. That was {noun}.",
        ],
        "f.trade": [
            "In Week {twk}, the two did business: {a} took {a_got}, and {b} took {b_got}. Pressure often builds after a trade.",
            "A Week {twk} trade links the two systems: {a} drew in {a_got}, and {b} drew in {b_got}.",
            "In Week {twk}, {b_got} blew toward {b} and {a_got} toward {a}.",
        ],
        "f.adj": [
            "In the standings, {hi} ({hi_rec}, {hi_rank}) sits just above {lo} ({lo_rec}, {lo_rank}), {pf_gap} apart in points scored. A tight pressure gradient.",
            "{hi} is {hi_rank}, {lo} is {lo_rank}, and they're only {pf_gap} apart in points scored.",
            "{lo} runs {pf_gap} cooler than {hi} in points scored, {lo_rank} to {hi_rank} in the table.",
        ],
        "f.blow": [
            "A storm from Week {gwk}: {w} {verb} {l}, {wp} to {lp}, by {m} points.",
            "In Week {gwk}, {w} put {m} on {l}, {wp}-{lp}. That kind of damage lingers.",
            "{w}'s {m}-point win over {l} in Week {gwk} ({wp}-{lp}) is the kind of storm a rival remembers.",
        ],
        "f.sg": [
            "The shotgun rain gauges read {a_sg} for {a} and {b_sg} for {b}.",
            "The rain gauge: {a}, {a_sg}; {b}, {b_sg}.",
            "The season rain totals: {a} at {a_sg}, {b} at {b_sg}.",
        ],
        "f.story": [
            "Locals call this system {rv_name}. {backstory}",
            "It's known as {rv_name}, a long-running system. {backstory}",
            "The system at hand is {rv_name}. {backstory}",
        ],
        "f.trait": [
            "{a} {a_trait}; {b} {b_trait}. Two systems bound to collide.",
            "Look at the pair: {a} {a_trait}, and {b} {b_trait}.",
            "{a} {a_trait}. {b} {b_trait}. Conditions are unstable.",
        ],
        "f.mid": [
            "The barometer through Week {wk}: {a} at {a_rec} ({a_rank}) and {b} at {b_rec} ({b_rank}).",
            "Isobars through Week {wk}: {a}, {a_rank}, {a_rec}; {b}, {b_rank}, {b_rec}.",
            "Current readings through Week {wk}: {a} at {a_rec} ({a_rank}), {b} at {b_rec} ({b_rank}).",
        ],
        "f.close": [
            "Expect the tension to continue through the weekend.",
            "No clearing is in sight.",
            "We'll keep an eye on the radar.",
        ],
        "h.v": [
            "{rv_name} returns: {a} vs. {b} in Week {wk}",
            "A storm front in Week {wk}: {a} and {b}, {rv_name}",
            "Week {wk} forecast: {rv_name}",
            "{a} and {b} meet again in {rv_name}, Week {wk}",
        ],
        "v.lede": [
            "A big system moves in for {wl}: {rv_name}, with {a} against {b}. {backstory}",
            "Keep an eye on the radar. {rv_name} returns in {wl}, {a} against {b}. {backstory}",
            "{wl} puts {rv_name} on the radar: {a} versus {b}. {backstory}",
        ],
        "v.form": [
            "{a} arrives at {a_rec} ({a_rank}) with a {a_avg} average; {b} arrives at {b_rec} ({b_rank}) with a {b_avg} average.",
            "Current readings: {a}, {a_rec}, {a_rank}, {a_avg} a game; {b}, {b_rec}, {b_rank}, {b_avg} a game.",
            "Out west, {b} holds {b_rank} at {b_rec} ({b_avg} a game); out east, {a} holds {a_rank} at {a_rec} ({a_avg} a game).",
        ],
        "v.close": [
            "That's the outlook for {a} and {b} in Week {wk}.",
            "Week {wk} can't blow in fast enough for {a} and {b}.",
            "See you on the radar in Week {wk}, {a} and {b}.",
        ],
        "h.o": [
            "Offseason outlook: {ntrades} and {npick}",
            "{ntrades} and {npick}: a stormy offseason",
            "Before kickoff: {ntrades}, {npick}",
        ],
        "o.lede": [
            "Before the season began, the league logged {ntrades} and {npick}, a busy offseason pattern.",
            "The offseason saw {ntrades} and {npick}, according to the log.",
            "{ntrades} and {npick}, all before the opening kickoff.",
        ],
        "o.busy": [
            "The busiest fronts: {busy_text}.",
            "Trade activity by region: {busy_text}.",
            "The gustiest of the bunch: {busy_text}.",
        ],
        "o.big": [
            "The biggest system of the offseason: {side_a} got {a_got}, and {side_b} got {b_got}.",
            "The strongest system of the winter pushed {b_got} to {side_b} and {a_got} to {side_a}.",
            "{side_a} took {a_got}; {side_b} took {b_got}. The biggest deal of the winter.",
        ],
        "o.close": [
            "{busiest} made the most trades. Quite the pressure system.",
            "The trade winds blew hardest around {busiest}.",
            "{busiest} was the stormiest trader of the offseason.",
        ],
        "x.sig": [
            "And then, as always: “{catch}” The usual from {n}.",
            "And the front moved through on {n}'s signature gust: “{catch}”",
            "{n}'s signature line, again: “{catch}”",
        ],
        "x.attr": [
            "“{qc}” {n} told the camera, squinting at the sky.",
            "{n}, asked about conditions: “{qp}”",
            "“{qc}” {n} told us.",
            "{n}'s outlook: “{qp}”",
            "“{qc}” {n} said, with a shrug at the radar.",
        ],
    },
}
