"""Wrestling play-by-play: shouting, ring terminology, heels and faces. Numbers are announced like finishing moves."""
FAMILY = {
    "id": "wrestling",
    "label": "Wrestling play-by-play",
    "desc": "Ringside announcer at full volume. Pinfalls, finishers, heels and faces, referees who missed it, folding chairs. Every score is a move and every owner a character, but the card is the real scoreboard.",
    "rhythm": "short shouted bursts with the occasional long build-up",
    "formality": "very low, theatrical",
    "metaphors": "the ring, title belts, cage matches, tag teams, referees",
    "numbers": "exact, announced like moves",
    "lex": {
        "verb": {
            "blowout": ["slammed", "demolished", "destroyed"],
            "comfortable": ["pinned", "outwrestled", "handled"],
            "normal": ["beat", "pinned", "took down"],
            "close": ["edged", "barely pinned", "survived"],
        },
        "noun": {
            "blowout": ["a squash match", "a total beatdown", "a one-sided massacre"],
            "comfortable": ["a clean pinfall", "a convincing win", "a dominant win"],
            "normal": ["a pinfall", "a clean win", "a one-two-three"],
            "close": ["a two-count finish", "a near-fall", "a photo finish"],
        },
        "tier": {
            "hi": ["a title-belt move", "a main-event steal", "a legend-making signing"],
            "mid": ["a solid mid-card pickup", "a decent undercard addition", "a fair tag-in"],
            "lo": ["a jobber so far", "a preliminary-card bust so far", "not main-event material yet"],
        },
    },
    "T": {
        "h.r.blow": [
            "{w} {verb} {l}, {wp}-{lp}! {noun}!",
            "OH MY! {w} wins by {m} points over {l}!",
            "{w_team} puts {l_team} through the table, {wp}-{lp}",
        ],
        "h.r.upset": [
            "THE UPSET! {w} ({w_rank0}) shocks {l} ({l_rank0})!",
            "{w} beats {l}, and the standings are in the ring, down!",
            "{w_rank0} pins {l_rank0}! The champion falls in {wl}!",
        ],
        "h.r.close": [
            "{w} {verb} {l} by {m}! Two-count!",
            "{m} points! {w} wins {noun} over {l}!",
            "A photo finish in {wl}: {w}, {wp}; {l}, {lp}!",
        ],
        "h.r.top": [
            "{wp}!!! {w} delivers the week's biggest move",
            "{w} hits for {wp}, the best of {wl}!",
            "The finisher of {wl}: {w}, {wp} points, over {l}!",
        ],
        "h.r.tie": [
            "NO CONTEST! {a} and {b} tie at {pts}!",
            "Double count-out! {a} and {b} each score {pts}!",
            "{pts} to {pts}! The referee has no answer for {a} and {b}!",
        ],
        "r.lede.blow": [
            "OH MY GOODNESS! {w} {verb} {l}, {wp} to {lp}, and the margin, {m} points, is the biggest of the week! {noun}!",
            "Ring the bell! {w_team} ({w}) put {l_team} ({l}) through the canvas in {wl}, {wp}-{lp}! The widest margin of the card: {m} points!",
            "That was {noun}! {w} over {l}, {wp} to {lp}, by {m}! The biggest margin of {wl}!",
        ],
        "r.lede.upset": [
            "The crowd is on its feet! Coming into {wl}, {l} was {l_rank0} and {w} was {w_rank0}, and {w} {verb} {l}, {wp} to {lp}! The biggest upset on the card!",
            "UNBELIEVABLE! {w}, {w_rank0} in the standings, just beat {l}, {l_rank0}, {wp}-{lp}! The biggest upset of {wl}!",
            "{l} was the {l_rank0}-ranked team. {w} was {w_rank0}. {w} won, {wp} to {lp}! Somebody call the referee!",
        ],
        "r.lede.close": [
            "TWO! No, it's a kickout! {w} {verb} {l}, {wp} to {lp}, by just {m} points! The closest match of {wl}!",
            "What a finish! {w_team} ({w}) and {l_team} ({l}) went to the wire, {wp}-{lp}, with only {m} points between them! The closest of the week!",
            "It was {noun}! {w} over {l} by {m}, {wp} to {lp}, the tightest match on the card!",
        ],
        "r.lede.top": [
            "Somebody is on FIRE! {w} hit {wp} in {wl}, the best score of the week against an average of {wavg}, and {verb} {l} on the way! {l} had {lp}!",
            "HOLD ON TO YOUR FOLDING CHAIRS! {w} posts {wp} in {wl}, the top score on the card! The average was {wavg}! {l} scored {lp}!",
            "{w_team} ({w}) climbs the top rope and drops {wp}, the highest score of {wl}! {l} answers with {lp}! The average: {wavg}!",
        ],
        "r.lede.tie": [
            "DOUBLE PIN! {a_team} ({a}) and {b_team} ({b}) tied at {pts} each in {wl}! Nobody wins!",
            "The referee counts three, and it's for BOTH! {a} and {b} each score {pts} in {wl}!",
            "A draw! {a} and {b}, {pts} apiece, in {wl}!",
        ],
        "g.result": [
            "{w} {verb} {l}, and the referee's hand hits the mat for {w}, {wp} to {lp}!",
            "{w_team} ({w}) {verb} {l_team} ({l}), {wp}-{lp}! That's {noun}!",
            "In {wl}, {w_nick} {verb} {l}: {wp}-{lp}!",
            "{l_nick} goes down to {w}, {lp} to {wp}! {noun}!",
            "The bell rings! {w} {wp}, {l} {lp}, by {m}! {noun}!",
            "{w} and {l} locked up, and {w} got the pin, {wp}-{lp}!",
            "{l} taps out to {w}, {lp} to {wp}!",
            "{w} {verb} {l} by {m}, and the crowd noticed!",
            "Ding ding ding! {w} wins, {wp}-{lp}, over {l}!",
            "{wp} to {lp}: {w} takes the match from {l}!",
        ],
        "g.tie": [
            "{a} and {b}: {pts} each! No winner!",
            "{a_team} ({a}) and {b_team} ({b}) finish level at {pts}! The referee is baffled!",
            "{pts} apiece for {a} and {b}! Nobody gets the belt!",
        ],
        "g.star": [
            "{star} ({spos}) was the finisher, with {spts}, {sshare} of {w}'s {wp}!",
            "And what a performance from {star} ({spos})! {spts} for {w}!",
            "{star} ({spos}) hit the big move: {spts}, and {w} took it home!",
        ],
        "g.goat": [
            "{l} got {gpts} from {gname} ({gpos}) in the starting lineup! That's a botched move!",
            "{gname} ({gpos}) was a no-show for {l}: {gpts}!",
            "Somebody check the tag rope! {gname} ({gpos}) scored {gpts} for {l}!",
        ],
        "g.bench": [
            "{l} left {bench_left} on the apron! {bench_name} ({bench_pos}) scored {bench_pts} from the bench!",
            "{bench_name} ({bench_pos}) had {bench_pts} waiting for the tag on {l}'s bench! A better lineup was worth {bench_left}!",
            "{l} never made the tag! {bench_left} sat on the bench, {bench_pts} from {bench_name} ({bench_pos})!",
        ],
        "g.streak_w": [
            "{w} has won {k} straight! The champ is {w_rec}, {w_rank} in the rankings!",
            "{k} in a row for {w}! They're {w_rec} and {w_rank}!",
            "A winning streak of {k}! {w} is {w_rec}, {w_rank}, and UNSTOPPABLE!",
        ],
        "g.streak_l": [
            "{l} has dropped {k} straight! They're {l_rec}, {l_rank} in the rankings!",
            "{k} in a row for {l}, now {l_rec} and {l_rank}! It's getting ugly out there!",
            "A losing streak of {k}! {l} is {l_rec}, {l_rank}, and in trouble!",
        ],
        "g.record": [
            "{w} improves to {w_rec} ({w_rank})! {l} falls to {l_rec} ({l_rank})!",
            "The rankings now: {w}, {w_rec}, {w_rank}; {l}, {l_rec}, {l_rank}!",
            "After {wl}, it's {w} at {w_rec} and {l} at {l_rec}!",
        ],
        "g.top": [
            "{wp} was the HIGHEST score of {wl}! The average was {wavg}!",
            "Nobody on the card scored more than {w}: {wp}! The average was {wavg}!",
            "{w} tops the card with {wp}! The league average: {wavg}!",
        ],
        "g.low": [
            "{lp} was the LOWEST score of {wl}! The average was {wavg}!",
            "Nobody on the card scored less than {l}: {lp}! The average was {wavg}!",
            "{l} sits at the bottom of the card with {lp}! The league average: {wavg}!",
        ],
        "g.luck_up": [
            "{n} ({n_rec}) is {luck} wins ahead of the all-play numbers! The referee was looking the other way!",
            "By all-play, {n} has {luck} extra wins at {n_rec}! Somebody's got a foreign object!",
            "{n}: {n_rec}, and {luck} wins above expectation! That's a lucky break!",
        ],
        "g.luck_down": [
            "{n} ({n_rec}) is {luck} wins behind the all-play numbers! The referee has it in for them!",
            "By all-play, {n} should have more than {n_rec}: {luck}! Robbed!",
            "{n}: {n_rec}, and {luck} wins below expectation! That's an unlucky break!",
        ],
        "g.upset": [
            "Coming in, {w} was {w_rank0} and {l} was {l_rank0}! Tell that to the scoreboard!",
            "The rankings had {l} at {l_rank0} and {w} at {w_rank0} before {wl}!",
            "{l_rank0} versus {w_rank0}, and {w} won it!",
        ],
        "g.shotgun": [
            "And {n} owes {sgn}! The ref saw it: {why}!",
            "Bring out the beer! {n} owes {sgn} for {why}!",
            "{n} takes {sgn} to the chin, thanks to {why}!",
        ],
        "g.aside": [
            "Don't forget {n}, who {trait}! That's a big hit, {event}!",
            "{n}, who {trait}, walks out of {wl} with {event}!",
            "And {n}, who {trait}, is left with {event}!",
        ],
        "r.close_shift": [
            "AND THE RANKINGS MOVED! {in_names} climb into the top six, and {out_names} fall out! {leader} still holds the belt at {leader_rec}!",
            "In the standings, {in_names} are IN the top six, and {out_names} are OUT! {leader} leads at {leader_rec}!",
            "After {wl}, {in_names} are in and {out_names} are out of the top six! {leader} leads the pack, {leader_rec}!",
        ],
        "r.close_table": [
            "After {wl}, {leader} holds the belt at {leader_rec}, and {cut} is clinging to sixth at {cut_rec}!",
            "The rankings after {wl}: {leader} on top ({leader_rec}), {cut} barely in at sixth ({cut_rec})!",
            "{leader} is first at {leader_rec}! {cut} is sixth at {cut_rec}!",
        ],
        "r.close_po": [
            "That's a wrap on {wl}! {ngames}! The widest margin: {big_m} points, {big_w} over {big_l}! The top score: {top_w}'s {top_pts}!",
            "{wl} is DONE! {big_w} won by {big_m} over {big_l}, and {top_w} had the top score, {top_pts}! {ngames}!",
            "{ngames} in {wl}! {big_w}'s {big_m}-point win over {big_l} was the biggest, and {top_w}'s {top_pts} the best score!",
        ],
        "h.p.fav": [
            "The oddsmakers send {fav} to the ring as the favorite against {dog} in {wl}!",
            "{wl}: {fav} ({fav_odds}) steps in against {dog} ({dog_odds})!",
            "Can {dog} shock {fav} in {wl}?",
        ],
        "h.p.even": [
            "{a} vs. {b} in {wl}: TOO CLOSE TO CALL!",
            "{a_odds} to {b_odds}! {a} and {b} are neck and neck in {wl}",
            "A coin flip for {a} and {b} in {wl}!",
        ],
        "h.p.lev": [
            "THE MAIN EVENT of {wl}: {a} vs. {b}, {swing} points of playoff swing!",
            "{a} and {b} meet with the playoffs on the line in {wl}!",
            "{wl}'s title match: {a} vs. {b}!",
        ],
        "p.lede": [
            "Your main event for {wl} is {a_team} ({a}) against {b_team} ({b})!",
            "Tonight's main event: {a} versus {b}, {wl}!",
            "It's {a} vs. {b} in {wl}, and it's the match of the card!",
            "{swing} points of playoff swing on {a} vs. {b} in {wl}! That's the main event!",
        ],
        "p.matchup": [
            "{a_team} ({a}, {a_rec}, {a_avg} a game) steps into the ring against {b_team} ({b}, {b_rec}, {b_avg})!",
            "{a} is {a_rec} and scoring {a_avg}. {b} is {b_rec} and scoring {b_avg}! Somebody's going through a table!",
            "In this corner, {a} ({a_rec}, {a_avg}); in that corner, {b} ({b_rec}, {b_avg})!",
            "{b_team} ({b}, {b_rec}, {b_avg} a game) versus {a_team} ({a}, {a_rec}, {a_avg}) in {wl}!",
        ],
        "p.h2h_split": [
            "They've met this season, and it's a split, {h2h_rec}! A rematch!",
            "{a} and {b} are {h2h_rec} against each other! Dead even!",
            "The series between {a} and {b} is tied at {h2h_rec}!",
        ],
        "p.h2h_lead": [
            "{lead} leads {trail} {h2h_rec} this season! {trail} wants a rematch!",
            "{trail} is down {h2h_rec} to {lead} in the series, and wants revenge!",
            "{lead} has the edge, {h2h_rec}, in the series!",
        ],
        "p.h2h_none": [
            "The two haven't met this season! The first showdown!",
            "{a} and {b} have yet to step in the ring together this season!",
            "This is {a} vs. {b} for the first time this year!",
        ],
        "p.stakes": [
            "A win sends {a} to {a_win} playoff odds; a loss, {a_loss}! For {b}, it's {b_win} or {b_loss}! That's the belt on the line!",
            "{a}: {a_win} with a win, {a_loss} with a loss! {b}: {b_win} with a win, {b_loss} with a loss!",
            "Look at those swings! {a} between {a_loss} and {a_win}, {b} between {b_loss} and {b_win}!",
        ],
        "p.leverage": [
            "{swing} points of combined playoff swing! No match on the card has more at stake!",
            "This is THE match of the week: {swing} points of swing between {a} and {b}!",
            "{a} and {b} are fighting for {swing} points of playoff odds! Nothing else comes close!",
        ],
        "p.favorite": [
            "{fav} is the favorite on {fav_why}: {fav_odds} to {dog}'s {dog_odds}!",
            "The odds like {fav}: {fav_odds} to {dog}'s {dog_odds}, going by {fav_why}!",
            "{dog} climbs through the ropes as the underdog at {dog_odds}, with {fav} the champ at {fav_odds}!",
        ],
        "p.vol": [
            "{vol_n} is a loose cannon, swinging {vol_std} points a week, while {other} is steady at {other_std}!",
            "Watch out for {vol_n}! A {vol_std}-point weekly swing against {other}'s {other_std}!",
            "{other} is a technician ({other_std} points of swing). {vol_n} is a brawler ({vol_std})!",
        ],
        "p.rivnote": [
            "And don't forget: this is {rv_name}! {backstory}",
            "It's {rv_name}, and these two HATE each other! {backstory}",
            "This one's {rv_name}, folks! {backstory}",
        ],
        "p.close": [
            "Ring the bell! {a} and {b} get it going in {wl}!",
            "The bell rings on {a} vs. {b} in {wl}, and nobody's leaving their seat!",
            "{wl} is coming, and so are {a} and {b}!",
        ],
        "h.t": [
            "BLOCKBUSTER! {a} hands {gave_s} to {b} for {got_s}!",
            "{a} and {b} make a deal: {gave_s} for {got_s}!",
            "{b} lands {gave_s} from {a}, who gets {got_s}!",
            "TAG TEAM TRADE: {a} sends {gave_s} to {b} for {got_s}!",
        ],
        "t.sides": [
            "A deal has been struck in {wl}! {a} takes {a_got}, and {b} takes {b_got}!",
            "A TAG IS MADE in {wl}! {a} comes in with {a_got}, and {b} tags out with {b_got}!",
            "{a} out with {b_got}, in with {a_got}, in {wl}!",
            "{b} sent {a_got} to {a} in {wl}, and took {b_got} back!",
        ],
        "t.returns": [
            "And the early returns! In the {since_wk} since, {a}'s new guys scored {a_pts} and {b}'s scored {b_pts}! {lead} is ahead!",
            "Scoreboard watch: {lead}'s new players have {lead_pts} to {trail}'s {trail_pts} over {since_wk}!",
            "After {since_wk}, {a}'s side has {a_pts}, {b}'s side has {b_pts}! {lead} has the edge!",
        ],
        "t.pending": [
            "{pk_side} got {pk_got}, and {pl_side} got {pl_got}! Picks for players, so we can't call the winner yet!",
            "It's picks for players! {pl_side} has {pl_got}, {pk_side} has {pk_got}! Check back when the picks play!",
            "{pl_side} took {pl_got}; {pk_side} took {pk_got}! No verdict yet!",
        ],
        "t.fresh": [
            "It's too early to call a winner, folks!",
            "The match hasn't been played yet, so there's no verdict!",
            "No production yet! Check back later!",
        ],
        "t.count": [
            "{n} makes the tag for the {nth} time this season!",
            "{n} is making deals! The {nth} trade of the year!",
            "It's the {nth} trade for {n}!",
        ],
        "t.rec": [
            "Coming into the ring, {a} was {a_rec} ({a_rank}) and {b} was {b_rec} ({b_rank})!",
            "The tale of the tape that week: {a}, {a_rec}, {a_rank}; {b}, {b_rec}, {b_rank}!",
            "On the rankings board that night, {a} was {a_rank} at {a_rec} and {b} was {b_rank} at {b_rec}!",
        ],
        "t.close": [
            "The league log has it: the deal is official!",
            "It's done and it's on the record!",
            "The deal cleared, and the ref counted three!",
        ],
        "h.w.big": [
            "{n} throws the whole bankroll across the ring: {bid} for {player}!",
            "{bid}! {n} breaks the bank on {player} ({pos})!",
            "{n} bids {bid} for {player}, a main-event move!",
        ],
        "h.w.small": [
            "{n} slides in and snatches {player} for {bid}!",
            "{player} ({pos}) lands with {n} for {bid}!",
            "{n} tags in {player} with a {bid} bid!",
        ],
        "h.w.free": [
            "{n} tags in free agent {player}!",
            "{player} ({pos}) joins {n}'s corner!",
            "{player} rolls under the bottom rope and into {n}'s corner!",
        ],
        "w.top_bid": [
            "{n} dropped {bid} on {player} ({pos}) in {wl}, the biggest bid of the week!",
            "The biggest waiver bid of {wl}: {bid}, from {n}, for {player} ({pos})!",
            "{n} climbed the top rope and bet {bid} on {player} ({pos})!",
        ],
        "w.top_free": [
            "{n} tagged in {player} ({pos}) in {wl}!",
            "The pickup of {wl}: {player} ({pos}), by {n}!",
            "{player} ({pos}) joins {n} in {wl}!",
        ],
        "w.since": [
            "Since the tag, {player} has laid down {spts} across {since_wk}! That's {tier}!",
            "Over {since_wk}, {n} has gotten {spts} out of {player}! That's {tier}!",
            "{player}: {spts} in the {since_wk} since the move! {tier}!",
        ],
        "w.others": [
            "Also on the wire: {others_text}!",
            "Others on the move: {others_text}!",
            "Elsewhere on the card: {others_text}!",
        ],
        "w.total": [
            "Count the bodies in the ring for {wl}: {total_n}, brought in by {total_owners}!",
            "{total_n} changed hands among {total_owners} in {wl}!",
            "The wire saw {total_n} go to {total_owners} in {wl}!",
        ],
        "w.budget": [
            "{n} has burned {spent} of a {budget} FAAB budget!",
            "{n}'s FAAB purse is {spent} lighter out of {budget}, folks!",
            "{n} has used {spent} of {budget}!",
        ],
        "w.close": [
            "{player} wears {n}'s colors now!",
            "The commissioner's table has {player} signed with {n}!",
            "It's official: {player} joins {n}'s side!",
        ],
        "h.s": [
            "STEEL CAGE BEER REPORT, Week {wk}: {total_n} owed to the crowd!",
            "{top} takes {topn} on the chin in Week {wk}!",
            "Week {wk}: {total_n} on the ledger! Crack them open!",
            "{top} leads the Week {wk} drinking card with {topn}!",
        ],
        "s.total": [
            "The Week {wk} shotgun ledger is in: {total_n} across {owners_n}!",
            "Week {wk} sends {owners_n} to the canvas for a combined {total_n}!",
            "Week {wk} has {total_n} on the books, across {owners_n}!",
        ],
        "s.owner": [
            "{n} is down for {sgn}! The pinfall was {list}!",
            "{n}: {sgn}! The damage: {list}!",
            "The ref's counting {sgn} against {n}! The finish: {list}!",
            "{n} ate {sgn} in the ring: {list}!",
        ],
        "s.low": [
            "THE BOTCH OF THE WEEK: {player} ({pos}) missed the ropes with {pts} in {n}'s lineup!",
            "The week's worst number: {player} ({pos}), {pts}, for {n}!",
            "{n} started {player} ({pos}), who scored {pts}! The lowest on the card!",
        ],
        "s.leader": [
            "{leader} holds the dubious title belt for the season, {ltotal}, through Week {wk}!",
            "The season's most-pinned man or woman: {leader}, {ltotal}, after Week {wk}!",
            "Nobody has hit the mat more often this season than {leader}: {ltotal}!",
        ],
        "s.close": [
            "{top} is first on the Week {wk} card!",
            "Week {wk} is in the books, and {top} leads the ledger!",
            "{top} sits in the ring's corner atop the Week {wk} list!",
        ],
        "h.n": [
            "STANDINGS through {wl}: {top} holds the belt, {six} holds sixth!",
            "{alive} teams still fighting for {spots} playoff spots through {wl}!",
            "{top} leads, {bottom} trails: the rankings through {wl}!",
            "Through {wl}, {six} is hanging off the ropes of the last playoff spot!",
        ],
        "h.nf": [
            "FINAL rankings: {top} wins the top seed!",
            "{six} grabs the last spot, {seven} is eliminated: the final standings!",
            "{top} first, {bottom} last: the regular season is DONE!",
            "The playoff card is set: {six} in, {seven} out!",
        ],
        "n.top": [
            "Through {wl}, {top} holds the belt at {top_rec}!",
            "{top} is the reigning champ at {top_rec} through {wl}!",
            "Through {wl}, your number-one contender: {top}, {top_rec}!",
            "{top} leads at {top_rec} with {top_odds} playoff odds!",
            "{top} leads at {top_rec}, with {top_odds} playoff odds and {bye} to earn a bye!",
        ],
        "n.cut": [
            "{six} ({six_rec}) holds the last rung of the ladder, with {seven} ({seven_rec}) right behind!",
            "The cut line falls between {six} ({six_rec}) and {seven} ({seven_rec})!",
            "{seven} ({seven_rec}) is banging on the cage door behind {six} ({six_rec})!",
        ],
        "n.luck": [
            "The ref missed a few! {lucky} is {lucky_luck} wins above all-play, and {unlucky} is {unlucky_luck}!",
            "The luckiest: {lucky} at {lucky_luck}! The unluckiest: {unlucky} at {unlucky_luck}!",
            "{lucky} ({lucky_luck}) has the referee on its side; {unlucky} ({unlucky_luck}) does not!",
        ],
        "n.clinch": [
            "The three-count is over: {names} have clinched!",
            "{names} have locked up their spots, with the bell in the bank!",
            "{names} are through to the main event!",
        ],
        "n.elim": [
            "Eliminated: {names}! Better luck next season!",
            "Pinned for good: {names}!",
            "{names} have been tossed over the top rope for the season!",
        ],
        "n.bottom": [
            "{bottom} is flat on the canvas at {bottom_rec}!",
            "{bottom} ({bottom_rec}) is wrestling in the cellar of the rankings!",
            "{bottom} is the bottom of the card at {bottom_rec}!",
        ],
        "n.eff": [
            "Technique ratings! {best_n} lands {best_pct} of the available points, while {worst_n} flops at {worst_pct}!",
            "{best_n} sets the best lineups at {best_pct}! {worst_n} is at {worst_pct}!",
            "Efficiency king: {best_n} ({best_pct})! Efficiency cellar: {worst_n} ({worst_pct})!",
        ],
        "n.records": [
            "The records! The high score is {hi_pts}, by {hi_n} in Week {hi_wk}! The biggest margin: {blow_m} points, {blow_w} over {blow_l}, Week {blow_wk}!",
            "{hi_n}'s {hi_pts} in Week {hi_wk} is the high score, and {blow_w}'s {blow_m}-point win over {blow_l} in Week {blow_wk} is the widest margin!",
            "Records alert! {hi_pts} points by {hi_n} (Week {hi_wk}) and a {blow_m}-point beating by {blow_w} over {blow_l} (Week {blow_wk})!",
        ],
        "n.ftop": [
            "{top} walks out the CHAMPION at {top_rec}, with {top_pf} on the board!",
            "Your number-one seed, ladies and gentlemen: {top}, {top_rec}, {top_pf}!",
            "{top} ran the regular season like a main event: {top_rec} and {top_pf}!",
        ],
        "n.fcut": [
            "{six} escaped with the last spot at {six_rec}! {seven} took the loss at {seven_rec} and is OUT of the ring!",
            "The final bell split {six} ({six_rec}) from {seven} ({seven_rec})!",
            "{seven} ({seven_rec}) was one count short while {six} ({six_rec}) kicked out in time!",
        ],
        "n.fpts": [
            "{pf_n} hit the most points all year ({pf_pts}), and {low_n} hit the fewest ({low_pts})!",
            "The heavyweight of scoring: {pf_n}, {pf_pts}! The lightweight: {low_n}, {low_pts}!",
            "{pf_n} put up {pf_pts}, the high-flyer's total! {low_n} brought {low_pts}, the floor!",
        ],
        "n.fbottom": [
            "{bottom} finished flat on its back at {bottom_rec}!",
            "The jobber of the year: {bottom}, {bottom_rec}!",
            "{bottom} limped out of the ring at the bottom, {bottom_rec}!",
        ],
        "n.close": [
            "Through {wl}, {top} is still holding the belt!",
            "{top} leads the rankings through {wl}!",
            "{top} is still the man or woman to beat through {wl}!",
        ],
        "h.f": [
            "{a} vs. {b}: IT'S GETTING PERSONAL!",
            "{a} and {b}: the feud heats up!",
            "Heel turn? {a} and {b} go at it!",
            "{a} and {b}: unfinished business!",
        ],
        "f.h2h": [
            "It all started in Week {gwk}, when {w} {verb} {l}, {wp} to {lp}, by {m}!",
            "In Week {gwk}, {w} pinned {l}, {wp}-{lp}, by {m} points!",
            "{l} lost to {w} in Week {gwk}, {lp} to {wp}! {noun}!",
        ],
        "f.trade": [
            "The two did business in Week {twk}: {a} took {a_got}, and {b} took {b_got}! Now look at them!",
            "In Week {twk}, {a} and {b} made a trade! {a} landed {a_got}, and {b} landed {b_got}!",
            "Week {twk}: the tag was made, with {b_got} going to {b} and {a_got} going to {a}!",
        ],
        "f.adj": [
            "In the rankings, {hi} ({hi_rec}, {hi_rank}) is one rung above {lo} ({lo_rec}, {lo_rank}), and {pf_gap} of points scored is all that separates them!",
            "{hi} is {hi_rank}, {lo} is {lo_rank}, and they're {pf_gap} apart in points scored, locked up collar and elbow!",
            "{lo} is chasing {hi}! {lo_rank} and {hi_rank}, with {pf_gap} between them in points scored!",
        ],
        "f.blow": [
            "Replay it! Week {gwk}: {w} {verb} {l}, {wp} to {lp}, by {m} points!",
            "{m} points! That's the beating {w} put on {l} in Week {gwk}, {wp}-{lp}!",
            "Check the scar tissue from Week {gwk}: {w} over {l} by {m}, {wp}-{lp}!",
        ],
        "f.sg": [
            "On the ledger, {a} has taken {a_sg} and {b} has taken {b_sg}!",
            "The tally of damage: {a}, {a_sg}; {b}, {b_sg}!",
            "{a} is in the hole for {a_sg} this season, and {b} for {b_sg}!",
        ],
        "f.story": [
            "This is {rv_name}, the oldest grudge in the promotion! {backstory}",
            "The promotion bills this one as {rv_name}! {backstory}",
            "Step right up, it's {rv_name}! {backstory}",
        ],
        "f.trait": [
            "In this corner, {a}, who {a_trait}! In that corner, {b}, who {b_trait}! Somebody was always going to throw the first chair!",
            "Read the character cards: {a} {a_trait}, and {b} {b_trait}!",
            "{a} {a_trait}. {b} {b_trait}. That's a feud booked itself!",
        ],
        "f.mid": [
            "The rankings board through Week {wk} reads {a}, {a_rec}, {a_rank}, and {b}, {b_rec}, {b_rank}!",
            "The rankings through Week {wk}: {a} {a_rank} at {a_rec}, {b} {b_rank} at {b_rec}!",
            "Through Week {wk}, {a} ranks {a_rank} at {a_rec}, and {b} ranks {b_rank} at {b_rec}!",
        ],
        "f.close": [
            "This feud is far from over!",
            "The ref can't stop these two!",
            "Keep one eye on the ring and one eye on {a} and {b}!",
        ],
        "h.v": [
            "{rv_name} IS BACK: {a} vs. {b}, Week {wk}!",
            "Week {wk}'s main event: {a} vs. {b}, and it's {rv_name}!",
            "The rematch is on! Week {wk}, {a} and {b}, {rv_name}!",
            "It's {rv_name} week at ringside! {a} locks up with {b}!",
        ],
        "v.lede": [
            "It's {rv_name} week! {a} steps in against {b} in {wl}, and you do NOT want to miss it! {backstory}",
            "Ring the bell! {rv_name} is on the card in {wl}, with {a} against {b}! {backstory}",
            "The card for {wl}: {a} vs. {b}, billed as {rv_name}! {backstory}",
        ],
        "v.form": [
            "{a} is {a_rec} ({a_rank}) and scoring {a_avg}! {b} is {b_rec} ({b_rank}) and scoring {b_avg}!",
            "{a}: {a_rec}, {a_rank}, {a_avg} a game! {b}: {b_rec}, {b_rank}, {b_avg} a game!",
            "{b} comes in {b_rank} at {b_rec} ({b_avg} a game)! {a} comes in {a_rank} at {a_rec} ({a_avg} a game)!",
        ],
        "v.close": [
            "Week {wk} can't ring the bell fast enough for {a} and {b}!",
            "Circle Week {wk} on the poster: {a} vs. {b}!",
            "Get to your seats for Week {wk}, {a} and {b} fans!",
        ],
        "h.o": [
            "OFFSEASON CARD: {ntrades}, {npick}, and a lot of drama!",
            "The offseason card: {ntrades} and {npick}, and nobody sat out!",
            "Before a single bell: {ntrades} and {npick}!",
        ],
        "o.lede": [
            "Before the opening bell, the league logged {ntrades} and {npick}! That's a full pre-show!",
            "The offseason never stopped throwing punches: {ntrades} and {npick}!",
            "{ntrades}! {npick}! All before the opening bell!",
        ],
        "o.busy": [
            "The busiest deal-makers: {busy_text}! Those phones were HOT!",
            "Leading the tag-team ranks: {busy_text}!",
            "The busiest corners: {busy_text}!",
        ],
        "o.big": [
            "The headline match of the offseason! {side_a} tagged in {a_got}, and {side_b} tagged in {b_got}!",
            "Pay-per-view material: {side_a} brought in {a_got} and {side_b} brought in {b_got}!",
            "The biggest swap on the card: {side_a} takes {a_got}, {side_b} takes {b_got}!",
        ],
        "o.close": [
            "{busiest} made the most tags, and the crowd salutes!",
            "{busiest} wore out the tag rope with the most trades, by a mile!",
            "Hat tip to {busiest}, the dealmaker of the offseason!",
        ],
        "x.sig": [
            "And the crowd knew it was coming, because {n} hits the finisher: “{catch}”",
            "{n} hit the catchphrase: “{catch}”",
            "Here comes the signature move from {n}: “{catch}”",
        ],
        "x.attr": [
            "“{qc}” said {n}, grabbing the mic!",
            "{n}, from the ring: “{qp}”",
            "“{qc}” {n} shouted!",
            "{n} cut a promo: “{qp}”",
            "“{qc}” {n} said, and the crowd went wild!",
        ],
    },
}
